### ISSUE TITLE
Im Ordner Objekte fehlermeldung

### ISSUE THREAD

**Issue by spidermike-74** [ioBroker/ioBroker.admin#1020]
instrument.ts:129 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at HTMLDivElement.removeChild (<anonymous>)
    at Oi (http://192.168.178.78:8081/static/js/5.937235c5.chunk.js:2:5504164)
    at jl (http://192.168.178.78:8081/static/js/5.937235c5.chunk.js:2:5515976)
    at t.unstable_runWithPriority (http://192.168.178.78:8081/static/js/5.937235c5.chunk.js:2:5542565)
    at Wa (http://192.168.178.78:8081/static/js/5.937235c5.chunk.js:2:5458951)
    at Vl (http://192.168.178.78:8081/static/js/5.937235c5.chunk.js:2:5513934)
    at ml (http://192.168.178.78:8081/static/js/5.937235c5.chunk.js:2:5510020)
    at http://192.168.178.78:8081/static/js/5.937235c5.chunk.js:2:5459174
    at t.unstable_runWithPriority (http://192.168.178.78:8081/static/js/5.937235c5.chunk.js:2:5542565)
    at Wa (http://192.168.178.78:8081/static/js/5.937235c5.chunk.js:2:5458951)
    at Ga (http://192.168.178.78:8081/static/js/5.937235c5.chunk.js:2:5459119)
    at Ua (http://192.168.178.78:8081/static/js/5.937235c5.chunk.js:2:5459054)
    at hl (http://192.168.178.78:8081/static/js/5.937235c5.chunk.js:2:5507164)
    at Object.enqueueForceUpdate (http://192.168.178.78:8081/static/js/5.937235c5.chunk.js:2:5463379)
    at s.m.forceUpdate (http://192.168.178.78:8081/static/js/5.937235c5.chunk.js:2:5534163)
    at http://192.168.178.78:8081/static/js/2.08affc58.chunk.js:1:11895
    at r (http://192.168.178.78:8081/static/js/5.937235c5.chunk.js:2:6152657)

**Comment by GermanBluefox** [comment]
Kannst du den Fehler reproduzieren in dem du erst F12 (Browser console) aufmachst und danach die Seite neu lädst? Und erst danach den Fehler reproduzieren. 
Dann kann man mehr sehen

**Comment by GermanBluefox** [comment]
that could happen if admin was updated, but only once. After reload everything should work as designed

**Comment by spidermike-74** [comment]
instrument.ts:129 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Oi (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5514841)
    at jl (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5526653)
    at t.unstable_runWithPriority (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5553242)
    at Wa (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5469628)
    at Vl (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5524611)
    at ml (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5520697)
    at http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5469851
    at t.unstable_runWithPriority (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5553242)
    at Wa (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5469628)
    at Ga (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5469796)
    at Ua (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5469731)
    at hl (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5517841)
    at Object.enqueueForceUpdate (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5474056)
    at s.m.forceUpdate (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5544840)
    at http://192.168.178.78:8081/static/js/2.c0c4af74.chunk.js:1:12055
    at r (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:6163749)

**Comment by spidermike-74** [comment]
Ich bekomme nur noch fehlermeldungen immer wenn ich versuche in meine Objekte hinein zu kommen. 
Hab nicht einmal die Chance irgendetwas zu öffnen. 
Habe jetzt schon alle Adapter auf neusten stand und controller auf neusten Stand.
Kenne mich aber mit der Programmiererei auch nicht aus-
Wie kann ich aus der Beta wieder aussteigen auf eine gut laufende Variante, bin es leid immer nur Fehlermeldungen zu bekommen.

Gruß Maik

**Comment by Apollon77** [comment]
Shoft reload und Browser cache mal gelöscht?

**Comment by spidermike-74** [comment]
Was ist Shoft reload? 
Browser Cache noch nicht gelöscht werde ich heute abend mal machen.

Ich habe das Gefühl das es mit dem Shelly Adapter oder mit einen bestimmten Shelly Dimmer2 zu tun hat. Da kommt immer eine Fehlermeldung das die Temperatur über den eingestellten Wert von 100 liegt. Komme aber nicht rein wie gesagt um da was zu ändern.

**Comment by Apollon77** [comment]
> Was ist Shoft reload?

Sollte Shift Reload heissen

**Comment by Feuer-sturm** [comment]
No more feedback. Issue closed.
