### ISSUE TITLE
index.html not found

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.admin#1033]
**Describe the bug**  
I connect via the zerotier network. some adapters do not show their settings.

**To Reproduce**  
1. Go to install zerotier or use VPN
2. Click on setting for net-tool adapter 
3. See error

**Expected behavior**  
can use setting via zerotier

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/37106885/126711241-32cef559-8568-4e81-8427-c18d27f165a9.png)

![image](https://user-images.githubusercontent.com/37106885/126712216-a152290f-8a5a-4c35-9d70-32a4164d3afe.png)

js is ok:
![image](https://user-images.githubusercontent.com/37106885/126712300-640cd1dd-a5d0-4c45-b212-1016b2f0babb.png)

**Versions:**  
 - Adapter version: 5.1.13
 - JS-Controller version: 3.3.14
 - Node version: v12.22.2
 - Operating system: raspberry

**Additional context**  

```
host.raspberrypi | 2021-07-22 22:18:00.753 | error | system.adapter.ping.0 invalid mode
-- | -- | -- | --
host.raspberrypi | 2021-07-22 22:18:00.741 | info | "system.adapter.ping.0" enabled
host.raspberrypi | 2021-07-22 22:17:58.319 | error | system.adapter.net-tools.0 invalid mode
host.raspberrypi | 2021-07-22 22:17:58.306 | info | "system.adapter.net-tools.0" enabled
host.raspberrypi | 2021-07-22 22:15:57.974 | error | system.adapter.onvif.0 invalid mode
host.raspberrypi | 2021-07-22 22:15:57.960 | info | Set hostname raspberrypi for system.adapter.onvif.0
host.raspberrypi | 2021-07-22 22:15:57.940 | error | cannot process: system.adapter.onvif.0: TypeError: Cannot read property 'enabled' of undefined / TypeError: Cannot read property 'enabled' of undefined at change (/opt/iobroker/node_modules/iobroker.js-controller/main.js:611:77) at Immediate._onImmediate (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:254:41) at processImmediate (internal/timers.js:461:21)
admin.0 | 2021-07-22 22:15:57.889 | warn | This object will not be created in future versions. Please report this to the developer.
admin.0 | 2021-07-22 22:15:57.887 | warn | Object system.adapter.onvif.0 is invalid: obj.type has to exist
host.raspberrypi | 2021-07-22 22:15:57.300 | info | iobroker exit 0
host.raspberrypi | 2021-07-22 22:15:56.230 | info | iobroker host.raspberrypi object system.adapter.onvif cre

```

**Comment by Anzic23** [comment]
upload all fix Issues
