### ISSUE TITLE
kein zugriff auf Objekte

### ISSUE THREAD

**Issue by spidermike-74** [ioBroker/ioBroker.admin#1065]
Beim öffnen von Objekte kommt sofort einer Fehlermeldung

instrument.ts:129 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Oi (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5514841)
    at jl (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5526653)
    at t.unstable_runWithPriority (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5553242)
    at Wa (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5469628)
    at Vl (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5524611)
    at ml (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5520697)
    at http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5469851
    at t.unstable_runWithPriority (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5553242)
    at Wa (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5469628)
    at Ga (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5469796)
    at Ua (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5469731)
    at hl (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5517841)
    at Object.enqueueForceUpdate (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5474056)
    at s.m.forceUpdate (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:5544840)
    at http://192.168.178.78:8081/static/js/2.c0c4af74.chunk.js:1:13184
    at r (http://192.168.178.78:8081/static/js/5.42ef9396.chunk.js:2:6163749)

**Comment by Apollon77** [comment]
Welche Admin Version? Falls direkt nach Update auf Admin 5.x bitte mittes Shift Reload neu laden ... dann immer noch?

Ansosten: Kommt nur die Meldung aber Objekte gehen oder geht nichts?
