### ISSUE TITLE
Error in GUI! - TypeError: Cannot read property 'object' of undefined instrument.ts:129 

### ISSUE THREAD

**Issue by hgehrts** [ioBroker/ioBroker.admin#1080]
Hi 
The page http://<iobroker-ip>:8081/#tab-intro/system/tabDefaultACL throws an error at my installation:

```
Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    
at a.value (http://192.168.1.5:8081/static/js/main.692229dc.chunk.js:2:1008221)
function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at a.value (http://192.168.1.5:8081/static/js/main.692229dc.chunk.js:2:1008360)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at http://192.168.1.5:8081/static/js/main.692229dc.chunk.js:2:1010416function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at Array.map (<anonymous>)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at a.value (http://192.168.1.5:8081/static/js/main.692229dc.chunk.js:2:1010254)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at Wo (http://192.168.1.5:8081/static/js/5.42ef9396.chunk.js:2:5496714)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at Io (http://192.168.1.5:8081/static/js/5.42ef9396.chunk.js:2:5496511)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at Ui (http://192.168.1.5:8081/static/js/5.42ef9396.chunk.js:2:5537614)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at Cl (http://192.168.1.5:8081/static/js/5.42ef9396.chunk.js:2:5523715)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at _l (http://192.168.1.5:8081/static/js/5.42ef9396.chunk.js:2:5523643)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at El (http://192.168.1.5:8081/static/js/5.42ef9396.chunk.js:2:5523506)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at ml (http://192.168.1.5:8081/static/js/5.42ef9396.chunk.js:2:5520472)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at http://192.168.1.5:8081/static/js/5.42ef9396.chunk.js:2:5469851function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at t.unstable_runWithPriority (http://192.168.1.5:8081/static/js/5.42ef9396.chunk.js:2:5553242)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at Wa (http://192.168.1.5:8081/static/js/5.42ef9396.chunk.js:2:5469628)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at Ga (http://192.168.1.5:8081/static/js/5.42ef9396.chunk.js:2:5469796)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at Ua (http://192.168.1.5:8081/static/js/5.42ef9396.chunk.js:2:5469731)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at hl (http://192.168.1.5:8081/static/js/5.42ef9396.chunk.js:2:5517841)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at Object.enqueueSetState (http://192.168.1.5:8081/static/js/5.42ef9396.chunk.js:2:5473749)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at a.m.setState (http://192.168.1.5:8081/static/js/5.42ef9396.chunk.js:2:5544753)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at http://192.168.1.5:8081/static/js/main.692229dc.chunk.js:2:1017085

![image](https://user-images.githubusercontent.com/7419436/128765894-ec43007c-c2e1-4115-999b-9694361148a2.png)

versions:
iobv2-vm
Plattform
linux
Betriebssystem
linux
Architektur
x64
CPUs
2
Geschwindigkeit
3503 MHz
Modell
Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
RAM
3.84 GB
System-Betriebszeit
11:15:00
Node.js
v12.22.4
NPM
6.14.14
Datenträgergröße
23 GB
freier Festplattenspeicher
7.97 GB
Anzahl der Adapter
339
Betriebszeit
08:44:18
Aktive Instanzen
19
location
/opt/iobroker/
Hostname
iobv2-vm
```
everything is up to date (adapter and admin)

**Comment by Feuer-sturm** [comment]
Issue is duplicate to https://github.com/ioBroker/ioBroker.admin/issues/1068
