### ISSUE TITLE
Tado altes Handy lässt sich nicht löschen

### ISSUE THREAD

**Issue by ferzbeidel** [ioBroker/ioBroker.admin#1108]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**  
react-dom.production.min.js:216 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at HTMLDivElement.removeChild (<anonymous>)
    at Oi (http://192.168.1.169:8081/static/js/5.208678be.chunk.js:2:5516222)
    at jl (http://192.168.1.169:8081/static/js/5.208678be.chunk.js:2:5528034)
    at t.unstable_runWithPriority (http://192.168.1.169:8081/static/js/5.208678be.chunk.js:2:5554623)
    at Wa (http://192.168.1.169:8081/static/js/5.208678be.chunk.js:2:5471009)
    at Vl (http://192.168.1.169:8081/static/js/5.208678be.chunk.js:2:5525992)
    at ml (http://192.168.1.169:8081/static/js/5.208678be.chunk.js:2:5522078)
    at http://192.168.1.169:8081/static/js/5.208678be.chunk.js:2:5471232
    at t.unstable_runWithPriority (http://192.168.1.169:8081/static/js/5.208678be.chunk.js:2:5554623)
    at Wa (http://192.168.1.169:8081/static/js/5.208678be.chunk.js:2:5471009)

**Comment by Feuer-sturm** [comment]
@ferzbeidel please check your problem with current admin version if it still exists.

**Comment by Feuer-sturm** [comment]
No more feedback. Issue closed.
