### ISSUE TITLE
Fehler Iobroker ?

### ISSUE THREAD

**Issue by jokerjo1001** [ioBroker/ioBroker.admin#1152]
Hallo,
leider wird mir nach dem neuen einbiden eines Shelly 1 dieser Fehler ständig angezeigt.
Wäre für jede Hilfe dankbar.
Danke !!!

 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Oi (http://192.168.178.21:8081/static/js/5.42ef9396.chunk.js:2:5514841)
    at jl (http://192.168.178.21:8081/static/js/5.42ef9396.chunk.js:2:5526653)
    at t.unstable_runWithPriority (http://192.168.178.21:8081/static/js/5.42ef9396.chunk.js:2:5553242)
    at Wa (http://192.168.178.21:8081/static/js/5.42ef9396.chunk.js:2:5469628)
    at Vl (http://192.168.178.21:8081/static/js/5.42ef9396.chunk.js:2:5524611)
    at ml (http://192.168.178.21:8081/static/js/5.42ef9396.chunk.js:2:5520697)
    at http://192.168.178.21:8081/static/js/5.42ef9396.chunk.js:2:5469851
    at t.unstable_runWithPriority (http://192.168.178.21:8081/static/js/5.42ef9396.chunk.js:2:5553242)
    at Wa (http://192.168.178.21:8081/static/js/5.42ef9396.chunk.js:2:5469628)
    at Ga (http://192.168.178.21:8081/static/js/5.42ef9396.chunk.js:2:5469796)
    at Ua (http://192.168.178.21:8081/static/js/5.42ef9396.chunk.js:2:5469731)
    at hl (http://192.168.178.21:8081/static/js/5.42ef9396.chunk.js:2:5517841)
    at Object.enqueueForceUpdate (http://192.168.178.21:8081/static/js/5.42ef9396.chunk.js:2:5474056)
    at s.m.forceUpdate (http://192.168.178.21:8081/static/js/5.42ef9396.chunk.js:2:5544840)
    at http://192.168.178.21:8081/static/js/2.c0c4af74.chunk.js:1:12055

**Comment by jokerjo1001** [comment]
Keiner einen Tipp für mich ???

**Comment by ldittmar81** [comment]
Wie kommst du darauf, dass diese Fehlermeldung was mit dem Admin Adapter zu tun hat? Diese Zeilen sagen nicht woher der Fehler stammt. Wenn es mit dem Shelly Adapter zu tun hat, solltest es auch dort gepostet werden. Schon mal im Forum oder auf Facebook gefragt/geschaut ob noch jemand das Problem hat?

**Comment by Apollon77** [comment]
Nein das kommt vom Admin und nicht von Shelly ... von daher ... ist das wirklich nur das oder noch mehr? oder anderes? Wenn du was tust kommt der Fehler? Welche Admin Version?

**Comment by Feuer-sturm** [comment]
No more feedback. Issue closed.
