### ISSUE TITLE
Sonoff Adapter wird nicht gefunden

### ISSUE THREAD

**Issue by 08041965** [ioBroker/ioBroker.admin#1180]
**iobroker.admin@5.1.25
socket.io.js:59 [2021-10-09T19:54:18.081Z] Try to connect
Instances.js:444 getInstances: 53
Adapters.js:447 [ADAPTERS] getAdapters
Adapters.js:651 [ADAPTERS] getAdaptersInfo
6Adapters.js:1443 [ADAPTERS] Render
react-dom.production.min.js:216 DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Mi (http://192.168.2.151:8081/static/js/5.bde6ca2f.chunk.js:2:5519083)
    at Mi (http://192.168.2.151:8081/static/js/5.bde6ca2f.chunk.js:2:5519156)
    at Mi (http://192.168.2.151:8081/static/js/5.bde6ca2f.chunk.js:2:5519156)
    at Mi (http://192.168.2.151:8081/static/js/5.bde6ca2f.chunk.js:2:5519156)
    at Mi (http://192.168.2.151:8081/static/js/5.bde6ca2f.chunk.js:2:5519156)
    at bi (http://192.168.2.151:8081/static/js/5.bde6ca2f.chunk.js:2:5518581)
    at jl (http://192.168.2.151:8081/static/js/5.bde6ca2f.chunk.js:2:5531362)
    at t.unstable_runWithPriority (http://192.168.2.151:8081/static/js/5.bde6ca2f.chunk.js:2:5558154)
    at Wa (http://192.168.2.151:8081/static/js/5.bde6ca2f.chunk.js:2:5474540)
    at Vl (http://192.168.2.151:8081/static/js/5.bde6ca2f.chunk.js:2:5529523)
ii @ react-dom.production.min.js:216
content_script.js:1 Uncaught SyntaxError: Identifier 'WBSAutoFillFormTypeUndetermined' has already been declared
socketio.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
charger.png:1 Failed to load resource: the server responded with a status of 404 ()
players.png:1 Failed to load resource: the server responded with a status of 404 () the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by Feuer-sturm** [comment]
@08041965 please check your problem with current admin version if it still exists.

**Comment by Feuer-sturm** [comment]
No more feedback. Issue closed.
