### ISSUE TITLE
Error in GUI!

### ISSUE THREAD

**Issue by d1nd141** [ioBroker/ioBroker.admin#1182]
Hi,

Running on a Debian V11 VM
root@master:/opt/iobroker/log# node -v
v12.22.6
root@master:/opt/iobroker/log# npm -v
6.14.15
All iobroker updates done. (inkl self upgrade)

immediately after accessing the Gui, i receive the default error Page "Error in GUI!" with the following error:

index.js:18 iobroker.admin@5.1.25
socket.io.js:59 [2021-10-12T15:27:03.968Z] Try to connect
App.js:836 
        
       SyntaxError: Unexpected token  in JSON at position 18886
    at JSON.parse (<anonymous>)
    at App.js:807
    at u (runtime.js:63)
    at Generator._invoke (runtime.js:294)
    at Generator.next (runtime.js:119)
    at r (asyncToGenerator.js:3)
    at i (asyncToGenerator.js:25)
(anonymous) @ App.js:836
react-dom.production.min.js:216 
        
       Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=SyntaxError%3A%20Unexpected%20token%20%1D%20in%20JSON%20at%20position%2018886 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Mc (react-dom.production.min.js:140)
    at react-dom.production.min.js:150
    at Ro (react-dom.production.min.js:176)
    at Ui (react-dom.production.min.js:271)
    at Cl (react-dom.production.min.js:250)
    at _l (react-dom.production.min.js:250)
    at El (react-dom.production.min.js:250)
    at ml (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
ii @ react-dom.production.min.js:216

In iobroker.current.log logfile i have the following error sometimes, maybe related?:
Also disabling the javascript adapter does not help:

2021-10-12 17:28:46.229  - error: host.master.luxtv2.dyndns.org Caught by controller[0]: /opt/iobroker/node_modules/typescript/lib/typescript.js:145162
2021-10-12 17:28:46.229  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:         var errorCodes = [ts.Diagnostics.JSDoc_types_can_only_be_used_inside_documentation_comments.code_;
2021-10-12 17:28:46.229  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:                                                                                                          ^
2021-10-12 17:28:46.229  - error: host.master.luxtv2.dyndns.org Caught by controller[0]: SyntaxError: Unexpected token ';'
2021-10-12 17:28:46.229  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at wrapSafe (internal/modules/cjs/loader.js:915:16)
2021-10-12 17:28:46.229  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:963:27)
2021-10-12 17:28:46.229  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2021-10-12 17:28:46.229  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:863:32)
2021-10-12 17:28:46.230  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2021-10-12 17:28:46.230  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:887:19)
2021-10-12 17:28:46.230  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at require (internal/modules/cjs/helpers.js:74:18)
2021-10-12 17:28:46.230  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/virtual-tsc/build/server.js:4:10)
2021-10-12 17:28:46.230  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
2021-10-12 17:28:46.230  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2021-10-12 17:28:46.230  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:863:32)
2021-10-12 17:28:46.230  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2021-10-12 17:28:46.230  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:887:19)
2021-10-12 17:28:46.230  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at require (internal/modules/cjs/helpers.js:74:18)
2021-10-12 17:28:46.230  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/virtual-tsc/build/index.js:8:16)
2021-10-12 17:28:46.230  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
2021-10-12 17:28:46.230  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2021-10-12 17:28:46.230  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:863:32)
2021-10-12 17:28:46.230  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2021-10-12 17:28:46.230  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:887:19)
2021-10-12 17:28:46.230  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at require (internal/modules/cjs/helpers.js:74:18)
2021-10-12 17:28:46.230  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/main.js:35:24)
2021-10-12 17:28:46.231  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
2021-10-12 17:28:46.231  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2021-10-12 17:28:46.231  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:863:32)
2021-10-12 17:28:46.231  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2021-10-12 17:28:46.231  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
2021-10-12 17:28:46.231  - error: host.master.luxtv2.dyndns.org Caught by controller[0]:     at internal/main/run_main_module.js:17:47
2021-10-12 17:28:46.231  - error: host.master.luxtv2.dyndns.org instance system.adapter.javascript.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2021-10-12 17:28:46.231  - info: host.master.luxtv2.dyndns.org Restart adapter system.adapter.javascript.0 because enabled

**Comment by GermanBluefox** [comment]
Should be fixed in 5.1.26 (not yet released)
