### ISSUE TITLE
Unknown error. Page not loading.

### ISSUE THREAD

**Issue by MC-1984** [ioBroker/ioBroker.admin#1207]
**Describe the bug**  
Vis stopped working and I either tried to reload vis or the admin page (sorry, not sure). I was asked to report the error and copy the console message.

**To Reproduce**  
Unknown. After waiting for a minute Vis and Admin worked again.

**Console Message
`Cookie “io” will be soon treated as cross-site cookie against “https://192.168.15.10:8081/#tab-objects” because the scheme does not match. 2 192.168.15.10:8081
Cookie “io” will be soon treated as cross-site cookie against “https://192.168.15.10:8081/lib/js/socket.io.js” because the scheme does not match. socket.io.js
Cookie “io” will be soon treated as cross-site cookie against “https://192.168.15.10:8081/css/leaflet.css” because the scheme does not match. leaflet.css
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. 192.168.15.10:8081
Cookie “io” will be soon treated as cross-site cookie against “https://192.168.15.10:8081/lib/js/sparkline.js” because the scheme does not match. sparkline.js
Cookie “io” will be soon treated as cross-site cookie against “https://192.168.15.10:8081/static/css/main.950070b4.chunk.css” because the scheme does not match. main.950070b4.chunk.css
Cookie “io” will be soon treated as cross-site cookie against “https://192.168.15.10:8081/static/css/5.66aabfbf.chunk.css” because the scheme does not match. 5.66aabfbf.chunk.css
Cookie “io” will be soon treated as cross-site cookie against “https://192.168.15.10:8081/static/js/main.1892293b.chunk.js” because the scheme does not match. main.1892293b.chunk.js
Cookie “io” will be soon treated as cross-site cookie against “https://192.168.15.10:8081/static/js/5.bde6ca2f.chunk.js” because the scheme does not match. 5.bde6ca2f.chunk.js
iobroker.admin@5.1.25 main.1892293b.chunk.js:2:1135948
[2021-11-18T20:49:54.755Z] Try to connect socket.io.js:59:41
Cookie “io” will be soon treated as cross-site cookie against “https://192.168.15.10:8081/logo192.png” because the scheme does not match. logo192.png
Cookie “io” will be soon treated as cross-site cookie against “https://192.168.15.10:8081/favicon.ico” because the scheme does not match. favicon.ico
[2021-11-18T20:50:01.908Z] ws connection error: CLOSE_ABNORMAL socket.io.js:61:32
[2021-11-18T20:50:01.909Z] Start reconnect 0 socket.io.js:59:41
[2021-11-18T20:50:01.910Z] Try to connect socket.io.js:59:41
[2021-11-18T20:50:02.143Z] Start reconnect 1 socket.io.js:59:41
[2021-11-18T20:50:02.143Z] ws connection error: CLOSE_ABNORMAL socket.io.js:61:32
[2021-11-18T20:50:02.143Z] Reconnect is already running 1 socket.io.js:59:41
Firefox can’t establish a connection to the server at wss://192.168.15.10:8081/?sid=1637268601910&name=admin. socket.io.js:91:21
[2021-11-18T20:50:03.144Z] Try to connect socket.io.js:59:41
[2021-11-18T20:50:03.149Z] Start reconnect 2 socket.io.js:59:41
[2021-11-18T20:50:03.149Z] ws connection error: CLOSE_ABNORMAL socket.io.js:61:32
[2021-11-18T20:50:03.149Z] Reconnect is already running 2 socket.io.js:59:41
Firefox can’t establish a connection to the server at wss://192.168.15.10:8081/?sid=1637268603144&name=admin. socket.io.js:91:21
[2021-11-18T20:50:05.153Z] Try to connect socket.io.js:59:41
[2021-11-18T20:50:05.158Z] Start reconnect 3 socket.io.js:59:41
[2021-11-18T20:50:05.158Z] ws connection error: CLOSE_ABNORMAL socket.io.js:61:32
[2021-11-18T20:50:05.159Z] Reconnect is already running 3 socket.io.js:59:41
Firefox can’t establish a connection to the server at wss://192.168.15.10:8081/?sid=1637268605153&name=admin. socket.io.js:91:21
[2021-11-18T20:50:08.161Z] Try to connect socket.io.js:59:41
[2021-11-18T20:50:08.168Z] Start reconnect 4 socket.io.js:59:41
[2021-11-18T20:50:08.168Z] ws connection error: CLOSE_ABNORMAL socket.io.js:61:32
[2021-11-18T20:50:08.168Z] Reconnect is already running 4 socket.io.js:59:41
Firefox can’t establish a connection to the server at wss://192.168.15.10:8081/?sid=1637268608161&name=admin. socket.io.js:91:21
Cannot getRepositoryCompact: getCompactRepository timeout main.1892293b.chunk.js:2:1101172
Cannot getInstalled: notConnectedError main.1892293b.chunk.js:2:1101119
Cannot read adapters: notConnectedError main.1892293b.chunk.js:2:1101119
[ADAPTERS] Cannot compare "" and "3.3.18" 2 main.1892293b.chunk.js:2:1287366
notConnectedError main.1892293b.chunk.js:2:1106981
[ADAPTERS] Cannot compare "" and "3.3.18" main.1892293b.chunk.js:2:1287366
Loading failed for the <script> with source “https://192.168.15.10:8081/static/js/2.3d1b50fc.chunk.js”. 192.168.15.10:8081:1:1
Cookie “io” will be soon treated as cross-site cookie against “https://192.168.15.10:8081/static/js/2.3d1b50fc.chunk.js” because the scheme does not match. 2.3d1b50fc.chunk.js
Loading failed for the <script> with source “https://192.168.15.10:8081/static/js/15.1f242916.chunk.js”. 192.168.15.10:8081:1:1
Cookie “io” will be soon treated as cross-site cookie against “https://192.168.15.10:8081/static/js/15.1f242916.chunk.js” because the scheme does not match. 15.1f242916.chunk.js
Cookie “io” will be soon treated as cross-site cookie against “https://192.168.15.10:8081/static/js/7.34479e94.chunk.js” because the scheme does not match. 7.34479e94.chunk.js
ChunkLoadError: Loading chunk 2 failed.
(error: https://192.168.15.10:8081/static/js/2.3d1b50fc.chunk.js)
    e https://192.168.15.10:8081/#tab-objects:1
    Ti https://192.168.15.10:8081/static/js/main.1892293b.chunk.js:2
    V https://192.168.15.10:8081/static/js/5.bde6ca2f.chunk.js:2
    Ui https://192.168.15.10:8081/static/js/5.bde6ca2f.chunk.js:2
    Cl https://192.168.15.10:8081/static/js/5.bde6ca2f.chunk.js:2
    _l https://192.168.15.10:8081/static/js/5.bde6ca2f.chunk.js:2
    El https://192.168.15.10:8081/static/js/5.bde6ca2f.chunk.js:2
    ml https://192.168.15.10:8081/static/js/5.bde6ca2f.chunk.js:2
    Ga https://192.168.15.10:8081/static/js/5.bde6ca2f.chunk.js:2
    unstable_runWithPriority https://192.168.15.10:8081/static/js/5.bde6ca2f.chunk.js:2
    Wa https://192.168.15.10:8081/static/js/5.bde6ca2f.chunk.js:2
    Ga https://192.168.15.10:8081/static/js/5.bde6ca2f.chunk.js:2
    Ua https://192.168.15.10:8081/static/js/5.bde6ca2f.chunk.js:2
    hl https://192.168.15.10:8081/static/js/5.bde6ca2f.chunk.js:2
    enqueueSetState https://192.168.15.10:8081/static/js/5.bde6ca2f.chunk.js:2
    setState https://192.168.15.10:8081/static/js/5.bde6ca2f.chunk.js:2
    t https://192.168.15.10:8081/static/js/main.1892293b.chunk.js:2
    u https://192.168.15.10:8081/static/js/5.bde6ca2f.chunk.js:2
    _invoke https://192.168.15.10:8081/static/js/5.bde6ca2f.chunk.js:2
    w https://192.168.15.10:8081/static/js/5.bde6ca2f.chunk.js:2
    r https://192.168.15.10:8081/static/js/5.bde6ca2f.chunk.js:2
    i https://192.168.15.10:8081/static/js/5.bde6ca2f.chunk.js:2
5.bde6ca2f.chunk.js:2:5512353
Uncaught (in promise) notConnectedError 3
Loading failed for the <script> with source “https://192.168.15.10:8081/static/js/7.34479e94.chunk.js”. 192.168.15.10:8081:1:1
Cookie “io” will be soon treated as cross-site cookie against “https://192.168.15.10:8081/static/js/7.34479e94.chunk.js” because the scheme does not match. 7.34479e94.chunk.js
Cannot get logs: notConnectedError main.1892293b.chunk.js:2:1101119
[2021-11-18T20:50:12.173Z] Try to connect socket.io.js:59:41
[2021-11-18T20:50:12.177Z] Start reconnect 5 socket.io.js:59:41
[2021-11-18T20:50:12.178Z] ws connection error: CLOSE_ABNORMAL socket.io.js:61:32
[2021-11-18T20:50:12.178Z] Reconnect is already running 5 socket.io.js:59:41
Firefox can’t establish a connection to the server at wss://192.168.15.10:8081/?sid=1637268612173&name=admin. socket.io.js:91:21
Uncaught (in promise) notConnectedError
notConnectedError 200 main.1892293b.chunk.js:2:1096855
[2021-11-18T20:50:17.182Z] Try to connect socket.io.js:59:41
[2021-11-18T20:50:17.188Z] Start reconnect 5 socket.io.js:59:41
[2021-11-18T20:50:17.188Z] ws connection error: CLOSE_ABNORMAL socket.io.js:61:32
[2021-11-18T20:50:17.188Z] Reconnect is already running 5 socket.io.js:59:41
Firefox can’t establish a connection to the server at wss://192.168.15.10:8081/?sid=1637268617183&name=admin. socket.io.js:91:21
[2021-11-18T20:50:22.192Z] Try to connect socket.io.js:59:41
Firefox can’t establish a connection to the server at wss://192.168.15.10:8081/?sid=1637268622192&name=admin. socket.io.js:91:21
[2021-11-18T20:50:22.196Z] Start reconnect 5 socket.io.js:59:41
[2021-11-18T20:50:22.196Z] ws connection error: CLOSE_ABNORMAL socket.io.js:61:32
[2021-11-18T20:50:22.196Z] Reconnect is already running 5 socket.io.js:59:41
[2021-11-18T20:50:27.199Z] Try to connect socket.io.js:59:41
[2021-11-18T20:50:27.203Z] Start reconnect 5 socket.io.js:59:41
[2021-11-18T20:50:27.203Z] ws connection error: CLOSE_ABNORMAL socket.io.js:61:32
[2021-11-18T20:50:27.203Z] Reconnect is already running 5 socket.io.js:59:41
Firefox can’t establish a connection to the server at wss://192.168.15.10:8081/?sid=1637268627199&name=admin. socket.io.js:91:21
[2021-11-18T20:50:32.206Z] Try to connect socket.io.js:59:41
[2021-11-18T20:50:33.061Z] Start reconnect 5 socket.io.js:59:41
[2021-11-18T20:50:33.061Z] ws connection error: CLOSE_ABNORMAL socket.io.js:61:32
[2021-11-18T20:50:33.061Z] Reconnect is already running 5 socket.io.js:59:41
Firefox can’t establish a connection to the server at wss://192.168.15.10:8081/?sid=1637268632206&name=admin. socket.io.js:91:21
[2021-11-18T20:50:38.065Z] Try to connect socket.io.js:59:41
[2021-11-18T20:50:41.069Z] No READY flag received in 3 seconds. Re-init socket.io.js:60:32
[2021-11-18T20:50:41.070Z] Start reconnect 5 socket.io.js:59:41
[2021-11-18T20:50:41.070Z] Reconnect is already running 5 socket.io.js:59:41
[2021-11-18T20:50:41.071Z] ws connection error: CLOSE_ABNORMAL socket.io.js:61:32
Firefox can’t establish a connection to the server at wss://192.168.15.10:8081/?sid=1637268638067&name=admin. socket.io.js:91:21
The connection to wss://192.168.15.10:8081/?sid=1637268638067&name=admin was interrupted while the page was loading. socket.io.js:91:21
[2021-11-18T20:50:41.071Z] Reconnect is already running 5 socket.io.js:59:41
[2021-11-18T20:50:46.072Z] Try to connect socket.io.js:59:41
[2021-11-18T20:50:46.077Z] Start reconnect 5 socket.io.js:59:41
[2021-11-18T20:50:46.077Z] ws connection error: CLOSE_ABNORMAL socket.io.js:61:32
[2021-11-18T20:50:46.077Z] Reconnect is already running 5 socket.io.js:59:41
Firefox can’t establish a connection to the server at wss://192.168.15.10:8081/?sid=1637268646072&name=admin. socket.io.js:91:21
[2021-11-18T20:50:51.080Z] Try to connect socket.io.js:59:41
[2021-11-18T20:50:54.084Z] No READY flag received in 3 seconds. Re-init socket.io.js:60:32
Firefox can’t establish a connection to the server at wss://192.168.15.10:8081/?sid=1637268651080&name=admin. socket.io.js:91:21
[2021-11-18T20:50:54.085Z] Start reconnect 5 socket.io.js:59:41
[2021-11-18T20:50:54.085Z] Reconnect is already running 5 socket.io.js:59:41
[2021-11-18T20:50:54.085Z] ws connection error: CLOSE_ABNORMAL socket.io.js:61:32
[2021-11-18T20:50:54.086Z] Reconnect is already running 5 socket.io.js:59:41
The connection to wss://192.168.15.10:8081/?sid=1637268651080&name=admin was interrupted while the page was loading. socket.io.js:91:21
[2021-11-18T20:50:59.088Z] Try to connect socket.io.js:59:41
[2021-11-18T20:50:59.250Z] Start reconnect 5 socket.io.js:59:41
[2021-11-18T20:50:59.250Z] ws connection error: CLOSE_ABNORMAL socket.io.js:61:32
[2021-11-18T20:50:59.251Z] Reconnect is already running 5 socket.io.js:59:41
Firefox can’t establish a connection to the server at wss://192.168.15.10:8081/?sid=1637268659088&name=admin. socket.io.js:91:21
[2021-11-18T20:51:04.252Z] Try to connect socket.io.js:59:41
[2021-11-18T20:51:07.253Z] No READY flag received in 3 seconds. Re-init socket.io.js:60:32
[2021-11-18T20:51:07.255Z] Start reconnect 5 socket.io.js:59:41
Firefox can’t establish a connection to the server at wss://192.168.15.10:8081/?sid=1637268664253&name=admin. socket.io.js:91:21
The connection to wss://192.168.15.10:8081/?sid=1637268664253&name=admin was interrupted while the page was loading. socket.io.js:91:21
[2021-11-18T20:51:07.264Z] Reconnect is already running 5 socket.io.js:59:41
[2021-11-18T20:51:07.264Z] ws connection error: CLOSE_ABNORMAL socket.io.js:61:32
[2021-11-18T20:51:07.265Z] Reconnect is already running 5 socket.io.js:59:41
[2021-11-18T20:51:12.257Z] Try to connect socket.io.js:59:41
[2021-11-18T20:51:15.262Z] No READY flag received in 3 seconds. Re-init socket.io.js:60:32
[2021-11-18T20:51:15.262Z] Start reconnect 5 socket.io.js:59:41
Firefox can’t establish a connection to the server at wss://192.168.15.10:8081/?sid=1637268672257&name=admin. socket.io.js:91:21
The connection to wss://192.168.15.10:8081/?sid=1637268672257&name=admin was interrupted while the page was loading. socket.io.js:91:21
[2021-11-18T20:51:15.263Z] Reconnect is already running 5 socket.io.js:59:41
[2021-11-18T20:51:15.265Z] ws connection error: CLOSE_ABNORMAL socket.io.js:61:32
[2021-11-18T20:51:15.265Z] Reconnect is already running 5 socket.io.js:59:41
[2021-11-18T20:51:20.268Z] Try to connect socket.io.js:59:41
Firefox can’t establish a connection to the server at wss://192.168.15.10:8081/?sid=1637268680268&name=admin. socket.io.js:91:21
[2021-11-18T20:51:20.293Z] Start reconnect 5 socket.io.js:59:41
[2021-11-18T20:51:20.293Z] ws connection error: CLOSE_ABNORMAL socket.io.js:61:32
[2021-11-18T20:51:20.294Z] Reconnect is already running 5 socket.io.js:59:41
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: https://192.168.15.10:8081/static/css/5.66aabfbf.chunk.css
Source Map URL: 5.66aabfbf.chunk.css.map

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: https://192.168.15.10:8081/static/css/main.950070b4.chunk.css
Source Map URL: main.950070b4.chunk.css.map

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: https://192.168.15.10:8081/static/js/main.1892293b.chunk.js
Source Map URL: main.1892293b.chunk.js.map

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: https://192.168.15.10:8081/static/js/5.bde6ca2f.chunk.js
Source Map URL: 5.bde6ca2f.chunk.js.map

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: https://192.168.15.10:8081/lib/js/sparkline.js
Source Map URL: sparkline.js.map`

**Expected behavior**  
Load iobroker in Firefox (current stable) on current MacOS

**Versions:**  
 - Adapter version: 5.1.25
 - JS-Controller version: 3.3.18
 - Node version: 14.18.0
 - Operating system: Raspbian Buster

**Comment by Feuer-sturm** [comment]
@MC-1984 please check your Problem with current admin version if it still exists.
