### ISSUE TITLE
Sourceanalytix funktioniert nicht

### ISSUE THREAD

**Issue by 08041965** [ioBroker/ioBroker.admin#1210]
iobroker.admin@5.1.25
socket.io.js:59 [2021-11-23T16:49:02.116Z] Try to connect
Adapters.js:447 [ADAPTERS] getAdapters
Adapters.js:651 [ADAPTERS] getAdaptersInfo
2Adapters.js:1443 [ADAPTERS] Render
raw.githubusercontent.com/instalator/ioBroker.vis-players/master/admin/players.png:1 Failed to load resource: the server responded with a status of 404 ()
:8081/adapter/socketio/socketio.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/adapter/sql/sql.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
Instances.js:444 getInstances: 59
​ iobroker.web@3.4.9 using theme "colored"
​ 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

​ Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
​ Help us to create open source project with reactJS!
​ See you :)
​ [2021-11-23T16:49:58.237Z] Try to connect
Adapters.js:447 [ADAPTERS] getAdapters
Adapters.js:651 [ADAPTERS] getAdaptersInfo
2Adapters.js:1443 [ADAPTERS] Render
:8081/adapter/socketio/socketio.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/adapter/sql/sql.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
raw.githubusercontent.com/instalator/ioBroker.vis-players/master/admin/players.png:1 Failed to load resource: the server responded with a status of 404 ()
Adapters.js:1443 [ADAPTERS] Render
:8081/adapter/socketio/socketio.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
Adapters.js:1443 [ADAPTERS] Render
:8081/adapter/sql/sql.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
raw.githubusercontent.com/instalator/ioBroker.vis-players/master/admin/players.png:1 Failed to load resource: the server responded with a status of 404 ()
5Adapters.js:1443 [ADAPTERS] Render
:8081/adapter/socketio/socketio.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
Adapters.js:1443 [ADAPTERS] Render
:8081/adapter/sql/sql.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
raw.githubusercontent.com/instalator/ioBroker.vis-players/master/admin/players.png:1 Failed to load resource: the server responded with a status of 404 ()
Adapters.js:447 [ADAPTERS] getAdapters
Adapters.js:651 [ADAPTERS] getAdaptersInfo
2Adapters.js:1443 [ADAPTERS] Render
:8081/adapter/socketio/socketio.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/adapter/sql/sql.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
raw.githubusercontent.com/instalator/ioBroker.vis-players/master/admin/players.png:1 Failed to load resource: the server responded with a status of 404 ()
4Adapters.js:1443 [ADAPTERS] Render
Instances.js:444 getInstances: 79
ObjectBrowser.js:2301 + subscribe sonoff.2.Sensor-Solar.ENERGY_ApparentPower
ObjectBrowser.js:2301 + subscribe sonoff.2.Sensor-Solar.ENERGY_Current
ObjectBrowser.js:2301 + subscribe sonoff.2.Sensor-Solar.ENERGY_Factor
ObjectBrowser.js:2301 + subscribe sonoff.2.Sensor-Solar.ENERGY_Period
ObjectBrowser.js:2301 + subscribe sonoff.2.Sensor-Solar.ENERGY_Power
ObjectBrowser.js:2301 + subscribe sonoff.2.Sensor-Solar.ENERGY_ReactivePower
ObjectBrowser.js:2301 + subscribe sonoff.2.Sensor-Solar.ENERGY_Today
ObjectBrowser.js:2301 + subscribe sonoff.2.Sensor-Solar.ENERGY_Total
ObjectBrowser.js:2301 + subscribe sonoff.2.Sensor-Solar.ENERGY_TotalStartTime
ObjectBrowser.js:2301 + subscribe sonoff.2.Sensor-Solar.ENERGY_Voltage
ObjectBrowser.js:2301 + subscribe sonoff.2.Sensor-Solar.ENERGY_Yesterday
ObjectBrowser.js:2301 + subscribe sonoff.2.Sensor-Solar.SleepMode
ObjectBrowser.js:2301 + subscribe sonoff.2.Sensor-Solar.Time
ObjectBrowser.js:2301 + subscribe sonoff.2.Sensor-Solar.Uptime
ObjectBrowser.js:2301 + subscribe sonoff.2.Sensor-Solar.Wifi_BSSId
ObjectBrowser.js:2301 + subscribe sonoff.2.Sensor-Solar.Wifi_Channel
ObjectBrowser.js:2301 + subscribe sonoff.2.Sensor-Solar.Wifi_Downtime
ObjectBrowser.js:2301 + subscribe sonoff.2.Sensor-Solar.Wifi_RSSI
ObjectBrowser.js:2301 + subscribe sonoff.2.Sensor-Solar.Wifi_SSId
ObjectBrowser.js:2301 + subscribe sonoff.2.Sensor-Solar.alive
ObjectBrowser.js:2301 + subscribe web.0.connected
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.ENERGY_ApparentPower
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.ENERGY_Current
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.ENERGY_Factor
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.ENERGY_Period
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.ENERGY_Power
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.ENERGY_ReactivePower
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.ENERGY_Today
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.ENERGY_Total
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.ENERGY_TotalStartTime
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.ENERGY_Voltage
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.ENERGY_Yesterday
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.SleepMode
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.Time
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.Uptime
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.Wifi_BSSId
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.Wifi_Channel
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.Wifi_Downtime
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.Wifi_RSSI
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.Wifi_SSId
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.alive
ObjectBrowser.js:2150 > stateChange web.0.connected
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.Time
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.Uptime
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.SleepMode
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.Wifi_SSId
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.Wifi_BSSId
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.Wifi_Channel
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.Wifi_RSSI
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.Wifi_Downtime
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.Time
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.ENERGY_TotalStartTime
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.ENERGY_Total
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.ENERGY_Yesterday
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.ENERGY_Today
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.ENERGY_Period
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.ENERGY_Power
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.ENERGY_ApparentPower
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.ENERGY_ReactivePower
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.ENERGY_Factor
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.ENERGY_Voltage
ObjectBrowser.js:2150 > stateChange sonoff.2.Sensor-Solar.ENERGY_Current
ObjectBrowser.js:2317 - unsubscribe sonoff.2.Sensor-Solar.alive
ObjectBrowser.js:2317 - unsubscribe sonoff.2.Sensor-Solar.Wifi_SSId
ObjectBrowser.js:2317 - unsubscribe sonoff.2.Sensor-Solar.Wifi_RSSI
ObjectBrowser.js:2317 - unsubscribe sonoff.2.Sensor-Solar.Wifi_Downtime
ObjectBrowser.js:2317 - unsubscribe sonoff.2.Sensor-Solar.Wifi_Channel
ObjectBrowser.js:2317 - unsubscribe sonoff.2.Sensor-Solar.Wifi_BSSId
ObjectBrowser.js:2317 - unsubscribe sonoff.2.Sensor-Solar.Uptime
ObjectBrowser.js:2317 - unsubscribe sonoff.2.Sensor-Solar.Time
ObjectBrowser.js:2317 - unsubscribe sonoff.2.Sensor-Solar.SleepMode
ObjectBrowser.js:2317 - unsubscribe sonoff.2.Sensor-Solar.ENERGY_Yesterday
ObjectBrowser.js:2317 - unsubscribe sonoff.2.Sensor-Solar.ENERGY_Voltage
ObjectBrowser.js:2317 - unsubscribe sonoff.2.Sensor-Solar.ENERGY_TotalStartTime
ObjectBrowser.js:2317 - unsubscribe sonoff.2.Sensor-Solar.ENERGY_Total
ObjectBrowser.js:2317 - unsubscribe sonoff.2.Sensor-Solar.ENERGY_Today
ObjectBrowser.js:2317 - unsubscribe sonoff.2.Sensor-Solar.ENERGY_ReactivePower
ObjectBrowser.js:2317 - unsubscribe sonoff.2.Sensor-Solar.ENERGY_Power
ObjectBrowser.js:2317 - unsubscribe sonoff.2.Sensor-Solar.ENERGY_Period
ObjectBrowser.js:2317 - unsubscribe sonoff.2.Sensor-Solar.ENERGY_Factor
ObjectBrowser.js:2317 - unsubscribe sonoff.2.Sensor-Solar.ENERGY_Current
ObjectBrowser.js:2317 - unsubscribe sonoff.2.Sensor-Solar.ENERGY_ApparentPower
ObjectBrowser.js:2301 + subscribe sonoff.2.info.connection
ObjectBrowser.js:2150 > stateChange sonoff.2.info.connection
ObjectBrowser.js:1801 - unsubscribe web.0.connected
ObjectBrowser.js:1801 - unsubscribe sonoff.2.info.connection
Adapters.js:447 [ADAPTERS] getAdapters
Adapters.js:651 [ADAPTERS] getAdaptersInfo
2Adapters.js:1443 [ADAPTERS] Render
:8081/adapter/socketio/socketio.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/adapter/sql/sql.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
raw.githubusercontent.com/instalator/ioBroker.vis-players/master/admin/players.png:1 Failed to load resource: the server responded with a status of 404 ()
Adapters.js:1443 [ADAPTERS] Render
react-dom.production.min.js:216 DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Mi (http://192.168.2.151:8081/static/js/5.bde6ca2f.chunk.js:2:5519083)
    at Mi (http://192.168.2.151:8081/static/js/5.bde6ca2f.chunk.js:2:5519156)
    at Mi (http://192.168.2.151:8081/static/js/5.bde6ca2f.chunk.js:2:5519156)
    at Mi (http://192.168.2.151:8081/static/js/5.bde6ca2f.chunk.js:2:5519156)
    at Mi (http://192.168.2.151:8081/static/js/5.bde6ca2f.chunk.js:2:5519156)
    at bi (http://192.168.2.151:8081/static/js/5.bde6ca2f.chunk.js:2:5518581)
    at jl (http://192.168.2.151:8081/static/js/5.bde6ca2f.chunk.js:2:5531362)
    at t.unstable_runWithPriority (http://192.168.2.151:8081/static/js/5.bde6ca2f.chunk.js:2:5558154)
    at Wa (http://192.168.2.151:8081/static/js/5.bde6ca2f.chunk.js:2:5474540)
    at Vl (http://192.168.2.151:8081/static/js/5.bde6ca2f.chunk.js:2:5529523)
ii @ react-dom.production.min.js:216

**Comment by Apollon77** [comment]
What exactly you mean? The adapter is not working any longer? Then open an issue with adapter. Else please be more specific what this should has to do with Admin. Thank you
