### ISSUE TITLE
Fehler in der GUI

### ISSUE THREAD

**Issue by Mike2302** [ioBroker/ioBroker.admin#1219]
Guten Abend,

folgenden Fehler habe ich wenn ich den S7 Adapter nutzen möchte
iobroker.admin@5.2.1
socket.io.js:59 [2021-11-29T17:36:05.673Z] Try to connect
VM15:317 
        
       edge Translation started
translateInternal @ VM15:317
ObjectBrowser.js:2317 + subscribe s7.0.info.connection
ObjectBrowser.js:2317 + subscribe s7.0.info.pdu
ObjectBrowser.js:2317 + subscribe s7.0.info.poll_time
ObjectBrowser.js:2317 + subscribe web.0.connected
ObjectBrowser.js:2158 > stateChange s7.0.info.connection
ObjectBrowser.js:2158 > stateChange s7.0.info.pdu
ObjectBrowser.js:2158 > stateChange s7.0.info.poll_time
ObjectBrowser.js:2158 > stateChange web.0.connected
S7.png:1 
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
2ObjectBrowser.js:2158 > stateChange s7.0.info.poll_time
ObjectBrowser.js:2317 + subscribe s7.0.Inputs.1.0
2react-dom.production.min.js:216 
        
       DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at _i (https://192.168.178.48:8081/static/js/5.11c30091.chunk.js:2:5653795)
    at Tl (https://192.168.178.48:8081/static/js/5.11c30091.chunk.js:2:5665585)
    at t.unstable_runWithPriority (https://192.168.178.48:8081/static/js/5.11c30091.chunk.js:2:5692108)
    at Ga (https://192.168.178.48:8081/static/js/5.11c30091.chunk.js:2:5608675)
    at xl (https://192.168.178.48:8081/static/js/5.11c30091.chunk.js:2:5663543)
    at zl (https://192.168.178.48:8081/static/js/5.11c30091.chunk.js:2:5659629)
    at https://192.168.178.48:8081/static/js/5.11c30091.chunk.js:2:5608898
    at t.unstable_runWithPriority (https://192.168.178.48:8081/static/js/5.11c30091.chunk.js:2:5692108)
    at Ga (https://192.168.178.48:8081/static/js/5.11c30091.chunk.js:2:5608675)
    at Ka (https://192.168.178.48:8081/static/js/5.11c30091.chunk.js:2:5608843)
ui @ react-dom.production.min.js:216
ObjectBrowser.js:1809 - unsubscribe s7.0.info.connection
ObjectBrowser.js:1809 - unsubscribe s7.0.info.pdu
ObjectBrowser.js:1809 - unsubscribe s7.0.info.poll_time
ObjectBrowser.js:1809 - unsubscribe web.0.connected
ObjectBrowser.js:1809 - unsubscribe s7.0.Inputs.1.0
ObjectBrowser.js:2158 > stat

ich bin zimlich neu auf dem Gebiet ioBroker, habe keine Ahnung wo ich da ansetzten soll.

als System nutzte ich einen Raspberry pi 4 mit 4 GB und 32GB SD Karte, angebunden per LAN

es wäre super wenn mir da jemand helfen könnte.

Vielen Dank

**Comment by GermanBluefox** [comment]
Browser refresh sollte das Problem fixen

**Comment by lobomau76** [comment]
@Mike2302 hat bei dir Browser refresh etwas gebracht? Mir mir nur für eine Sekunde, dann kommt sofrt wieder das Error in GUI (siehe issue 1273)

**Comment by Feuer-sturm** [comment]
No more feedback. Issue closed.
