### ISSUE TITLE
not possible to change any sql settings

### ISSUE THREAD

**Issue by magi1982** [ioBroker/ioBroker.admin#1284]
**Describe the bug**  
If i click in the obects the gear to manage sql settings this error comes
**To Reproduce**  
1. objects
2. clock on a active sql state on the "gear" button
3. error promts

**Expected behavior**  
Failed to load resource: the server responded with a status of 404 (Not Found)
socketio.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
upnp.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
web.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)

TypeError: o.getHours is not a function
    at new s (ObjectChart.js:160:32)
    at zc (react-dom.production.min.js:135:172)
    at Uo (react-dom.production.min.js:181:146)
    at Zi (react-dom.production.min.js:269:427)
    at jl (react-dom.production.min.js:250:347)
    at Sl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at zl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: sql.1 <v1.15.7>
 - JS-Controller version: <3.3.22> 
 - Node version: <v12.22.6> 
 - Operating system: <linux on raspberry "core">

**Additional context**

**Comment by magi1982** [comment]
Update: this error only comes if i use a state that already has sql activatet. if i click on a state where sql is not active i can configure the sql settings

**Comment by magi1982** [comment]
I could solve the issue. I deleted the browser cache from chrome and it worked again.

**Comment by magi1982** [comment]
I could solve the issue. I deleted the browser cache from chrome and it worked again.
