### ISSUE TITLE
Message "Error in GUI" when i try to open the Tab "adapters"

### ISSUE THREAD

**Issue by dachauan** [ioBroker/ioBroker.admin#1295]
Message "Error in GUI" when i try to open the Tab "adapters"

react-dom.production.min.js:216 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BAdapter%20to%20query%20values%20from%20sma%20devices%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ec (react-dom.production.min.js:140:47)
    at react-dom.production.min.js:150:265
    at Po (react-dom.production.min.js:176:171)
    at Zi (react-dom.production.min.js:271:134)
    at jl (react-dom.production.min.js:250:347)
    at Sl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at zl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)

Node.js
v14.18.3

**Comment by GermanBluefox** [comment]
Is still reproducible?

**Comment by Feuer-sturm** [comment]
No more feedback. Issue closed.
