### ISSUE TITLE
Update auf v5.2.3 fehlgeschlagen

### ISSUE THREAD

**Issue by Steiger04** [ioBroker/ioBroker.admin#1296]
**Describe the bug**  
Das Update von Adminversion 5.2.1 auf Adminversion 5.2.3 ist fehlgeschlagen. Es scheint Probleme mit der neuen  web-socket library zu geben. Ich nutze den Dockercontainer von buanet.

**Screenshots & Logfiles**  
```
2022-01-26 14:51:24.961  - info: host.iobrokerproduktion iobroker upgrade admin@5.2.3
2022-01-26 14:51:27.080  - info: host.iobrokerproduktion iobroker Update admin from @5.2.1 to @5.2.3
2022-01-26 14:51:27.110  - info: host.iobrokerproduktion iobroker host.iobrokerproduktion Adapter "system.adapter.admin.0" is stopped.
2022-01-26 14:51:27.142  - info: host.iobrokerproduktion "system.adapter.admin.0" disabled
2022-01-26 14:51:27.145  - info: host.iobrokerproduktion stopInstance system.adapter.admin.0 (force=false, process=true)
2022-01-26 14:51:27.151  - info: host.iobrokerproduktion stopInstance system.adapter.admin.0 send kill signal
2022-01-26 14:51:27.646  - info: host.iobrokerproduktion iobroker NPM version: 6.14.15
2022-01-26 14:51:27.649  - info: host.iobrokerproduktion iobroker npm install iobroker.admin@5.2.3 --loglevel error --prefix "/opt/iobroker" (System call)
================================== > LOG REDIRECT system.adapter.admin.0 => false [Process stopped]
2022-01-26 14:51:27.766  - info: host.iobrokerproduktion instance system.adapter.admin.0 terminated with code 0 (NO_ERROR)
================================== > LOG REDIRECT system.adapter.admin.0 => false [system.adapter.admin.0.logging]
2022-01-26 14:53:11.488  - info: host.iobrokerproduktion iobroker upload [14] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/words.js words.js application/javascript
2022-01-26 14:53:11.543  - info: host.iobrokerproduktion iobroker Update "system.adapter.admin.0"
2022-01-26 14:53:11.666  - info: host.iobrokerproduktion iobroker upload [13] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/jsonConfig.json jsonConfig.json application/json
2022-01-26 14:53:11.724  - info: host.iobrokerproduktion iobroker upload [12] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/index_m.html index_m.html text/html
2022-01-26 14:53:11.781  - info: host.iobrokerproduktion iobroker upload [11] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/index.html index.html text/html
2022-01-26 14:53:11.840  - info: host.iobrokerproduktion iobroker upload [10] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/zh-cn/translations.json i18n/zh-cn/translations.json application/json
2022-01-26 14:53:11.897  - info: host.iobrokerproduktion iobroker upload [9] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/ru/translations.json i18n/ru/translations.json application/json
2022-01-26 14:53:11.954  - info: host.iobrokerproduktion iobroker upload [8] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/pt/translations.json i18n/pt/translations.json application/json
2022-01-26 14:53:12.026  - info: host.iobrokerproduktion iobroker upload [7] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/pl/translations.json i18n/pl/translations.json application/json
2022-01-26 14:53:12.084  - info: host.iobrokerproduktion iobroker upload [6] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/nl/translations.json i18n/nl/translations.json application/json
2022-01-26 14:53:12.140  - info: host.iobrokerproduktion iobroker upload [5] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/it/translations.json i18n/it/translations.json application/json
2022-01-26 14:53:12.197  - info: host.iobrokerproduktion iobroker upload [4] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/fr/translations.json i18n/fr/translations.json application/json
2022-01-26 14:53:12.253  - info: host.iobrokerproduktion iobroker upload [3] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/es/translations.json i18n/es/translations.json application/json
2022-01-26 14:53:12.310  - info: host.iobrokerproduktion iobroker upload [2] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/en/translations.json i18n/en/translations.json application/json
2022-01-26 14:53:12.365  - info: host.iobrokerproduktion iobroker upload [1] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/de/translations.json i18n/de/translations.json application/json
2022-01-26 14:53:12.422  - info: host.iobrokerproduktion iobroker upload [0] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/admin.png admin.png image/png
2022-01-26 14:53:12.480  - info: host.iobrokerproduktion iobroker Adapter "admin" updated
2022-01-26 14:53:12.481  - info: host.iobrokerproduktion iobroker host.iobrokerproduktion Adapter "system.adapter.admin.0" is started
2022-01-26 14:53:12.507  - info: host.iobrokerproduktion "system.adapter.admin.0" enabled
2022-01-26 14:53:12.649  - info: host.iobrokerproduktion instance system.adapter.admin.0 started with pid 5398
2022-01-26 14:53:13.566  - info: host.iobrokerproduktion iobroker exit 0
TypeError: bufferUtil.unmask is not a function
    at unmask (/opt/iobroker/node_modules/iobroker.admin/node_modules/ws/lib/buffer-util.js:115:23)
    at Receiver.getData (/opt/iobroker/node_modules/iobroker.admin/node_modules/ws/lib/receiver.js:425:9)
    at Receiver.startLoop (/opt/iobroker/node_modules/iobroker.admin/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/opt/iobroker/node_modules/iobroker.admin/node_modules/ws/lib/receiver.js:83:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Receiver.Writable.write (internal/streams/writable.js:303:10)
    at Socket.socketOnData (/opt/iobroker/node_modules/iobroker.admin/node_modules/ws/lib/websocket.js:1192:35)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at addChunk (internal/streams/readable.js:293:12)

================================== > LOG REDIRECT system.adapter.admin.0 => false [Process stopped]
2022-01-26 14:53:22.466  - error: host.iobrokerproduktion Caught by controller[0]: TypeError: bufferUtil.unmask is not a function
2022-01-26 14:53:22.467  - error: host.iobrokerproduktion Caught by controller[0]:     at unmask (/opt/iobroker/node_modules/iobroker.admin/node_modules/ws/lib/buffer-util.js:115:23)
2022-01-26 14:53:22.468  - error: host.iobrokerproduktion Caught by controller[0]:     at Receiver.getData (/opt/iobroker/node_modules/iobroker.admin/node_modules/ws/lib/receiver.js:425:9)
2022-01-26 14:53:22.468  - error: host.iobrokerproduktion Caught by controller[0]:     at Receiver.startLoop (/opt/iobroker/node_modules/iobroker.admin/node_modules/ws/lib/receiver.js:148:22)
2022-01-26 14:53:22.469  - error: host.iobrokerproduktion Caught by controller[0]:     at Receiver._write (/opt/iobroker/node_modules/iobroker.admin/node_modules/ws/lib/receiver.js:83:10)
2022-01-26 14:53:22.469  - error: host.iobrokerproduktion Caught by controller[0]:     at writeOrBuffer (internal/streams/writable.js:358:12)
2022-01-26 14:53:22.470  - error: host.iobrokerproduktion Caught by controller[0]:     at Receiver.Writable.write (internal/streams/writable.js:303:10)
2022-01-26 14:53:22.470  - error: host.iobrokerproduktion Caught by controller[0]:     at Socket.socketOnData (/opt/iobroker/node_modules/iobroker.admin/node_modules/ws/lib/websocket.js:1192:35)
2022-01-26 14:53:22.470  - error: host.iobrokerproduktion Caught by controller[0]:     at Socket.emit (events.js:400:28)
2022-01-26 14:53:22.471  - error: host.iobrokerproduktion Caught by controller[0]:     at Socket.emit (domain.js:475:12)
2022-01-26 14:53:22.471  - error: host.iobrokerproduktion Caught by controller[0]:     at addChunk (internal/streams/readable.js:293:12)
2022-01-26 14:53:22.472  - error: host.iobrokerproduktion instance system.adapter.admin.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
```

**Versions:**  
 - Adapter version: 5.2.3
 - JS-Controller version: 3.3.22
 - Node version: 14.18.3
 - Operating system: Dockercontainer von Buanet v6.0.0
 -

**Comment by Apollon77** [comment]
Da scheint irgendwas in deinen npm Paketen nicht zu stimmen! Da scheint das Paket bufferutil defekt zu sein.

Gab es ggf ein nodejs update oder ein  major update des Containers (was ggf ein nodejs upgrade bedeutet oder das npm pakete rebuilded wurden?

**Comment by Steiger04** [comment]
@Apollon77 Ja gab es. Ich hab für Admin 5.2.3 den iobroker container neu gebaut und dafür das neueste Image von iobroker (Buanet v6.0.0) genommen, da im alten, von mir bisher verwendeten  Image, noch node v12 drin war. Ich hab aber dann zur Insallation des neuen Admin v5.2.3 den alten Admin v5.2.1 erst komplett deinstalliert und dann via iobroker install admin@5.2.3 und anschliessendem iobroker add admin.0 die neue Version installiert und eine Instanz gestartet. Bei der Vorgehensweise dürfte doch npm-seitig eigentlich nichts passiert sein, oder? Hast Du da noch einen Tip für mich, was ich jetzt am sinnvollsten probiern sollte?

**Comment by Apollon77** [comment]
Bei nodejs Major updates muss ein "npm rebuild" ausgeführt werden damit die Binär-Module neu erstellt werden

**Comment by Steiger04** [comment]
@Apollon77 Ich habe jetzt ein "npm rebuild" im iobroker.admin Ordner durchgeführt, nachdem ich  die v5.2.3 installiert habe. Die Fehlermeldung ist identisch. Mir ist auch noch nicht ganz klar was "npm rebuild" an der Stelle bewirken soll, da ich ja vor der Neuinstallation des Admin v5.2.3 den alten Admin (bei mir v5.2.1) komplett gelöscht hatte, mithin also auch das nod_modules-Verzeichnis innerhalb von iobroker.admin.  Der Fehler taucht ja unter:
`/opt/iobroker/node_modules/iobroker.admin/node_modules/ws/lib/websocket.js`
auf. D.h. mit dem Entfernen und der Neuanlage des Admin unter node 14 sollte dann doch auch die ws-Library "richtig" gebuildet worden seien, oder? Ich muss allerdings gestehen, dass ich mich mit den Tiefen von npm noch nicht intensiv befasst habe. Ist denn das gesagte von mir soweit richtig, oder muss ich den "npm rebulid" direkt im iobroker-Verzeichnis ausführen?

**Comment by Apollon77** [comment]
neeee "npm rebuild" muss quasi in "/opt/iobroker" laufen

**Comment by GermanBluefox** [comment]
```
cd node_modules/iobroker.admin
npm i bufferutil@4.0.1 --production
```
Sollte das Problem lösen

**Comment by Feuer-sturm** [comment]
@Steiger04 Ist das issue noch aktiv?
