### ISSUE TITLE
Error: Minified React error #137;

### ISSUE THREAD

**Issue by q1w2q1** [ioBroker/ioBroker.admin#1328]
Error: Minified React error #137; visit https://reactjs.org/docs/error-decoder.html?invariant=137&args[]=meta for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ee (react-dom.production.min.js:47:92)
    at ii (react-dom.production.min.js:208:42)
    at Ll (react-dom.production.min.js:251:81)
    at jl (react-dom.production.min.js:250:408)
    at Sl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at zl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
    at Ka (react-dom.production.min.js:123:61)
    at Za (react-dom.production.min.js:122:428)
    at pl (react-dom.production.min.js:237:203)
    at Object.enqueueSetState (react-dom.production.min.js:133:211)
    at a.m.setState (react.production.min.js:12:369)
    at a.<anonymous> (AdapterInfoDialog.js:76:18)
    at u (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at i (asyncToGenerator.js:25:9)
(anonymous) @ instrument.ts:125

**Comment by Feuer-sturm** [comment]
@q1w2q1 which admin version do you use? What did you do to see the error?

**Comment by Feuer-sturm** [comment]
No more feedback. Issue closed.
