### ISSUE TITLE
User Tab | Error in GUI

### ISSUE THREAD

**Issue by Sakul85** [ioBroker/ioBroker.admin#1351]
**When clicking on the tab "users" this error appears:**

```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ec (react-dom.production.min.js:140:47)
    at react-dom.production.min.js:150:265
    at Po (react-dom.production.min.js:176:171)
    at Zi (react-dom.production.min.js:271:134)
    at jl (react-dom.production.min.js:250:347)
    at Sl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at zl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
    at Ka (react-dom.production.min.js:123:61)
    at Za (react-dom.production.min.js:122:428)
    at pl (react-dom.production.min.js:237:203)
    at Object.enqueueSetState (react-dom.production.min.js:133:211)
    at s.m.setState (react.production.min.js:12:369)
    at UsersList.js:331:22
```

**Versions:**  
 - Admin v5.3.1
 - JS-Controller version: 4.0.15
 - Node version: v12.22.5
 - Operating system: linux lxc ubuntu 21.10
 - Clean and fresh installation with ioBroker script

**Comment by Feuer-sturm** [comment]
Is duplicate to https://github.com/ioBroker/ioBroker.admin/issues/1337
