### ISSUE TITLE
Error in GUI - Tab-Users

### ISSUE THREAD

**Issue by 1stXerox** [ioBroker/ioBroker.admin#1352]
**Describe the bug**  
Click ob tab "Users" leads to GUI Error.

**To Reproduce**  
1. Click on Users

**Screenshots & Logfiles**  
instrument.ts:125 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ec (react-dom.production.min.js:140:47)
    at react-dom.production.min.js:150:265
    at Po (react-dom.production.min.js:176:171)
    at Zi (react-dom.production.min.js:271:134)
    at jl (react-dom.production.min.js:250:347)
    at Sl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at zl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
    at Ka (react-dom.production.min.js:123:61)
    at Za (react-dom.production.min.js:122:428)
    at pl (react-dom.production.min.js:237:203)
    at Object.enqueueSetState (react-dom.production.min.js:133:211)
    at s.m.setState (react.production.min.js:12:369)
    at UsersList.js:331:22

**Versions:**  
 - Adapter version: v5.3.1 (Docker Container)
 - Operating system: Raspberry Pi OS lite 64 bit

**Comment by Feuer-sturm** [comment]
Is duplicate to https://github.com/ioBroker/ioBroker.admin/issues/1337
