### ISSUE TITLE
Error in Gui Tab Hosts

### ISSUE THREAD

**Issue by martinschm** [ioBroker/ioBroker.admin#1353]
I have opened the host Tab, went to settings of my slave iobroker and clicked the "log" sub-tab. Then the screen appeared that there was a bug which I am hereby reporting:

```
instrument.ts:125 TypeError: Cannot read properties of undefined (reading 'includes')
    at :8081/static/js/12.dafd75b0.chunk.js:1:91672
    at Array.forEach (<anonymous>)
    at new s (:8081/static/js/12.dafd75b0.chunk.js:1:91589)
    at zc (6.501acaca.chunk.js:2:5593946)
    at Uo (6.501acaca.chunk.js:2:5613412)
    at Zi (6.501acaca.chunk.js:2:5656945)
    at jl (6.501acaca.chunk.js:2:5643113)
    at Sl (6.501acaca.chunk.js:2:5643041)
    at Cl (6.501acaca.chunk.js:2:5642904)
    at zl (6.501acaca.chunk.js:2:5639870)
    at 6.501acaca.chunk.js:2:5589364
    at t.unstable_runWithPriority (6.501acaca.chunk.js:2:5672574)
    at Ga (6.501acaca.chunk.js:2:5589141)
    at Ka (6.501acaca.chunk.js:2:5589309)
    at Za (6.501acaca.chunk.js:2:5589244)
    at ke (6.501acaca.chunk.js:2:5660411)
    at Yt (6.501acaca.chunk.js:2:5567862)
    at HTMLBodyElement.a (6.501acaca.chunk.js:2:6337076)
```

Admin 5.3.1
js-controller 4.1.5.

**Comment by Feuer-sturm** [comment]
Is duplicate to https://github.com/ioBroker/ioBroker.admin/issues/1327
