### ISSUE TITLE
Error in GUI

### ISSUE THREAD

**Issue by alexbababu** [ioBroker/ioBroker.admin#1357]
**Describe the bug**  
Clean Install ioborker via buanet container in docker on NAS
After installation is done, go through assistant setup.
After first discovery of adapters, click on "cloud" and got this error

New Screen asks me to get this log and open an issue on github

**Screenshots & Logfiles**  

```
instrument.ts:125 TypeError: Cannot read properties of undefined (reading 'icon')
    at DiscoveryDialog.js:800:114
    at Array.map (<anonymous>)
    at xi (DiscoveryDialog.js:788:43)
    at oo (react-dom.production.min.js:157:137)
    at $o (react-dom.production.min.js:180:154)
    at Zi (react-dom.production.min.js:269:343)
    at jl (react-dom.production.min.js:250:347)
    at Sl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at zl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
    at Ka (react-dom.production.min.js:123:61)
    at Za (react-dom.production.min.js:122:428)
    at react-dom.production.min.js:244:114
    at Re (react-dom.production.min.js:292:136)
    at De (react-dom.production.min.js:49:410)
    at react-dom.production.min.js:50:81
    at Rr (react-dom.production.min.js:105:469)
    at Qt (react-dom.production.min.js:75:265)
    at Jt (react-dom.production.min.js:74:124)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
    at ke (react-dom.production.min.js:292:48)
    at Yt (react-dom.production.min.js:73:352)
    at HTMLBodyElement.a (helpers.ts:98:17)


```

**Comment by Feuer-sturm** [comment]
@alexbababu Please verify with Admin 5.3.2
