### ISSUE TITLE
Error in GUI!

### ISSUE THREAD

**Issue by exaware** [ioBroker/ioBroker.admin#1361]
index.js:18 iobroker.admin@5.3.1
instrument.ts:125 [2022-03-09T08:26:09.042Z] Try to connect
instrument.ts:125 Translate: time
instrument.ts:125 Translate: timeOffset
instrument.ts:125 Translate: time
instrument.ts:125 Translate: timeOffset
instrument.ts:125 Translate: time
instrument.ts:125 Translate: timeOffset
instrument.ts:125 Translate: You can enter more than one address divided by comma
instrument.ts:125 TypeError: Cannot read properties of null (reading 'includes')
    at :8081/static/js/12.dafd75b0.chunk.js:1:91672
    at Array.forEach (<anonymous>)
    at new s (:8081/static/js/12.dafd75b0.chunk.js:1:91589)
    at zc (6.501acaca.chunk.js:2:5593946)
    at Uo (6.501acaca.chunk.js:2:5613412)
    at Zi (6.501acaca.chunk.js:2:5656945)
    at jl (6.501acaca.chunk.js:2:5643113)
    at Sl (6.501acaca.chunk.js:2:5643041)
    at Cl (6.501acaca.chunk.js:2:5642904)
    at zl (6.501acaca.chunk.js:2:5639870)
    at 6.501acaca.chunk.js:2:5589364
    at t.unstable_runWithPriority (6.501acaca.chunk.js:2:5672574)
    at Ga (6.501acaca.chunk.js:2:5589141)
    at Ka (6.501acaca.chunk.js:2:5589309)
    at Za (6.501acaca.chunk.js:2:5589244)
    at ke (6.501acaca.chunk.js:2:5660411)
    at Yt (6.501acaca.chunk.js:2:5567862)
    at HTMLBodyElement.a (6.501acaca.chunk.js:2:6337076)
(anonymous) @ instrument.ts:125

**Comment by Feuer-sturm** [comment]
@exaware which menu did you enter to trigger the error?

**Comment by exaware** [comment]
![image](https://user-images.githubusercontent.com/55593493/157437010-a958305c-7780-4600-8634-7294ee2378ef.png)

**Comment by Feuer-sturm** [comment]
Thanks. This issue is duplicate to #1327
