### ISSUE TITLE
Error in GUI

### ISSUE THREAD

**Issue by Schorsch99** [ioBroker/ioBroker.admin#1362]
I get a GUI Error when trying to access the "Log" tab in the host settings (Hosts > Host-Basiseinstellungen > Log)

admin 5.3.1
js controller 4.0.19
Node.js v14.19.0

instrument.ts:125 TypeError: Cannot read properties of null (reading 'includes')
    at BaseSettingsLog.js:77:65
    at Array.forEach (<anonymous>)
    at new s (BaseSettingsLog.js:75:41)
    at zc (react-dom.production.min.js:135:172)
    at Uo (react-dom.production.min.js:181:146)
    at Zi (react-dom.production.min.js:269:427)
    at jl (react-dom.production.min.js:250:347)
    at Sl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at zl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
    at Ka (react-dom.production.min.js:123:61)
    at Za (react-dom.production.min.js:122:428)
    at ke (react-dom.production.min.js:292:101)
    at Yt (react-dom.production.min.js:73:352)
    at HTMLBodyElement.a (helpers.ts:98:17)

**Comment by Schorsch99** [comment]
Sorry, just noticed that it is duplicate to https://github.com/ioBroker/ioBroker.admin/issues/1327

**Comment by Feuer-sturm** [comment]
No problem :-)
