### ISSUE TITLE
Fehler in der GUI

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.admin#1375]
Fehler in der GUI, wenn man aus dem skriptadapter heraus auf Instanzen klickt:

`ncaught Error: Cannot read properties of null (reading '0')

TypeError: Cannot read properties of null (reading '0')
    at v.fire (:8081/adapter/javascript/vs/editor/editor.main.js:51:1837)
    at k.x.onMouseDown (:8081/adapter/javascript/vs/editor/editor.main.js:622:18133)
    at k.emitMouseDown (:8081/adapter/javascript/vs/editor/editor.main.js:611:24840)
    at L.emitMouseDown (:8081/adapter/javascript/vs/editor/editor.main.js:620:60000)
    at r._onMouseDown (:8081/adapter/javascript/vs/editor/editor.main.js:611:14634)
    at :8081/adapter/javascript/vs/editor/editor.main.js:611:11904
    at HTMLDivElement.<anonymous> (:8081/adapter/javascript/vs/editor/editor.main.js:125:7626)
    at HTMLDivElement.a (:8081/adapter/javascript/static/js/2.b7bbd921.chunk.js:2:86054)
    at :8081/adapter/javascript/vs/editor/editor.main.js:6:56079
    at a (:8081/adapter/javascript/static/js/2.b7bbd921.chunk.js:2:86054)`

**Comment by Feuer-sturm** [comment]
@BenAhrdt Hast du einen Screenshot wo du draufgeklickt hast der näher beschreibt, was du mit "wenn man aus dem skriptadapter heraus auf Instanzen klickt:" meinst?

**Comment by BenAhrdt** [comment]
Es könnte sein, dass das Problem daran liegt, dass wenn ich über den Namen der Nas und den Port zugreife.
Habe jetzt mal umgestellt und greife über die IP zu und bis jetzt ist es nicht mehr aufgetreten.

**Comment by Feuer-sturm** [comment]
@BenAhrdt worauf hast du denn zugegriffen? Wollte versuchen es einmal bei mir nachzustellen aber ich weiß nicht was du machst, wenn du schreibst "wenn man aus dem skriptadapter heraus auf Instanzen klickt".

**Comment by BenAhrdt** [comment]
Ich hatte ein Skript offen und habe irgendwo links auf die Navigation geklickt.

**Comment by GermanBluefox** [comment]
Es ist sowieso das Problem mit javascript und nicht Admin
