### ISSUE TITLE
Problem Iobroker nach Stromausfall

### ISSUE THREAD

**Issue by ThePoshExpert** [ioBroker/ioBroker.admin#1379]
**Describe the bug**  
ChunkLoadError: Loading chunk 11 failed.
(missing: https://iobroker:8081/static/js/11.3f36021b.chunk.js)
    at Function.u.e (iobroker/:1:3998)
    at main.22a9d49c.chunk.js:2:1113718
    at V (6.501acaca.chunk.js:2:5666268)
    at Zi (6.501acaca.chunk.js:2:5656452)
    at jl (6.501acaca.chunk.js:2:5643113)
    at Sl (6.501acaca.chunk.js:2:5643041)
    at Cl (6.501acaca.chunk.js:2:5642904)
    at zl (6.501acaca.chunk.js:2:5639870)
    at 6.501acaca.chunk.js:2:5589364
    at t.unstable_runWithPriority (6.501acaca.chunk.js:2:5672574)
    at Ga (6.501acaca.chunk.js:2:5589141)
    at Ka (6.501acaca.chunk.js:2:5589309)
    at Za (6.501acaca.chunk.js:2:5589244)
    at pl (6.501acaca.chunk.js:2:5637247)
    at Object.enqueueSetState (6.501acaca.chunk.js:2:5593262)
    at o.m.setState (6.501acaca.chunk.js:2:5664084)
    at n.onHashChanged (main.22a9d49c.chunk.js:2:1119896)
    at a (6.501acaca.chunk.js:2:6337076)
(anonym) @ instrument.ts:125

**To Reproduce**  
1. Install DIscovery Adapter, while after successfull Host Update stated it is missing:
The following notifications happened during sync:
- Ignoring Directory "discovery.admin" because officially not created as meta object. Please remove directory!
- Ignoring Directory "mqtt-client.admin" because officially not created as meta object. Please remove directory!
2. after installing Browser did a refresh and the error occured:
3. https://iobroker:8081/#tab-instances/config/system.adapter.discovery.0

**Expected behavior**  
Expected discovery Adapter to be installed and config site to open.

**Screenshots & Logfiles**  
see above

**Versions:**  
 - Adapter version: admin 5.3.1;discovery 2.7.5
 - JS-Controller version: 4.0.21
 - Node version: v12.22.4
 - Operating system: Debian GNU/Linux

**Additional context**

**Comment by Apollon77** [comment]
Does it work that after installing discovery you can open the Page? Could maybe a browser reload help?

**Comment by ThePoshExpert** [comment]
Yes, a browser reload did help. Not sure why this even came up, but now everything is fine. Discovery Adapter could be installed without issues. Thank you!
