### ISSUE TITLE
Error in GUI unter Host/Hostbasiseinstellung

### ISSUE THREAD

**Issue by mrjeschke** [ioBroker/ioBroker.admin#1381]
Wenn man unter Host/Host-Basiseintellung auf Log klickt kommt ein Error in GUI.
(Version 4.0.21)
instrument.ts:125
 
        
`    TypeError: Cannot read properties of null (reading 'includes')
    at BaseSettingsLog.js:77:65
    at Array.forEach (<anonymous>)
    at new s (BaseSettingsLog.js:75:41)
    at zc (react-dom.production.min.js:135:172)
    at Uo (react-dom.production.min.js:181:146)
    at Zi (react-dom.production.min.js:269:427)
    at jl (react-dom.production.min.js:250:347)
    at Sl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at zl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
    at Ka (react-dom.production.min.js:123:61)
    at Za (react-dom.production.min.js:122:428)
    at ke (react-dom.production.min.js:292:101)
    at Yt (react-dom.production.min.js:73:352)
    at HTMLBodyElement.a (helpers.ts:98:17)
(anonym) @ instrument.ts:125
ui @ react-dom.production.min.js:216
n.payload @ react-dom.production.min.js:217
fc @ react-dom.production.min.js:130
Uo @ react-dom.production.min.js:184
Zi @ react-dom.production.min.js:269
jl @ react-dom.production.min.js:250
Sl @ react-dom.production.min.js:250
Cl @ react-dom.production.min.js:250
zl @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
Za @ react-dom.production.min.js:122
ke @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
a @ helpers.ts:98

`

**Comment by crunchip77** [comment]
bei mir das selbe, js-controller Installiert: 4.0.21, admin 5.3.1, Browser Edge, Chrome, Opera, FF
`instrument.ts:125 TypeError: Cannot read properties of undefined (reading 'includes')
    at BaseSettingsLog.js:77:65
    at Array.forEach (<anonymous>)
    at new s (BaseSettingsLog.js:75:41)
    at zc (react-dom.production.min.js:135:172)
    at Uo (react-dom.production.min.js:181:146)
    at Zi (react-dom.production.min.js:269:427)
    at jl (react-dom.production.min.js:250:347)
    at Sl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at zl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
    at Ka (react-dom.production.min.js:123:61)
    at Za (react-dom.production.min.js:122:428)
    at ke (react-dom.production.min.js:292:101)
    at Yt (react-dom.production.min.js:73:352)
    at HTMLBodyElement.a (helpers.ts:98:17)
(anonymous) @ instrument.ts:125
ui @ react-dom.production.min.js:216
n.payload @ react-dom.production.min.js:217
fc @ react-dom.production.min.js:130
Uo @ react-dom.production.min.js:184
Zi @ react-dom.production.min.js:269
jl @ react-dom.production.min.js:250
Sl @ react-dom.production.min.js:250
Cl @ react-dom.production.min.js:250
zl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
Za @ react-dom.production.min.js:122
ke @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
a @ helpers.ts:98
`

**Comment by Feuer-sturm** [comment]
Issue is duplicate to #1327
