### ISSUE TITLE
Error in GUI

### ISSUE THREAD

**Issue by BOSC4895** [ioBroker/ioBroker.admin#1410]
Von Instanzen nach Objekte gewechselt

28instrument.ts:124 
        
       DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at _i (http://192.168.1.21:8081/static/js/6.1cf1778f.chunk.js:2:5632131)
    at Tl (http://192.168.1.21:8081/static/js/6.1cf1778f.chunk.js:2:5643921)
    at t.unstable_runWithPriority (http://192.168.1.21:8081/static/js/6.1cf1778f.chunk.js:2:5670444)
    at Ga (http://192.168.1.21:8081/static/js/6.1cf1778f.chunk.js:2:5587011)
    at xl (http://192.168.1.21:8081/static/js/6.1cf1778f.chunk.js:2:5641879)
    at bl (http://192.168.1.21:8081/static/js/6.1cf1778f.chunk.js:2:5637965)
    at http://192.168.1.21:8081/static/js/6.1cf1778f.chunk.js:2:5587234
    at t.unstable_runWithPriority (http://192.168.1.21:8081/static/js/6.1cf1778f.chunk.js:2:5670444)
    at Ga (http://192.168.1.21:8081/static/js/6.1cf1778f.chunk.js:2:5587011)
    at Ka (http://192.168.1.21:8081/static/js/6.1cf1778f.chunk.js:2:5587179)
    at Za (http://192.168.1.21:8081/static/js/6.1cf1778f.chunk.js:2:5587114)
    at pl (http://192.168.1.21:8081/static/js/6.1cf1778f.chunk.js:2:5635117)
    at Object.enqueueSetState (http://192.168.1.21:8081/static/js/6.1cf1778f.chunk.js:2:5591132)
    at s.m.setState (http://192.168.1.21:8081/static/js/6.1cf1778f.chunk.js:2:5661954)
    at http://192.168.1.21:8081/static/js/3.e5852c98.chunk.js:1:90268
    at a (http://192.168.1.21:8081/static/js/6.1cf1778f.chunk.js:2:6328631)

**Comment by Feuer-sturm** [comment]
@BOSC4895 Welche Admin Version hast du im Einsatz?

**Comment by BOSC4895** [comment]
Sorry, Version 5.1.25

**Comment by Feuer-sturm** [comment]
Bitte einmal mit der aktuellen Version 5.3.4 gegentesten, ob das Problem dort auch noch existiert.

**Comment by GermanBluefox** [comment]
@BOSC4895  Ist sentry deaktiviert bei dir?

**Comment by GermanBluefox** [comment]
Fixed in Fixed in 5.4.7
