### ISSUE TITLE
Failture on creating instance

### ISSUE THREAD

**Issue by matzehard** [ioBroker/ioBroker.admin#1420]
I gon an error on creating an instance of an adapter installed directly from github (oilfox). I got the message "Error in GUI" to create a bugreport.

instrument.ts:124 Translation for word "Main settings" in "de" was ignored: existing = "Allgemeine Einstellungen", new = Haupteinstellungen
(anonymous) @ instrument.ts:124

instrument.ts:124 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at a.value (ConfigPanel.js:124:23)
    at a.value (ConfigPanel.js:262:31)
    at Go (react-dom.production.min.js:187:188)
    at Uo (react-dom.production.min.js:186:173)
    at Zi (react-dom.production.min.js:269:427)
    at jl (react-dom.production.min.js:250:347)
    at Sl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at bl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
    at Ka (react-dom.production.min.js:123:61)
    at Za (react-dom.production.min.js:122:428)
    at pl (react-dom.production.min.js:237:203)
    at Object.enqueueSetState (react-dom.production.min.js:133:211)
    at s.m.setState (react.production.min.js:12:369)
    at index.js:148:34

**Comment by Feuer-sturm** [comment]
I can reproduce the issue by installing the adater v4.1.1 using beta channel.

@Apollon77 @GermanBluefox Is this a issue for admin or for oilfox adapter?

**Comment by GermanBluefox** [comment]
Please update to new oilfox version

**Comment by Feuer-sturm** [comment]
With oilfox version 4.1.2 everything looks fine after adding an instance.
