### ISSUE TITLE
iobroker does not start after update of the admin adapter

### ISSUE THREAD

**Issue by kupeme** [ioBroker/ioBroker.admin#1427]
After I updated the admin adapter the iobroker cannot start the GUI

This is the error message (the output of the console is below)
```
Loading chunk 14 failed. (error: http://192.168.178.8:8081/static/js/14.b28d85a4.chunk.js)
ChunkLoadError: Loading chunk 14 failed.function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}(error: http://192.168.178.8:8081/static/js/14.b28d85a4.chunk.js)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Function.u.e (http://192.168.178.8:8081/:1:3974)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at http://192.168.178.8:8081/static/js/main.22a9d49c.chunk.js:2:1113786function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at V (http://192.168.178.8:8081/static/js/6.501acaca.chunk.js:2:5666268)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Zi (http://192.168.178.8:8081/static/js/6.501acaca.chunk.js:2:5656452)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at jl (http://192.168.178.8:8081/static/js/6.501acaca.chunk.js:2:5643113)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Sl (http://192.168.178.8:8081/static/js/6.501acaca.chunk.js:2:5643041)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Cl (http://192.168.178.8:8081/static/js/6.501acaca.chunk.js:2:5642904)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at zl (http://192.168.178.8:8081/static/js/6.501acaca.chunk.js:2:5639870)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at http://192.168.178.8:8081/static/js/6.501acaca.chunk.js:2:5589364function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at t.unstable_runWithPriority (http://192.168.178.8:8081/static/js/6.501acaca.chunk.js:2:5672574)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Ga (http://192.168.178.8:8081/static/js/6.501acaca.chunk.js:2:5589141)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Ka (http://192.168.178.8:8081/static/js/6.501acaca.chunk.js:2:5589309)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Za (http://192.168.178.8:8081/static/js/6.501acaca.chunk.js:2:5589244)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at pl (http://192.168.178.8:8081/static/js/6.501acaca.chunk.js:2:5637247)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Object.enqueueSetState (http://192.168.178.8:8081/static/js/6.501acaca.chunk.js:2:5593262)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at o.m.setState (http://192.168.178.8:8081/static/js/6.501acaca.chunk.js:2:5664084)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at http://192.168.178.8:8081/static/js/main.22a9d49c.chunk.js:2:1126466function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at u (http://192.168.178.8:8081/static/js/6.501acaca.chunk.js:2:5676516)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Generator._invoke (http://192.168.178.8:8081/static/js/6.501acaca.chunk.js:2:5676304)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Generator.next (http://192.168.178.8:8081/static/js/6.501acaca.chunk.js:2:5676945)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at r (http://192.168.178.8:8081/static/js/6.501acaca.chunk.js:2:35792)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at i (http://192.168.178.8:8081/static/js/6.501acaca.chunk.js:2:35995)

-------------------------------------------------------------------------------------------------------------------------

iobroker.admin@5.3.1
6.501acaca.chunk.js:2 [2022-04-13T22:44:31.083Z] Try to connect
DevTools failed to load source map: Could not load content for chrome-extension://gannpgaobkkhmpomoijebaigcapoeebl/bundle.min.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
6.501acaca.chunk.js:2 [2022-04-13T22:44:39.833Z] ws connection error: CLOSE_ABNORMAL
(anonymous) @ 6.501acaca.chunk.js:2
error @ socket.io.js:61
socket.onclose @ socket.io.js:131
6.501acaca.chunk.js:2 [2022-04-13T22:44:39.835Z] Start reconnect 0
6.501acaca.chunk.js:2 [2022-04-13T22:44:39.836Z] Try to connect
DevTools failed to load source map: Could not load content for http://192.168.178.8:8081/static/js/6.501acaca.chunk.js.map: HTTP error: status code 200, net::ERR_INCOMPLETE_CHUNKED_ENCODING
socket.io.js:94 WebSocket connection to 'ws://192.168.178.8:8081/?sid=1649889879837&name=admin' failed: 
SocketClient.connect @ socket.io.js:94
(anonymous) @ socket.io.js:375
a @ 6.501acaca.chunk.js:2
6.501acaca.chunk.js:2 [2022-04-13T22:44:41.891Z] Start reconnect 1
6.501acaca.chunk.js:2 [2022-04-13T22:44:41.892Z] ws connection error: CLOSE_ABNORMAL
(anonymous) @ 6.501acaca.chunk.js:2
error @ socket.io.js:61
socket.onclose @ socket.io.js:131
6.501acaca.chunk.js:2 [2022-04-13T22:44:41.892Z] Reconnect is already running 1
6.501acaca.chunk.js:2 [2022-04-13T22:44:42.893Z] Try to connect
socket.io.js:94 WebSocket connection to 'ws://192.168.178.8:8081/?sid=1649889882894&name=admin' failed: 
SocketClient.connect @ socket.io.js:94
(anonymous) @ socket.io.js:375
a @ 6.501acaca.chunk.js:2
6.501acaca.chunk.js:2 [2022-04-13T22:44:44.937Z] Start reconnect 2
6.501acaca.chunk.js:2 [2022-04-13T22:44:44.938Z] ws connection error: CLOSE_ABNORMAL
(anonymous) @ 6.501acaca.chunk.js:2
error @ socket.io.js:61
socket.onclose @ socket.io.js:131
6.501acaca.chunk.js:2 [2022-04-13T22:44:44.938Z] Reconnect is already running 2
6.501acaca.chunk.js:2 [2022-04-13T22:44:46.942Z] Try to connect
socket.io.js:94 WebSocket connection to 'ws://192.168.178.8:8081/?sid=1649889886943&name=admin' failed: 
SocketClient.connect @ socket.io.js:94
(anonymous) @ socket.io.js:375
a @ 6.501acaca.chunk.js:2
6.501acaca.chunk.js:2 [2022-04-13T22:44:48.998Z] Start reconnect 3
6.501acaca.chunk.js:2 [2022-04-13T22:44:48.998Z] ws connection error: CLOSE_ABNORMAL
(anonymous) @ 6.501acaca.chunk.js:2
error @ socket.io.js:61
socket.onclose @ socket.io.js:131
6.501acaca.chunk.js:2 [2022-04-13T22:44:48.999Z] Reconnect is already running 3
6.501acaca.chunk.js:2 [2022-04-13T22:44:51.999Z] Try to connect
socket.io.js:94 WebSocket connection to 'ws://192.168.178.8:8081/?sid=1649889892015&name=admin' failed: 
SocketClient.connect @ socket.io.js:94
(anonymous) @ socket.io.js:375
a @ 6.501acaca.chunk.js:2
6.501acaca.chunk.js:2 [2022-04-13T22:44:54.070Z] Start reconnect 4
6.501acaca.chunk.js:2 [2022-04-13T22:44:54.071Z] ws connection error: CLOSE_ABNORMAL
(anonymous) @ 6.501acaca.chunk.js:2
error @ socket.io.js:61
socket.onclose @ socket.io.js:131
6.501acaca.chunk.js:2 [2022-04-13T22:44:54.071Z] Reconnect is already running 4
6.501acaca.chunk.js:2 Cannot getInstalled: timeout
6.501acaca.chunk.js:2 Cannot read adapters: notConnectedError
(anonymous) @ 6.501acaca.chunk.js:2
window.alert @ App.js:265
(anonymous) @ App.js:886
Promise.catch (async)
(anonymous) @ App.js:886
Promise.then (async)
(anonymous) @ App.js:883
u @ 6.501acaca.chunk.js:2
(anonymous) @ 6.501acaca.chunk.js:2
(anonymous) @ 6.501acaca.chunk.js:2
r @ 6.501acaca.chunk.js:2
i @ 6.501acaca.chunk.js:2
(anonymous) @ 6.501acaca.chunk.js:2
(anonymous) @ 6.501acaca.chunk.js:2
(anonymous) @ App.js:260
(anonymous) @ App.js:535
u @ 6.501acaca.chunk.js:2
(anonymous) @ 6.501acaca.chunk.js:2
(anonymous) @ 6.501acaca.chunk.js:2
.
.
.
socket.io.js:94 WebSocket connection to 'ws://192.168.178.8:8081/?sid=1649889898080&name=admin' failed: 
SocketClient.connect @ socket.io.js:94
(anonymous) @ socket.io.js:375
a @ 6.501acaca.chunk.js:2
6.501acaca.chunk.js:2 [2022-04-13T22:45:00.139Z] Start reconnect 5
6.501acaca.chunk.js:2 [2022-04-13T22:45:00.139Z] ws connection error: CLOSE_ABNORMAL
(anonymous) @ 6.501acaca.chunk.js:2
error @ socket.io.js:61
socket.onclose @ socket.io.js:131
6.501acaca.chunk.js:2 [2022-04-13T22:45:00.140Z] Reconnect is already running 5
6.501acaca.chunk.js:2 [2022-04-13T22:45:05.141Z] Try to connect
socket.io.js:94 WebSocket connection to 'ws://192.168.178.8:8081/?sid=1649889905156&name=admin' failed: 
SocketClient.connect @ socket.io.js:94
(anonymous) @ socket.io.js:375
a @ 6.501acaca.chunk.js:2
6.501acaca.chunk.js:2 [2022-04-13T22:45:07.199Z] Start reconnect 5
6.501acaca.chunk.js:2 [2022-04-13T22:45:07.217Z] ws connection error: CLOSE_ABNORMAL
(anonymous) @ 6.501acaca.chunk.js:2
error @ socket.io.js:61
socket.onclose @ socket.io.js:131
6.501acaca.chunk.js:2 [2022-04-13T22:45:07.217Z] Reconnect is already running 5
6.501acaca.chunk.js:2 [2022-04-13T22:45:12.218Z] Try to connect
```

-----------------------------------------------------------------------------------------------------
Can you help please?
Many thanks.
kupeme

**Comment by Apollon77** [comment]
Please doa shift reload and pot clear browser cache

**Comment by kupeme** [comment]
Hello,

thanks for the tipp, but it didn't resolve the problem. The ioBroker
doesn't start - nor in Firefox nor in Chrome.

Am Do., 14. Apr. 2022 um 07:45 Uhr schrieb Ingo Fischer <
***@***.***>:

**Comment by Apollon77** [comment]
What the iobroker server side log says when you restart admin?

**Comment by GermanBluefox** [comment]
I would close it. Backend does not run.

**Comment by kupeme** [comment]
Hello Ingo,

I wish you a happy Easter!
I can't restart the admin, because I cant access the ioBroker-GUI. ioBroker
doesn't start! Or is there another way to restart admin directly from the
shell?

Am Do., 14. Apr. 2022 um 16:50 Uhr schrieb Ingo Fischer <
***@***.***>:

**Comment by Apollon77** [comment]
"iob restart admin.0" ?
