### ISSUE TITLE
Error in GUI

### ISSUE THREAD

**Issue by djwisch** [ioBroker/ioBroker.admin#1434]
Failed to load resource: the server responded with a status of 404 (Not Found)
5.6300204f.chunk.js:2 ChunkLoadError: Loading chunk 12 failed.
(error: http://192.168.11.160:8081/static/js/12.11af713b.chunk.js)
    at Function.u.e (VM9:1:3981)
    at main.4ec45a8c.chunk.js:2:1086592
    at V (5.6300204f.chunk.js:2:5680544)
    at Zi (5.6300204f.chunk.js:2:5670728)
    at jl (5.6300204f.chunk.js:2:5657389)
    at Sl (5.6300204f.chunk.js:2:5657317)
    at Cl (5.6300204f.chunk.js:2:5657180)
    at zl (5.6300204f.chunk.js:2:5654146)
    at 5.6300204f.chunk.js:2:5603640
    at t.unstable_runWithPriority (5.6300204f.chunk.js:2:5686850)
ui @ 5.6300204f.chunk.js:2
:8081/#tab-logs:1 Refused to apply style from 'http://192.168.11.160:8081/static/css/5.ee374fb6.chunk.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by Feuer-sturm** [comment]
Hello @djwisch which admin version is installed? What did yoiu do to trigger the error?

**Comment by Feuer-sturm** [comment]
@djwisch Please check with admin 5.4.9
