### ISSUE TITLE
Error in GUI!

### ISSUE THREAD

**Issue by flar11** [ioBroker/ioBroker.admin#1440]
Hi,
made an adapter "zigbee" update today, since then I can no longer access the instances page.
There is a message to create a new issue on github, this is the error text from the console.

iobroker.admin@5.3.7
instrument.ts:124 [2022-04-24T15:53:28.989Z] Try to connect
instrument.ts:124 getInstances: 395
instrument.ts:124 Translate: [object Object]
instrument.ts:124 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bvalue%2C%20desc%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ec (react-dom.production.min.js:140:47)
    at react-dom.production.min.js:150:265
    at Po (react-dom.production.min.js:176:171)
    at Zi (react-dom.production.min.js:271:134)
    at jl (react-dom.production.min.js:250:347)
    at Sl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at bl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
    at Ka (react-dom.production.min.js:123:61)
    at Za (react-dom.production.min.js:122:428)
    at pl (react-dom.production.min.js:237:203)
    at Object.enqueueSetState (react-dom.production.min.js:133:211)
    at n.m.setState (react.production.min.js:12:369)
    at Instances.js:459:14
    at u (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at i (asyncToGenerator.js:25:9)

js version 4.0.23
node version v14.19.0
npm version 6.14.16
raspberry 4/ linux
Help is very much appreciated. 
if you need more information just let me know.
Ralf

**Comment by Apollon77** [comment]
Which zigbee version? And you are sure not also sony-bravia was updated? There was an error in that adapter

**Comment by flar11** [comment]
zibee 1.6.18, but yes, the sony bravia adapter too, totally forgotten, I hadn't noticed the error before
the sony adapter to version 1.0.6

**Comment by Apollon77** [comment]
sony-bravia 1.0.7 is on Github and in repo soon ... this was causing the issue

**Comment by flar11** [comment]
That means I just need to wait for the update?

**Comment by Apollon77** [comment]
Yes, or update sony-bravia from GitHub ... then it should fix itself

**Comment by flar11** [comment]
just installed from github, fixed

**Comment by flar11** [comment]
unbelievable how fast you get help here, thanks again
