### ISSUE TITLE
Browser asked me to open this issue

### ISSUE THREAD

**Issue by Leuselator** [ioBroker/ioBroker.admin#1450]
ChunkLoadError: Loading chunk 1 failed.
(error: https://X.X.X.X:8081/static/js/1.7dc4b47d.chunk.js)
    at Function.u.e (VM23:1:3974)
    at main.5451f6a7.chunk.js:2:1114186
    at V (6.1cf1778f.chunk.js:2:5664138)
    at Zi (6.1cf1778f.chunk.js:2:5654322)
    at jl (6.1cf1778f.chunk.js:2:5640983)
    at Sl (6.1cf1778f.chunk.js:2:5640911)
    at Cl (6.1cf1778f.chunk.js:2:5640774)
    at bl (6.1cf1778f.chunk.js:2:5637740)
    at 6.1cf1778f.chunk.js:2:5587234
    at t.unstable_runWithPriority (6.1cf1778f.chunk.js:2:5670444)
    at Ga (6.1cf1778f.chunk.js:2:5587011)
    at Ka (6.1cf1778f.chunk.js:2:5587179)
    at Za (6.1cf1778f.chunk.js:2:5587114)
    at ke (6.1cf1778f.chunk.js:2:5658281)
    at Yt (6.1cf1778f.chunk.js:2:5565732)
    at HTMLDivElement.a (6.1cf1778f.chunk.js:2:6328631)
(anonymous) @ 6.1cf1778f.chunk.js:2

**Comment by Leuselator** [comment]
Woohaa - if my forgetful head remembers right, I was on page "Hosts" and clicked on sidemenu "Instances"...

**Comment by Feuer-sturm** [comment]
Which admin version is in use?

**Comment by Leuselator** [comment]
Admin 5.3.8, Host 4.0.21, running in Docker-Container from buanet/iobroker:v6.1.0 on QNAP NAS

**Comment by GermanBluefox** [comment]
This error should be away in 5.4.7
