### ISSUE TITLE
Error auf auf 5.4.1 oder 5.4.2

### ISSUE THREAD

**Issue by fuchs-1978** [ioBroker/ioBroker.admin#1451]
Ich habe nach dem Update folgendes Problem mit dem Adminadapter:

Es tritt auf bei dem Update von 5.3.8 auf 5.4.1 und auch auf 5.4.2

<html>
<body>

host.iobroker0921 | 2022-05-06 10:47:44.992 | info | iobroker exit 0
-- | -- | -- | --
host.iobroker0921 | 2022-05-06 10:47:44.504 | info | Restart adapter system.adapter.admin.0 because enabled
host.iobroker0921 | 2022-05-06 10:47:44.504 | error | instance system.adapter.admin.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker0921 | 2022-05-06 10:47:44.504 | error | Caught by controller[0]: }
host.iobroker0921 | 2022-05-06 10:47:44.504 | error | Caught by controller[0]: requireStack: [ '/opt/iobroker/node_modules/iobroker.admin/main.js' ]
host.iobroker0921 | 2022-05-06 10:47:44.504 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.iobroker0921 | 2022-05-06 10:47:44.503 | error | Caught by controller[0]: at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
host.iobroker0921 | 2022-05-06 10:47:44.503 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:708:14)
host.iobroker0921 | 2022-05-06 10:47:44.503 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:863:32)
host.iobroker0921 | 2022-05-06 10:47:44.503 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
host.iobroker0921 | 2022-05-06 10:47:44.503 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:999:30)
host.iobroker0921 | 2022-05-06 10:47:44.503 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.admin/main.js:21:18)
host.iobroker0921 | 2022-05-06 10:47:44.503 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:74:18)
host.iobroker0921 | 2022-05-06 10:47:44.503 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:887:19)
host.iobroker0921 | 2022-05-06 10:47:44.503 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:667:27)
host.iobroker0921 | 2022-05-06 10:47:44.503 | error | Caught by controller[0]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
host.iobroker0921 | 2022-05-06 10:47:44.503 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.admin/main.js
host.iobroker0921 | 2022-05-06 10:47:44.503 | error | Caught by controller[0]: Require stack:
host.iobroker0921 | 2022-05-06 10:47:44.502 | error | Caught by controller[0]: Error: Cannot find module '@iobroker/js-controller-common'
host.iobroker0921 | 2022-05-06 10:47:44.502 | error | Caught by controller[0]: ^
host.iobroker0921 | 2022-05-06 10:47:44.502 | error | Caught by controller[0]: throw err;
host.iobroker0921 | 2022-05-06 10:47:44.502 | error | Caught by controller[0]: internal/modules/cjs/loader.js:818
host.iobroker0921 | 2022-05-06 10:47:43.999 | info | instance system.adapter.admin.0 started with pid 796736

</body>
</html>

**Comment by GermanBluefox** [comment]
Please test 5.4.6

**Comment by fuchs-1978** [comment]
Version 5.4.8 works fine
