### ISSUE TITLE
Cannot create user

### ISSUE THREAD

**Issue by EvilEls** [ioBroker/ioBroker.admin#1464]
On attempt to create a new user in ui, the admin adapter crashes.
Ui shows a timeout error.
![image](https://user-images.githubusercontent.com/29343914/168680687-290400f4-3b6d-4d5f-a0f2-b1191c8b5f44.png)

After restart of the adapter, the newly created user is there but the chosen password was not set.
```{
  "type": "user",
  "common": {
    "name": "demo",
    "password": "",
    "dontDelete": false,
    "enabled": true,
    "color": false,
    "desc": "demo",
    "icon": "data:image/svg+xml;base64,xxx"
  },
  "native": {},
  "enums": {},
  "_id": "system.user.demo",
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1652734311367,
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

Repeated retries cause the adapter to not recover anymore and iob has to be stopped and restarted.
![image](https://user-images.githubusercontent.com/29343914/168680922-68a5a954-0449-4a61-8ff7-69f6f5e8251c.png)

```2022-05-16 22:43:31.173 - error: admin.0 (3119) uncaught exception: this.__updateSession is not a function
2022-05-16 22:43:31.182 - error: admin.0 (3119) TypeError: this.__updateSession is not a function
at Object.commands.changePassword (/opt/iobroker/node_modules/@iobroker/socket-classes/lib/socketCommandsAdmin.js:570:22)
at Socket. (/opt/iobroker/node_modules/@iobroker/socket-classes/lib/socketCommands.js:1043:43)
at /opt/iobroker/node_modules/@iobroker/ws-server/index.js:115:67
at Array.forEach ()
at Immediate. (/opt/iobroker/node_modules/@iobroker/ws-server/index.js:115:50)
at processImmediate (internal/timers.js:464:21)
2022-05-16 22:43:31.183 - error: admin.0 (3119) this.__updateSession is not a function
2022-05-16 22:43:31.186 - info: admin.0 (3119) terminating https server on port 8081
2022-05-16 22:43:31.188 - info: admin.0 (3119) terminating
2022-05-16 22:43:31.190 - warn: admin.0 (3119) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-05-16 22:43:31.814 - error: host.xxxinstance system.adapter.admin.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-05-16 22:43:31.818 - info: host.xxxRestart adapter system.adapter.admin.0 because enabled
2022-05-16 22:43:32.914 - info: host.xxx instance system.adapter.admin.0 started with pid 3278
2022-05-16 22:43:33.853 - info: admin.0 (3278) Plugin sentry Sentry Plugin disabled for this process because data reporting is disabled on instance
2022-05-16 22:43:33.975 - info: admin.0 (3278) starting. Version 5.4.9 in /opt/iobroker/node_modules/iobroker.admin, node: v14.19.2, js-controller: 4.0.23
2022-05-16 22:43:34.107 - info: admin.0 (3278) requesting all states
2022-05-16 22:43:34.108 - info: admin.0 (3278) requesting all objects
2022-05-16 22:43:34.474 - info: admin.0 (3278) Request actual repository...
2022-05-16 22:43:35.187 - info: host.strausbox Updating repository "beta" under "http://download.iobroker.net/sources-dist-latest.json"
2022-05-16 22:43:35.479 - info: admin.0 (3278) received all objects
2022-05-16 22:43:35.603 - info: admin.0 (3278) https server listening on port 8081
2022-05-16 22:43:35.603 - info: admin.0 (3278) Use link "https://localhost:8081" to configure.
2022-05-16 22:43:35.608 - info: admin.0 (3278) Secure socket.io server listening on port 8081
2022-05-16 22:43:36.027 - info: admin.0 (3278) ==> Connected system.user.admin from 192.168.0.107
2022-05-16 22:43:38.466 - info: admin.0 (3278) Repository received successfully.```

admin: 5.4.9
node: v14.19.2
js-controller: 4.0.23

**Comment by GermanBluefox** [comment]
Please verify next admin version

**Comment by EvilEls** [comment]
Working again with 6.0.0
thank you!
