### ISSUE TITLE
Admin 6: GUI stürzt ab bei Klick auf Einstellungen im Menüpunkt Objekte

### ISSUE THREAD

**Issue by ninja-warrior** [ioBroker/ioBroker.admin#1512]
Hallo zusammen,

ich bin im Admin-Adapter in Version 6.0.1 unterwegs. Ansonsten sind alle Adapter und die Linux-Distribution auf dem neusten Stand.

Wenn ich im Menüpunkt 'Objekte' oben rechts auf das Werkzeug-Symbol (Benutzerdefinierte Konfiguration) klicke, stürzt die GUI ab. 

Fehlermeldung in der Browser-Konsole (instrument.js:109):

<html>
<body>

<sub>TypeError: this.state._value.trim is not a function
    at rg.renderItem (ConfigNumber.jsx:105:77)
    at rg.render (ConfigGeneric.jsx:473:23)
    at mi (react-dom.production.min.js:222:189)
    at uo (react-dom.production.min.js:221:224)
    at wa (react-dom.production.min.js:291:286)
    at va (react-dom.production.min.js:279:389)
    at hf (react-dom.production.min.js:279:320)
    at Hr (react-dom.production.min.js:279:180)
    at Ei (react-dom.production.min.js:270:88)
    at pa (react-dom.production.min.js:267:429)
    at k (scheduler.production.min.js:13:203)
    at MessagePort.nt (scheduler.production.min.js:14:128)</sub>
--

</body>
</html>

**Comment by ninja-warrior** [comment]
Funktioniert wird, danke!
