### ISSUE TITLE
Admin 6.0.3 (but was als 5.4.9) Crash when calling Adapters page

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#1524]
<img width="1792" alt="Bildschirmfoto 2022-06-12 um 23 16 43" src="https://user-images.githubusercontent.com/11976694/173253932-abe63a52-823f-40ef-8cff-759124b4a3aa.png">

**Comment by Grothesk242** [comment]
Same/similar issue with the #tab-intro page:

```
iobroker.admin@6.0.3
instrument.js:109 MUI: The LocalizationProvider component was moved from `@mui/lab` to `@mui/x-date-pickers`.
The component will no longer be exported from `@mui/lab` in the first release of July 2022.

You should use `import { LocalizationProvider } from '@mui/x-date-pickers'`
or `import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider'`

More information about this migration on our blog: https://mui.com/blog/lab-date-pickers-to-mui-x/.
(anonymous) @ instrument.js:109
kR4 @ LocalizationProvider.js:10
(anonymous) @ LocalizationProvider.js:19
Ji @ react-dom.production.min.js:166
lo @ react-dom.production.min.js:211
wa @ react-dom.production.min.js:293
va @ react-dom.production.min.js:279
hf @ react-dom.production.min.js:279
Hr @ react-dom.production.min.js:279
pa @ react-dom.production.min.js:267
k @ scheduler.production.min.js:13
nt @ scheduler.production.min.js:14
instrument.js:109 [2022-06-13T16:26:32.717Z] Try to connect
instrument.js:109 Stored version: , new version: 6.0.3
instrument.js:109 > objectChange tado.0.109324
instrument.js:109 > objectChange tado.0.109324
instrument.js:109 > objectChange tado.0.109324.Mobile_Devices
instrument.js:109 > objectChange tado.0.109324.Mobile_Devices
instrument.js:109 > objectChange tado.0.109324.Mobile_Devices.371286
instrument.js:109 > objectChange tado.0.109324.Mobile_Devices.371286
instrument.js:109 > objectChange tado.0.109324.Mobile_Devices.411365
instrument.js:109 > objectChange tado.0.109324.Mobile_Devices.411365
instrument.js:109 > objectChange tado.0.109324.Mobile_Devices.2722559
instrument.js:109 > objectChange tado.0.109324.Mobile_Devices.2722559
instrument.js:109 > objectChange tado.0.109324.Rooms
instrument.js:109 > objectChange tado.0.109324.Rooms
instrument.js:109 > objectChange tado.0.109324.Rooms.1
instrument.js:109 > objectChange tado.0.109324.Rooms.1
instrument.js:109 > objectChange tado.0.109324.Rooms.3
instrument.js:109 > objectChange tado.0.109324.Rooms.3
instrument.js:109 > objectChange tado.0.109324.Rooms.2
instrument.js:109 > objectChange tado.0.109324.Rooms.2
instrument.js:109 > objectChange tado.0.109324.Rooms.4
instrument.js:109 > objectChange tado.0.109324.Rooms.4
instrument.js:109 > objectChange tado.0.109324.Weather
instrument.js:109 > objectChange tado.0.109324.Weather
instrument.js:109 > objectChange tado.0.109324.Weather.solarIntensity
instrument.js:109 > objectChange tado.0.109324.Weather.solarIntensity
instrument.js:109 > objectChange tado.0.109324.Weather.outsideTemperature
instrument.js:109 > objectChange tado.0.109324.Weather.outsideTemperature
instrument.js:109 > objectChange tado.0.109324.Weather.weatherState
instrument.js:109 > objectChange tado.0.109324.Weather.weatherState
instrument.js:109 > objectChange tado.0.109324.Home.state
instrument.js:109 > objectChange tado.0.109324.Home.state
instrument.js:109 MUI: The Skeleton component was moved from the lab to the core.

You should use `import { Skeleton } from '@mui/material'`
or `import Skeleton from '@mui/material/Skeleton'`
(anonymous) @ instrument.js:109
instrument.js:109 TypeError: Invalid Version: undefined
    at new D (semver.js:314:11)
    at Y (semver.js:647:10)
    at Function.t1 [as gt] (semver.js:683:10)
    at lt.getHostDescription (Intro.jsx:573:24)
    at Intro.jsx:204:52
    at Array.map (<anonymous>)
    at lt.getInstancesCards (Intro.jsx:176:37)
    at lt.render (Intro.jsx:719:27)
    at mi (react-dom.production.min.js:222:189)
    at uo (react-dom.production.min.js:221:224)
    at wa (react-dom.production.min.js:291:286)
    at va (react-dom.production.min.js:279:389)
    at hf (react-dom.production.min.js:279:320)
    at Hr (react-dom.production.min.js:279:180)
    at Ei (react-dom.production.min.js:270:88)
    at pa (react-dom.production.min.js:267:429)
    at k (scheduler.production.min.js:13:203)
    at MessagePort.nt (scheduler.production.min.js:14:128)
(anonymous) @ instrument.js:109
:8081/#tab-intro:1 Access to fetch at 'https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7' from origin 'http://192.168.178.48:8081' has been blocked by CORS policy: Request had a target IP address space of `unknown` yet the resource is in address space `public`.
sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1          Failed to load resource: net::ERR_FAILED
```

**Comment by GermanBluefox** [comment]
> 

This one is fixed in latest

**Comment by Feuer-sturm** [comment]
@Apollon77 Can we close this issue with current admin version?

**Comment by Apollon77** [comment]
sorry stilll open, can add stack trace later today

**Comment by GermanBluefox** [comment]
> sorry stilll open, can add stack trace later today

Please provide call stack

**Comment by Apollon77** [comment]
![Bildschirmfoto 2022-06-29 um 10 00 50](https://user-images.githubusercontent.com/11976694/176384188-721388c8-cc45-4adb-848f-2a2c2a954210.png)

**Comment by Feuer-sturm** [comment]
Feedback from @Apollon77  is that this issue still exists

**Comment by foxriver76** [comment]
How can this be reproduced?

**Comment by Feuer-sturm** [comment]
@Apollon77 is this issue still active with admin 7?

**Comment by mcm1957** [comment]
@Apollon77 Any feedback?
