### ISSUE TITLE
GUI Error

### ISSUE THREAD

**Issue by MojitoJoe1813** [ioBroker/ioBroker.admin#1526]
Browser console states
```
TypeError: J2.map is not a function
    at kl.render (ChipInput.jsx:552:38)
    at mi (react-dom.production.min.js:222:189)
    at uo (react-dom.production.min.js:221:224)
    at wa (react-dom.production.min.js:291:286)
    at va (react-dom.production.min.js:279:389)
    at hf (react-dom.production.min.js:279:320)
    at Hr (react-dom.production.min.js:279:180)
    at Ei (react-dom.production.min.js:270:88)
    at wo (react-dom.production.min.js:272:300)
    at dn (react-dom.production.min.js:127:105)
    at gf (react-dom.production.min.js:282:419)
    at vn (react-dom.production.min.js:280:398)
    at pa (react-dom.production.min.js:269:269)
    at k (scheduler.production.min.js:13:203)
    at MessagePort.nt (scheduler.production.min.js:14:128)
(anonym) @ instrument.js:109
```

I was opening the cloud-adapter-configuration screen when this happened.

**Comment by Feuer-sturm** [comment]
@MojitoJoe1813 which admin version is installed?

**Comment by MojitoJoe1813** [comment]
Admin v6.0.3

**Comment by Feuer-sturm** [comment]
@MojitoJoe1813 Please check with current admin version 6.1.2

**Comment by MojitoJoe1813** [comment]
Installed 6.1.4. However, I'm sorry, I can't check it the same way I was producing the error originally as I meanwhile dismissed the cloud adapter and switched completely to the IOT adapter.
