### ISSUE TITLE
Cannot add new Instance

### ISSUE THREAD

**Issue by EvilEls** [ioBroker/ioBroker.admin#1541]
When I try to add another instance of an existing adapter on `/#tab-adapters`, nothing happens in GUI. 
There is no error in iob logs.
Browser dev console shows

```Uncaught TypeError: P is not a function
    at W (LicenseDialog.jsx:120:16)
    at onAddInstance (Adapters.jsx:1526:25)
    at Object.ga (react-dom.production.min.js:54:317)
    at ka (react-dom.production.min.js:54:471)
    at Sa (react-dom.production.min.js:55:35)
    at Po (react-dom.production.min.js:105:68)
    at To (react-dom.production.min.js:106:380)
    at react-dom.production.min.js:117:104
    at ou (react-dom.production.min.js:274:42)
    at Ou (react-dom.production.min.js:52:375)
```

![image](https://user-images.githubusercontent.com/29343914/174473190-4521e930-4364-425b-a95f-fc381edfbb88.png)

```starting. Version 6.0.5 in /opt/iobroker/node_modules/iobroker.admin, node: v14.19.2, js-controller: 4.0.23```

**Comment by Feuer-sturm** [comment]
@EvilEls can you please check with current Version 6.0.7?

**Comment by EvilEls** [comment]
Confirmed working again with 6.0.7 👍
Thank you!
