### ISSUE TITLE
System said report error in github

### ISSUE THREAD

**Issue by AxelF1977** [ioBroker/ioBroker.admin#1547]
IoBroker is starting agai and again. Now it does not start anymore. The system said, to copy the code of the Chrome console. here it is

```
iobroker.admin@5.4.9
6.dbdea4c4.chunk.js:2 [2022-06-22T07:54:52.002Z] Try to connect
6.dbdea4c4.chunk.js:2 Stored version: , new version: 5.4.9
6.dbdea4c4.chunk.js:2 [2022-06-22T07:54:54.536Z] ws connection error: CLOSE_ABNORMAL
(anonym) @ 6.dbdea4c4.chunk.js:2
6.dbdea4c4.chunk.js:2 [2022-06-22T07:54:54.537Z] Start reconnect 0
6.dbdea4c4.chunk.js:2 [2022-06-22T07:54:54.539Z] Try to connect
socket.io.js:94 WebSocket connection to 'ws://192.168.178.46:8081/?sid=1655884494539&name=admin' failed: 
SocketClient.connect @ socket.io.js:94
6.dbdea4c4.chunk.js:2 [2022-06-22T07:54:56.595Z] Start reconnect 1
6.dbdea4c4.chunk.js:2 [2022-06-22T07:54:56.596Z] ws connection error: CLOSE_ABNORMAL
(anonym) @ 6.dbdea4c4.chunk.js:2
6.dbdea4c4.chunk.js:2 [2022-06-22T07:54:56.596Z] Reconnect is already running 1
6.dbdea4c4.chunk.js:2 [2022-06-22T07:54:57.633Z] Try to connect
socket.io.js:94 WebSocket connection to 'ws://192.168.178.46:8081/?sid=1655884497633&name=admin' failed: 
SocketClient.connect @ socket.io.js:94
6.dbdea4c4.chunk.js:2 [2022-06-22T07:54:59.678Z] Start reconnect 2
6.dbdea4c4.chunk.js:2 [2022-06-22T07:54:59.678Z] ws connection error: CLOSE_ABNORMAL
(anonym) @ 6.dbdea4c4.chunk.js:2
6.dbdea4c4.chunk.js:2 [2022-06-22T07:54:59.678Z] Reconnect is already running 2
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:01.688Z] Try to connect
socket.io.js:94 WebSocket connection to 'ws://192.168.178.46:8081/?sid=1655884501688&name=admin' failed: 
SocketClient.connect @ socket.io.js:94
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:03.719Z] Start reconnect 3
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:03.719Z] ws connection error: CLOSE_ABNORMAL
(anonym) @ 6.dbdea4c4.chunk.js:2
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:03.719Z] Reconnect is already running 3
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:07.628Z] Try to connect
6.dbdea4c4.chunk.js:2 Cannot getRepositoryCompact: timeout
6.dbdea4c4.chunk.js:2 Cannot getInstalled: notConnectedError
(anonym) @ 6.dbdea4c4.chunk.js:2
6.dbdea4c4.chunk.js:2 Cannot read adapters: notConnectedError
(anonym) @ 6.dbdea4c4.chunk.js:2
26.dbdea4c4.chunk.js:2 [ADAPTERS] Cannot compare "" and "4.0.23"
(anonym) @ 6.dbdea4c4.chunk.js:2
:8081/#tab-intro:1 Uncaught (in promise) notConnectedError
6.dbdea4c4.chunk.js:2 Uncaught (in promise) notConnectedError
:8081/#tab-intro:1 Uncaught (in promise) notConnectedError
6.dbdea4c4.chunk.js:2 Cannot get logs: notConnectedError
(anonym) @ 6.dbdea4c4.chunk.js:2
6.dbdea4c4.chunk.js:2 [ADAPTERS] Cannot compare "" and "4.0.23"
(anonym) @ 6.dbdea4c4.chunk.js:2
socket.io.js:94 WebSocket connection to 'ws://192.168.178.46:8081/?sid=1655884507629&name=admin' failed: 
SocketClient.connect @ socket.io.js:94
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:09.682Z] Start reconnect 4
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:09.683Z] ws connection error: CLOSE_ABNORMAL
(anonym) @ 6.dbdea4c4.chunk.js:2
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:09.683Z] Reconnect is already running 4
:8081/img/no-image.png:1          Failed to load resource: net::ERR_CONNECTION_REFUSED
:8081/static/js/14.c02ffa53.chunk.js:1          Failed to load resource: net::ERR_CONNECTION_REFUSED
6.dbdea4c4.chunk.js:2 ChunkLoadError: Loading chunk 14 failed.
(error: http://192.168.178.46:8081/static/js/14.c02ffa53.chunk.js)
    at u.e (VM18:1:3974)
    at main.35255785.chunk.js:2:1112895
    at S (6.dbdea4c4.chunk.js:2:5687745)
    at Zi (6.dbdea4c4.chunk.js:2:5677929)
    at jl (6.dbdea4c4.chunk.js:2:5664590)
    at Vl (6.dbdea4c4.chunk.js:2:5664518)
    at Cl (6.dbdea4c4.chunk.js:2:5664381)
    at bl (6.dbdea4c4.chunk.js:2:5661347)
    at 6.dbdea4c4.chunk.js:2:5610841
    at t.unstable_runWithPriority (6.dbdea4c4.chunk.js:2:5694051)
    at Ga (6.dbdea4c4.chunk.js:2:5610618)
    at Ka (6.dbdea4c4.chunk.js:2:5610786)
    at Za (6.dbdea4c4.chunk.js:2:5610721)
    at pl (6.dbdea4c4.chunk.js:2:5658724)
    at Object.enqueueSetState (6.dbdea4c4.chunk.js:2:5614739)
    at m.setState (6.dbdea4c4.chunk.js:2:5685561)
    at main.35255785.chunk.js:2:1125807
    at u (6.dbdea4c4.chunk.js:2:5698751)
    at Generator._invoke (6.dbdea4c4.chunk.js:2:5698539)
    at Generator.next (6.dbdea4c4.chunk.js:2:5699180)
    at r (6.dbdea4c4.chunk.js:2:35687)
    at i (6.dbdea4c4.chunk.js:2:35890)
(anonym) @ 6.dbdea4c4.chunk.js:2
browserError.png:1          Failed to load resource: net::ERR_CONNECTION_REFUSED
:8081/#tab-intro:1 Uncaught (in promise) notConnectedError
2006.dbdea4c4.chunk.js:2 notConnectedError
(anonym) @ 6.dbdea4c4.chunk.js:2
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:13.693Z] Try to connect
socket.io.js:94 WebSocket connection to 'ws://192.168.178.46:8081/?sid=1655884513693&name=admin' failed: 
SocketClient.connect @ socket.io.js:94
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:15.742Z] Start reconnect 5
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:15.742Z] ws connection error: CLOSE_ABNORMAL
(anonym) @ 6.dbdea4c4.chunk.js:2
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:15.742Z] Reconnect is already running 5
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:20.748Z] Try to connect
socket.io.js:94 WebSocket connection to 'ws://192.168.178.46:8081/?sid=1655884520762&name=admin' failed: 
SocketClient.connect @ socket.io.js:94
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:22.793Z] Start reconnect 5
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:22.793Z] ws connection error: CLOSE_ABNORMAL
(anonym) @ 6.dbdea4c4.chunk.js:2
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:22.793Z] Reconnect is already running 5
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:27.799Z] Try to connect
socket.io.js:94 WebSocket connection to 'ws://192.168.178.46:8081/?sid=1655884527815&name=admin' failed: 
SocketClient.connect @ socket.io.js:94
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:29.864Z] Start reconnect 5
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:29.864Z] ws connection error: CLOSE_ABNORMAL
(anonym) @ 6.dbdea4c4.chunk.js:2
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:29.864Z] Reconnect is already running 5
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:34.879Z] Try to connect
socket.io.js:94 WebSocket connection to 'ws://192.168.178.46:8081/?sid=1655884534896&name=admin' failed: 
SocketClient.connect @ socket.io.js:94
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:36.946Z] Start reconnect 5
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:36.946Z] ws connection error: CLOSE_ABNORMAL
(anonym) @ 6.dbdea4c4.chunk.js:2
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:36.946Z] Reconnect is already running 5
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:42.629Z] Try to connect
Entwicklertools konnten Quellzuordnung nicht laden: Inhalt für http://192.168.178.46:8081/lib/js/sparkline.js.map: Verbindungsfehler: net::ERR_CONNECTION_REFUSED konnte nicht geladen werden
Entwicklertools konnten Quellzuordnung nicht laden: Inhalt für http://192.168.178.46:8081/static/js/6.dbdea4c4.chunk.js.map: Verbindungsfehler: net::ERR_CONNECTION_REFUSED konnte nicht geladen werden
Entwicklertools konnten Quellzuordnung nicht laden: Inhalt für http://192.168.178.46:8081/static/js/main.35255785.chunk.js.map: Verbindungsfehler: net::ERR_CONNECTION_REFUSED konnte nicht geladen werden
socket.io.js:94 WebSocket connection to 'ws://192.168.178.46:8081/?sid=1655884542629&name=admin' failed: 
SocketClient.connect @ socket.io.js:94
(anonym) @ socket.io.js:375
a @ 6.dbdea4c4.chunk.js:2
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:44.676Z] Start reconnect 5
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:44.677Z] ws connection error: CLOSE_ABNORMAL
(anonym) @ 6.dbdea4c4.chunk.js:2
error @ socket.io.js:61
socket.onclose @ socket.io.js:131
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:44.677Z] Reconnect is already running 5
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:50.630Z] Try to connect
socket.io.js:94 WebSocket connection to 'ws://192.168.178.46:8081/?sid=1655884550648&name=admin' failed: 
SocketClient.connect @ socket.io.js:94
(anonym) @ socket.io.js:375
a @ 6.dbdea4c4.chunk.js:2
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:52.703Z] Start reconnect 5
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:52.703Z] ws connection error: CLOSE_ABNORMAL
(anonym) @ 6.dbdea4c4.chunk.js:2
error @ socket.io.js:61
socket.onclose @ socket.io.js:131
6.dbdea4c4.chunk.js:2 [2022-06-22T07:55:52.703Z] Reconnect is already running 5
```

**Comment by Feuer-sturm** [comment]
@AxelF1977 which admin version is installed? What are the steps to trigger the error?
