### ISSUE TITLE
Admin 6.1.2 Error in GUI, kein Login mehr möglich

### ISSUE THREAD

**Issue by Brandy-f1** [ioBroker/ioBroker.admin#1551]
**Describe the bug**  
Error in GUI beim Versuch die Loginseite des Admin aufzurufen.
Bis zur Admin V6.1.1 kein Problem. Nach Installation der 6.1.2 und erneutem aufruf von iobroker.web trat der Fehler auf.

**To Reproduce**  
1. Aufruf des Iobroker über IP:8082
2. Click on 'Admin'
3. See error

**Expected behavior**  

**Screenshots & Logfiles**  
Auszug aus der Browser Konsole:

Uncaught TypeError: document.getElement is not a function
    <anonymous> https://192.168.178.71:8081/?login&href=#tab-intro:1
[192.168.178.71:8081:1:64](https://192.168.178.71:8081/?login&href=#tab-intro)
iobroker.admin@6.1.2 [bootstrap.jsx:19:8](https://192.168.178.71:8081/static/js/bootstrap.jsx)
TypeError: window.document.getElement is not a function
    fr Login.jsx:90
    React 8
    Ln scheduler.production.min.js:13
    Gn scheduler.production.min.js:14
[instrument.ts:124:32](https://192.168.178.71:8081/static/node_modules/@sentry/src/instrument.ts)
    T0 instrument.ts:124
    React 9
    Ln scheduler.production.min.js:13
    Gn scheduler.production.min.js:14

**Versions:**  
 - Adapter version: admin 6.1.2
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**  
![Error Admin](https://user-images.githubusercontent.com/60137562/175375699-1f973abb-38a1-4a75-8c2a-1c79da30b579.jpg)

**Comment by Archie-ndw** [comment]
Same here.
Console-Log:

Uncaught TypeError: document.getElement is not a function
    at ?login&href=:1:1359
bootstrap.jsx:19 iobroker.admin@6.1.2
instrument.ts:124 TypeError: window.document.getElement is not a function
    at new fr (Login.jsx:90:38)
    at Zo (react-dom.production.min.js:147:172)
    at Rs (react-dom.production.min.js:198:97)
    at oa (react-dom.production.min.js:292:172)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
(anonymous) @ instrument.ts:124

**Comment by Feuer-sturm** [comment]
I just installed Admin 6.1.4 (already available on npm) and with Admin 6.1.4 I have no problem with logout and login.

**Comment by GermanBluefox** [comment]
Please use 6.1.4
