### ISSUE TITLE
Admin 6.1.6 - Update of multiple adapters not possible

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#1564]
**Describe the bug**  
If an update of multiple adapters is triggered there will be an GUI error

**To Reproduce**  
1. Go to adapter menu
2. Click on "Alle Adapter aktualisieren"
3. Start update

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/25422320/176185107-67831f9e-3341-41ca-a1aa-0e83f063665c.png)

**Versions:**  
 - Adapter version: Admin 6.1.6

**Comment by Chaot1** [comment]
Error im Browser:
`iobroker.admin@6.1.6
instrument.ts:124 [2022-06-28T04:13:54.641Z] Try to connect
instrument.ts:124 Stored version: , new version: 6.1.6
instrument.ts:124 Connected: true
instrument.ts:124 [ADAPTERS] getAdapters
instrument.ts:124 [ADAPTERS] getAdaptersInfo
instrument.ts:124 [ADAPTERS] admin
instrument.ts:124 [ADAPTERS] getAdapters
instrument.ts:124 [ADAPTERS] getAdaptersInfo
2instrument.ts:124 [ADAPTERS] admin
instrument.ts:124 Repo updated!
instrument.ts:124 Cannot compare "" and "1.13.5"
(anonymous) @ instrument.ts:124
instrument.ts:124 Cannot compare "" and "0.3.6-1"
(anonymous) @ instrument.ts:124
instrument.ts:124 Cannot compare "" and "0.2.11"
(anonymous) @ instrument.ts:124
instrument.ts:124 Cannot compare "" and "0.0.7"
(anonymous) @ instrument.ts:124
instrument.ts:124 Cannot compare "" and "0.1.6-0"
(anonymous) @ instrument.ts:124
instrument.ts:124 STARTED: upgrade history@2.1.7
instrument.ts:124 TypeError: Cannot read properties of undefined (reading 'startsWith')
    at y.executeCommand (Command.jsx:93:51)
    at y.componentDidMount (Command.jsx:62:18)
    at Zs (react-dom.production.min.js:261:217)
    at Gs (react-dom.production.min.js:260:446)
    at Gs (react-dom.production.min.js:260:343)
    at Xc (react-dom.production.min.js:259:431)
    at bc (react-dom.production.min.js:283:96)
    at $n (react-dom.production.min.js:281:398)
    at ea (react-dom.production.min.js:273:439)
    at hn (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonymous) @ instrument.ts:124`

**Comment by tobasium** [comment]
Same Problem:

![image](https://user-images.githubusercontent.com/23247891/176230186-3766687e-cf00-4668-89bf-fe81971019cd.png)

**Comment by tmycgn** [comment]
Same here.

![image](https://user-images.githubusercontent.com/82310796/176274953-229fdf62-8b76-4624-9c19-1451c378a363.png)
