### ISSUE TITLE
Error in GUI!

### ISSUE THREAD

**Issue by Schimi1983** [ioBroker/ioBroker.admin#1575]
Tritt erst seit Admin Version 6.1.10

Wenn  ich das Repository wechseln möchte... ist es egal was ich zuerst anklicke:

![image](https://user-images.githubusercontent.com/4581474/177520166-ecabdb89-c6c2-402b-845b-295f251e3f2f.png)

sofort kommt das:
![image](https://user-images.githubusercontent.com/4581474/177520237-657b5329-c98f-4457-a021-1e35185d4df7.png)

in der konsole steht dann das:

`iobroker.admin@6.1.10
instrument.ts:124 [2022-07-06T09:27:42.599Z] Try to connect
sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 503 ()
instrument.ts:124 Stored version: , new version: 6.1.10
instrument.ts:124 Connected: true
instrument.ts:124 [ADAPTERS] getAdapters
sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 503 ()
sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 503 ()
sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 503 ()
sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 503 ()
sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 503 ()
instrument.ts:124 [ADAPTERS] getAdaptersInfo
instrument.ts:124 system.adapter.admin.0
instrument.ts:124 system.adapter.alexa2.0
instrument.ts:124 system.adapter.backitup.0
instrument.ts:124 system.adapter.cloud.0
instrument.ts:124 system.adapter.daswetter.0
instrument.ts:124 system.adapter.denon.0
instrument.ts:124 system.adapter.devices.0
instrument.ts:124 system.adapter.echarts.0
instrument.ts:124 system.adapter.ecovacs-deebot.0
instrument.ts:124 system.adapter.ecovacs-deebot.1
instrument.ts:124 system.adapter.emby.0
instrument.ts:124 system.adapter.feiertage.0
instrument.ts:124 system.adapter.flot.0
instrument.ts:124 system.adapter.ical.0
instrument.ts:124 system.adapter.icons-mfd-svg.0
instrument.ts:124 system.adapter.info.0
instrument.ts:124 system.adapter.iot.0
instrument.ts:124 system.adapter.jarvis.0
instrument.ts:124 system.adapter.javascript.0
instrument.ts:124 system.adapter.modbus.0
instrument.ts:124 system.adapter.modbus.1
instrument.ts:124 system.adapter.modbus.2
instrument.ts:124 system.adapter.modbus.3
instrument.ts:124 system.adapter.modbus.4
instrument.ts:124 system.adapter.mqtt.0
instrument.ts:124 system.adapter.netatmo.0
instrument.ts:124 system.adapter.ocpp.0
instrument.ts:124 system.adapter.pvforecast.0
instrument.ts:124 system.adapter.shelly.0
instrument.ts:124 system.adapter.shelly.1
instrument.ts:124 system.adapter.shuttercontrol.0
instrument.ts:124 system.adapter.simple-api.0
instrument.ts:124 system.adapter.smartmeter.0
instrument.ts:124 system.adapter.sonoff.0
instrument.ts:124 system.adapter.sourceanalytix.0
instrument.ts:124 system.adapter.sql.0
instrument.ts:124 system.adapter.stiebel-isg.0
instrument.ts:124 system.adapter.telegram.0
instrument.ts:124 system.adapter.trashschedule.0
instrument.ts:124 system.adapter.unifi.0
instrument.ts:124 system.adapter.vis.0
instrument.ts:124 system.adapter.vis-hqwidgets.0
instrument.ts:124 system.adapter.vis-materialdesign.0
instrument.ts:124 system.adapter.web.0
instrument.ts:124 system.adapter.whatsapp-cmb.0
instrument.ts:124 system.adapter.whatsapp-cmb.1
instrument.ts:124 system.adapter.zigbee.0
instrument.ts:124 getInstances: 58
sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 503 ()
sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 503 ()
sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 503 ()
sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 503 ()
instrument.ts:124 
        
       TypeError: w is not a function
    at hr.<anonymous> (SystemSettingsDialog.jsx:417:41)
    at Yo (react-dom.production.min.js:144:189)
    at Zs (react-dom.production.min.js:261:422)
    at Gs (react-dom.production.min.js:260:446)
    at Xc (react-dom.production.min.js:259:431)
    at bc (react-dom.production.min.js:283:96)
    at $n (react-dom.production.min.js:281:398)
    at ea (react-dom.production.min.js:273:439)
    at hn (react-dom.production.min.js:127:105)
    at Qn (react-dom.production.min.js:274:266)
    at Ou (react-dom.production.min.js:52:423)
    at oi (react-dom.production.min.js:109:469)
    at Ql (react-dom.production.min.js:74:59)
    at ja (react-dom.production.min.js:73:73)
    at HTMLBodyElement.C1 (helpers.ts:99:17)
(anonym) @ instrument.ts:124
sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 503 ()`

**Comment by Schimi1983** [comment]
zurück auf 6.1.9 und alles funktioniert wieder...
