### ISSUE TITLE
instrument.ts:124 ChunkLoadError: Loading chunk 2261 failed.

### ISSUE THREAD

**Issue by EDSTOBI** [ioBroker/ioBroker.admin#1586]
**Describe the bug**  
After reboot I got the message to report the error to GIT

**To Reproduce**  
2. Click on '...'

**Expected behavior**  
on console from pi sudo reboot

**Screenshots & Logfiles**  
instrument.ts:124 ChunkLoadError: Loading chunk 2261 failed.
(timeout: http://10.11.12.240:8081/static/js/2261.fe6732e6.chunk.js)
    at n.f.j (jsonp chunk loading:27:18)
    at ensure chunk:6:25
    at Array.reduce (<anonymous>)
    at n.e (ensure chunk:5:56)
    at App.jsx:76:36
    at G (react.production.min.js:18:161)
    at oa (react-dom.production.min.js:291:300)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at ea (react-dom.production.min.js:273:245)
    at hn (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by Apollon77** [comment]
What did you do? just opening Admin or on which action the eror occurs?

**Comment by EDSTOBI** [comment]
Yes I tried to open the console normally after restarting the Pi. I see the IObroker logo and a white screen where the blue loading bar is running.
On the PI4 console with htop 100% iobroker.js-controler and io.mqtt.0. mqtt has the most CPU time

**Comment by EDSTOBI** [comment]
on the console >iobroker stop mqtt.0
ergebniss:  no connection to database pssible

**Comment by EDSTOBI** [comment]
Restor of backup solved the problem. I stil have a clon from broken instant

**Comment by GermanBluefox** [comment]
This error happens when iobroker.admin adapter has other version than in Browser. E.g. after update or downgrade of admin, the user must manually refresh the browser. In last versions this must happen automatically. In Older this could happen

**Comment by EDSTOBI** [comment]
Hello
Thank you for this answer.
Unfortunately I can not confirm this, as I tested on different machines, which were fresh and clean booted and absolutely virgin from a test image. 
Furthermore I have closed Brouser and tried Chrome, old Internet explorer, Edge and Morzilla. Here too I have always closed everything before, because I know similar behavior from other programs.
