### ISSUE TITLE
Instanzen Fehler

### ISSUE THREAD

**Issue by linux150** [ioBroker/ioBroker.admin#1587]
getInstances: 9
instrument.ts:124 Error: Invalid characters, got value: 11;23;38;51
    at u._parseField (expression.js:177:11)
    at d (expression.js:866:36)
    at u.parse (expression.js:919:10)
    at v.parseExpression (parser.js:41:25)
    at Jt (InstanceRow.jsx:881:25)
    at Fi (react-dom.production.min.js:167:137)
    at oa (react-dom.production.min.js:290:337)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
(anonymous) @ instrument.ts:124

**Comment by linux150** [comment]
Node.js: v16.16.0
time: 1657774732309
timeOffset: --
Adapter-Anzahl: 501
NPM: v8.11.0

**Comment by magnus2501** [comment]
I got also an error with the Instances, but looks different.

Error: Constraint error, cannot repeat at every 0 time.
    g expression.js:335
    t expression.js:283
    f expression.js:261
    _parseField expression.js:353
    d expression.js:866
    parse expression.js:919
    parseExpression parser.js:41
    Jt InstanceRow.jsx:881
    React 7
        Fi
        oa
        ra
        Jc
        ml
        iu
        bs
    Ln scheduler.production.min.js:13
    Gn scheduler.production.min.js:14
    41196 scheduler.production.min.js:14
    Webpack 18
        n
        72851
        n
        57799
        n
        73961
        n
        I
        t
        n
        24470
        n
        52898
        n
        promise callback*72063
        n
        <anonymous>
        <anonymous>
instrument.ts:124:32

**Comment by linux150** [comment]
Warten? Version ist bei mir schon die 6.2 - Fehler besteht, sorry kenn mich mit dem Github Link nicht aus ...

**Comment by magnus2501** [comment]
I'm also not quite sure what to do. Wait for 6.2.1 as indicated in the link? Can I manually trigger the update? Sorry for these questions

**Comment by GermanBluefox** [comment]
New version will appear after 14:00 auf latest

**Comment by magnus2501** [comment]
Thanks!

**Comment by linux150** [comment]
Did make the update via console now, all fine THANKS
