### ISSUE TITLE
Error in der Gui

### ISSUE THREAD

**Issue by Knoddel** [ioBroker/ioBroker.admin#1615]
Beim öffnen vom Adapter Influxdb kommt dieser Fehler der GUI

`instrument.ts:124 TypeError: Cannot read properties of undefined (reading 'value')
    at vn.renderItem (ConfigText.jsx:36:34)
    at vn.render (ConfigGeneric.jsx:514:39)
    at Wi (react-dom.production.min.js:204:189)
    at Rs (react-dom.production.min.js:203:149)
    at oa (react-dom.production.min.js:292:172)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)`

**Comment by raschy** [comment]
instrument.ts:124 
        
       TypeError: Cannot read properties of undefined (reading 'value')
    at vn.renderItem (ConfigText.jsx:36:34)
    at vn.render (ConfigGeneric.jsx:514:39)
    at Wi (react-dom.production.min.js:204:189)
    at Rs (react-dom.production.min.js:203:149)
    at oa (react-dom.production.min.js:292:172)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)

**Comment by Feuer-sturm** [comment]
@Knoddel @raschy which admin version do you use?

**Comment by Knoddel** [comment]
Ich benutze die Admin Version 6.26

**Comment by raschy** [comment]
Dito. Die gerade angebotene 6.2.6

**Comment by JohGrei** [comment]
Ähnlicher Fehler mit Admin Version 6.2.10

`TypeError: Cannot read properties of undefined (reading 'toString')
    at et.componentDidMount (ConfigNumber.jsx:43:40)
    at Zs (react-dom.production.min.js:261:217)
    at Gs (react-dom.production.min.js:260:446)
    at Gs (react-dom.production.min.js:260:343)
    at Xc (react-dom.production.min.js:259:431)
    at bc (react-dom.production.min.js:283:96)
    at $n (react-dom.production.min.js:281:398)
    at bs (react-dom.production.min.js:270:269)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)`

**Comment by Negalein** [comment]
Xbox 1.0.0-beta.0 mit Admin: 6.2.6

`Cannot read properties of undefined (reading 'value')
TypeError: Cannot read properties of undefined (reading 'value')($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))    at vn.renderItem (https://10.0.1.202:8081/static/js/5710.7d75fb68.chunk.js:74:150640)($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))    at vn.render (https://10.0.1.202:8081/static/js/5710.7d75fb68.chunk.js:74:40920)($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))    at Wi (https://10.0.1.202:8081/static/js/3961.a98ff7ab.chunk.js:16:6209)($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))    at Rs (https://10.0.1.202:8081/static/js/3961.a98ff7ab.chunk.js:16:6006)($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))    at oa (https://10.0.1.202:8081/static/js/3961.a98ff7ab.chunk.js:16:44992)($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))    at ra (https://10.0.1.202:8081/static/js/3961.a98ff7ab.chunk.js:16:39832)($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))    at Jc (https://10.0.1.202:8081/static/js/3961.a98ff7ab.chunk.js:16:39763)($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))    at ml (https://10.0.1.202:8081/static/js/3961.a98ff7ab.chunk.js:16:39622)($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))    at iu (https://10.0.1.202:8081/static/js/3961.a98ff7ab.chunk.js:16:36004)($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))    at bs (https://10.0.1.202:8081/static/js/3961.a98ff7ab.chunk.js:16:34957)($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))    at Ln (https://10.0.1.202:8081/static/js/3961.a98ff7ab.chunk.js:24:1614)($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))    at MessagePort.Gn (https://10.0.1.202:8081/static/js/3961.a98ff7ab.chunk.js:24:2007)`

**Comment by Feuer-sturm** [comment]
@Knoddel Can you please check if you can open influx adapter configuration with Admin 6.2.10. On my test system this is working with 6.2.10 (I had the same issue than you with 6.2.6)

@JohGrei What did you do to trigger the error?

@Negalein Can you please double check with admin 6.2.10

**Comment by Negalein** [comment]
Danke, funktioniert mit 6.2.10

**Comment by JohGrei** [comment]
@Feuer-sturm:  In der Objektansicht möchte ich bei einem Attribute eines Objektes in den Custom Settings (Zahnrad ganz rechts aussen) zusätzlich zu SQL noch Influx aktivieren. Klick ich aufs Zahnrad sieht man das sich die Konfigurationsseite noch aufbaut, aber dann kommt der Fehler und die Seite schmiert ab. Bei einen Attribut das noch keine Aktivierung irgend einer Option hat geht die Seite sauber auf. Der Fehler kommt auch in einer inkognito Session des Browsers.

Habe auch schon auf Admin 6.2.11 upgedated, leider das selbe Problem.

**Comment by Feuer-sturm** [comment]
@GermanBluefox I can reproduce the error from @JohGrei as well with Admin 6.2.11

Debug Konsole
![grafik](https://user-images.githubusercontent.com/25422320/181949121-434addfc-608d-47a1-b62c-cbd57dae7e81.png)

**Comment by Diginix** [comment]
It is still not possible to view or edit objects properties by clicking the gear icon.
Last beta where it is working fine is 6.2.4.

browser console:
```
TypeError: Cannot read properties of undefined (reading 'toString')
    at et.componentDidMount (ConfigNumber.jsx:43:40)
    at Zs (react-dom.production.min.js:261:217)
    at Gs (react-dom.production.min.js:260:446)
    at Gs (react-dom.production.min.js:260:343)
    at Xc (react-dom.production.min.js:259:431)
    at bc (react-dom.production.min.js:283:96)
    at $n (react-dom.production.min.js:281:398)
    at bs (react-dom.production.min.js:270:269)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
(anonymous) @ instrument.ts:124
Hi @ react-dom.production.min.js:189
i.componentDidCatch.t.callback @ react-dom.production.min.js:190
Yo @ react-dom.production.min.js:144
Zs @ react-dom.production.min.js:261
Gs @ react-dom.production.min.js:260
Xc @ react-dom.production.min.js:259
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
ea @ react-dom.production.min.js:273
hn @ react-dom.production.min.js:127
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
bs @ react-dom.production.min.js:270
Ln @ scheduler.production.min.js:13
Gn @ scheduler.production.min.js:14
instrument.ts:124 debounceTime => 0
instrument.ts:124 blockTime => 1000
instrument.ts:124 ignoreBelowNumber => 
instrument.ts:124 disableSkippedValueLogging => false
instrument.ts:124 customRetentionDuration => 365
instrument.ts:124 enableDebugLogs => false
```

**Comment by Feuer-sturm** [comment]
Issue is fixed on my test system with admin 6.2.13
@Diginix @JohGrei @stmiko @cburghardt @Armin46 you can doublecheck as well

**Comment by JohGrei** [comment]
@Feuer-sturm funkt nun wieder, Danke

**Comment by Diginix** [comment]
hier auch

**Comment by Armin46** [comment]
I can confirm its working. Thx for the quick fix.
