### ISSUE TITLE
click on instance settings menu for login background leads to crash of admin

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.admin#1618]
admin 6.2.6
nodejs 14.20.0

browser console:
```
TypeError: Cannot read properties of undefined (reading 'value')
    at vn.renderItem (ConfigText.jsx:36:34)
    at vn.render (ConfigGeneric.jsx:514:39)
    at Wi (react-dom.production.min.js:204:189)
    at Rs (react-dom.production.min.js:203:149)
    at oa (react-dom.production.min.js:292:172)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
```

**Comment by Diginix** [comment]
fixed with 6.2.10
