### ISSUE TITLE
Error adding a custom value in 0_userdata

### ISSUE THREAD

**Issue by MikeEcho0815** [ioBroker/ioBroker.admin#1620]
I am getting this error message, while activating Data Logging (influxdb) for this datapoint.

`2instrument.ts:124 TypeError: Cannot read properties of undefined (reading 'value')
    at vn.renderItem (ConfigText.jsx:36:34)
    at vn.render (ConfigGeneric.jsx:514:39)
    at Wi (react-dom.production.min.js:204:189)
    at Rs (react-dom.production.min.js:203:149)
    at oa (react-dom.production.min.js:292:172)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
(anonym) @ instrument.ts:124`

**Comment by Feuer-sturm** [comment]
Is duplicate to #1614 and fixed in next version
