### ISSUE TITLE
GUI error in Objects tab when editing data loggin options

### ISSUE THREAD

**Issue by darkwaiter** [ioBroker/ioBroker.admin#1628]
Error page showes up while klicking the "userdefined settings" option in the Objects tab on an entry to edit the data logging options (mysql):

Following the on screen instructions - here is the error:

"Error: Promised response from onMessage listener went out of scope"

I hope someone can make some sense out of it and correct the bug...

**Comment by Feuer-sturm** [comment]
@darkwaiter Which admin version is in use?

Do you get the error if you activate mysql logging or do you get the error if you click on the gear icon to enter the menu for configuring the logging?

**Comment by TbsJah** [comment]
Same for me
v6.2.12
Occurs only if InfluxDB is active for the object

`instrument.ts:124 TypeError: Cannot read properties of undefined (reading 'toString')
    at et.componentDidMount (ConfigNumber.jsx:43:40)
    at Zs (react-dom.production.min.js:261:217)
    at Gs (react-dom.production.min.js:260:446)
    at Gs (react-dom.production.min.js:260:343)
    at Xc (react-dom.production.min.js:259:431)
    at bc (react-dom.production.min.js:283:96)
    at $n (react-dom.production.min.js:281:398)
    at bs (react-dom.production.min.js:270:269)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)`

**Comment by Feuer-sturm** [comment]
@TbsJah your error is a known issue https://github.com/ioBroker/ioBroker.admin/issues/1615#issuecomment-1200093990

**Comment by darkwaiter** [comment]
updated admin to v6.2.13 - works fine again.
