### ISSUE TITLE
GUI Error if trying to edit settings of web socket instance

### ISSUE THREAD

**Issue by git-jrgsch** [ioBroker/ioBroker.admin#1629]
I played with "Let's Encrypt SSL Setting" in Web Socket instance, now each time I try to edit Web Socket Settings I get an GUI error.
Admin 6.2.12

instrument.ts:124 TypeError: Cannot read properties of undefined (reading 'toString')
    at et.componentDidMount (ConfigNumber.jsx:43:40)
    at Zs (react-dom.production.min.js:261:217)
    at Gs (react-dom.production.min.js:260:446)
    at Gs (react-dom.production.min.js:260:343)
    at Xc (react-dom.production.min.js:259:431)
    at bc (react-dom.production.min.js:283:96)
    at $n (react-dom.production.min.js:281:398)
    at bs (react-dom.production.min.js:270:269)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)

**Comment by GermanBluefox** [comment]
Duplicate
