### ISSUE TITLE
GUI Error in Chrome but not in Edge

### ISSUE THREAD

**Issue by daBoehmer** [ioBroker/ioBroker.admin#1643]
**Describe the bug**  
When opening the dashboard in Chrome, there is a big "GUI Error" headline and the prompt to post the error from browser console here in github.

**Expected behavior**  
If I go to the dashboard, I expect the dashboard to open.

**Screenshots & Logfiles**  
```
iobroker.admin@5.3.8
instrument.ts:124 [2022-08-10T18:28:26.732Z] Try to connect
:8081/favicon.ico:1          Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
:8081/static/js/14.3cc5fdb8.chunk.js:1          Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
no-image.png:1          Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
instrument.ts:124 ChunkLoadError: Loading chunk 14 failed.
(error: http://192.168.178.90:8081/static/js/14.3cc5fdb8.chunk.js)
    at u.e (VM14:1:3974)
    at App.js:68:36
    at S (react.production.min.js:18:52)
    at Zi (react-dom.production.min.js:269:22)
    at jl (react-dom.production.min.js:250:347)
    at Vl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at bl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
    at Ka (react-dom.production.min.js:123:61)
    at Za (react-dom.production.min.js:122:428)
    at pl (react-dom.production.min.js:237:203)
    at Object.enqueueSetState (react-dom.production.min.js:133:211)
    at m.setState (react.production.min.js:12:369)
    at App.js:579:38
    at u (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at i (asyncToGenerator.js:25:9)
(anonymous) @ instrument.ts:124
browserError.png:1          Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
DevTools failed to load source map: Could not load content for chrome-extension://pgjjikdiikihdfpoppgaidccahalehjh/webspeed.js.map: System error: net::ERR_BLOCKED_BY_CLIENT

```

**Versions:**  
 - Operating system: <Windows>

**Comment by Feuer-sturm** [comment]
@daBoehmer did you try clearing your Browser Cache?

**Comment by GermanBluefox** [comment]
Does anything from the suggestions helped? https://aboutssl.org/fix-google-chrome-error-err_ssl_protocol_error/

**Comment by Feuer-sturm** [comment]
No feedback from @daBoehmer 
Issue closed.
