### ISSUE TITLE
Admin 6: Cannot read properties of undefined (reading 'localIcon')

### ISSUE THREAD

**Issue by patrickbs96** [ioBroker/ioBroker.admin#1666]
**Describe the bug**  
While installing all open updates admin crashed with this error message. 
I still have available updates for admin so maybe this has already been solved.

**Screenshots & Logfiles**  
```
instrument.ts:123 TypeError: Cannot read properties of undefined (reading 'localIcon')
    at Aa.renderOneAdapter (AdaptersUpdater.jsx:178:59)
    at AdaptersUpdater.jsx:351:55
    at Array.map (<anonymous>)
    at Aa.render (AdaptersUpdater.jsx:351:35)
    at Wi (react-dom.production.min.js:204:189)
    at Rs (react-dom.production.min.js:203:149)
    at oa (react-dom.production.min.js:292:172)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
```

**Versions:**  
 - Adapter version: <6.2.14>
 - JS-Controller version: <4.0.23> 
 - Node version: <v16.14.0> 
 - Operating system: <linux>

**Comment by Feuer-sturm** [comment]
@patrickbs96 Please check with current admin version

**Comment by GermanBluefox** [comment]
It is fixed already
