### ISSUE TITLE
Error in Gui on Adapter Page

### ISSUE THREAD

**Issue by Horgul123** [ioBroker/ioBroker.admin#1671]
Today I found out that I can't open the adapter page in admin 6.2.19 anymore "Error in GUI".
Downgrade to 6.2.17 doen't help, restart and fix do not change anything

Console shows this:

instrument.ts:123 TypeError: Cannot read properties of undefined (reading 'beta')
    at Zs.render (Adapters.jsx:1732:34)
    at Wi (react-dom.production.min.js:204:189)
    at Rs (react-dom.production.min.js:203:149)
    at oa (react-dom.production.min.js:292:172)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.admin/issues/1670
