### ISSUE TITLE
[v3] Error in config dialog can crash admin

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#168]
While debugging a new config dialog for an adapter, I managed to crash the entire admin through a faulty socket.emit:

```
2018-02-02 21:00:03.648  - error: Caught by controller[0]: TypeError: callback is not a function
2018-02-02 21:00:03.649  - error: Caught by controller[0]:     at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.admin/lib/socket.js:645:17)
2018-02-02 21:00:03.649  - error: Caught by controller[0]:     at emitTwo (events.js:125:13)
2018-02-02 21:00:03.649  - error: Caught by controller[0]:     at Socket.emit (events.js:213:7)
2018-02-02 21:00:03.649  - error: Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.admin/node_modules/socket.io/lib/socket.js:503:12
2018-02-02 21:00:03.649  - error: Caught by controller[0]:     at _combinedTickCallback (internal/process/next_tick.js:131:7)
2018-02-02 21:00:03.649  - error: Caught by controller[0]:     at process._tickCallback (internal/process/next_tick.js:180:9)
```

The faulty call was as follows:
```js
socket.emit("getStates", ["info.apiVersion", "info.requiresPairing", "info.paired"], (error, states) => { ... });
```

**Comment by GermanBluefox** [comment]
Fixed in 3.1.9
