### ISSUE TITLE
Error in GUI beim Öffnen der INstanzen

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.admin#1683]
Hier der Fehlercode aus der console (Nach dem F12 gedrückt wurde)
```
Access to script at 'http://datenspeicher:8081/static/js/4191.3894ba77.chunk.js' from origin 'http://datenspeicher:8081' has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space `private`.
4191.3894ba77.chunk.js:1          Failed to load resource: net::ERR_FAILED
:8081/?#tab-instances:1 Access to script at 'http://datenspeicher:8081/static/js/8596.375716c9.chunk.js' from origin 'http://datenspeicher:8081' has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space `private`.
8596.375716c9.chunk.js:1          Failed to load resource: net::ERR_FAILED
:8081/?#tab-instances:1 Access to script at 'http://datenspeicher:8081/static/js/7397.990440f2.chunk.js' from origin 'http://datenspeicher:8081' has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space `private`.
7397.990440f2.chunk.js:1          Failed to load resource: net::ERR_FAILED
8891.e3a76861.chunk.js:11 ChunkLoadError: Loading chunk 4191 failed.
(error: http://datenspeicher:8081/static/js/4191.3894ba77.chunk.js)
    at n.f.j (main.85ac6cc5.js:3:1011)
    at main.85ac6cc5.js:1:1300
    at Array.reduce (<anonymous>)
    at n.e (main.85ac6cc5.js:1:1266)
    at 5710.ca68a70f.chunk.js:73:88031
    at G (9526.113dc042.chunk.js:9:3265)
    at oa (3961.a98ff7ab.chunk.js:16:44605)
    at ra (3961.a98ff7ab.chunk.js:16:39832)
    at Jc (3961.a98ff7ab.chunk.js:16:39763)
    at ml (3961.a98ff7ab.chunk.js:16:39622)
    at ea (3961.a98ff7ab.chunk.js:16:36762)
    at hn (3961.a98ff7ab.chunk.js:14:3267)
    at 3961.a98ff7ab.chunk.js:16:34331
(anonym) @ 8891.e3a76861.chunk.js:11
:8081/?#tab-instances:1 Access to image at 'http://datenspeicher:8081/img/browserError.png' from origin 'http://datenspeicher:8081' has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space `private`.
browserError.png:1          Failed to load resource: net::ERR_FAILED
:8081/?#tab-instances:1 Access to CSS stylesheet at 'http://datenspeicher:8081/css/leaflet.css' from origin 'http://datenspeicher:8081' has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space `private`.
:8081/?#tab-instances:1 Access to CSS stylesheet at 'http://datenspeicher:8081/static/css/5710.41ed5ace.chunk.css' from origin 'http://datenspeicher:8081' has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space `private`.
:8081/?#tab-instances:1 Access to internal resource at 'http://datenspeicher:8081/manifest.json' from origin 'http://datenspeicher:8081' has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space `private`.
```

**Comment by Feuer-sturm** [comment]
@BenAhrdt Which admin version was used to trigger the error?

**Comment by BenAhrdt** [comment]
6.2.20

**Comment by Feuer-sturm** [comment]
@BenAhrdt can you please double check with 6.2.21 as well?

**Comment by BenAhrdt** [comment]
it looks like in 6.2.22 it works
