### ISSUE TITLE
ERROR in GUI:

### ISSUE THREAD

**Issue by Speedwire2020** [ioBroker/ioBroker.admin#1786]
DUMP:

instrument.ts:123 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BAdapter%20to%20query%20values%20from%20sma%20devices%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Zr (react-dom.production.min.js:152:60)
    at Q (react-dom.production.min.js:162:372)
    at ae (react-dom.production.min.js:192:308)
    at oa (react-dom.production.min.js:294:9)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
(anonym) @ instrument.ts:123
Hi @ react-dom.production.min.js:189
i.componentDidCatch.t.callback @ react-dom.production.min.js:190
Yo @ react-dom.production.min.js:144
Zs @ react-dom.production.min.js:261
Gs @ react-dom.production.min.js:260
Xc @ react-dom.production.min.js:259
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
bs @ react-dom.production.min.js:269
Ln @ scheduler.production.min.js:13
Gn @ scheduler.production.min.js:14

++++++++++++++++++++++++++++++++++++++++++++++++++++
**Versions:**  
Kernel-release  5.15.64-1-pve
Verteilung  Ubuntu
OS build-version  UTF-8
Architektur   x64
Release  22.04.1 LTS
Plattform  linux
Codename  Jammy Jellyfish

Python 3 version   3.10.4
Perl-version       5.34.0
Git-version        2.34.1
v8-version         9.4.146.26-node.22
Postfix-version    3.6.4
GCC version        11.2.0
Knoten openssl-version  1.1.1q+quic
Bash-Version       5.1.16
Kernel-release     5.15.64-1-pve
Python version     2.7.16
Redis-version      6.0.16
OpenSSL-Bibliothek  OpenSSL
os.pip             18.1
OS openssl-version 3.0.2
Node.js version    16.17.0
NPM version        6.14.8

**Comment by Feuer-sturm** [comment]
@Speedwire2020 Which admin version do you use?
What did you do to trigger the error?

**Comment by Speedwire2020** [comment]
@Feuer-sturm   Admin version is 6.2.23
The trigger was when I try to hover over the Adapter:
 "[ioBroker.sma-speedwire](https://github.com/AttackStrawbery/ioBroker.sma-speedwire)"

then the GUI crashed. It was not neccessary to klick - it was just a hover over the Icon of the adapter.
It was also not possible any longer to open the "general" Adapters in ListView Mode.  It won't open.

I strongly believe this is the smy-speedwire Adapter which causes the problem.

**Comment by Apollon77** [comment]
Yes the adapter io-package is broken!!
https://github.com/AttackStrawbery/ioBroker.sma-speedwire/blob/release/io-package.json#L16

**Comment by Apollon77** [comment]
And in fact the adapte ris NOT in any repio, so there is nothing we can really do against it ... beside ignoring auch invalid data maybe

**Comment by Feuer-sturm** [comment]
Issue in adapter repo is available to fix io-package.json: https://github.com/AttackStrawbery/ioBroker.sma-speedwire/issues/14
Changed this issue from bug to enhancment (see last comment https://github.com/ioBroker/ioBroker.admin/issues/1786#issuecomment-1367650036)
