### ISSUE TITLE
Fehler in Gui

### ISSUE THREAD

**Issue by Unbekannter1900** [ioBroker/ioBroker.admin#1795]
Moin 
ich bekomme immer wieder diese Fehlermeldungen raus gehauen. Die kommen immer wieder mal egal wo man klickt. 
Woran kann das liegen ? Hab das alles neu und gerade erst gestern angefangen mit iobroker 

lg 

instrument.ts:123 
 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Ks (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:26162)
    at Ie (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27463)
    at Xs (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27920)
    at Ie (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27725)
    at Ie (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27920)
    at Ie (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27920)
    at Ie (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27725)
    at Ie (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27725)
    at Ie (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27920)
    at Ie (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27920)
    at Ie (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27725)
    at Ie (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27725)
    at Ie (http://192.168.178.66:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
﻿

**Comment by Feuer-sturm** [comment]
@Unbekannter1900 Hi,  welche Admin Version hast du installiert? 
Wo klickst du genau hin, um den Fehler zu triggern?

**Comment by Unbekannter1900** [comment]
@Feuer-sturm Moin , es ist die Adminversion v.6.2.23 installiert. Ich hatte gestern das alles aufgesetzt nach der Anleitung von verdrahtet.Info und den Rasberry so aufgesetzt mit den 64Bit Programm wie beschrieben inklusive IoBroker. Hat auch alles geklappt bis ich alle Adapter dann installiert hatte ( hatte letztes Jahr den Pi schon mal laufen aber der kam nach Umbau in Vergessenheit) . Der Fehler kommt überall mal aber am meisten wenn ich auf Objekte gehe . 
Dachte erst es liegt an den Müllabfuhradapter aber den hab ich vorhin weg gelassen als ich das noch mal neu aufgesetzt habe und es kam wieder der Fehler

**Comment by Feuer-sturm** [comment]
@Unbekannter1900 nach welcher genauen Anleitung hast du iobroker installiert? Wird dort der Installations Einzeiler Verwendet, über welchen alles installiert wird?
Tritt dein Problem auch mit einen ganz frischen Installation auf, ohne das du zusätzliche Adapter installiert hast?

**Comment by Unbekannter1900** [comment]
@Feuer-sturm ich habe nach dieser Videoanleitung hier genau installiert [Verdrahtet.info](https://youtu.be/xb-S8pWtwu4) 
Das hab ich noch nicht direkt probiert, hatte das schon mehrmals aufgesetzt mit verschiedenen Versionen aber das Problem ging dann immer so nach 20 min los. Hatte gestern noch die Node neu gemacht auf eine ältere Version aber das hat auch nichts geholfen leider.

**Comment by Feuer-sturm** [comment]
@Unbekannter1900 Ich hab gerade in einer Virtuellen Maschine (hab keinen Pi zur Hand) einen frischen ioBroker aufgesetzt und konnte das Problem spontan nicht reproduzieren.
Mein Vorschlag: Wir lassen dieses issue offen, damit Bluefox es sich einmal ansehen kann ob er spontan was finden kann. Parallel wäre es für dich eine Möglichkeit im Forum ein Thread zu erstellen, wo man einmal dein System durchleuchten kann ob dort irgendwas anderes auffällig ist (z.B. welche Node Version du installiert hast, arbeitest du als root etc. )

**Comment by Nobse80** [comment]
Hallo Zusammen,

auch bei mir tritt dieses Problem auf sobald ich mit dem Edge Browser ich auf den Reiter Objekte klicke. Wenn ich bei der Nutzung des Firefox Browsers oder über den Browser des Tablets auf den Reiter Objekte gehe, erscheint die Fehlermeldung nicht und ich kann alle Objekte anklicken.

Die Fehlermeldung bei der Nutzung des Edge Browsers ist identisch wie die von @Unbekannter1900:

OMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Ks (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:26162)
    at Ie (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27463)
    at Xs (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27920)
    at Ie (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27725)
    at Ie (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27920)
    at Ie (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27920)
    at Ie (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27725)
    at Ie (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27725)
    at Ie (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27920)
    at Ie (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27920)
    at Ie (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27725)
    at Ie (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27725)
    at Ie (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27725)
    at Ie (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27725)
    at Ie (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27920)
    at Ie (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27725)
    at Ie (http://192.168.178.52:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)

**Comment by Feuer-sturm** [comment]
Sehe gerade, dass eure beiden Fehlermeldungen hier auch schon gemeldet sind #1785
@Unbekannter1900 Nutzt du auch den Edge Browser?

**Comment by Nobse80** [comment]
@Feuer-sturm Danke für den Hinweis auf die Fehlermeldung #1785. Darin wird ebenfalls der Edge Browser im Zusammenhang mit dem eingeschalteten Microsoft Translator erwähnt. Das Problem tritt wirklich nur bei eingeschalteten Translator auf. Ist er deaktiviert, kann man ohne Probleme im Reiter Objekte arbeiten.

**Comment by Feuer-sturm** [comment]
@Nobse80 danke für dein Feedback. Kannst du bitte deine Erkenntniss unter das Hauptticket #1785 ebenfalls posten. Das nutze ich aktuell als Master Ticket. Dann hat Bluefox die relevanten Infos an einer Stelle.

**Comment by Feuer-sturm** [comment]
@Unbekannter1900 @Nobse80 Bitte einmal Browser Cache leeren und prüfen ob nach einem neu laden der Seite der Fehler weiterhin auftritt.

**Comment by Nobse80** [comment]
Den Cache des Browsers hatte ich bereits schon geleert in der Hoffnung, damit das Problem zu lösen. Aber leider hat das nicht geholfen.

**Comment by Apollon77** [comment]
Und hattest Du auch einen "harten Reload" (Shift f5) versucht/gemacht?
