### ISSUE TITLE
Error in GUI

### ISSUE THREAD

**Issue by Haifeif** [ioBroker/ioBroker.admin#1798]
instrument.ts:123 TypeError: t is not a function
    at Zi (react-dom.production.min.js:240:251)
    at ur (react-dom.production.min.js:244:163)
    at Et (react-dom.production.min.js:284:388)
    at bc (react-dom.production.min.js:283:409)
    at $n (react-dom.production.min.js:281:398)
    at ea (react-dom.production.min.js:273:439)
    at hn (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273

More needed?

**Comment by Apollon77** [comment]
Yes, ideally infos to what you did before/as you get that error :-)

**Comment by Feuer-sturm** [comment]
@Haifeif which admin version is in use?

**Comment by Haifeif** [comment]
@ feuersturm -> v6.2.23
@Apollon77 -> nothing :-) Honest, during work, nothing special as far as I can remember. It suddenly appears.

**Comment by GermanBluefox** [comment]
It is impossible to find this error... No traces
