### ISSUE TITLE
Found not Language German

### ISSUE THREAD

**Issue by Tony-0808** [ioBroker/ioBroker.admin#1803]
**Describe the bug**  

**To Reproduce**  
Start ioBroker, Click on Objects an then Click on Instanz

```
in@6.2.23
instrument.ts:123 [2022-11-23T07:57:29.572Z] Try to connect
:8081/#tab-intro:1 Unchecked runtime.lastError: The message port closed before a response was received.
:8081/favicon.ico:1          Failed to load resource: net::ERR_CACHE_READ_FAILURE
instrument.ts:123 Stored version: , new version: 6.2.23
instrument.ts:123 Connected: true
instrument.ts:123 Double links: "flot.0/flot/edit.html" and "flot.0"
instrument.ts:123 Double links: "material.0/material/index.html" and "material.0"
instrument.ts:123 Double links: "vis.0/vis/edit.html" and "vis.0"
instrument.ts:123 Translate: Link
dwd.png:1          Failed to load resource: net::ERR_CACHE_READ_FAILURE
instrument.ts:123 Translate: time
instrument.ts:123 Translate: timeOffset
instrument.ts:123 Translate: _nodeCurrent
instrument.ts:123 Translate: _nodeNewest
instrument.ts:123 Translate: _nodeNewestNext
instrument.ts:123 Translate: _npmCurrent
instrument.ts:123 Translate: _npmNewest
instrument.ts:123 Translate: _npmNewestNext
:8081/static/js/7412.a02b4628.chunk.js:1          Failed to load resource: net::ERR_CACHE_READ_FAILURE
:8081/static/js/9533.5df9dcf6.chunk.js:1          Failed to load resource: net::ERR_CACHE_READ_FAILURE
:8081/static/js/6322.e8b8cd7b.chunk.js:1          Failed to load resource: net::ERR_CACHE_READ_FAILURE
instrument.ts:123 ChunkLoadError: Loading chunk 7412 failed.
(error: http://192.168.178.44:8081/static/js/7412.a02b4628.chunk.js)
    at n.f.j (jsonp chunk loading:27:18)
    at ensure chunk:6:25
    at Array.reduce (<anonymous>)
    at n.e (ensure chunk:5:56)
    at App.jsx:85:36
    at G (react.production.min.js:18:161)
    at oa (react-dom.production.min.js:291:300)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at ea (react-dom.production.min.js:273:245)
    at hn (react-dom.production.min.js:127:105)
    at react-dom.p
  ```

**Comment by Feuer-sturm** [comment]
@Tony-0808 
Which admin version do you use?
Which Browser do you use?  Is in your Browser a Page translator activated?

**Comment by Feuer-sturm** [comment]
No feedback from @Tony-0808 . Issue closed.
If this issue is still relevant please write a comment here an we can reopen the issue.
