### ISSUE TITLE
Fehler in der GUI beim Aufrufen von Objekten

### ISSUE THREAD

**Issue by dietmarhabert** [ioBroker/ioBroker.admin#1826]
VM14:2 Edge Translation started
bootstrap.jsx:19 iobroker.admin@6.2.23
instrument.ts:123 [2022-12-08T10:28:54.978Z] Try to connect
instrument.ts:123 Stored version: , new version: 6.2.23
instrument.ts:123 Connected: true
instrument.ts:123 Double links: "flot.0/flot/edit.html" and "flot.0"
instrument.ts:123 Double links: "vis.0/vis/edit.html" and "vis.0"
instrument.ts:123 Translate: Link
instrument.ts:123 Translate: time
instrument.ts:123 Translate: timeOffset
instrument.ts:123 Translate: _nodeCurrent
instrument.ts:123 Translate: _nodeNewest
instrument.ts:123 Translate: _nodeNewestNext
instrument.ts:123 Translate: _npmCurrent
instrument.ts:123 Translate: _npmNewest
instrument.ts:123 Translate: _npmNewestNext
instrument.ts:123 + subscribe ping.0.iPhone-3
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.INFO.Hostname
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.INFO.IPAddress
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.INFO.Info1_Module
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.INFO.Info1_Version
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.INFO.Info2_Hostname
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.INFO.Info2_IPAddress
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.INFO.Info3_RestartReason
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.INFO.Module
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.INFO.RestartReason
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.INFO.Version
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.Heap
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.Hostname
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.LoadAvg
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.MqttCount
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.POWER
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.POWER1
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.POWER2
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.POWER3
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.POWER4
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.Sleep
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.SleepMode
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.Time
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.Uptime
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.UptimeSec
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.Vcc
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.Wifi_AP
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.Wifi_BSSId
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.Wifi_Channel
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.Wifi_Downtime
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.Wifi_LinkCount
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.Wifi_Mode
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.Wifi_RSSI
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.Wifi_SSId
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.Wifi_Signal
instrument.ts:123 + subscribe sonoff.0.Sicherung oben 4 fach.alive
instrument.ts:123 + subscribe system.adapter.tado.0.plugins.sentry.enabled
instrument.ts:123 + subscribe system.adapter.tado.0.alive
instrument.ts:123 + subscribe system.adapter.tado.0.compactMode
instrument.ts:123 + subscribe system.adapter.tado.0.connected
instrument.ts:123 + subscribe system.adapter.tado.0.cpu
instrument.ts:123 + subscribe system.adapter.tado.0.cputime
instrument.ts:123 + subscribe system.adapter.tado.0.eventLoopLag
instrument.ts:123 + subscribe system.adapter.tado.0.inputCount
instrument.ts:123 + subscribe system.adapter.tado.0.logLevel
instrument.ts:123 + subscribe system.adapter.tado.0.memHeapTotal
instrument.ts:123 + subscribe system.adapter.tado.0.memHeapUsed
instrument.ts:123 + subscribe system.adapter.tado.0.memRss
instrument.ts:123 + subscribe system.adapter.tado.0.outputCount
instrument.ts:123 + subscribe system.adapter.tado.0.sigKill
instrument.ts:123 + subscribe system.adapter.tado.0.uptime
instrument.ts:123 + subscribe tado.0.280004.Home.autoAssistFreeTrialEnabled
instrument.ts:123 + subscribe tado.0.280004.Home.awayRadiusInMeters
instrument.ts:123 + subscribe tado.0.280004.Home.christmasModeEnabled
instrument.ts:123 + subscribe tado.0.280004.Home.consentGrantSkippable
instrument.ts:123 + subscribe tado.0.280004.Home.dateCreated
instrument.ts:123 + subscribe tado.0.280004.Home.dateTimeZone
instrument.ts:123 + subscribe tado.0.280004.Home.enabledFeatures
instrument.ts:123 + subscribe tado.0.280004.Home.id
instrument.ts:123 + subscribe tado.0.280004.Home.installationCompleted
instrument.ts:123 + subscribe tado.0.280004.Home.isAirComfortEligible
instrument.ts:123 + subscribe tado.0.280004.Home.isBalanceAcEligible
instrument.ts:123 + subscribe tado.0.280004.Home.masterswitch
instrument.ts:123 + subscribe tado.0.280004.Home.name
instrument.ts:123 + subscribe tado.0.280004.Home.partner
instrument.ts:123 + subscribe tado.0.280004.Home.showAutoAssistReminders
instrument.ts:123 + subscribe tado.0.280004.Home.simpleSmartScheduleEnabled
instrument.ts:123 + subscribe tado.0.280004.Home.temperatureUnit
instrument.ts:123 + subscribe tado.0.280004._info. autoAssistFreeTrialEnabled
instrument.ts:123 + subscribe tado.0.280004._info. enabledFeatures
instrument.ts:123 + subscribe tado.0.280004._info. legacyHeatingInstallationsEnabled
instrument.ts:123 + subscribe tado.0.280004._info. quickActionsEnabled
instrument.ts:123 + subscribe tado.0.280004._info.awayRadiusInMeters
instrument.ts:123 + subscribe tado.0.280004._info.christmasModeEnabled
instrument.ts:123 + subscribe tado.0.280004._info.dateCreated
instrument.ts:123 + subscribe tado.0.280004._info.dateTimeZone
instrument.ts:123 + subscribe tado.0.280004._info.id
instrument.ts:123 + subscribe tado.0.280004._info.installationCompleted
instrument.ts:123 + subscribe tado.0.280004._info.latitude
instrument.ts:123 + subscribe tado.0.280004._info.longitude
instrument.ts:123 + subscribe tado.0.280004._info.name
instrument.ts:123 + subscribe tado.0.280004._info.partner
instrument.ts:123 + subscribe tado.0.280004._info.showAutoAssistReminders
instrument.ts:123 + subscribe tado.0.280004._info.simpleSmartScheduleEnabled
instrument.ts:123 + subscribe tado.0.280004._info.skills
instrument.ts:123 + subscribe tado.0.280004._info.temperatureUnit
instrument.ts:123 + subscribe tado.0.online
instrument.ts:123 > stateChange ping.0.iPhone-3
eventlist.png:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
tr-064-community.png:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
jqui-mfd.png:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.INFO.Hostname
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.INFO.IPAddress
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.INFO.Info1_Module
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.INFO.Info1_Version
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.INFO.Info2_Hostname
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.INFO.Info2_IPAddress
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.INFO.Info3_RestartReason
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.INFO.Module
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.INFO.RestartReason
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.INFO.Version
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.Heap
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.Hostname
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.LoadAvg
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.MqttCount
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.POWER
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.POWER1
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.POWER2
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.POWER3
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.POWER4
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.Sleep
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.SleepMode
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.Time
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.Uptime
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.UptimeSec
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.Vcc
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.Wifi_AP
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.Wifi_BSSId
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.Wifi_Channel
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.Wifi_Downtime
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.Wifi_LinkCount
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.Wifi_Mode
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.Wifi_RSSI
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.Wifi_SSId
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.Wifi_Signal
instrument.ts:123 > stateChange sonoff.0.Sicherung oben 4 fach.alive
instrument.ts:123 > stateChange system.adapter.tado.0.plugins.sentry.enabled
instrument.ts:123 > stateChange system.adapter.tado.0.alive
instrument.ts:123 > stateChange system.adapter.tado.0.compactMode
instrument.ts:123 > stateChange system.adapter.tado.0.connected
instrument.ts:123 > stateChange system.adapter.tado.0.cpu
instrument.ts:123 > stateChange system.adapter.tado.0.cputime
instrument.ts:123 > stateChange system.adapter.tado.0.eventLoopLag
instrument.ts:123 > stateChange system.adapter.tado.0.inputCount
instrument.ts:123 > stateChange system.adapter.tado.0.logLevel
instrument.ts:123 > stateChange system.adapter.tado.0.memHeapTotal
instrument.ts:123 > stateChange system.adapter.tado.0.memHeapUsed
instrument.ts:123 > stateChange system.adapter.tado.0.memRss
instrument.ts:123 > stateChange system.adapter.tado.0.outputCount
instrument.ts:123 > stateChange system.adapter.tado.0.sigKill
instrument.ts:123 > stateChange system.adapter.tado.0.uptime
instrument.ts:123 > stateChange tado.0.280004.Home.autoAssistFreeTrialEnabled
instrument.ts:123 > stateChange tado.0.280004.Home.awayRadiusInMeters
instrument.ts:123 > stateChange tado.0.280004.Home.christmasModeEnabled
instrument.ts:123 > stateChange tado.0.280004.Home.consentGrantSkippable
instrument.ts:123 > stateChange tado.0.280004.Home.dateCreated
instrument.ts:123 > stateChange tado.0.280004.Home.dateTimeZone
instrument.ts:123 > stateChange tado.0.280004.Home.enabledFeatures
instrument.ts:123 > stateChange tado.0.280004.Home.id
instrument.ts:123 > stateChange tado.0.280004.Home.installationCompleted
instrument.ts:123 > stateChange tado.0.280004.Home.isAirComfortEligible
instrument.ts:123 > stateChange tado.0.280004.Home.isBalanceAcEligible
instrument.ts:123 > stateChange tado.0.280004.Home.masterswitch
instrument.ts:123 > stateChange tado.0.280004.Home.name
instrument.ts:123 > stateChange tado.0.280004.Home.partner
instrument.ts:123 > stateChange tado.0.280004.Home.showAutoAssistReminders
instrument.ts:123 > stateChange tado.0.280004.Home.simpleSmartScheduleEnabled
instrument.ts:123 > stateChange tado.0.280004.Home.temperatureUnit
instrument.ts:123 > stateChange tado.0.280004._info. autoAssistFreeTrialEnabled
instrument.ts:123 > stateChange tado.0.280004._info. enabledFeatures
instrument.ts:123 > stateChange tado.0.280004._info. legacyHeatingInstallationsEnabled
instrument.ts:123 > stateChange tado.0.280004._info. quickActionsEnabled
instrument.ts:123 > stateChange tado.0.280004._info.awayRadiusInMeters
instrument.ts:123 > stateChange tado.0.280004._info.christmasModeEnabled
instrument.ts:123 > stateChange tado.0.280004._info.dateCreated
instrument.ts:123 > stateChange tado.0.280004._info.dateTimeZone
instrument.ts:123 > stateChange tado.0.280004._info.id
instrument.ts:123 > stateChange tado.0.280004._info.installationCompleted
instrument.ts:123 > stateChange tado.0.280004._info.latitude
instrument.ts:123 > stateChange tado.0.280004._info.longitude
instrument.ts:123 > stateChange tado.0.280004._info.name
instrument.ts:123 > stateChange tado.0.280004._info.partner
instrument.ts:123 > stateChange tado.0.280004._info.showAutoAssistReminders
instrument.ts:123 > stateChange tado.0.280004._info.simpleSmartScheduleEnabled
instrument.ts:123 > stateChange tado.0.280004._info.skills
instrument.ts:123 > stateChange tado.0.280004._info.temperatureUnit
instrument.ts:123 > stateChange tado.0.online
instrument.ts:123 > stateChange ping.0.iPhone-3
instrument.ts:123 > stateChange system.adapter.tado.0.alive
instrument.ts:123 > stateChange system.adapter.tado.0.connected
instrument.ts:123 > stateChange system.adapter.tado.0.memRss
instrument.ts:123 > stateChange system.adapter.tado.0.memHeapTotal
instrument.ts:123 > stateChange system.adapter.tado.0.memHeapUsed
instrument.ts:123 > stateChange system.adapter.tado.0.eventLoopLag
instrument.ts:123 > stateChange system.adapter.tado.0.uptime
instrument.ts:123 > stateChange system.adapter.tado.0.inputCount
instrument.ts:123 > stateChange system.adapter.tado.0.outputCount
instrument.ts:123 > stateChange system.adapter.tado.0.cpu
instrument.ts:123 > stateChange system.adapter.tado.0.cputime
instrument.ts:123 - unsubscribe ping.0.iPhone-3
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.INFO.Hostname
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.INFO.IPAddress
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.INFO.Info1_Module
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.INFO.Info1_Version
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.INFO.Info2_Hostname
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.INFO.Info2_IPAddress
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.INFO.Info3_RestartReason
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.INFO.Module
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.INFO.RestartReason
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.INFO.Version
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.Heap
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.Hostname
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.LoadAvg
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.MqttCount
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.POWER
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.POWER1
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.POWER2
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.POWER3
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.POWER4
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.Sleep
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.SleepMode
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.Time
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.Uptime
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.UptimeSec
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.Vcc
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.Wifi_AP
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.Wifi_BSSId
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.Wifi_Channel
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.Wifi_Downtime
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.Wifi_LinkCount
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.Wifi_Mode
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.Wifi_RSSI
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.Wifi_SSId
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.Wifi_Signal
instrument.ts:123 - unsubscribe sonoff.0.Sicherung oben 4 fach.alive
instrument.ts:123 - unsubscribe system.adapter.tado.0.plugins.sentry.enabled
instrument.ts:123 - unsubscribe system.adapter.tado.0.alive
instrument.ts:123 - unsubscribe system.adapter.tado.0.compactMode
instrument.ts:123 - unsubscribe system.adapter.tado.0.connected
instrument.ts:123 - unsubscribe system.adapter.tado.0.cpu
instrument.ts:123 - unsubscribe system.adapter.tado.0.cputime
instrument.ts:123 - unsubscribe system.adapter.tado.0.eventLoopLag
instrument.ts:123 - unsubscribe system.adapter.tado.0.inputCount
instrument.ts:123 - unsubscribe system.adapter.tado.0.logLevel
instrument.ts:123 - unsubscribe system.adapter.tado.0.memHeapTotal
instrument.ts:123 - unsubscribe system.adapter.tado.0.memHeapUsed
instrument.ts:123 - unsubscribe system.adapter.tado.0.memRss
instrument.ts:123 - unsubscribe system.adapter.tado.0.outputCount
instrument.ts:123 - unsubscribe system.adapter.tado.0.sigKill
instrument.ts:123 - unsubscribe system.adapter.tado.0.uptime
instrument.ts:123 - unsubscribe tado.0.280004.Home.autoAssistFreeTrialEnabled
instrument.ts:123 - unsubscribe tado.0.280004.Home.awayRadiusInMeters
instrument.ts:123 - unsubscribe tado.0.280004.Home.christmasModeEnabled
instrument.ts:123 - unsubscribe tado.0.280004.Home.consentGrantSkippable
instrument.ts:123 - unsubscribe tado.0.280004.Home.dateCreated
instrument.ts:123 - unsubscribe tado.0.280004.Home.dateTimeZone
instrument.ts:123 - unsubscribe tado.0.280004.Home.enabledFeatures
instrument.ts:123 - unsubscribe tado.0.280004.Home.id
instrument.ts:123 - unsubscribe tado.0.280004.Home.installationCompleted
instrument.ts:123 - unsubscribe tado.0.280004.Home.isAirComfortEligible
instrument.ts:123 - unsubscribe tado.0.280004.Home.isBalanceAcEligible
instrument.ts:123 - unsubscribe tado.0.280004.Home.masterswitch
instrument.ts:123 - unsubscribe tado.0.280004.Home.name
instrument.ts:123 - unsubscribe tado.0.280004.Home.partner
instrument.ts:123 - unsubscribe tado.0.280004.Home.showAutoAssistReminders
instrument.ts:123 - unsubscribe tado.0.280004.Home.simpleSmartScheduleEnabled
instrument.ts:123 - unsubscribe tado.0.280004.Home.temperatureUnit
instrument.ts:123 - unsubscribe tado.0.280004._info. autoAssistFreeTrialEnabled
instrument.ts:123 - unsubscribe tado.0.280004._info. enabledFeatures
instrument.ts:123 - unsubscribe tado.0.280004._info. legacyHeatingInstallationsEnabled
instrument.ts:123 - unsubscribe tado.0.280004._info. quickActionsEnabled
instrument.ts:123 - unsubscribe tado.0.280004._info.awayRadiusInMeters
instrument.ts:123 - unsubscribe tado.0.280004._info.christmasModeEnabled
instrument.ts:123 - unsubscribe tado.0.280004._info.dateCreated
instrument.ts:123 - unsubscribe tado.0.280004._info.dateTimeZone
instrument.ts:123 - unsubscribe tado.0.280004._info.id
instrument.ts:123 - unsubscribe tado.0.280004._info.installationCompleted
instrument.ts:123 - unsubscribe tado.0.280004._info.latitude
instrument.ts:123 - unsubscribe tado.0.280004._info.longitude
instrument.ts:123 - unsubscribe tado.0.280004._info.name
instrument.ts:123 - unsubscribe tado.0.280004._info.partner
instrument.ts:123 - unsubscribe tado.0.280004._info.showAutoAssistReminders
instrument.ts:123 - unsubscribe tado.0.280004._info.simpleSmartScheduleEnabled
instrument.ts:123 - unsubscribe tado.0.280004._info.skills
instrument.ts:123 - unsubscribe tado.0.280004._info.temperatureUnit
instrument.ts:123 - unsubscribe tado.0.online
12instrument.ts:123 
        
       DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Ks (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:26162)
    at Ie (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:27463)
    at Xs (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:27920)
    at Ie (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:27725)
    at Ie (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:27920)
    at Ie (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:27920)
    at Ie (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:27725)
    at Ie (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:27725)
    at Ie (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)
    at Xs (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)
    at Ie (http://192.168.178.112:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)

**Comment by Feuer-sturm** [comment]
@dietmarhabert 
Sounds like this issue #1785

Do you use Edge Browser with activated translation?

**Comment by dietmarhabert** [comment]
Yes, i use edge Browser with activated Translation.Danke und Gruß Dietmar Habert

**Comment by Feuer-sturm** [comment]
@dietmarhabert Please deactivate translation feature to prevent this error. You can track issue #1785 if Bluefox finds a soloutin for this problem.
