### ISSUE TITLE
Tab objects does not open/Вкладка объекты не открывается 

### ISSUE THREAD

**Issue by saykl** [ioBroker/ioBroker.admin#1835]
Error in GUI!
Please open the browser console (F12), copy error text from there and create the issue on github
Without this information it is not possible to analyse the error.
It should looks like

```
instrument.ts:124 TypeError: d.startsWith is not a function
    at Gt (ObjectBrowser.jsx:1089:22)
    at W.renderLeaf (ObjectBrowser.jsx:4507:37)
    at W.renderItem (ObjectBrowser.jsx:4592:25)
    at ObjectBrowser.jsx:4623:45
    at Array.map (<anonymous>)
    at W.renderItem (ObjectBrowser.jsx:4618:59)
    at ObjectBrowser.jsx:4623:45
    at Array.map (<anonymous>)
    at W.renderItem (ObjectBrowser.jsx:4618:59)
    at ObjectBrowser.jsx:4623:45
    at Array.map (<anonymous>)
    at W.renderItem (ObjectBrowser.jsx:4618:59)
    at W.render (ObjectBrowser.jsx:5205:28)
    at Wi (react-dom.production.min.js:204:189)
    at Rs (react-dom.production.min.js:203:149)
    at oa (react-dom.production.min.js:292:172)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
```

**Comment by Feuer-sturm** [comment]
@saykl which admin version do you use? 
Is your posted error the Real error from the browser console? I am confused, because you wrote "It should looks like"

**Comment by Feuer-sturm** [comment]
@saykl Please check with admin 6.3.4 :-)
