### ISSUE TITLE
Admin @ 6.3.3: delete filter not possible

### ISSUE THREAD

**Issue by m-s-b** [ioBroker/ioBroker.admin#1836]
Deleting "last" filter is leading to an error:
![image](https://user-images.githubusercontent.com/46641961/208059931-87e62b92-88df-4920-a237-4ec5ee70dfbd.png)

`instrument.ts:124 TypeError: d.startsWith is not a function
    at Gt (ObjectBrowser.jsx:1090:22)
    at W.renderLeaf (ObjectBrowser.jsx:4508:37)
    at W.renderItem (ObjectBrowser.jsx:4593:25)
    at ObjectBrowser.jsx:4637:45
    at Array.map (<anonymous>)
    at W.renderItem (ObjectBrowser.jsx:4632:59)
    at ObjectBrowser.jsx:4624:45
    at Array.map (<anonymous>)
    at W.renderItem (ObjectBrowser.jsx:4619:59)
    at ObjectBrowser.jsx:4624:45
    at Array.map (<anonymous>)
    at W.renderItem (ObjectBrowser.jsx:4619:59)
    at ObjectBrowser.jsx:4624:45
    at Array.map (<anonymous>)
    at W.renderItem (ObjectBrowser.jsx:4619:59)
    at W.render (ObjectBrowser.jsx:5206:28)
    at Wi (react-dom.production.min.js:204:189)
    at Rs (react-dom.production.min.js:203:149)
    at oa (react-dom.production.min.js:292:172)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)`

When an additional filter is used (e.g. colum name) filter in "ID" can be deleted and error occurs in "name". Deleting each single letter has the same error like deleting all with "X".

**Comment by m-s-b** [comment]
Problem occurs replicable with Chrome, no problem with Edge.

**Comment by m-s-b** [comment]
Actual no possibility (maybe reboot) to access objects tab again with chrome. Edge still working
Refresh / forced refresh is leading to:
`instrument.ts:124 TypeError: d.startsWith is not a function
    at Gt (ObjectBrowser.jsx:1090:22)
    at W.renderLeaf (ObjectBrowser.jsx:4508:37)
    at W.renderItem (ObjectBrowser.jsx:4593:25)
    at ObjectBrowser.jsx:4637:45
    at Array.map (<anonymous>)
    at W.renderItem (ObjectBrowser.jsx:4632:59)
    at ObjectBrowser.jsx:4624:45
    at Array.map (<anonymous>)
    at W.renderItem (ObjectBrowser.jsx:4619:59)
    at ObjectBrowser.jsx:4624:45
    at Array.map (<anonymous>)
    at W.renderItem (ObjectBrowser.jsx:4619:59)
    at ObjectBrowser.jsx:4624:45
    at Array.map (<anonymous>)
    at W.renderItem (ObjectBrowser.jsx:4619:59)
    at W.render (ObjectBrowser.jsx:5206:28)
    at Wi (react-dom.production.min.js:204:189)
    at Rs (react-dom.production.min.js:203:149)
    at oa (react-dom.production.min.js:292:172)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at ea (react-dom.production.min.js:273:300)
    at hn (react-dom.production.min.js:127:105)
    at bc (react-dom.production.min.js:283:470)
    at $n (react-dom.production.min.js:281:398)
    at bs (react-dom.production.min.js:270:269)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)`

**Comment by Apollon77** [comment]
You can delete local storage and cache, this then resets all locally stored settings

**Comment by Feuer-sturm** [comment]
@m-s-b Can you please check if you can reproduce this issue with admin 6.5.8?
On my system i am not able to reproduce your issue in my chrome browser.

**Comment by m-s-b** [comment]
@Feuer-sturm 
Mit Admin 6.5.8 und Chrome funktioniert es wieder einwandfrei.
