### ISSUE TITLE
Cannot read properties of null (reading '_acl')

### ISSUE THREAD

**Issue by Dennis4b** [ioBroker/ioBroker.admin#1843]
I run iobroker in a FreeBSD jail. Used the admin interface to upgrade the admin adapter, which then got stuck (because it died). Restoring a backup did not fix it, and even with a fresh install the admin adapter doesn't run. `iobroker fix` also didn't change anything.

I am not sure how to debug the following, hopefully someone can give some pointers: 

```
[iobroker@iobroker /]$ iobroker debug admin.0
Debugger listening on ws://127.0.0.1:9229/49c053a7-7253-4bd7-bd35-7dd7de8905fc
For help, see: https://nodejs.org/en/docs/inspector
2022-12-22 14:15:48.415  - debug: admin.0 (54453) Redis Objects: Use Redis connection: 127.0.0.1:9001
2022-12-22 14:15:48.427  - debug: admin.0 (54453) Objects client ready ... initialize now
2022-12-22 14:15:48.428  - debug: admin.0 (54453) Objects create System PubSub Client
2022-12-22 14:15:48.428  - debug: admin.0 (54453) Objects create User PubSub Client
2022-12-22 14:15:48.432  - debug: admin.0 (54453) Objects client initialize lua scripts
2022-12-22 14:15:48.435  - debug: admin.0 (54453) Objects connected to redis: 127.0.0.1:9001
2022-12-22 14:15:48.441  - debug: admin.0 (54453) Redis States: Use Redis connection: 127.0.0.1:9000
2022-12-22 14:15:48.443  - debug: admin.0 (54453) States create System PubSub Client
2022-12-22 14:15:48.443  - debug: admin.0 (54453) States create User PubSub Client
2022-12-22 14:15:48.446  - debug: admin.0 (54453) States connected to redis: 127.0.0.1:9000
2022-12-22 14:15:48.453  - debug: admin.0 (54453) Plugin sentry Initialize Plugin (enabled=true)
2022-12-22 14:15:48.535  - info: admin.0 (54453) starting. Version 6.3.4 in /opt/iobroker/node_modules/iobroker.admin, node: v16.18.1, js-controller: 4.0.23
2022-12-22 14:15:48.547  - info: admin.0 (54453) requesting all states
2022-12-22 14:15:48.548  - info: admin.0 (54453) requesting all objects
2022-12-22 14:15:48.707  - warn: admin.0 (54453) Cannot check node.js versions: Error: unexpected end of file
2022-12-22 14:15:48.707  - info: admin.0 (54453) received all objects
2022-12-22 14:15:48.711  - debug: admin.0 (54453) Using http createServer
2022-12-22 14:15:48.770  - debug: admin.0 (54453) Next repo update on 12/23/2022, 7:09:49 AM
2022-12-22 14:15:48.815  - info: admin.0 (54453) http server listening on port 8081
2022-12-22 14:15:48.816  - info: admin.0 (54453) Use link "http://localhost:8081" to configure.
2022-12-22 14:15:48.819  - info: admin.0 (54453) socket.io server listening on port 8081
2022-12-22 14:15:48.821  - error: admin.0 (54453) uncaught exception: Cannot read properties of null (reading '_acl')
2022-12-22 14:15:48.821  - error: admin.0 (54453) TypeError: Cannot read properties of null (reading '_acl')
    at SocketCommandsAdmin.subscribe (/opt/iobroker/node_modules/@iobroker/socket-classes/lib/socketCommands.js:288:117)
    at SocketAdmin.subscribe (/opt/iobroker/node_modules/@iobroker/socket-classes/lib/socketAdmin.js:181:23)
    at initSocket (/opt/iobroker/node_modules/iobroker.admin/main.js:499:12)
    at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.admin/lib/web.js:1048:29)
    at processImmediate (node:internal/timers:468:21)
2022-12-22 14:15:48.821  - error: admin.0 (54453) Cannot read properties of null (reading '_acl')
TypeError: Cannot read properties of null (reading '_acl')
    at SocketCommandsAdmin.subscribe (/opt/iobroker/node_modules/@iobroker/socket-classes/lib/socketCommands.js:288:117)
    at SocketAdmin.subscribe (/opt/iobroker/node_modules/@iobroker/socket-classes/lib/socketAdmin.js:181:23)
    at initSocket (/opt/iobroker/node_modules/iobroker.admin/main.js:499:12)
    at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.admin/lib/web.js:1048:29)
    at processImmediate (node:internal/timers:468:21)
2022-12-22 14:15:48.828  - info: admin.0 (54453) terminating http server on port 8081
2022-12-22 14:15:48.828  - info: admin.0 (54453) terminating
2022-12-22 14:15:48.828  - debug: admin.0 (54453) Plugin sentry destroyed
2022-12-22 14:15:48.829  - warn: admin.0 (54453) Terminated (UNCAUGHT_EXCEPTION): Without reason
[iobroker@iobroker /]$ 

```

```
[iobroker@iobroker /]$ iobroker info
Platform       : freebsd
os             : freebsd
Architecture   : x64
CPUs           : 4
Speed          : 3092 MHz
Model          : Intel(R) Xeon(R) CPU E3-1220 v3 @ 3.10GHz
RAM            : 15.9 GB 
System uptime  : 1d. 02:44:58
Node.js        : v16.18.1
time           : 1671715179085
timeOffset     : -60
adapters count : 449
NPM            : v8.19.1
Disk size      : 1.9 TiB
Disk free      : 1.9 TiB
```
(the system rebooted yesterday, but was running normally again until I tried to upgrade the adapter).

```
[iobroker@iobroker /]$ iobroker list adapters
system.adapter.admin                   : admin          - v6.3.4
system.adapter.backitup                : backitup       - v2.5.9
system.adapter.discovery               : discovery      - v3.1.0
```

**Comment by Apollon77** [comment]
Fixed in Admin 6.3.5 .. already stable too
