### ISSUE TITLE
Error in GUI (Dateien -> Zugriffssteuerungsliste)

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.admin#1844]
**Describe the bug**  
There is an error if click on "Abbrechen" in the window "Zugriffssteuerungsliste"

**To Reproduce**  
![Animation](https://user-images.githubusercontent.com/69053781/209281836-1d49fdb4-3aed-4f8d-8755-f793ed853a55.gif)

**Expected behavior**  
- no error
- access will be changed

**Screenshots & Logfiles**  
```
instrument.ts:124 TypeError: t is not a function
    at Zi (react-dom.production.min.js:240:251)
    at ur (react-dom.production.min.js:244:163)
    at Et (react-dom.production.min.js:284:388)
    at bc (react-dom.production.min.js:283:409)
    at $n (react-dom.production.min.js:281:398)
    at ea (react-dom.production.min.js:273:439)
    at hn (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
```

**Versions:**  
 - Adapter version: admin v6.3.5
 - JS-Controller version: v4.0.23
 - Node version: v16.19.0
 - Operating system: ioBroker.docker v7.2.0

**Comment by Feuer-sturm** [comment]
With admin v6.5.8 I can not reproduce the issue.
@ice987987 can you please double check with current beta admin version?

**Comment by ice987987** [comment]
issue does no longer appear in admin v6.5.9
thank you!
