### ISSUE TITLE
Error in Gui - when using textSendTo element

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#1891]
Admin crashes with ERROR IN GUI

```iobroker.admin@6.3.6
instrument.ts:124 [2023-03-09T19:47:01.503Z] Try to connect
(index):31 Uncaught (in promise) TypeError: window.io.emit is not a function
    at (index):31:15
    at new Promise (<anonymous>)
    at readJsonConfig ((index):30:10)
    at (index):39:25
(anonymous) @ (index):31
readJsonConfig @ (index):30
(anonymous) @ (index):39
setTimeout (async)
(anonymous) @ (index):38
instrument.ts:124 Stored version: , new version: 6.3.6
instrument.ts:124 Connected: true
instrument.ts:124 Translate: Link
instrument.ts:124 Translate: time
instrument.ts:124 Translate: timeOffset
instrument.ts:124 Translate: _nodeCurrent
instrument.ts:124 Translate: _nodeNewest
instrument.ts:124 Translate: _nodeNewestNext
instrument.ts:124 Translate: _npmCurrent
instrument.ts:124 Translate: _npmNewest
instrument.ts:124 Translate: _npmNewestNext
instrument.ts:124 [ADAPTERS] getAdapters
instrument.ts:124 [ADAPTERS] getAdaptersInfo
instrument.ts:124 [ADAPTERS] admin
scheduler.production.min.js:1 [Violation] 'message' handler took 2202ms
[Violation] Forced reflow while executing JavaScript took 425ms
rssfeed.png:1          GET https://raw.githubusercontent.com/oweitman/ioBroker.rssfeed/main/admin/rssfeed.png 404
Image (async)
Zs @ react-dom.production.min.js:262
Gs @ react-dom.production.min.js:260
Gs @ react-dom.production.min.js:260
Xc @ react-dom.production.min.js:259
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
bs @ react-dom.production.min.js:270
Ln @ scheduler.production.min.js:13
Gn @ scheduler.production.min.js:14
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://github.com/hausbus/ioBroker.hausbus_de/blob/main/admin/hausbusde.png with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
Image (async)
Zs @ react-dom.production.min.js:262
Gs @ react-dom.production.min.js:260
Gs @ react-dom.production.min.js:260
Xc @ react-dom.production.min.js:259
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
bs @ react-dom.production.min.js:270
Ln @ scheduler.production.min.js:13
Gn @ scheduler.production.min.js:14
instrument.ts:124 system.adapter.admin.0
instrument.ts:124 system.adapter.envertech-pv.0
instrument.ts:124 getInstances: 8
instrument.ts:124 Translate: lblCloudUsername
instrument.ts:124 Translate: hlpCloudUsername
instrument.ts:124 Translate: ttCloudUsername
instrument.ts:124 Translate: ttCloudPassword
instrument.ts:124 Translate: ttStationId
instrument.ts:124 Translate: lblCloudPassword
instrument.ts:124 Translate: hlpCloudPassword
instrument.ts:124 Translate: lblStationStations
instrument.ts:124 Translate: lblStationAct
instrument.ts:124 Translate: lblStationId
instrument.ts:124 Translate: lblPollIntvl
instrument.ts:124 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Berror%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Zr (react-dom.production.min.js:152:60)
    at Q (react-dom.production.min.js:162:372)
    at ae (react-dom.production.min.js:192:308)
    at oa (react-dom.production.min.js:294:9)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
(anonymous) @ instrument.ts:124
Hi @ react-dom.production.min.js:189
i.componentDidCatch.t.callback @ react-dom.production.min.js:190
Yo @ react-dom.production.min.js:144
Zs @ react-dom.production.min.js:261
Gs @ react-dom.production.min.js:260
Xc @ react-dom.production.min.js:259
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
bs @ react-dom.production.min.js:269
Ln @ scheduler.production.min.js:13
Gn @ scheduler.production.min.js:14```

Problem occures when textSendTo Element is used.

Extract from jsonConfig.json:

```
                "testTest": {
                    "type": "textSendTo",
                    "label": "lblStationId",
                    "command": "getStationId",
                    "jsonData": { "username": "aaa", "password": "bbb" },
                    "tooltip": "ttStationId",
                    "help": "hlpStationId"
                },
```

**Comment by GermanBluefox** [comment]
Please use:
```
"testTest": {
                "type": "textSendTo",
                "label": "lblStationId",
                "command": "getStationId",
                "jsonData": "{\"username\": \"aaa\", \"password\": \"bbb\" }",
                "tooltip": "ttStationId",
                "help": "hlpStationId"
            },
```

**Comment by mcm1957** [comment]
Thanks for feedback regarding escaping. I added the escaping to the example at SCHEMA.md as seraching for correcte scaping took a longt time :-)

I'm retrying textSendTo with correct escaping.

**Comment by mcm1957** [comment]
Problem is NOT yet fixed with **6.3.7**

```
iobroker.admin@6.3.7
instrument.ts:124 [2023-03-12T19:19:16.271Z] Try to connect
instrument.ts:124 Stored version: , new version: 6.3.7
instrument.ts:124 Connected: true
(index):31 Uncaught (in promise) TypeError: window.io.emit is not a function
    at (index):31:15
    at new Promise (<anonymous>)
    at readJsonConfig ((index):30:10)
    at (index):39:25
(anonymous) @ (index):31
readJsonConfig @ (index):30
(anonymous) @ (index):39
setTimeout (async)
(anonymous) @ (index):38
instrument.ts:124 system.adapter.admin.0
instrument.ts:124 system.adapter.jsonconfig-demo.0
instrument.ts:124 getInstances: 90
instrument.ts:124 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btext%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Zr (react-dom.production.min.js:152:60)
    at Q (react-dom.production.min.js:162:372)
    at ae (react-dom.production.min.js:192:308)
    at oa (react-dom.production.min.js:294:9)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
```

Please see github demo repo for demo adapter containing only minimal config:

https://github.com/mcm1957/ioBroker.jsonconfig-demo

```
        "testTest": {
            "type": "textSendTo",
            "label": "lblStationId",
            "command": "send",
            "jsonData": "{\"username\": \"aaa\", \"password\": \"bbb\" }",
            "alsoDependsOn": ["option2"]
        }
```

Debugging showed up that the crash occures during processing of the answer. Or more detailled after executing the answer sendTo.

Mayby this code is incorrect - but I did nogt find a working example yet:

```
 onMessage(obj) {
        if (typeof obj === 'object' && obj.message) {
            if (obj.command === 'send') {
                // e.g. send email or pushover or whatever
                this.log.info('send command');

                // Send response in callback if required
                if (obj.callback) this.sendTo(obj.from, obj.command, {text:'Message received'}, obj.callback);
            }
        }
    }
```

**Comment by GermanBluefox** [comment]
Please use:
```
onMessage(obj) {
        if (typeof obj === 'object' && obj.message) {
            if (obj.command === 'send') {
                // e.g. send email or pushover or whatever
                this.log.info('send command');

                // Send response in callback if required
                if (obj.callback) this.sendTo(obj.from, obj.command, 'Message received', obj.callback);
            }
        }
    }
```

**Comment by mcm1957** [comment]
Thanks, 
Element works now as expected (or nearly as expected :-).

Feel free to close this issue or keep itz opne as long as a gui crash occures when sending a bad response (in my oppinion it should result in an error message somewhere but not in en GUI crash - but the possibilities and effort must be checked by you.)

As expected:
I would expect that the returned text is displayed formatted at static text. Currently ist is formatted as a label text (smaller size). But mayby this is the official react standard ...

![image](https://user-images.githubusercontent.com/28575778/224809812-890e0adb-54c1-4030-9eec-21b3a18eb5dd.png)
