### ISSUE TITLE
Error in GUI

### ISSUE THREAD

**Issue by ausbremen** [ioBroker/ioBroker.admin#1895]
**Describe the bug**  

I wanted to check the log file and got the error message "Error in GUI" create issue in gitub

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles** 
```
Failed to load resource: the server responded with a status of 403 (Forbidden)
​ Forbidden
request.onload @ adapter/info/lib/js/…gle-calender.js:190
​ Channel: Error in handleResponse UNK/SW_UNREACHABLE REGISTER_FRAME undefined
_handleResponsePromise @ chrome-extension://p…ntScriptFrames.js:2
chrome-extension://p…ntScriptFrames.js:2 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
commons.js:2 Channel: Error in handleResponse UNK/SW_UNREACHABLE contextMenu createContextMenu
_handleResponsePromise @ commons.js:2
commons.js:2 Channel: Error in handleResponse UNK/SW_UNREACHABLE tabClipper checkBackgroundStatus
_handleResponsePromise @ commons.js:2
commons.js:2 Channel: Error in handleResponse UNK/SW_UNREACHABLE contextMenu createContextMenu
_handleResponsePromise @ commons.js:2
commons.js:2 Channel: Error in handleResponse UNK/SW_UNREACHABLE tabClipper checkBackgroundStatus
_handleResponsePromise @ commons.js:2
2commons.js:2 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
5710.edd703fc.chunk.js:73 Repo updated!
commons.js:2 Channel: Error in handleResponse UNK/SW_UNREACHABLE broadcastEventToTab clipper_state_changed
_handleResponsePromise @ commons.js:2
commons.js:2 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
commons.js:2 Channel: Error in handleResponse UNK/SW_UNREACHABLE broadcastEventToTab clipper_state_changed
_handleResponsePromise @ commons.js:2
commons.js:2 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
217.022a0015.chunk.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
3961.a98ff7ab.chunk.js:16 ChunkLoadError: Loading chunk 217 failed.
(error: https://iobroker.pro/admin/static/js/217.022a0015.chunk.js)
    at n.f.j (main.a9612c89.js:3:1011)
    at main.a9612c89.js:1:1300
    at Array.reduce (<anonymous>)
    at n.e (main.a9612c89.js:1:1266)
    at 5710.edd703fc.chunk.js:73:88194
    at G (react.production.min.js:18:161)
    at oa (3961.a98ff7ab.chunk.js:16:44605)
    at ra (3961.a98ff7ab.chunk.js:16:39832)
    at Jc (3961.a98ff7ab.chunk.js:16:39763)
    at ml (3961.a98ff7ab.chunk.js:16:39622)
Hi @ 3961.a98ff7ab.chunk.js:16
commons.js:2 Channel: Error in handleResponse UNK/SW_UNREACHABLE contextMenu createContextMenu
_handleResponsePromise @ commons.js:2
commons.js:2 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
commons.js:2 Channel: Error in handleResponse UNK/SW_UNREACHABLE contextMenu createContextMenu
_handleResponsePromise @ commons.js:2
commons.js:2 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
DevTools failed to load source map: Could not load content for https://iobroker.pro/admin/static/js/7526.333aae36.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```
**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by Feuer-sturm** [comment]
@ausbremen which admin version do you use?

**Comment by Feuer-sturm** [comment]
@ausbremen Is this issue still open from your side? Can you please answer Bluefox question?
