### ISSUE TITLE
Probleme mit der Lizenz VIS-2

### ISSUE THREAD

**Issue by eyichbins** [ioBroker/ioBroker.admin#1900]
Mein erster Post hier, hoffe so Richtig.
wenn ich den Lizensschlüssel von VIS eingeben will bekomme ich diese Fehlermeldung.
Auch bleibt der Adapter rot. komischerweise kann ich die VIS aber öffnen.

**instrument.ts:124 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BCountry%2C%20Name%2C%20AddressLine1%2C%20ZIP%2C%20City%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Zr (react-dom.production.min.js:152:60)
    at h (react-dom.production.min.js:156:186)
    at S (react-dom.production.min.js:158:331)
    at Q (react-dom.production.min.js:162:334)
    at ae (react-dom.production.min.js:192:308)
    at oa (react-dom.production.min.js:294:9)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at ea (react-dom.production.min.js:273:300)
    at hn (react-dom.production.min.js:127:105)
    at bc (react-dom.production.min.js:283:470)
    at $n (react-dom.production.min.js:281:398)
    at bs (react-dom.production.min.js:270:269)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128) the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by Feuer-sturm** [comment]
Same issue is mentioned in vis-2 repository as well: https://github.com/ioBroker/ioBroker.vis/issues/675
@Apollon77 @GermanBluefox   I think this topic is more an admin issue than an vis-2 issue. Is this correct?

**Comment by Xtrqqz** [comment]
Habe genau das gleiche Problem. Der Vis-2 Adapter bleibt rot.

Admin: 6.3.5
Vis2: 2.0.20

instrument.ts:124 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BCountry%2C%20Name%2C%20AddressLine1%2C%20ZIP%2C%20City%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Zr (react-dom.production.min.js:152:60)
    at h (react-dom.production.min.js:156:186)
    at S (react-dom.production.min.js:158:331)
    at Q (react-dom.production.min.js:162:334)
    at ae (react-dom.production.min.js:192:308)
    at oa (react-dom.production.min.js:294:9)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at ea (react-dom.production.min.js:273:300)
    at hn (react-dom.production.min.js:127:105)
    at bc (react-dom.production.min.js:283:470)
    at $n (react-dom.production.min.js:281:398)
    at bs (react-dom.production.min.js:270:269)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)

**Comment by Feuer-sturm** [comment]
@eyichbins @Xtrqqz Please check with admin 6.4.0

**Comment by Smarthome17** [comment]
Hallo, wer kann helfen? In meiner Iobroker Installation kann ich in den Instanzen keine Einstellungen des Vis Adapters vornehmen. Schraubenschlüssel fehlt? Kann mir also keinen Lizenzschlüssel der 1. Version kopieren?

**Comment by Feuer-sturm** [comment]
@Smarthome17 für vis1 wird keine Lizenz mehr benötigt, daher gibt es auch keine Einstellungen mehr bei vis1.

Generieren die bei iobroker.net eine vis2 Lizenz und trage diese in den vis2 Adapter ein.
