### ISSUE TITLE
Nach BackitUp Update beendet sich ioB selbstständig (Schleife)

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.admin#1905]
Nach einer missglückte BackItUp Sicherung (Admin war über 2 Stunden gestoppt und BackItUp hat keine Sicherung mehr durchgeführt), wurde der ioBroker Dienst (Windows Installation) händisch gestartet, was dann zu der unten aufgeführten Fehlermeldung führt.

Seit dem läßt sich ioB (Admin) nicht mehr starten.

```
3589.fc244685.chunk.js:74 iobroker.admin@6.4.1
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:16.789Z] Try to connect
31576.b3c6f0a9.chunk.js:12 Stored version: , new version: 6.4.1
1576.b3c6f0a9.chunk.js:12 Connected: true
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:23.999Z] ws connection error: CLOSE_ABNORMAL
(anonym) @ 1576.b3c6f0a9.chunk.js:12
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:24.000Z] Start reconnect 0
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:24.005Z] Try to connect
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:27.018Z] No READY flag received in 3 seconds. Re-init
(anonym) @ 1576.b3c6f0a9.chunk.js:12
socket.io.js:396 WebSocket connection to 'ws://10.122.60.87:8081/?sid=1679917224006&name=admin' failed: WebSocket is closed before the connection is established.
SocketClient.close @ socket.io.js:396
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:27.020Z] Start reconnect 1
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:27.020Z] ws connection error: CLOSE_ABNORMAL
(anonym) @ 1576.b3c6f0a9.chunk.js:12
21576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:27.020Z] Reconnect is already running 1
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:28.034Z] Try to connect
31576.b3c6f0a9.chunk.js:12 Cannot read adapters: timeout
1576.b3c6f0a9.chunk.js:12 Cannot get instances: notConnectedError
(anonym) @ 1576.b3c6f0a9.chunk.js:12
1576.b3c6f0a9.chunk.js:12 Cannot get notifications: notConnectedError
(anonym) @ 1576.b3c6f0a9.chunk.js:12
3589.fc244685.chunk.js:74 Uncaught (in promise) notConnectedError
1576.b3c6f0a9.chunk.js:12 Cannot get logs: notConnectedError
(anonym) @ 1576.b3c6f0a9.chunk.js:12
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:31.038Z] No READY flag received in 3 seconds. Re-init
(anonym) @ 1576.b3c6f0a9.chunk.js:12
socket.io.js:396 WebSocket connection to 'ws://10.122.60.87:8081/?sid=1679917228035&name=admin' failed: WebSocket is closed before the connection is established.
SocketClient.close @ socket.io.js:396
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:31.038Z] Start reconnect 2
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:31.038Z] ws connection error: CLOSE_ABNORMAL
(anonym) @ 1576.b3c6f0a9.chunk.js:12
21576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:31.039Z] Reconnect is already running 2
3:8081/#tab-intro:1 Uncaught (in promise) notConnectedError
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:33.039Z] Try to connect
6001576.b3c6f0a9.chunk.js:12 notConnectedError
(anonym) @ 1576.b3c6f0a9.chunk.js:12
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:36.041Z] No READY flag received in 3 seconds. Re-init
(anonym) @ 1576.b3c6f0a9.chunk.js:12
socket.io.js:396 WebSocket connection to 'ws://10.122.60.87:8081/?sid=1679917233039&name=admin' failed: WebSocket is closed before the connection is established.
SocketClient.close @ socket.io.js:396
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:36.042Z] Start reconnect 3
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:36.042Z] ws connection error: CLOSE_ABNORMAL
(anonym) @ 1576.b3c6f0a9.chunk.js:12
21576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:36.042Z] Reconnect is already running 3
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:39.051Z] Try to connect
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:42.055Z] No READY flag received in 3 seconds. Re-init
(anonym) @ 1576.b3c6f0a9.chunk.js:12
socket.io.js:396 WebSocket connection to 'ws://10.122.60.87:8081/?sid=1679917239051&name=admin' failed: WebSocket is closed before the connection is established.
SocketClient.close @ socket.io.js:396
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:42.056Z] Start reconnect 4
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:42.056Z] ws connection error: CLOSE_ABNORMAL
(anonym) @ 1576.b3c6f0a9.chunk.js:12
21576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:42.057Z] Reconnect is already running 4
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:46.067Z] Try to connect
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:49.080Z] No READY flag received in 3 seconds. Re-init
(anonym) @ 1576.b3c6f0a9.chunk.js:12
socket.io.js:396 WebSocket connection to 'ws://10.122.60.87:8081/?sid=1679917246068&name=admin' failed: WebSocket is closed before the connection is established.
SocketClient.close @ socket.io.js:396
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:49.080Z] Start reconnect 5
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:49.080Z] ws connection error: CLOSE_ABNORMAL
(anonym) @ 1576.b3c6f0a9.chunk.js:12
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:49.080Z] Reconnect is already running 5
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:49.081Z] Reconnect is already running 5
2261.26c121ec.chunk.js:1          Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
1576.b3c6f0a9.chunk.js:12 ChunkLoadError: Loading chunk 2261 failed.
(error: http://10.122.60.87:8081/static/js/2261.26c121ec.chunk.js)
    at n.f.j (main.a612f10d.js:3:1081)
    at main.a612f10d.js:1:1319
    at Array.reduce (<anonymous>)
    at n.e (main.a612f10d.js:1:1285)
    at 3589.fc244685.chunk.js:73:88411
    at G (9526.113dc042.chunk.js:9:3265)
    at oa (3961.36e663dd.chunk.js:16:44245)
    at ra (3961.36e663dd.chunk.js:16:39567)
    at Jc (3961.36e663dd.chunk.js:16:39498)
    at ml (3961.36e663dd.chunk.js:16:39357)
    at bs (3961.36e663dd.chunk.js:16:34501)
    at Ln (3961.36e663dd.chunk.js:24:1614)
    at MessagePort.Gn (3961.36e663dd.chunk.js:24:2007)
(anonym) @ 1576.b3c6f0a9.chunk.js:12
no-image.png:1          Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
browserError.png:1          Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:54.089Z] Try to connect
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:57.098Z] No READY flag received in 3 seconds. Re-init
(anonym) @ 1576.b3c6f0a9.chunk.js:12
socket.io.js:396 WebSocket connection to 'ws://10.122.60.87:8081/?sid=1679917254089&name=admin' failed: WebSocket is closed before the connection is established.
SocketClient.close @ socket.io.js:396
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:57.098Z] Start reconnect 5
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:57.099Z] ws connection error: CLOSE_ABNORMAL
(anonym) @ 1576.b3c6f0a9.chunk.js:12
21576.b3c6f0a9.chunk.js:12 [2023-03-27T11:40:57.099Z] Reconnect is already running 5
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:41:02.465Z] Try to connect
DevTools failed to load source map: Could not load content for chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/browser-polyfill.js.map: Systemfehler: net::ERR_FILE_NOT_FOUND
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:41:05.489Z] No READY flag received in 3 seconds. Re-init
(anonym) @ 1576.b3c6f0a9.chunk.js:12
warn @ socket.io.js:67
(anonym) @ socket.io.js:148
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
socket.io.js:396 WebSocket connection to 'ws://10.122.60.87:8081/?sid=1679917262468&name=admin' failed: WebSocket is closed before the connection is established.
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:41:05.490Z] Start reconnect 5
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:41:05.492Z] ws connection error: CLOSE_ABNORMAL
(anonym) @ 1576.b3c6f0a9.chunk.js:12
error @ socket.io.js:68
socket.onclose @ socket.io.js:177
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:41:05.493Z] Reconnect is already running 5
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:41:05.494Z] Reconnect is already running 5
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:41:10.501Z] Try to connect
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:41:13.507Z] No READY flag received in 3 seconds. Re-init
(anonym) @ 1576.b3c6f0a9.chunk.js:12
warn @ socket.io.js:67
(anonym) @ socket.io.js:148
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
socket.onerror @ socket.io.js:189
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
error (async)
SocketClient.connect @ socket.io.js:182
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
socket.io.js:396 WebSocket connection to 'ws://10.122.60.87:8081/?sid=1679917270502&name=admin' failed: WebSocket is closed before the connection is established.
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
socket.onerror @ socket.io.js:189
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
error (async)
SocketClient.connect @ socket.io.js:182
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:41:13.508Z] Start reconnect 5
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:41:13.509Z] ws connection error: CLOSE_ABNORMAL
(anonym) @ 1576.b3c6f0a9.chunk.js:12
error @ socket.io.js:68
socket.onclose @ socket.io.js:177
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
socket.onerror @ socket.io.js:189
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
error (async)
SocketClient.connect @ socket.io.js:182
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:41:13.511Z] Reconnect is already running 5
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:41:13.512Z] Reconnect is already running 5
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:41:18.522Z] Try to connect
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:41:21.575Z] No READY flag received in 3 seconds. Re-init
(anonym) @ 1576.b3c6f0a9.chunk.js:12
warn @ socket.io.js:67
(anonym) @ socket.io.js:148
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
socket.onerror @ socket.io.js:189
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
error (async)
SocketClient.connect @ socket.io.js:182
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
socket.onerror @ socket.io.js:189
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
error (async)
SocketClient.connect @ socket.io.js:182
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
socket.io.js:396 WebSocket connection to 'ws://10.122.60.87:8081/?sid=1679917278558&name=admin' failed: WebSocket is closed before the connection is established.
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
socket.onerror @ socket.io.js:189
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
error (async)
SocketClient.connect @ socket.io.js:182
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
socket.onerror @ socket.io.js:189
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
error (async)
SocketClient.connect @ socket.io.js:182
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:41:21.621Z] Start reconnect 5
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:41:21.622Z] ws connection error: CLOSE_ABNORMAL
(anonym) @ 1576.b3c6f0a9.chunk.js:12
error @ socket.io.js:68
socket.onclose @ socket.io.js:177
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
socket.onerror @ socket.io.js:189
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
error (async)
SocketClient.connect @ socket.io.js:182
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
socket.onerror @ socket.io.js:189
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
error (async)
SocketClient.connect @ socket.io.js:182
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:41:21.623Z] Reconnect is already running 5
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:41:21.624Z] Reconnect is already running 5
DevTools failed to load source map: Could not load content for http://10.122.60.87:8081/lib/js/sparkline.js.map: Verbindungsfehler: net::ERR_CONNECTION_TIMED_OUT
DevTools failed to load source map: Could not load content for http://10.122.60.87:8081/static/js/main.a612f10d.js.map: Verbindungsfehler: net::ERR_CONNECTION_TIMED_OUT
DevTools failed to load source map: Could not load content for http://10.122.60.87:8081/static/js/5233.9fc47124.chunk.js.map: Verbindungsfehler: net::ERR_CONNECTION_TIMED_OUT
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:41:26.630Z] Try to connect
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:41:29.672Z] No READY flag received in 3 seconds. Re-init
(anonym) @ 1576.b3c6f0a9.chunk.js:12
warn @ socket.io.js:67
(anonym) @ socket.io.js:148
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
socket.onerror @ socket.io.js:189
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
error (async)
SocketClient.connect @ socket.io.js:182
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
socket.onerror @ socket.io.js:189
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
error (async)
SocketClient.connect @ socket.io.js:182
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
socket.onerror @ socket.io.js:189
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
error (async)
SocketClient.connect @ socket.io.js:182
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
socket.io.js:396 WebSocket connection to 'ws://10.122.60.87:8081/?sid=1679917286663&name=admin' failed: WebSocket is closed before the connection is established.
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
socket.onerror @ socket.io.js:189
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
error (async)
SocketClient.connect @ socket.io.js:182
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
socket.onerror @ socket.io.js:189
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
error (async)
SocketClient.connect @ socket.io.js:182
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
socket.onerror @ socket.io.js:189
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
error (async)
SocketClient.connect @ socket.io.js:182
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:41:29.722Z] Start reconnect 5
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:41:29.723Z] ws connection error: CLOSE_ABNORMAL
(anonym) @ 1576.b3c6f0a9.chunk.js:12
error @ socket.io.js:68
socket.onclose @ socket.io.js:177
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
socket.onerror @ socket.io.js:189
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
error (async)
SocketClient.connect @ socket.io.js:182
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
socket.onerror @ socket.io.js:189
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
error (async)
SocketClient.connect @ socket.io.js:182
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
socket.onerror @ socket.io.js:189
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
error (async)
SocketClient.connect @ socket.io.js:182
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:41:29.726Z] Reconnect is already running 5
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:41:29.726Z] Reconnect is already running 5
DevTools failed to load source map: Could not load content for http://10.122.60.87:8081/static/js/7230.40ae870f.chunk.js.map: Verbindungsfehler: net::ERR_CONNECTION_TIMED_OUT
DevTools failed to load source map: Could not load content for http://10.122.60.87:8081/static/js/1012.3d445672.chunk.js.map: Ladevorgang wegen Zeitüberschreitung abgebrochen
DevTools failed to load source map: Could not load content for http://10.122.60.87:8081/static/js/1720.22c2a168.chunk.js.map: Ladevorgang wegen Zeitüberschreitung abgebrochen
DevTools failed to load source map: Could not load content for http://10.122.60.87:8081/static/js/9526.113dc042.chunk.js.map: Ladevorgang wegen Zeitüberschreitung abgebrochen
DevTools failed to load source map: Could not load content for http://10.122.60.87:8081/static/js/2652.9a062c3e.chunk.js.map: Ladevorgang wegen Zeitüberschreitung abgebrochen
DevTools failed to load source map: Could not load content for http://10.122.60.87:8081/static/js/9039.666cd7f2.chunk.js.map: Ladevorgang wegen Zeitüberschreitung abgebrochen
DevTools failed to load source map: Could not load content for http://10.122.60.87:8081/static/js/3961.36e663dd.chunk.js.map: Ladevorgang wegen Zeitüberschreitung abgebrochen
DevTools failed to load source map: Could not load content for http://10.122.60.87:8081/static/js/6346.0e3da766.chunk.js.map: Ladevorgang wegen Zeitüberschreitung abgebrochen
DevTools failed to load source map: Could not load content for http://10.122.60.87:8081/static/js/6537.ad8e448d.chunk.js.map: Ladevorgang wegen Zeitüberschreitung abgebrochen
DevTools failed to load source map: Could not load content for http://10.122.60.87:8081/static/js/9522.946f8bf9.chunk.js.map: Ladevorgang wegen Zeitüberschreitung abgebrochen
DevTools failed to load source map: Could not load content for http://10.122.60.87:8081/static/js/9297.86d0a7b2.chunk.js.map: Ladevorgang wegen Zeitüberschreitung abgebrochen
DevTools failed to load source map: Could not load content for http://10.122.60.87:8081/static/js/3938.e0ae78ec.chunk.js.map: Ladevorgang wegen Zeitüberschreitung abgebrochen
DevTools failed to load source map: Could not load content for http://10.122.60.87:8081/static/js/2435.d82ffe39.chunk.js.map: Ladevorgang wegen Zeitüberschreitung abgebrochen
DevTools failed to load source map: Could not load content for http://10.122.60.87:8081/static/js/2636.bad18420.chunk.js.map: Ladevorgang wegen Zeitüberschreitung abgebrochen
DevTools failed to load source map: Could not load content for http://10.122.60.87:8081/static/js/5199.d0945c98.chunk.js.map: Ladevorgang wegen Zeitüberschreitung abgebrochen
DevTools failed to load source map: Could not load content for http://10.122.60.87:8081/static/js/3755.6b785bde.chunk.js.map: Ladevorgang wegen Zeitüberschreitung abgebrochen
DevTools failed to load source map: Could not load content for http://10.122.60.87:8081/static/js/610.4ad03a50.chunk.js.map: Ladevorgang wegen Zeitüberschreitung abgebrochen
DevTools failed to load source map: Could not load content for http://10.122.60.87:8081/static/js/6090.85f9d639.chunk.js.map: Ladevorgang wegen Zeitüberschreitung abgebrochen
DevTools failed to load source map: Could not load content for http://10.122.60.87:8081/static/js/2262.c89d4fd0.chunk.js.map: Ladevorgang wegen Zeitüberschreitung abgebrochen
DevTools failed to load source map: Could not load content for http://10.122.60.87:8081/static/js/1576.b3c6f0a9.chunk.js.map: Ladevorgang wegen Zeitüberschreitung abgebrochen
DevTools failed to load source map: Could not load content for http://10.122.60.87:8081/static/js/7228.46fee55c.chunk.js.map: Ladevorgang wegen Zeitüberschreitung abgebrochen
DevTools failed to load source map: Could not load content for http://10.122.60.87:8081/static/js/3589.fc244685.chunk.js.map: Ladevorgang wegen Zeitüberschreitung abgebrochen
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:41:34.726Z] Try to connect
1576.b3c6f0a9.chunk.js:12 [2023-03-27T11:41:37.776Z] No READY flag received in 3 seconds. Re-init
(anonym) @ 1576.b3c6f0a9.chunk.js:12
warn @ socket.io.js:67
(anonym) @ socket.io.js:148
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
socket.onerror @ socket.io.js:189
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
error (async)
SocketClient.connect @ socket.io.js:182
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
socket.onerror @ socket.io.js:189
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
error (async)
SocketClient.connect @ socket.io.js:182
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
socket.onerror @ socket.io.js:189
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
error (async)
SocketClient.connect @ socket.io.js:182
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
setTimeout (async)
(anonym) @ 1576.b3c6f0a9.chunk.js:15
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
socket.onerror @ socket.io.js:189
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
zt @ 1576.b3c6f0a9.chunk.js:15
error (async)
SocketClient.connect @ socket.io.js:182
(anonym) @ socket.io.js:428
zt @ 1576.b3c6f0a9.chunk.js:15
socket.io.js:396 WebSocket connection to 'ws://10.122.60.87:8081/?sid=1679917294761&name=admin' failed: WebSocket is closed before the connection is established.
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
 [2023-03-27T11:43:39.027Z] Reconnect is already running 5
 [2023-03-27T11:43:39.028Z] Reconnect is already running 5
 [2023-03-27T11:43:44.034Z] Try to connect
```

**Comment by GermanBluefox** [comment]
Admin instant läuft nicht. Bitte über CLI starten
