### ISSUE TITLE
[Bug]: iobroker crashed

### ISSUE THREAD

**Issue by Ludwig345** [ioBroker/ioBroker.admin#1951]
### Contact Details

ottilie.faber@gmail.com

### What happened?

iobroker bleibt stehen, die Seiten adapter, objects, instances usw. werden nicht angezeigt.
Stattdessen kommt der u.a. Fehlertext.

### Link

http://192.168.178.57:8081/#tab-objects

### Relevant log output

```shell
If in the second line you will see at :3000/static/js/main.chunk.js:36903 and not the normal file name,
please try to reproduce an error with opened browser console. In this case the special "map" files will be loaded and the developers can see the real name of functions and files.
Loading chunk 7951 failed. (timeout: http://192.168.178.57:8081/static/js/7951.09ea3511.chunk.js)
ChunkLoadError: Loading chunk 7951 failed.(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))(timeout: http://192.168.178.57:8081/static/js/7951.09ea3511.chunk.js)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at n.f.j (http://192.168.178.57:8081/static/js/main.f92f1824.js:3:1067)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at http://192.168.178.57:8081/static/js/main.f92f1824.js:1:1319(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Array.reduce (<anonymous>)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at n.e (http://192.168.178.57:8081/static/js/main.f92f1824.js:1:1285)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at http://192.168.178.57:8081/static/js/5710.096bba9e.chunk.js:73:88352(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at G (http://192.168.178.57:8081/static/js/9526.113dc042.chunk.js:9:3265)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at oa (http://192.168.178.57:8081/static/js/3961.a98ff7ab.chunk.js:16:44605)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at ra (http://192.168.178.57:8081/static/js/3961.a98ff7ab.chunk.js:16:39832)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Jc (http://192.168.178.57:8081/static/js/3961.a98ff7ab.chunk.js:16:39763)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at ml (http://192.168.178.57:8081/static/js/3961.a98ff7ab.chunk.js:16:39622)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at bs (http://192.168.178.57:8081/static/js/3961.a98ff7ab.chunk.js:16:34730)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ln (http://192.168.178.57:8081/static/js/3961.a98ff7ab.chunk.js:24:1614)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at MessagePort.Gn (http://192.168.178.57:8081/static/js/3961.a98ff7ab.chunk.js:24:2007)
```

**Comment by GermanBluefox** [comment]
Unfortunately, it is not posible to reproduce the error
