### ISSUE TITLE
Alias Datenpunkte: Werte werden nicht / nur kurzzeitig angezeigt

### ISSUE THREAD

**Issue by m-s-b** [ioBroker/ioBroker.admin#1964]
Seit dem Update auf Admin 6.5.9 (js-controller 5.0.5) werden die Werte der Alias-Datenpunkte mit (null) aufgeführt.
Wird ein Wert geändert wird (null) durch den Wert ersetzt. Sobald z.B. der überliegende Ordner geschlossen und wieder geöffnet wird ist der Wert wieder (null). Gleiches Verhalten wenn vom Tab Objekte zu einem beliebigen anderen Tab und wieder zurück gewechselt wird.
Die Aliase an sich funktionieren weiterhin problemlos, d.h. Skripte die von einem Alias getriggert werden starten auch. Ebenso werden die Daten auch korrekt in die InfluxDB geschoben. (Nach Aussage von @Apollon77 [hier](https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/298) ist das daher ein Admin und kein js-controller issue.

**Expected behavior**  
Die Werte der Alias Datenpunkte sollten durchgehend (auch nach reboot) dargestellt werden. 

**Screenshots & Logfiles**  
[Screenshot im ioBroker Forum](https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/275)

**Versions:**  
 - Adapter version: 6.5.9
 - JS-Controller version: 5.0.5
 - Node version: 18.16.1
 - Operating system: bullseye (VM in Proxmox)

**Additional context**  
Ich habe mittlerweile die States von JSONL auf Redis umgestellt. Bei beiden Varianten ist das Verhalten identisch.

**Comment by m-s-b** [comment]
Kleiner Nachtrag, wenn ich mich nicht als mein Standarduser sondern als "admin" anmelde werden die Alias-Werte korrekt und nicht als "null" angezeigt. Beide Nutzer sind in der Administratorgruppe und sollten demnach die gleichen Rechte haben.

**Comment by Apollon77** [comment]
hhm ... neeeeee  Weitere User in Admin gruppe ahaben nicht gleiche rechte wie "der" admin ... am besten mal neue gruppe anlegen und den anderen user da rein

**Comment by m-s-b** [comment]
So, neue Gruppe mit allen Berechtigungen angelegt, neuen Benutzer angelegt und in die neue Gruppe aufgenommen.
Als admin abmelden, als neuer Testnutzer in Testgruppe anmelden, alle Aliase wieder bei "null".
![image](https://github.com/ioBroker/ioBroker.admin/assets/46641961/5cec3d15-7d6b-4f1f-8c9c-b7c7446c3d7c)
Selbiges wenn ich meinen Standarnutzer in die neue Gruppe packe.
Melde ich mich ab und wieder als "admin" an sieht es dann so aus:
![image](https://github.com/ioBroker/ioBroker.admin/assets/46641961/1af0ba4f-b35b-4094-9b9c-97e073f90437)
Nach erstellen der neuen Gruppe / User noch
`iob stop
iob fix
sudo reboot`

Bei den Versuchen hab ich mich nach dem reboot immer erst als admin angemeldet. Habe dann mal einen reboot gemacht und direkt als user angemeldet bzw. versucht. Das klappt nicht Fehlermeldungen kommen unten. Wenn ich mich dann über Port :8082 den web adapter aufrufe und mich (user) dort auslogge kann ich mich über :8081 wieder als admin anmelden. Wenn ich mich dann abmelde und als user anmelde komme ich wieder in den admin, allerdings ohne aliase.
Auszug aus iob logs --watch:
`2023-07-03 10:28:31.328  - info: admin.0 (552) ==> Connected system.user.bommel from ::ffff:192.168.10.57
2023-07-03 10:28:31.797  - warn: admin.0 (552) Permission error for user "system.user.bommel" on "system.adapter.admin.0.logging": setState
2023-07-03 10:28:31.798  - error: admin.0 (552) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-07-03 10:28:31.798  - error: admin.0 (552) unhandled promise rejection: permissionError
2023-07-03 10:28:31.920  - error: admin.0 (552) Error: permissionError
    at AdapterClass._checkStates (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:7931:27)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at processImmediate (node:internal/timers:447:9)
    at AdapterClass.setForeignState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:8290:24)
2023-07-03 10:28:31.920  - error: admin.0 (552) permissionError
2023-07-03 10:28:31.926  - info: admin.0 (552) terminating https server on port 8081
2023-07-03 10:28:31.927  - info: admin.0 (552) terminating
2023-07-03 10:28:31.927  - warn: admin.0 (552) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-07-03 10:28:32.428  - info: admin.0 (552) terminating
2023-07-03 10:28:32.658  - error: host.iobroker-master Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-07-03 10:28:32.660  - error: host.iobroker-master Caught by controller[0]: Error: permissionError
2023-07-03 10:28:32.660  - error: host.iobroker-master Caught by controller[0]:     at AdapterClass._checkStates (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:7931:27)
2023-07-03 10:28:32.660  - error: host.iobroker-master Caught by controller[0]:     at runNextTicks (node:internal/process/task_queues:60:5)
2023-07-03 10:28:32.660  - error: host.iobroker-master Caught by controller[0]:     at processImmediate (node:internal/timers:447:9)
2023-07-03 10:28:32.660  - error: host.iobroker-master Caught by controller[0]:     at AdapterClass.setForeignState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:8290:24)
2023-07-03 10:28:32.661  - error: host.iobroker-master instance system.adapter.admin.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-07-03 10:28:31.328  - info: admin.0 (552) ==> Connected system.user.bommel from ::ffff:192.168.10.57
2023-07-03 10:28:31.797  - warn: admin.0 (552) Permission error for user "system.user.bommel" on "system.adapter.admin.0.logging": setState
2023-07-03 10:28:31.798  - error: admin.0 (552) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-07-03 10:28:31.798  - error: admin.0 (552) unhandled promise rejection: permissionError
2023-07-03 10:28:31.920  - error: admin.0 (552) Error: permissionError
    at AdapterClass._checkStates (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:7931:27)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at processImmediate (node:internal/timers:447:9)
    at AdapterClass.setForeignState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:8290:24)
2023-07-03 10:28:31.920  - error: admin.0 (552) permissionError
2023-07-03 10:28:31.926  - info: admin.0 (552) terminating https server on port 8081
2023-07-03 10:28:31.927  - info: admin.0 (552) terminating
2023-07-03 10:28:31.927  - warn: admin.0 (552) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-07-03 10:28:32.428  - info: admin.0 (552) terminating
2023-07-03 10:28:32.658  - error: host.iobroker-master Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-07-03 10:28:32.660  - error: host.iobroker-master Caught by controller[0]: Error: permissionError
2023-07-03 10:28:32.660  - error: host.iobroker-master Caught by controller[0]:     at AdapterClass._checkStates (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:7931:27)
2023-07-03 10:28:32.660  - error: host.iobroker-master Caught by controller[0]:     at runNextTicks (node:internal/process/task_queues:60:5)
2023-07-03 10:28:32.660  - error: host.iobroker-master Caught by controller[0]:     at processImmediate (node:internal/timers:447:9)
2023-07-03 10:28:32.660  - error: host.iobroker-master Caught by controller[0]:     at AdapterClass.setForeignState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:8290:24)
2023-07-03 10:28:32.661  - error: host.iobroker-master instance system.adapter.admin.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-07-03 10:29:05.246  - info: admin.0 (2211) starting. Version 6.5.9 in /opt/iobroker/node_modules/iobroker.admin, node: v18.16.1, js-controller: 5.0.6
2023-07-03 10:29:05.308  - info: admin.0 (2211) requesting all states
2023-07-03 10:29:05.309  - info: admin.0 (2211) requesting all objects
2023-07-03 10:29:05.746  - info: admin.0 (2211) Request actual repository...
2023-07-03 10:29:05.246  - info: admin.0 (2211) starting. Version 6.5.9 in /opt/iobroker/node_modules/iobroker.admin, node: v18.16.1, js-controller: 5.0.6
2023-07-03 10:29:05.308  - info: admin.0 (2211) requesting all states
2023-07-03 10:29:05.309  - info: admin.0 (2211) requesting all objects
2023-07-03 10:29:05.746  - info: admin.0 (2211) Request actual repository...
2023-07-03 10:29:07.936  - info: admin.0 (2211) received all objects
2023-07-03 10:29:08.074  - info: admin.0 (2211) Secure socket.io server listening on port 8081
2023-07-03 10:29:08.075  - info: admin.0 (2211) https server listening on port 8081
2023-07-03 10:29:08.075  - info: admin.0 (2211) Use link "https://127.0.0.1:8081" to configure.
2023-07-03 10:29:08.389  - info: admin.0 (2211) Repository received successfully.
2023-07-03 10:29:07.936  - info: admin.0 (2211) received all objects
2023-07-03 10:29:08.074  - info: admin.0 (2211) Secure socket.io server listening on port 8081
2023-07-03 10:29:08.075  - info: admin.0 (2211) https server listening on port 8081
2023-07-03 10:29:08.075  - info: admin.0 (2211) Use link "https://127.0.0.1:8081" to configure.
2023-07-03 10:29:08.389  - info: admin.0 (2211) Repository received successfully.
2023-07-03 10:29:11.994  - info: admin.0 (2211) ==> Connected system.user.bommel from ::ffff:192.168.10.57
2023-07-03 10:29:11.994  - info: admin.0 (2211) ==> Connected system.user.bommel from ::ffff:192.168.10.57
2023-07-03 10:29:12.506  - warn: admin.0 (2211) Permission error for user "system.user.bommel" on "system.adapter.admin.0.logging": setState
2023-07-03 10:29:12.507  - error: admin.0 (2211) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-07-03 10:29:12.507  - error: admin.0 (2211) unhandled promise rejection: permissionError
2023-07-03 10:29:12.575  - error: admin.0 (2211) Error: permissionError
    at AdapterClass._checkStates (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:7931:27)
    at AdapterClass.setForeignState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:8290:24)
2023-07-03 10:29:12.575  - error: admin.0 (2211) permissionError
2023-07-03 10:29:12.581  - info: admin.0 (2211) terminating https server on port 8081
2023-07-03 10:29:12.582  - info: admin.0 (2211) terminating
2023-07-03 10:29:12.582  - warn: admin.0 (2211) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-07-03 10:29:13.083  - info: admin.0 (2211) terminating
2023-07-03 10:29:13.213  - error: host.iobroker-master Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-07-03 10:29:13.214  - error: host.iobroker-master Caught by controller[0]: Error: permissionError
2023-07-03 10:29:13.214  - error: host.iobroker-master Caught by controller[0]:     at AdapterClass._checkStates (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:7931:27)
2023-07-03 10:29:13.214  - error: host.iobroker-master Caught by controller[0]:     at AdapterClass.setForeignState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:8290:24)
2023-07-03 10:29:13.214  - error: host.iobroker-master instance system.adapter.admin.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-07-03 10:29:12.506  - warn: admin.0 (2211) Permission error for user "system.user.bommel" on "system.adapter.admin.0.logging": setState
2023-07-03 10:29:12.507  - error: admin.0 (2211) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-07-03 10:29:12.507  - error: admin.0 (2211) unhandled promise rejection: permissionError
2023-07-03 10:29:12.575  - error: admin.0 (2211) Error: permissionError
    at AdapterClass._checkStates (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:7931:27)
    at AdapterClass.setForeignState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:8290:24)
2023-07-03 10:29:12.575  - error: admin.0 (2211) permissionError
2023-07-03 10:29:12.581  - info: admin.0 (2211) terminating https server on port 8081
2023-07-03 10:29:12.582  - info: admin.0 (2211) terminating
2023-07-03 10:29:12.582  - warn: admin.0 (2211) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-07-03 10:29:13.083  - info: admin.0 (2211) terminating
2023-07-03 10:29:13.213  - error: host.iobroker-master Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-07-03 10:29:13.214  - error: host.iobroker-master Caught by controller[0]: Error: permissionError
2023-07-03 10:29:13.214  - error: host.iobroker-master Caught by controller[0]:     at AdapterClass._checkStates (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:7931:27)
2023-07-03 10:29:13.214  - error: host.iobroker-master Caught by controller[0]:     at AdapterClass.setForeignState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:8290:24)
2023-07-03 10:29:13.214  - error: host.iobroker-master instance system.adapter.admin.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-07-03 10:29:49.336  - info: admin.0 (2248) starting. Version 6.5.9 in /opt/iobroker/node_modules/iobroker.admin, node: v18.16.1, js-controller: 5.0.6
2023-07-03 10:29:49.410  - info: admin.0 (2248) requesting all states
2023-07-03 10:29:49.411  - info: admin.0 (2248) requesting all objects
2023-07-03 10:29:49.858  - info: admin.0 (2248) Request actual repository...
2023-07-03 10:29:49.336  - info: admin.0 (2248) starting. Version 6.5.9 in /opt/iobroker/node_modules/iobroker.admin, node: v18.16.1, js-controller: 5.0.6
2023-07-03 10:29:49.410  - info: admin.0 (2248) requesting all states
2023-07-03 10:29:49.411  - info: admin.0 (2248) requesting all objects
2023-07-03 10:29:49.858  - info: admin.0 (2248) Request actual repository...
2023-07-03 10:29:52.140  - info: admin.0 (2248) received all objects
2023-07-03 10:29:52.377  - info: admin.0 (2248) Secure socket.io server listening on port 8081
2023-07-03 10:29:52.379  - info: admin.0 (2248) https server listening on port 8081
2023-07-03 10:29:52.379  - info: admin.0 (2248) Use link "https://127.0.0.1:8081" to configure.
2023-07-03 10:29:52.914  - info: admin.0 (2248) Repository received successfully.
2023-07-03 10:29:52.140  - info: admin.0 (2248) received all objects
2023-07-03 10:29:52.377  - info: admin.0 (2248) Secure socket.io server listening on port 8081
2023-07-03 10:29:52.379  - info: admin.0 (2248) https server listening on port 8081
2023-07-03 10:29:52.379  - info: admin.0 (2248) Use link "https://127.0.0.1:8081" to configure.
2023-07-03 10:29:52.914  - info: admin.0 (2248) Repository received successfully.
2023-07-03 10:29:56.215  - info: admin.0 (2248) failed connection to socket.io from ::ffff:192.168.10.57: Passport was not initialized
2023-07-03 10:29:56.215  - info: admin.0 (2248) failed connection to socket.io from ::ffff:192.168.10.57: Passport was not initialized
2023-07-03 10:30:02.990  - info: admin.0 (2248) ==> Connected system.user.admin from ::ffff:192.168.10.57
2023-07-03 10:30:02.990  - info: admin.0 (2248) ==> Connected system.user.admin from ::ffff:192.168.10.57
`

**Comment by foxriver76** [comment]
> Seit dem Update auf Admin 6.5.9 (js-controller 5.0.5) werden die Werte der Alias-Datenpunkte mit (null) aufgeführt.

Heißt seit dem Update von Admin oder vom Controller, können wir es evtl. einschränken?

**Comment by m-s-b** [comment]
@foxriver76 
Nein, lässt sich leider nicht genauer einschränken. Da Skripte und Logging weiterhin funktionieren bestand keine Notwendigkeit sich die Aliase anzusehen.

**Comment by foxriver76** [comment]
I can reproduce it with controller v5 but not with controller 4.0.24 so most likely a change in controller has caused this.
