### ISSUE TITLE
/#tab-instances geht nicht

### ISSUE THREAD

**Issue by thomashde** [ioBroker/ioBroker.admin#1984]
Uncaught SyntaxError: missing ) after argument list
instrument.ts:132 ChunkLoadError: Loading chunk 8578 failed.
(missing: http://192.168.2.244:8081/static/js/8578.171b64fd.chunk.js)
    at t.f.j (jsonp chunk loading:27:18)
    at ensure chunk:6:25
    at Array.reduce (<anonymous>)
    at t.e (ensure chunk:5:56)
    at App.jsx:76:36
    at P (react.production.min.js:18:161)
    at Ei (react-dom.production.min.js:291:292)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at ss (react-dom.production.min.js:273:245)
    at Hl (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
DevTools failed to load source map: Could not load content for chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT

**Comment by mcm1957** [comment]
Please add minimum release information:

Adapter Version:
Admin Version:
js-controller Version:
Node version
Operating system and version:

**Comment by thomashde** [comment]
Adapter Version: 
Admin Version: admin 6.6.0
js-controller Version: 4.0.24
Node version: 16.20.0
Operating system and version: Debian 5.10.158-2

**Comment by foxriver76** [comment]
Isn't there any other log in the console? The shown log is unfortunately not very helpful.

**Comment by foxriver76** [comment]
If it reoccurs with 6.6.5 or above let me know
