### ISSUE TITLE
Kann keine Datenpunkte anlegen admin 6.6.4

### ISSUE THREAD

**Issue by mrjeschke** [ioBroker/ioBroker.admin#2010]
Ich habe versucht einen Datenpunkt unter 0_userdata.0 anzulegen.
Nach anklicken des hinzufügen-Buttons passiert nichts.
Fehler in der Browser-Konsole
`
helpers.ts:120 Uncaught TypeError: t.setObject is not a function
at setObject (Objects.jsx:238:58)
at R (ObjectAddNewObject.jsx:132:9)
at onApply (ObjectAddNewObject.jsx:143:24)
at onClick (CustomModal.jsx:96:32)
at Object.Re (react-dom.production.min.js:54:317)
at Be (react-dom.production.min.js:54:471)
at react-dom.production.min.js:55:35
at Ir (react-dom.production.min.js:105:68)
at Ur (react-dom.production.min.js:106:380)
at react-dom.production.min.js:117:104
at cs (react-dom.production.min.js:274:42)
at Le (react-dom.production.min.js:52:375)
at Qr (react-dom.production.min.js:109:469)
at qn (react-dom.production.min.js:74:59)
at $n (react-dom.production.min.js:73:73)
at HTMLBodyElement.o (helpers.ts:98:1)
`

**Comment by skvarel** [comment]
Hier das selbe Problem

Admin v6.6.4
js-controller: v5.0.10

**Comment by JackDaniel007** [comment]
hier das selbe
`helpers.ts:120 Uncaught TypeError: t.setObject is not a function
    at setObject (Objects.jsx:238:58)
    at R (ObjectAddNewObject.jsx:132:9)
    at onApply (ObjectAddNewObject.jsx:143:24)
    at onClick (CustomModal.jsx:96:32)
    at Object.Re (react-dom.production.min.js:54:317)
    at Be (react-dom.production.min.js:54:471)
    at react-dom.production.min.js:55:35
    at Ir (react-dom.production.min.js:105:68)
    at Ur (react-dom.production.min.js:106:380)
    at react-dom.production.min.js:117:104
    at cs (react-dom.production.min.js:274:42)
    at Le (react-dom.production.min.js:52:375)
    at Qr (react-dom.production.min.js:109:469)
    at qn (react-dom.production.min.js:74:59)
    at $n (react-dom.production.min.js:73:73)
    at HTMLBodyElement.o (helpers.ts:98:1)`

**Comment by Dreistein19** [comment]
geht schon seit 6.6.3 nicht mehr.

**Comment by bicmac** [comment]
Habe das selbe Problem im Admin Adapter 6.6.4

**Comment by Feuer-sturm** [comment]
Is duplicate to #2004

**Comment by skvarel** [comment]
> Is duplicate to #2004

Bezog sich allerdings auf 5.0.9 und ist geschlossen.

**Comment by Feuer-sturm** [comment]
@skvarel der Titel ist leider irreführend. Es wurde zuerst im Rahmen des js-controller 5.0.9 gemeldet da der Autor dachte, dass es damit zusammenhängt. Parallel kam aber auch die neue admin  version mit dem Bug. Das issue wurde dann aber von foxriver ins admin Repository verschoben. Es handelt sich im Titel also nicht um die 5.x er Admin Version  sondern es kommt vom js-controller 5.0.9

**Comment by foxriver76** [comment]
Weil Admin 6.6.5 veröffentlicht wurde und der Bug darin behoben ist. 6.6.1 ist 15 Tage alt und es gibt bereits 4 neuere Versionen (ja so ist das als Beta-Tester)

**Comment by guergen1** [comment]
Wenn es mit 6.6.5 funktionieren würde, würde ich ja nichts sagen wollen, aber admin 6.6.5 habe ich gestern installiert und da ging es leider noch nicht.

**Comment by Feuer-sturm** [comment]
@guergen1 Hinzu kommt das dieses Ticket als duplicate markiert ist und das hauptticket die #2004 ist. Wenn etwas nicht funktioniert, dann bitte in dem issue weiter machen

**Comment by foxriver76** [comment]
gerade nochmal getesetet mit 6.6.5 - funktioniert mindestens bei mir wieder. bist du sicher, dass hier 6.6.5 installiert ist?
