### ISSUE TITLE
Error in GUI! Edit instance

### ISSUE THREAD

**Issue by EarnyHerzberg** [ioBroker/ioBroker.admin#2014]
**Describe the bug**  
"Error in GUI!" pops up if i try to edit adapter instance mqtt.0

**To Reproduce**  
Admin --> Instances --> mqtt.0 edit

**Versions:**  
 - Adapter version: Admin 6.6.4
 - JS-Controller version: 5.0.10
 - Node version: <node-version> v16.20.1
 - Operating system: Ubuntu 22.04.2 LTS

bootstrap.jsx:20 iobroker.admin@6.6.4
instrument.ts:132 [2023-07-30T12:56:50.308Z] Try to connect
instrument.ts:132 Stored version: , new version: 6.6.4
instrument.ts:132 Connected: true
instrument.ts:132 [ADAPTERS] getAdapters
instrument.ts:132 [ADAPTERS] getAdaptersInfo
instrument.ts:132 [ADAPTERS] admin
instrument.ts:132 system.adapter.admin.0
instrument.ts:132 system.adapter.backitup.0
instrument.ts:132 system.adapter.discovery.0
instrument.ts:132 system.adapter.dwd.0
instrument.ts:132 system.adapter.echarts.0
instrument.ts:132 system.adapter.hm-rpc.0
instrument.ts:132 system.adapter.javascript.0
instrument.ts:132 system.adapter.mihome-cloud.0
instrument.ts:132 system.adapter.minuvis.0
instrument.ts:132 system.adapter.mqtt.0
instrument.ts:132 system.adapter.octoprint.0
instrument.ts:132 system.adapter.samsung.0
instrument.ts:132 system.adapter.shelly.0
instrument.ts:132 system.adapter.smartmeter.0
instrument.ts:132 system.adapter.sql.0
instrument.ts:132 system.adapter.web.0
instrument.ts:132 getInstances: 44
instrument.ts:132 Translate: These states will be published. (Divided by comma, e.g. 'mqtt.0.*,javascript.*')
instrument.ts:132 TypeError: Cannot read properties of undefined (reading 'length')
    at a.value (ChipInput.jsx:573:65)
    at Po (react-dom.production.min.js:204:189)
    at No (react-dom.production.min.js:203:149)
    at Ei (react-dom.production.min.js:292:172)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at us (react-dom.production.min.js:271:88)
    at as (react-dom.production.min.js:268:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
(anonym) @ instrument.ts:132
fo @ react-dom.production.min.js:189
a.componentDidCatch.t.callback @ react-dom.production.min.js:190
Ua @ react-dom.production.min.js:144
wi @ react-dom.production.min.js:261
ki @ react-dom.production.min.js:260
bi @ react-dom.production.min.js:259
(anonym) @ react-dom.production.min.js:283
Ss @ react-dom.production.min.js:281
as @ react-dom.production.min.js:270
S @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
instrument.ts:132 TypeError: Cannot read properties of undefined (reading 'length')
    at a.value (ChipInput.jsx:573:65)
    at Po (react-dom.production.min.js:204:189)
    at No (react-dom.production.min.js:203:149)
    at Ei (react-dom.production.min.js:292:172)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at us (react-dom.production.min.js:271:88)
    at as (react-dom.production.min.js:268:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
(anonym) @ instrument.ts:132
fo @ react-dom.production.min.js:189
a.componentDidCatch.t.callback @ react-dom.production.min.js:190
Ua @ react-dom.production.min.js:144
wi @ react-dom.production.min.js:261
ki @ react-dom.production.min.js:260
bi @ react-dom.production.min.js:259
(anonym) @ react-dom.production.min.js:283
Ss @ react-dom.production.min.js:281
as @ react-dom.production.min.js:270
S @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14

This line looks strange:

https://github.com/ioBroker/ioBroker.admin/blob/3c8a0896aeee07d74ab711af22a7f7dce3ae8251/src/src/components/JsonConfigComponent/ChipInput.jsx#L575

**Comment by EarnyHerzberg** [comment]
OkOk, duplicate of #2006
