### ISSUE TITLE
Error in GUI by clicking on info-button

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.admin#2017]
**Describe the bug**  
Error in GUI by clicking on info-button

```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BisDocker%2C%20isOfficial%2C%20officialVersion%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
--
  | at Ka (react-dom.production.min.js:152:60)
  | at d (react-dom.production.min.js:156:186)
  | at h (react-dom.production.min.js:158:331)
  | at e (react-dom.production.min.js:162:334)
  | at wo (react-dom.production.min.js:192:308)
  | at Ei (react-dom.production.min.js:294:9)
  | at ks (react-dom.production.min.js:280:389)
  | at ys (react-dom.production.min.js:280:320)
  | at vs (react-dom.production.min.js:280:180)
  | at us (react-dom.production.min.js:271:88)
  | at ss (react-dom.production.min.js:273:300)
  | at Hl (react-dom.production.min.js:127:105)
  | at react-dom.production.min.js:267:273
  | (anonymous) @ instrument.ts:132
  | fo @ react-dom.production.min.js:189
  | a.componentDidCatch.t.callback @ react-dom.production.min.js:190
  | Ua @ react-dom.production.min.js:144
  | wi @ react-dom.production.min.js:261
  | ki @ react-dom.production.min.js:260
  | bi @ react-dom.production.min.js:259
  | (anonymous) @ react-dom.production.min.js:283
  | Ss @ react-dom.production.min.js:281
  | ss @ react-dom.production.min.js:273
  | Hl @ react-dom.production.min.js:127
  | (anonymous) @ react-dom.production.min.js:267

```

**To Reproduce**  
![Animation](https://github.com/ioBroker/ioBroker.admin/assets/69053781/05ba30a2-7d28-4fa1-847f-23bb25a534f6)

**Expected behavior**  
no error

**Versions:**  
ioBroker.docker: v8.1.0-beta.4
Node.js: v18.17.0
NPM: v9.6.7
ioBroker.admin: v6.6.4
ioBroker.js-controller: v5.0.11

**Additional context**

**Comment by Maschler** [comment]
I have the same problem. It also happens when you go to "adapter"-> "info" (from any adapter) -> "read me".

Versions:
ioBroker.docker: v8.1.0-beta.4
Node.js: v18.17.0
NPM: v9.6.7
ioBroker.admin: v6.6.4
ioBroker.js-controller: v5.0.11

**Comment by ice987987** [comment]
at least in my installation, this issue is not yet fixed:

![Animation](https://github.com/ioBroker/ioBroker.admin/assets/69053781/72691466-87bc-4e5e-87d1-2f35bc61f1ea)

Versions:
ioBroker.docker: v8.1.0-beta.4
Node.js: v18.17.0
NPM: v9.6.7
ioBroker.admin: v6.6.5
ioBroker.js-controller: v5.0.11

```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BisDocker%2C%20isOfficial%2C%20officialVersion%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ka (react-dom.production.min.js:152:60)
    at d (react-dom.production.min.js:156:186)
    at h (react-dom.production.min.js:158:331)
    at e (react-dom.production.min.js:162:334)
    at wo (react-dom.production.min.js:192:308)
    at Ei (react-dom.production.min.js:294:9)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at us (react-dom.production.min.js:271:88)
    at as (react-dom.production.min.js:268:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
```
