### ISSUE TITLE
Uncaught TypeError: t.setObject is not a function

### ISSUE THREAD

**Issue by tobi-nmx** [ioBroker/ioBroker.admin#2024]
**Describe the bug**  
I cannot create objects (e.g. in 0_userdata) anymore, button "hinzufügen" causes an error visible in console.

**To Reproduce**  
1. go to objects tab
2. navigate to 0_userdata
3. use "+" to create a new datapoint
4. the add/hinzufügen button does not work. Javascript console shows an error

**Expected behavior**  
I want to be able to add objects again

**Screenshots & Logfiles**  
`Uncaught TypeError: t.setObject is not a function
    at setObject (Objects.jsx:238:58)
    at R (ObjectAddNewObject.jsx:132:9)
    at onApply (ObjectAddNewObject.jsx:143:24)
    at onClick (CustomModal.jsx:96:32)
    at Object.Re (react-dom.production.min.js:54:317)
    at Be (react-dom.production.min.js:54:471)
    at react-dom.production.min.js:55:35
    at Ir (react-dom.production.min.js:105:68)
    at Ur (react-dom.production.min.js:106:380)
    at react-dom.production.min.js:117:104
    at cs (react-dom.production.min.js:274:42)
    at Le (react-dom.production.min.js:52:375)
    at Qr (react-dom.production.min.js:109:469)
    at qn (react-dom.production.min.js:74:59)
    at $n (react-dom.production.min.js:73:73)
    at HTMLBodyElement.o (helpers.ts:98:1)`

**Versions:**  
 - Adapter version: 6.6.4
 - JS-Controller version: 4.0.24
 - Node version: v18.17.0
 - Operating system: docker

**Additional context**  
---

**Comment by foxriver76** [comment]
6.6.5 nutzen
