### ISSUE TITLE
Error in GUI

### ISSUE THREAD

**Issue by romew137** [ioBroker/ioBroker.admin#2033]
**Describe the bug**  
Clicking on the Info Button of the Host on the Overview Page. After this, it opens a Window with the Error Message: Error in GUI

**Expected behavior**  
See the Information of the Host.

**Screenshots & Logfiles**  
This is the Log of the Console.
instrument.ts:132 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BisDocker%2C%20isOfficial%2C%20officialVersion%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ka (react-dom.production.min.js:152:60)
    at d (react-dom.production.min.js:156:186)
    at h (react-dom.production.min.js:158:331)
    at e (react-dom.production.min.js:162:334)
    at wo (react-dom.production.min.js:192:308)
    at Ei (react-dom.production.min.js:294:9)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at us (react-dom.production.min.js:271:88)
    at ss (react-dom.production.min.js:273:300)
    at Hl (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonymous) @ instrument.ts:132

**Versions:**  
 - Adapter version: Admin<6.7.0>
 - JS-Controller version: <5.0.11> 
 - Node version: <18.17.0>
 - Operating system: <docker>

**Additional context**  
This Problem exist after updating the Admin Adapter on Version 6.7.0

**Comment by romew137** [comment]
The Operating System is Docker.
![Screenshot 2023-08-05 150355](https://github.com/ioBroker/ioBroker.admin/assets/121033241/ecda975a-1afe-40d2-980f-19f13e1b6206)

**Comment by Feuer-sturm** [comment]
Related to #2027 with s fix in 6.7.0 but it seems that the issue is stll there @foxriver76

**Comment by foxriver76** [comment]
If you go to tab hosts and than back to this tab is it working then?

**Comment by romew137** [comment]
> If you go to tab hosts and then back to this tab is it working then?

Yes. After this it is working again. Thanks
