### ISSUE TITLE
Error when try to Upload a File in the "Files" Tab 

### ISSUE THREAD

**Issue by jogibear9988** [ioBroker/ioBroker.admin#2068]
**Describe the bug**  
No File could be uploaded in Admin UI

**To Reproduce**  
1. Go to 'Files'
2. Click on 'Upload'

**Expected behavior**  
It should work to upload a File

**Screenshots & Logfiles**  
3946.e1001277.chunk.js:2 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Rs (4164.29c179b8.chunk.js:2:116947)
    at e (4164.29c179b8.chunk.js:2:61063)
    at wo (4164.29c179b8.chunk.js:2:73213)
    at Ei (4164.29c179b8.chunk.js:2:122139)
    at ks (4164.29c179b8.chunk.js:2:109418)
    at ys (4164.29c179b8.chunk.js:2:109346)
    at vs (4164.29c179b8.chunk.js:2:109209)
    at us (4164.29c179b8.chunk.js:2:105989)
    at ss (4164.29c179b8.chunk.js:2:106380)
    at Hl (4164.29c179b8.chunk.js:2:46920)
    at 4164.29c179b8.chunk.js:2:103922

**Versions:**  
 - Adapter version: current

**Comment by foxriver76** [comment]
Current means 6.9.1?

**Comment by foxriver76** [comment]
Good, because I could not reproduce :smile:
