### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by holydevil72** [ioBroker/ioBroker.admin#2089]
:8081/#tab-adapters/discovery:1  Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
bootstrap.jsx:20 iobroker.admin@6.8.0
instrument.ts:132 [2023-09-01T05:24:48.069Z] Try to connect
instrument.ts:132 Stored version: , new version: 6.8.0
instrument.ts:132 Connected: true
instrument.ts:132 [ADAPTERS] getAdapters
instrument.ts:132 [ADAPTERS] getAdaptersInfo
instrument.ts:132 [ADAPTERS] admin
instrument.ts:132  TypeError: Cannot read properties of undefined (reading '_id')
    at rn (GenereteInputsModal.jsx:284:64)
    at xu (react-dom.production.min.js:167:137)
    at Ei (react-dom.production.min.js:290:337)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at us (react-dom.production.min.js:271:88)
    at ss (react-dom.production.min.js:273:300)
    at Hl (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273

**Comment by mcm1957** [comment]
Please add versions to all issues
Admin
Js-controller
Node
O/s
