### ISSUE TITLE
Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by Tscheurgen** [ioBroker/ioBroker.admin#2093]
When opening tab objects under https://[iobroker-host]:8081/#tab-objects I receive following error.

```
instrument.ts:132  TypeError: Cannot read properties of undefined (reading 'name')
    at st (ObjectBrowser.jsx:1420:37)
    at s.value (ObjectBrowser.jsx:4338:36)
    at s.value (ObjectBrowser.jsx:4671:25)
    at ObjectBrowser.jsx:4702:45
    at Array.map (<anonymous>)
    at s.value (ObjectBrowser.jsx:4697:59)
    at s.value (ObjectBrowser.jsx:5284:28)
    at Po (react-dom.production.min.js:204:189)
    at No (react-dom.production.min.js:203:149)
    at Ei (react-dom.production.min.js:292:172)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at us (react-dom.production.min.js:271:88)
    at as (react-dom.production.min.js:268:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)

```
Details can be seen on screenshot:

![image](https://github.com/ioBroker/ioBroker.admin/assets/94912591/8556c033-ab85-479c-bc7d-18fae3bf703e)
I'm going to update all my adapters first

**Comment by Tscheurgen** [comment]
I've updated to latest beta (Admin 6.9.2), without any improvement.
How can I get the specific object or adapter where the error occurs?

**Comment by foxriver76** [comment]
Unfortunately I do not know to which version you error belongs and you haven't posted the error of version 6.9.2, we have 65 occurrences where a property of name `name` is accessed in this file.

**Comment by Tscheurgen** [comment]
I'm very sorry for my incompetent request and incomplete information. I was a bit of nervous.
indeed the line changed on version 6.9.2 to 139 in instruments.ts

see here the error output and screenshot
![image](https://github.com/ioBroker/ioBroker.admin/assets/94912591/d509b268-17b7-4456-9e0c-f83bbebcc2f7)

`instrument.ts:139  TypeError: Cannot read properties of undefined (reading 'name')
    at at (ObjectBrowser.jsx:1493:37)
    at s.value (ObjectBrowser.jsx:5028:36)
    at s.value (ObjectBrowser.jsx:5567:25)
    at ObjectBrowser.jsx:5608:53
    at Array.map (<anonymous>)
    at s.value (ObjectBrowser.jsx:5603:39)
    at s.value (ObjectBrowser.jsx:6689:28)
    at Po (react-dom.production.min.js:204:189)
    at No (react-dom.production.min.js:203:149)
    at Ei (react-dom.production.min.js:292:172)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at us (react-dom.production.min.js:271:88)
    at as (react-dom.production.min.js:268:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)`

I'm assuming there is an orphaned or misconfigured object in one of the adapters. Is there any log browserfunction a can use to geht a list of objects or to step into the code? I tried setting a breakpoint, without success for now.
Thank you very much!

**Comment by Tscheurgen** [comment]
I'm sorry for writing to this closed issue, but I didn't find any hint in which version this fix will be included. I've updated to 6.10.1 but still facing it. Thank you very much!

**Comment by Apollon77** [comment]
@Tscheurgen if it still happens in the current admin version please open a new issue and post the current error you get
