### ISSUE TITLE
Restart loop detected because of invalid ID pattern?

### ISSUE THREAD

**Issue by Rookiestyle** [ioBroker/ioBroker.admin#2105]
Not sure whether this is the correct place or whether I should post this in the viessmanapi adapter.

Adapter versions used:
admin 6.10.0
viessmannapi 2.1.1

When I expand the object tree for viessmann.0, I can see following error messages for admin.0 in the log
```
The pattern "viessmannapi.0.xxxxxxx.gateways01.devices01.roles.capability:monetization;DhwSavingsCalculator" is not a valid ID pattern
ReplyError: Error The pattern "viessmannapi.0.xxxxxxx.gateways01.devices01.roles.capability:monetization;DhwSavingsCalculator" is not a valid ID pattern at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12) at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
unhandled promise rejection: Error The pattern "viessmannapi.0.xxxxxxx.gateways01.devices01.roles.capability:monetization;DhwSavingsCalculator" is not a valid ID pattern
Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
Invalid pattern on subscribe: The pattern "viessmannapi.0.xxxxxxx.gateways01.devices01.roles.type:product;Vitodens_200" is not a valid ID Invalid pattern on subscribe: The pattern "viessmannapi.0.xxxxxxx.gateways01.devices01.roles.capability:monetization;AdvancedReport" is not a valid ID pattern
Invalid pattern on subscribe: The pattern "viessmannapi.0.xxxxxxx.gateways01.devices01.roles.capability:backup;0002_HMU_VD2" is not a valid ID pattern
```
I guess it's because `,` and/or *:* or invalid, anyhow the uncatched exception in the promise should be catched

Everytime this happens, I have no other choice but must restart iobroker.
After restart, I'm *greeted* by an adapter warning because of repeated crashes of admin
![image](https://github.com/ioBroker/ioBroker.admin/assets/36454520/416dc34e-1a56-49b6-ac54-3594aeee0926)

If this shoukd be posted in viessmannapi, let me know

**Comment by foxriver76** [comment]
please check with admin 6.10.1, should no longer crash hopefully

**Comment by Rookiestyle** [comment]
6.10.1 works, thanks
