### ISSUE TITLE
Cannot store jsonconfig UI with empty table

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#2124]
Admin 6.9.0 and newer incl. 6.10.2
js-controller 5.0.12
niode 18.16.1

Browser Chrome Version 117.0.5938.92

Problem occures with adapter snmp. This adapter has a jsonConfig with 3 Tabs. On every tab there is a table. As long as any table is empty (= no row has been added) saving is not possible. The save and save+close buttons get active and are clickable, but nothing happens.

Detail step to reproduce:
Create a new instance (impottant- a NEW instance ist required, see below)

- at first tab (OID) add a line and fill in some dummy data
- save button should get active
- clicking save button does nothing (console logs an exception see below)

- now create a line at second tab (devices)
- still no savong is possible

- now open third tabe (authorization)
- create a tablerow, no data is required to be filled
- saving should work now

To make the problem more complex you now may delete the row on the third tab. Saving should still be possible.

The problem can only be reproduced again if using an new untouches instance.

----------

Console logs the following error:
```
JsonConfig.jsx:415 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at n.value (JsonConfig.jsx:415:43)
    at n.value (JsonConfig.jsx:428:30)
    at n.value (JsonConfig.jsx:426:30)
    at n.<anonymous> (JsonConfig.jsx:477:18)
    at d (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:128:22)
    at Generator.next (regeneratorRuntime.js:69:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:22:9)
value @ JsonConfig.jsx:415
value @ JsonConfig.jsx:428
value @ JsonConfig.jsx:426
(anonymous) @ JsonConfig.jsx:477
d @ regeneratorRuntime.js:44
(anonymous) @ regeneratorRuntime.js:128
(anonymous) @ regeneratorRuntime.js:69
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:22
Promise.then (async)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
(anonymous) @ JsonConfig.jsx:518
onSave @ JsonConfig.jsx:576
onClick @ SaveCloseButtons.js:84
Re @ react-dom.production.min.js:54
Be @ react-dom.production.min.js:54
(anonymous) @ react-dom.production.min.js:55
Ir @ react-dom.production.min.js:105
Ur @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
cs @ react-dom.production.min.js:274
Le @ react-dom.production.min.js:52
Qr @ react-dom.production.min.js:109
qn @ react-dom.production.min.js:74
$n @ react-dom.production.min.js:73
o @ helpers.ts:98
```

Please feel free to contact me if further information is needed.

**Comment by mcm1957** [comment]
Additional info:
Maybe the tables should be initialized as empty table within io-package.json. This is not the case now. But this should not cause this behaviour especially as it worked up to 6.8.3.
