### ISSUE TITLE
Error in GUI

### ISSUE THREAD

**Issue by UrsKobler** [ioBroker/ioBroker.admin#2142]
**Describe the bug**  
After starting Admin the GUI error appeared.

**To Reproduce**  
After restarting Admin, the GUI error could no longer be reproduced.

**Screenshots & Logfiles**  
```
iobroker.admin@6.10.1
5966.a0d97006.chunk.js:2 [2023-10-08T08:43:09.197Z] Try to connect
5966.a0d97006.chunk.js:2 Stored version: , new version: 6.10.1
5966.a0d97006.chunk.js:2 Connected: true
user1.24fa2b07.svg:1     Failed to load resource: the server responded with a status of 404 (Not Found)
5966.a0d97006.chunk.js:2 Translate: Link
5966.a0d97006.chunk.js:2 Translate: time
5966.a0d97006.chunk.js:2 Translate: timeOffset
5966.a0d97006.chunk.js:2 Translate: _npmNewestNext
5966.a0d97006.chunk.js:2 Translate: _nodeNewestNext
5966.a0d97006.chunk.js:2 Translate: _npmCurrent
5966.a0d97006.chunk.js:2 Translate: _npmNewest
5966.a0d97006.chunk.js:2 Translate: _nodeCurrent
5966.a0d97006.chunk.js:2 Translate: _nodeNewest
 iobroker.javascript@7.1.4 using theme "colored"
 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
 Help us to create open source project with reactJS!
 See you :)
 [2023-10-08T08:44:51.270Z] Try to connect
sentry.iobroker.net/api/56/envelope/?sentry_key=504499a725eb4898930d3b9e9da95740&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.62.0:1     Failed to load resource: the server responded with a status of 403 ()
 Detected custom blockly: awtrix-light
 Detected custom blockly: sayit
 Detected custom blockly: email
 Detected custom blockly: telegram
 Detected custom blockly: iot
 Detected custom blockly: whatsapp-cmb
:8081/adapter/whatsapp-cmb/blockly.js:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/adapter/iot/blockly.js:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/adapter/sayit/blockly.js:1     Failed to load resource: the server responded with a status of 404 (Not Found)
 Translate: AI code generator
 Init editor
 Translation for word "Sends message via telegram" in "de" was ignored: existing = "Sendet eine Nachricht per telegram", new = Sendet Nachricht per Telegramm
(anonym) @ :8081/adapter/javasc…cfbef968.chunk.js:2
 Translation for word "You can use %s in the text to display current trigger value or %id to display the triggered object ID" in "de" was ignored: existing = "Sie können %s im Text verwenden, um den aktuellen Triggerwert anzuzeigen, %id, um die ausgelöste Objekt-ID zu verwenden, %name, um den ID-Namen des ausgelösten Objekts anzuzeigen, oder %old, um den alten Triggerwert zu verwenden", new = Sie können %s im Text verwenden, um den aktuellen Triggerwert anzuzeigen, oder %id, um die ID des ausgelösten Objekts anzuzeigen
(anonym) @ :8081/adapter/javasc…cfbef968.chunk.js:2
:8081/#tab-javascript:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
 crbug/1173575, non-JS module files deprecated.
(anonym) @ chrome-error://chromewebdata/:6583
:8081/adapter/admin/admin.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/adapter/hm-rega/homematic.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/adapter/scenes/scenes.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/adapter/tr-064/tr-064.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
5966.a0d97006.chunk.js:2 [ADAPTERS] getAdapters
5966.a0d97006.chunk.js:2 [ADAPTERS] getAdaptersInfo
:8081/adapter/admin/admin.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
sentry.e732e10c5c1ceed0955b2fec6dab33f8.svg:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/adapter/awtrix-light/awtrix-light.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/adapter/influxdb/influxdb.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/adapter/simple-api/simple-api.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/adapter/feiertage/feiertage.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/adapter/fritzdect/fritzdect_logo.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/adapter/fronius/fronius.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/adapter/devices/devices.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/adapter/discovery/discovery.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/adapter/hm-rega/homematic.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/adapter/hm-rpc/homematic.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/adapter/icons-mfd-png/icons-mfd-png.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/adapter/mqtt/mqtt.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/adapter/swiss-weather-api/swiss-weather-api.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/adapter/rpi2/rpi.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/adapter/luftdaten/luftdaten.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/adapter/info/info.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/adapter/socketio/socketio.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/adapter/sonos/sonos.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/adapter/spotify-premium/spotify-premium.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/adapter/scenes/scenes.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/adapter/telegram/telegram.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/adapter/tr-064/tr-064.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
github.com/iobroker-community-adapters/ioBroker.fakeroku/master/admin/fakeroku.png:1     Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.vis-players/master/admin/players.png:1     Failed to load resource: the server responded with a status of 404 ()
:8081/adapter/ws/ws.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/adapter/web/web.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/static/js/2887.4368cb86.chunk.js:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/static/js/9164.3f61792a.chunk.js:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/static/js/1801.019e34c0.chunk.js:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/static/js/2688.c287fe3c.chunk.js:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
:8081/static/js/4280.8a72801f.chunk.js:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
5966.a0d97006.chunk.js:2 ChunkLoadError: Loading chunk 2887 failed.
(error: https://10.0.0.13:8081/static/js/2887.4368cb86.chunk.js)
    at t.f.j (main.bd750574.js:1:13524)
    at main.bd750574.js:1:1285
    at Array.reduce (<anonymous>)
    at t.e (main.bd750574.js:1:1250)
    at 4207.a0534e65.chunk.js:2:243104
    at P (2791.8afe157f.chunk.js:2:3351)
    at Ei (4164.29c179b8.chunk.js:2:120786)
    at ks (4164.29c179b8.chunk.js:2:109418)
    at ys (4164.29c179b8.chunk.js:2:109346)
    at vs (4164.29c179b8.chunk.js:2:109209)
    at ss (4164.29c179b8.chunk.js:2:106325)
    at Hl (4164.29c179b8.chunk.js:2:46920)
    at 4164.29c179b8.chunk.js:2:103922
(anonym) @ 5966.a0d97006.chunk.js:2
browserError.png:1     Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
```

**Versions:**  
 - Adapter version: <adapter-version> 2.2.4 (arm64)
 - JS-Controller version: <js-controller-version>  5.0.12
 - Node version: <node-version>  v18.18.0
 - Operating system: <os-name> linux arm64

**Comment by GermanBluefox** [comment]
Hm... https://kinsta.com/knowledgebase/neterr-cert-authority-invalid/

**Comment by UrsKobler** [comment]
Thank you for the informative Kinsta article.

I do not use an SSL certificate on my local network because I am the only authorized user of my smart home system.

When I access my smart home system externally, I do this with a VPN connection.

I was not aware that this intermittent problem could be due to a bad SSL certificate in the browser cache.

Thank you for your support.

Best regards
Kobi
