### ISSUE TITLE
admin 6.10.3 manuelle Alias erstellung erzeugt absturz

### ISSUE THREAD

**Issue by NinjaTurtle85** [ioBroker/ioBroker.admin#2146]
Nach dem Update auf 6.10.3 konnte ich keine Alias-Objekte unter Objekte manuel erstellen. Der Admin Adapter stürtz sofort ab.

**Comment by foxriver76** [comment]
Mit 6.10.5 auch? Falls ja, bitte Log posten. Ich kann es leider nicht nachstellen.

**Comment by m-s-b** [comment]
Ich hab das gleiche Problem mit 6.10.5 auch noch, siehe hier:
https://forum.iobroker.net/topic/69012/alias-erstellen-killt-admin-instanz?_=1697021717354
Log von erstellen bis Absturz
`2023-10-11 10:03:43.710  - warn: influxdb.0 (6080) Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:43.710  - warn: scenes.0 (6140) Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:43.712  - warn: influxdb.0 (6080) Could not add alias subscription: Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:43.713  - warn: scenes.0 (6140) Could not add alias subscription: Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:43.710  - warn: influxdb.1 (6095) Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:43.712  - warn: influxdb.1 (6095) Could not add alias subscription: Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:43.710  - warn: javascript.0 (6110) Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:43.716  - warn: history.0 (6200) Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:43.716  - warn: javascript.0 (6110) Could not add alias subscription: Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:43.716  - warn: admin.3 (7224) Alias alias.0.Gewerke.Licht.Joel.test has no target 8
2023-10-11 10:03:43.718  - warn: history.0 (6200) Could not add alias subscription: Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:43.727  - warn: javascript.0 (6110) Alias alias.0.Gewerke.Licht.Joel.test has no target 8
2023-10-11 10:03:43.710  - warn: influxdb.0 (6080) Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:43.710  - warn: scenes.0 (6140) Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:43.712  - warn: influxdb.0 (6080) Could not add alias subscription: Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:43.713  - warn: scenes.0 (6140) Could not add alias subscription: Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:43.710  - warn: influxdb.1 (6095) Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:43.712  - warn: influxdb.1 (6095) Could not add alias subscription: Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:43.710  - warn: javascript.0 (6110) Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:43.716  - warn: history.0 (6200) Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:43.716  - warn: javascript.0 (6110) Could not add alias subscription: Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:43.716  - warn: admin.3 (7224) Alias alias.0.Gewerke.Licht.Joel.test has no target 8
2023-10-11 10:03:43.718  - warn: history.0 (6200) Could not add alias subscription: Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:43.727  - warn: javascript.0 (6110) Alias alias.0.Gewerke.Licht.Joel.test has no target 8
2023-10-11 10:03:44.512  - warn: admin.3 (7224) Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:44.513  - error: admin.3 (7224) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-10-11 10:03:44.513  - error: admin.3 (7224) unhandled promise rejection: Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:44.601  - error: admin.3 (7224) Error: Alias alias.0.Gewerke.Licht.Joel.test has no target 12
    at Admin._addAliasSubscribe (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:9523:59)
    at Admin._subscribeForeignStates (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:9783:32)
2023-10-11 10:03:44.602  - error: admin.3 (7224) Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:44.612  - warn: admin.3 (7224) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-10-11 10:03:44.512  - warn: admin.3 (7224) Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:44.513  - error: admin.3 (7224) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-10-11 10:03:44.513  - error: admin.3 (7224) unhandled promise rejection: Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:44.601  - error: admin.3 (7224) Error: Alias alias.0.Gewerke.Licht.Joel.test has no target 12
    at Admin._addAliasSubscribe (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:9523:59)
    at Admin._subscribeForeignStates (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:9783:32)
2023-10-11 10:03:44.602  - error: admin.3 (7224) Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:44.612  - warn: admin.3 (7224) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-10-11 10:03:45.285  - error: host.iobroker-master Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-10-11 10:03:45.287  - error: host.iobroker-master Caught by controller[0]: Error: Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:45.288  - error: host.iobroker-master Caught by controller[0]:     at Admin._addAliasSubscribe (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:9523:59)
2023-10-11 10:03:45.288  - error: host.iobroker-master Caught by controller[0]:     at Admin._subscribeForeignStates (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:9783:32)
2023-10-11 10:03:45.288  - error: host.iobroker-master instance system.adapter.admin.3 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-10-11 10:03:45.285  - error: host.iobroker-master Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-10-11 10:03:45.287  - error: host.iobroker-master Caught by controller[0]: Error: Alias alias.0.Gewerke.Licht.Joel.test has no target 12
2023-10-11 10:03:45.288  - error: host.iobroker-master Caught by controller[0]:     at Admin._addAliasSubscribe (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:9523:59)
2023-10-11 10:03:45.288  - error: host.iobroker-master Caught by controller[0]:     at Admin._subscribeForeignStates (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:9783:32)
2023-10-11 10:03:45.288  - error: host.iobroker-master instance system.adapter.admin.3 terminated with code 6 (UNCAUGHT_EXCEPTION)`

**Comment by m-s-b** [comment]
Mit 6.10.7 leider noch nicht komplett gefixed. Alias anlegen geht. Bearbeitungsmodus neuer Alias (Stift) geht auch wieder.
Quelldatenpunkt manuell eintragen funktioniert auch. Quelldatenpunkt über den Objektbrowser (3 Punkte im Tab Alias) führt zum Browserabsturz.
`instrument.ts:144 TypeError: F.default.isStringInteger is not a function
    at t.data.state.state (ObjectBrowser.js:1571:23)
    at n.value (ObjectBrowser.js:4483:31)
    at n.value (ObjectBrowser.js:5626:23)
    at n.value (ObjectBrowser.js:5648:25)
    at ObjectBrowser.js:5705:53
    at Array.map (<anonymous>)
    at n.value (ObjectBrowser.js:5700:39)
    at ObjectBrowser.js:5689:53
    at Array.map (<anonymous>)
    at n.value (ObjectBrowser.js:5684:39)
    at ObjectBrowser.js:5689:53
    at Array.map (<anonymous>)
    at n.value (ObjectBrowser.js:5684:39)
    at ObjectBrowser.js:5689:53
    at Array.map (<anonymous>)
    at n.value (ObjectBrowser.js:5684:39)
    at ObjectBrowser.js:5689:53
    at Array.map (<anonymous>)
    at n.value (ObjectBrowser.js:5684:39)
    at n.value (ObjectBrowser.js:6767:28)
    at Po (react-dom.production.min.js:204:189)
    at No (react-dom.production.min.js:203:149)
    at Ei (react-dom.production.min.js:292:172)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at us (react-dom.production.min.js:271:88)
    at as (react-dom.production.min.js:268:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)`
