### ISSUE TITLE
Fehler in GUI

### ISSUE THREAD

**Issue by Biker1789** [ioBroker/ioBroker.admin#2154]
Hallo zusammen,

keine leider im ioborcker keine Shelly in die Instanzen hinzufügen bekomme immer diese Fehlermeldung.

Vielleicht gibt's es ja Fehler Behebung

VM29:359 Edge Translation started
bootstrap.jsx:20 iobroker.admin@6.10.1
instrument.ts:144 [2023-10-14T17:56:22.376Z] Try to connect
instrument.ts:144 Stored version: , new version: 6.10.1
instrument.ts:144 Connected: true
instrument.ts:144 system.adapter.admin.0
instrument.ts:144 system.adapter.backitup.0
instrument.ts:144 system.adapter.discovery.0
instrument.ts:144 system.adapter.shelly.0
instrument.ts:144 getInstances: 6
 [2023-10-14T17:56:23.087Z] Try to connect
 "comma": {"en": "comma", "de": "comma", "ru": "comma", "pt": "comma", "nl": "comma", "fr": "comma", "es": "comma", "pl": "comma", "it": "comma", "zh-cn": "comma"},
 "point": {"en": "point", "de": "point", "ru": "point", "pt": "point", "nl": "point", "fr": "point", "es": "point", "pl": "point", "it": "point", "zh-cn": "point"},
instrument.ts:144 Translate: Link
instrument.ts:144 Translate: time
instrument.ts:144 Translate: timeOffset
instrument.ts:144 Translate: _nodeCurrent
instrument.ts:144 Translate: _nodeNewest
instrument.ts:144 Translate: _nodeNewestNext
instrument.ts:144 Translate: _npmCurrent
instrument.ts:144 Translate: _npmNewest
instrument.ts:144 Translate: _npmNewestNext
instrument.ts:144 [ADAPTERS] getAdapters
instrument.ts:144 [ADAPTERS] getAdaptersInfo
github.com/iobroker-community-adapters/ioBroker.fakeroku/master/admin/fakeroku.png:1 
        
        
        Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.vis-players/master/admin/players.png:1 
        
        
        Failed to load resource: the server responded with a status of 404 ()
instrument.ts:144 Execute: add shelly --host OlafMSI 
instrument.ts:144 STARTED: add shelly --host OlafMSI 
22instrument.ts:144 cmdStdout
instrument.ts:144 cmdExit
instrument.ts:144 24778305
instrument.ts:144 0
instrument.ts:144 system.adapter.admin.0
instrument.ts:144 system.adapter.backitup.0
instrument.ts:144 system.adapter.discovery.0
instrument.ts:144 system.adapter.shelly.0
instrument.ts:144 system.adapter.shelly.1
instrument.ts:144 getInstances: 7
instrument.ts:144  DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at ci (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:95082)
    at ci (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:95155)
    at yi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:100254)
    at vi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:97116)
    at gi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:96995)
    at vi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:97305)
    at gi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:96995)
    at vi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:97108)
    at gi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:96995)
    at vi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:97108)
    at gi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:96995)
    at vi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:97305)
    at gi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:96995)
    at vi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:97108)
    at gi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:96995)
    at vi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:97108)
    at gi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:96995)
    at vi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:97305)
    at gi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:96995)
    at vi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:97108)
    at gi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:96995)
    at vi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:97108)
    at gi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:96995)
    at vi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:97108)
    at gi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:96995)
    at vi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:97108)
    at gi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:96995)
    at vi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:97305)
    at gi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:96995)
    at vi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:97108)
    at gi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:96995)
    at vi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:97108)
    at gi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:96995)
    at vi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:97243)
    at gi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:96995)
    at vi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:97108)
    at gi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:96995)
    at vi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:97305)
    at gi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:96995)
    at vi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:97108)
    at gi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:96995)
    at vi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:97108)
    at gi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:96995)
    at vi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:97243)
    at gi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:96995)
    at vi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:97108)
    at gi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:96995)
    at vi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:97108)
    at gi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:96995)
    at vi (http://localhost:8081/static/js/4164.29c179b8.chunk.js:2:98693)
(anonymous) @ instrument.ts:144

**Comment by mcm1957** [comment]
VM29:359 Edge Translation started

Kann es sein dass du wonexautomatische Übersetzung aktiv hast? Schalt diemal aus

A sonste gib bitte versionen an
Admin
Js- controller
Node
O/S

**Comment by Biker1789** [comment]
Danke, 
a das war es könnte die Instanz jetzt Installieren.
