### ISSUE TITLE
Hosts Menu is not being displayed

### ISSUE THREAD

**Issue by Paragon46** [ioBroker/ioBroker.admin#2169]
After clicking on the hosts menu, the following eeror message appears.

iobroker.admin@6.3.5
sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.28.0:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
instrument.ts:124 [2023-10-22T13:19:55.196Z] Try to connect
instrument.ts:124 Stored version: , new version: 6.3.5
instrument.ts:124 Connected: true
instrument.ts:124 Translate: Link
instrument.ts:124 Translate: time
instrument.ts:124 Translate: timeOffset
instrument.ts:124 Translate: dockerInformation
instrument.ts:124 Translate: _nodeCurrent
instrument.ts:124 Translate: _nodeNewest
instrument.ts:124 Translate: _nodeNewestNext
instrument.ts:124 Translate: _npmCurrent
instrument.ts:124 Translate: _npmNewest
instrument.ts:124 Translate: _npmNewestNext
sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.28.0:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
instrument.ts:124 Translate: nonExistingFileErrors
instrument.ts:124 [ADAPTERS] getAdapters
sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.28.0:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.28.0:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
instrument.ts:124 [ADAPTERS] getAdaptersInfo
instrument.ts:124 [ADAPTERS] admin
sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.28.0:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.28.0:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
instrument.ts:124 Translate: You cannot delete host, when it is alive
instrument.ts:124 Translate: Copy
instrument.ts:124 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BisDocker%2C%20isOfficial%2C%20officialVersion%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Zr (react-dom.production.min.js:152:60)
    at h (react-dom.production.min.js:156:186)
    at S (react-dom.production.min.js:158:331)
    at Q (react-dom.production.min.js:162:334)
    at ae (react-dom.production.min.js:192:308)
    at oa (react-dom.production.min.js:294:9)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
(anonymous) @ instrument.ts:124
client.ts:138 
        
        
       POST https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.28.0 net::ERR_BLOCKED_BY_CLIENT

**Comment by Feuer-sturm** [comment]
@Paragon46 Please update admin to current stable version 6.10.1 and check if the issue is still there.

**Comment by foxriver76** [comment]
This is fixed in stable

**Comment by Paragon46** [comment]
The Menu is now displayed again.
Thank you.
