### ISSUE TITLE
/#tab-hosts GUI Error

### ISSUE THREAD

**Issue by MedizinPumPer** [ioBroker/ioBroker.admin#2171]
Error on Open /#tab-hosts

error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BisDocker%2C%20isOfficial%2C%20officialVersion%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Zr (react-dom.production.min.js:152:60)
    at h (react-dom.production.min.js:156:186)
    at S (react-dom.production.min.js:158:331)
    at Q (react-dom.production.min.js:162:334)
    at ae (react-dom.production.min.js:192:308)
    at oa (react-dom.production.min.js:294:9)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
(anonymous) @ instrument.ts:124
:7234/#tab-hosts:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

**Comment by foxriver76** [comment]
Admin version?

**Comment by foxriver76** [comment]
This should pretty sure be fixed in current stable (6.10.1)
