### ISSUE TITLE
TypeError: Load failed when updating admin adapter

### ISSUE THREAD

**Issue by marvingrieger** [ioBroker/ioBroker.admin#2180]
**Describe the bug**  
When updating the admin-adapter from v6.8.0 to v6.12.0, an error is displayed within the update window stating _TypeError: Load failed_. Thereafter, the web interface is not accessible anymore.

**To Reproduce**  
1. Go to page 'Adapter'
2. Click on 'Update' in the admin adapter row. The update window opens
3. Wait.
4. See error in the update window.

**Expected behavior**  
The admin adapter is updated to v6.12.0 and the web interface is accessible afterward.

**Screenshots & Logfiles** 
<img width="1193" alt="Bildschirmfoto 2023-10-28 um 09 25 22" src="https://github.com/ioBroker/ioBroker.admin/assets/1997765/a6d29422-f3ca-40a1-b212-db0fb7fbf3e1">

I searched the log files but did not see anything directly related to this issue. 

**Versions:**  
 - Adapter version: v6.8.0
 - JS-Controller version: 5.0.12
 - Node version: v16.20.2
 - Operating system: Ubuntu 22.04.3 LTS

**Additional context**  

- The error also occurred when updating to v6.10.x.
- After clicking the update button and it failed, I switched to the console. When checking the installed packages, I noticed that it was still on v6.8.0. Thereafter, I triggered the upgrade via the console (by _iobroker upgrade admin_). Then, it showed v6.12.0 as installed. However, the web interface was still not accessible anymore.

**Comment by abcklaus** [comment]
I am facing the same issue. In the logs I see the following:

`================================== > LOG REDIRECT system.adapter.admin.0 => false [system.adapter.admin.0.logging]
Uncaught Rejection: Error: error:0480006C:PEM routines::no start line
    at node:internal/tls/secure-context:70:13
    at Array.forEach (<anonymous>)
    at setCerts (node:internal/tls/secure-context:68:3)
    at configSecureContext (node:internal/tls/secure-context:157:5)
    at Object.createSecureContext (node:_tls_common:117:3)
    at Server.setSecureContext (node:_tls_wrap:1412:27)
    at Server (node:_tls_wrap:1276:8)
    at new Server (node:https:74:3)
    at Object.createServer (node:https:112:10)
    at AdapterUpgradeManager.startSecureWebServer (/opt/iobroker/node_modules/iobroker.js-controller/src/lib/adapterUpgradeManager.ts:309:29)
error:0480006C:PEM routines::no start line
Error: error:0480006C:PEM routines::no start line
    at node:internal/tls/secure-context:70:13
    at Array.forEach (<anonymous>)
    at setCerts (node:internal/tls/secure-context:68:3)
    at configSecureContext (node:internal/tls/secure-context:157:5)
    at Object.createSecureContext (node:_tls_common:117:3)
    at Server.setSecureContext (node:_tls_wrap:1412:27)
    at Server (node:_tls_wrap:1276:8)
    at new Server (node:https:74:3)
    at Object.createServer (node:https:112:10)
    at AdapterUpgradeManager.startSecureWebServer (/opt/iobroker/node_modules/iobroker.js-controller/src/lib/adapterUpgradeManager.ts:309:29)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: error:0480006C:PEM routines::no start line
    at node:internal/tls/secure-context:70:13
    at Array.forEach (<anonymous>)
    at setCerts (node:internal/tls/secure-context:68:3)
    at configSecureContext (node:internal/tls/secure-context:157:5)
    at Object.createSecureContext (node:_tls_common:117:3)
    at Server.setSecureContext (node:_tls_wrap:1412:27)
    at Server (node:_tls_wrap:1276:8)
    at new Server (node:https:74:3)
    at Object.createServer (node:https:112:10)
    at AdapterUpgradeManager.startSecureWebServer (/opt/iobroker/node_modules/iobroker.js-controller/src/lib/adapterUpgradeManager.ts:309:29)
================================== > LOG REDIRECT system.adapter.javascript.0 => false [Process stopped]`

**Comment by Feuer-sturm** [comment]
@marvingrieger @abcklaus is this issue still relevant with admin7 updates? perhaps you can retest with current beta admin version.
