### ISSUE TITLE
[bug]: IoBroker Parser GUI error after update of adapter

### ISSUE THREAD

**Issue by fimoknete** [ioBroker/ioBroker.admin#2228]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Parser GUI doesnt start at all in IoBroker. Just produces GUI error after update of adapter. all other adapter are working.

![image](https://github.com/ioBroker/ioBroker.admin/assets/151381355/2079a640-7afc-4524-b693-724913c789aa)

![image](https://github.com/ioBroker/ioBroker.admin/assets/151381355/e36ab404-dc93-48d0-87d0-8e94242219a7)

### To Reproduce

start parser adapter

### Expected behavior

should start

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.admin/assets/151381355/021de291-1a92-42d2-ba84-00b34b6dbc20)

### Adapter version

parser version 2.0.7

### js-controller version

?

### Node version

?

### Operating system

windows 11

**Comment by oiramgh** [comment]
bei mir leider das gleiche Problem.
[...hatte gestern einige Adapter-Updates gemacht...]

bootstrap.jsx:19 iobroker.admin@6.3.5
instrument.ts:124 [2023-11-20T12:06:32.444Z] Try to connect
instrument.ts:124 Stored version: , new version: 6.3.5
instrument.ts:124 Connected: true
instrument.ts:124 system.adapter.admin.0
instrument.ts:124 system.adapter.backitup.0
instrument.ts:124 system.adapter.daswetter.0
instrument.ts:124 system.adapter.dwd.0
instrument.ts:124 system.adapter.flot.0
instrument.ts:124 system.adapter.heizoel.0
instrument.ts:124 system.adapter.history.0
instrument.ts:124 system.adapter.info.0
instrument.ts:124 system.adapter.javascript.0
instrument.ts:124 system.adapter.modbus.0
instrument.ts:124 system.adapter.parser.0
instrument.ts:124 system.adapter.ping.0
instrument.ts:124 system.adapter.rpi2.0
instrument.ts:124 system.adapter.sonoff.0
instrument.ts:124 system.adapter.tankerkoenig.0
instrument.ts:124 system.adapter.telegram.0
instrument.ts:124 system.adapter.text2command.0
instrument.ts:124 system.adapter.tr-064.0
instrument.ts:124 system.adapter.vis.0
instrument.ts:124 system.adapter.vis-bars.0
instrument.ts:124 system.adapter.vis-canvas-gauges.0
instrument.ts:124 system.adapter.vis-fancyswitch.0
instrument.ts:124 system.adapter.vis-history.0
instrument.ts:124 system.adapter.vis-hqwidgets.0
instrument.ts:124 system.adapter.vis-jqui-mfd.0
instrument.ts:124 system.adapter.vis-justgage.0
instrument.ts:124 system.adapter.vis-rgraph.0
instrument.ts:124 system.adapter.vis-timeandweather.0
instrument.ts:124 system.adapter.web.0
instrument.ts:124 getInstances: 1315
instrument.ts:124 ConfigCustomParserSet Components ParserComponent
instrument.ts:124 TypeError: this.props.socket.getObjectViewSystem is not a function
    at x.componentDidMount (ParserComponent.jsx:187:27)
    at Zs (react-dom.production.min.js:261:217)
    at Gs (react-dom.production.min.js:260:446)
    at Gs (react-dom.production.min.js:260:343)
    at Xc (react-dom.production.min.js:259:431)
    at bc (react-dom.production.min.js:283:96)
    at $n (react-dom.production.min.js:281:398)
    at bs (react-dom.production.min.js:270:269)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
(anonym) @ instrument.ts:124




Raspberry | 1400 MHz | Modell: ARMv7 Processor rev 4 (v7l) | RAM: 926 MB
Node.js: v16.19.0 | Adapter-Anzahl: 514 |  NPM: 8.19.3 | Aktive Instanzen: 13

**Comment by oiramgh** [comment]
nach...

iob stop
iob update
iob fix
iob upgrade self
iob start

...und... 

Admin-Adapter-Update

bei mir wieder ohne Probleme / kein Fehler

**Comment by foxriver76** [comment]
not a admin issue, parser provides it own frontend code https://github.com/ioBroker/ioBroker.parser/blob/master/src-admin/src/ParserComponent.jsx
