### ISSUE TITLE
error in gui after js-controller update in dock env [bug]: 

### ISSUE THREAD

**Issue by MadRat8** [ioBroker/ioBroker.admin#2231]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Webinterface is loading properly, you can login but then after couple of seconds "error in gui" appears and webinterface is gone

### To Reproduce

1 open webinterface
2 wait seconds

### Expected behavior

webinterface working

### Screenshots & Logfiles

instrument.ts:124 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BisDocker%2C%20isOfficial%2C%20officialVersion%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Zr (react-dom.production.min.js:152:60)
    at h (react-dom.production.min.js:156:186)
    at S (react-dom.production.min.js:158:331)
    at Q (react-dom.production.min.js:162:334)
    at ae (react-dom.production.min.js:192:308)
    at oa (react-dom.production.min.js:294:9)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)

### Adapter version

buanet/iobroker:latest

### js-controller version

5.0.16

### Node version

v18.18.2

### Operating system

Synology Docker

**Comment by foxriver76** [comment]
The adapter version of admin is missing on hour report. I guess your admin is not up to date

**Comment by MadRat8** [comment]
updated js-controller again. solved it partially - updating admin solved it completely.
