### ISSUE TITLE
[bug]: Error in GUI!

### ISSUE THREAD

**Issue by Tschirpke84** [ioBroker/ioBroker.admin#2250]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

react-dom.production.min.js:189 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BisDocker%2C%20isOfficial%2C%20officialVersion%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Zr (react-dom.production.min.js:152:60)
    at h (react-dom.production.min.js:156:186)
    at S (react-dom.production.min.js:158:331)
    at Q (react-dom.production.min.js:162:334)
    at ae (react-dom.production.min.js:192:308)
    at oa (react-dom.production.min.js:294:9)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
Hi @ react-dom.production.min.js:189

### To Reproduce

??

### Expected behavior

3F8906B1DBCA
Plattform: docker
RAM: 46.9 GB
Node.js: v18.19.0
NPM: 10.2.3

### Screenshots & Logfiles

![IObroker](https://github.com/ioBroker/ioBroker.admin/assets/152598154/03baa305-bea1-499c-b5ff-07c22936ed2a)

### Adapter version

??

### js-controller version

v18.19.0

### Node version

10.2.3

### Operating system

Debian 11

**Comment by Feuer-sturm** [comment]
@Tschirpke84 please add the version of admin adapter. What did you do to trigger the issue?

**Comment by foxriver76** [comment]
This is already fixed in 6.12.0
