### ISSUE TITLE
[bug]: Error In UI after clicking the gear icon under linkeddevices

### ISSUE THREAD

**Issue by dbuchhorn** [ioBroker/ioBroker.admin#2256]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

I installed the influxdb and the linkeddevices adapter. After that I create a link for a shelly device with the following values: Power, Voltage, Switch, temperature. Under the linkeddevices I clicked the gear icon for Power and I activate and configure influxdb. If I click the gear icon for another value then the error occurs. If I do it direct in the shelly device it works. But I want to use the virtual device.
The Power value can be configured but the other values not.

### To Reproduce

see previous description

### Expected behavior

no error

### Screenshots & Logfiles

```
Cannot find adapter "null"
(anonymous) @ instrument.ts:144
value @ ObjectCustomEditor.jsx:189
(anonymous) @ ObjectCustomEditor.jsx:161
value @ ObjectCustomEditor.jsx:157
s @ ObjectCustomEditor.jsx:139
Wa @ react-dom.production.min.js:147
No @ react-dom.production.min.js:198
Ei @ react-dom.production.min.js:292
ks @ react-dom.production.min.js:280
ys @ react-dom.production.min.js:280
vs @ react-dom.production.min.js:280
ss @ react-dom.production.min.js:273
Hl @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:267

Cannot find i18n for linkeddevices / undefined
(anonymous) @ instrument.ts:144
(anonymous) @ index.jsx:94
f @ regeneratorRuntime.js:45
(anonymous) @ regeneratorRuntime.js:133
(anonymous) @ regeneratorRuntime.js:74
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:22
Promise.then (async)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
Promise.then (async)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
Promise.then (async)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
Promise.then (async)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
(anonymous) @ index.jsx:101
(anonymous) @ ObjectCustomEditor.jsx:215
Promise.then (async)
value @ ObjectCustomEditor.jsx:202
(anonymous) @ ObjectCustomEditor.jsx:161
value @ ObjectCustomEditor.jsx:157
s @ ObjectCustomEditor.jsx:139
Wa @ react-dom.production.min.js:147
No @ react-dom.production.min.js:198
Ei @ react-dom.production.min.js:292
ks @ react-dom.production.min.js:280
ys @ react-dom.production.min.js:280
vs @ react-dom.production.min.js:280
ss @ react-dom.production.min.js:273
Hl @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:267

Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ka (react-dom.production.min.js:152:60)
    at e (react-dom.production.min.js:162:372)
    at wo (react-dom.production.min.js:192:308)
    at Ei (react-dom.production.min.js:294:9)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at us (react-dom.production.min.js:271:88)
    at as (react-dom.production.min.js:268:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
(anonymous) @ instrument.ts:144
```

### Adapter version

6.12.0

### js-controller version

4.0.24

### Node version

18.19.0

### Operating system

Raspberry

### Additional context

I use the docker image buanet/iobroker:v9.0.1

**Comment by foxriver76** [comment]
Please try if `iob u linked-devices` fixes this. If not I need to look into.

**Comment by dbuchhorn** [comment]
I don't know that I shuld try? But I alrady tried to restart the linkeddevices instance and the "repair button" in the configuration section. All this doesn't work.

**Comment by dbuchhorn** [comment]
I run the command `iob u linkeddevices` but the problem still exists.
