### ISSUE TITLE
vis2.0 V2.9.11 Socket Error: Error: xhr post error [bug]: 

### ISSUE THREAD

**Issue by BNeubauer77** [ioBroker/ioBroker.admin#2307]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

After intalling vis 2 adapter some failure occure in vis2 adapter. One permanent failure is: Socket Error: xhr post error. Details and log see below

### To Reproduce

open vis 2
import a project 
while import process failure occures 

### Expected behavior

fixing the issue

### Screenshots & Logfiles

failure description from browser console

iobroker.admin@6.3.7
socket.io.js:3 WebSocket connection to 'wss://iobroker.pro/socket.io/?ws=true&EIO=3&transport=websocket&sid=0gvBoMzAMupYlbPbAE-r' failed: 

Failed to load resource: the server responded with a status of 404 (Not Found)
i18n.js:147 Translate: ra_Suitable license not found in license manager
react-dom.production.min.js:189 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BCountry%2C%20Name%2C%20FirmName%2C%20AddressLine1%2C%20ZIP%2C%20City%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Zr (react-dom.production.min.js:152:60)
    at h (react-dom.production.min.js:156:186)
    at S (react-dom.production.min.js:158:331)
    at Q (react-dom.production.min.js:162:334)
    at ae (react-dom.production.min.js:192:308)
    at oa (react-dom.production.min.js:294:9)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
Hi @ react-dom.production.min.js:189
Show 1 more frame
Show less

### Adapter version

2.9.11

### js-controller version

5.0.17

### Node version

18.17.1

### Operating system

linux

**Comment by foxriver76** [comment]
Is it via ioBroker.pro?

**Comment by BNeubauer77** [comment]
yes it is via ioBroker.pro connection.
-------- Ursprüngliche Nachricht --------Von: Max Hauser ***@***.***> Datum: 04.01.24  15:02  (GMT+01:00) An: "ioBroker/ioBroker.admin" ***@***.***> Cc: BNeubauer77 ***@***.***>, Manual ***@***.***> Betreff: Re: [ioBroker/ioBroker.admin] vis2.0 V2.9.11 Socket Error: Error: xhr
  post error [bug]:  (Issue #2307) 
Is it via ioBroker.pro?
