### ISSUE TITLE
[bug]: Error in GUI!

### ISSUE THREAD

**Issue by bfelizardo** [ioBroker/ioBroker.admin#2311]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Since few weeks I always get an error. Specially when I try to edit the scripts. The system just freezes and I get an error.

### To Reproduce

1. Edit a script 
2. Go back to other page
3. System freezes and I get the error message.

### Expected behavior

A smooth performance as it was before ;-) 

### Screenshots & Logfiles

```
Loading chunk 1951 failed. (timeout: https://192.168.178.201:8081/static/js/1951.2b5ecce1.chunk.js)
ChunkLoadError: Loading chunk 1951 failed.function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}(timeout: https://192.168.178.201:8081/static/js/1951.2b5ecce1.chunk.js)function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}    at t.f.j (https://192.168.178.201:8081/static/js/main.56eaa755.js:1:13504)function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}    at https://192.168.178.201:8081/static/js/main.56eaa755.js:1:1285function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}    at Array.reduce (<anonymous>)function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}    at t.e (https://192.168.178.201:8081/static/js/main.56eaa755.js:1:1250)function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}    at https://192.168.178.201:8081/static/js/7136.2908cc23.chunk.js:2:238497function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}    at P (https://192.168.178.201:8081/static/js/2791.8afe157f.chunk.js:2:3351)function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}    at Ei (https://192.168.178.201:8081/static/js/4164.29c179b8.chunk.js:2:120786)function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}    at ks (https://192.168.178.201:8081/static/js/4164.29c179b8.chunk.js:2:109418)function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}    at ys (https://192.168.178.201:8081/static/js/4164.29c179b8.chunk.js:2:109346)function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}    at vs (https://192.168.178.201:8081/static/js/4164.29c179b8.chunk.js:2:109209)function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}    at ss (https://192.168.178.201:8081/static/js/4164.29c179b8.chunk.js:2:106325)function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}    at Hl (https://192.168.178.201:8081/static/js/4164.29c179b8.chunk.js:2:46920)function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}    at https://192.168.178.201:8081/static/js/4164.29c179b8.chunk.js:2:103922
```

`ChunkLoadError: Loading chunk 1951 failed.function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}(timeout: https://192.168.178.201:8081/static/js/1951.2b5ecce1.chunk.js)function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}    at t.f.j (https://192.168.178.201:8081/static/js/main.56eaa755.js:1:13504)function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}    at https://192.168.178.201:8081/static/js/main.56eaa755.js:1:1285function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}    at Array.reduce (<anonymous>)function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}    at t.e (https://192.168.178.201:8081/static/js/main.56eaa755.js:1:1250)function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}    at https://192.168.178.201:8081/static/js/7136.2908cc23.chunk.js:2:238497function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}    at P (https://192.168.178.201:8081/static/js/2791.8afe157f.chunk.js:2:3351)function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}    at Ei (https://192.168.178.201:8081/static/js/4164.29c179b8.chunk.js:2:120786)function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}    at ks (https://192.168.178.201:8081/static/js/4164.29c179b8.chunk.js:2:109418)function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}    at ys (https://192.168.178.201:8081/static/js/4164.29c179b8.chunk.js:2:109346)function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}    at vs (https://192.168.178.201:8081/static/js/4164.29c179b8.chunk.js:2:109209)function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}    at ss (https://192.168.178.201:8081/static/js/4164.29c179b8.chunk.js:2:106325)function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}    at Hl (https://192.168.178.201:8081/static/js/4164.29c179b8.chunk.js:2:46920)function(e,t){return(0,y.jsxs)("div",{children:[e,(0,y.jsx)("br",{})]},t)}    at https://192.168.178.201:8081/static/js/4164.29c179b8.chunk.js:2:103922`

### Adapter version

v7.1.6

### js-controller version

5.0.17

### Node version

v4.0.3

### Operating system

v6.12.0

**Comment by Feuer-sturm** [comment]
@bfelizardo Is this issue still active on your system?
please retest with current stable version of admin (7.1.5 (you wrote you have 7.1.6)) or test with latest admin version (currently 7.4.8)
