### ISSUE TITLE
Fehlermeldung beim Aufruf von Liesmich [bug]: 

### ISSUE THREAD

**Issue by UweRP** [ioBroker/ioBroker.admin#2336]
### No existing issues.

- [x] There is no existing issue for my problem.

### Describe the bug

Ich erhalte eine Fehlermeldung, vermutlich vom Admin Adapter selbst, beim Aufruf von Liesmich für den FullyBrowser Adapter.
Getestet mit Chrome und Firefox.

### To Reproduce

[Admin Fehler.webm](https://github.com/ioBroker/ioBroker.admin/assets/17329042/56bb92f4-cf99-4e18-824d-f3180ae8223b)

### Expected behavior

-

### Screenshots & Logfiles

```
Failed to load resource: the server responded with a status of 404 (Not Found)
console.ts:40 DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('img<') is not a valid name.
    at qo (http://10.111.112.39:8081/static/js/2882.4644449f.chunk.js:2:86039)
    at ws (http://10.111.112.39:8081/static/js/2882.4644449f.chunk.js:2:109592)
    at ks (http://10.111.112.39:8081/static/js/2882.4644449f.chunk.js:2:109473)
    at ys (http://10.111.112.39:8081/static/js/2882.4644449f.chunk.js:2:109340)
    at vs (http://10.111.112.39:8081/static/js/2882.4644449f.chunk.js:2:109203)
    at us (http://10.111.112.39:8081/static/js/2882.4644449f.chunk.js:2:105983)
    at ss (http://10.111.112.39:8081/static/js/2882.4644449f.chunk.js:2:106374)
    at Hl (http://10.111.112.39:8081/static/js/2882.4644449f.chunk.js:2:46914)
    at http://10.111.112.39:8081/static/js/2882.4644449f.chunk.js:2:112797
    at Ss (http://10.111.112.39:8081/static/js/2882.4644449f.chunk.js:2:112802)
    at as (http://10.111.112.39:8081/static/js/2882.4644449f.chunk.js:2:105260)
    at S (http://10.111.112.39:8081/static/js/2882.4644449f.chunk.js:2:131297)
    at MessagePort.T (http://10.111.112.39:8081/static/js/2882.4644449f.chunk.js:2:131831)
(anonymous) @ console.ts:40
Show 1 more frame
Show less
index.html#tab-adapt…adme/fullybrowser:1 Uncaught (in promise) timeout

```

### Adapter version

6.13.15

### js-controller version

 5.0.17

### Node version

v18.19.0

### Operating system

Windows 10 x64

**Comment by foxriver76** [comment]
Langfristig sollten wir das ganze geparse in MDUtils vermutlich durch eine Lib ersetzen die darauf spezialisiert ist wie https://github.com/remarkjs/react-markdown
 
Für jetzt: es liegt daran dass admin https://github.com/arteck/ioBroker.fullybrowser/pull/192 das nicht richtig geparsed bekommt.

**Comment by Feuer-sturm** [comment]
@UweRP bitte einmal mit der Verion >= 3.0.10 vom ioBroker.fullybrowser testen ob das Problem gelöst ist.

**Comment by UweRP** [comment]
Ja, Fehler scheint behoben. Im Admin erhalte ich keine Fehlermeldung mehr.
Danke.
