### ISSUE TITLE
[bug]: export jsonconfig

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.admin#2351]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

if i click on the right export button nothing happens
![image](https://github.com/ioBroker/ioBroker.admin/assets/92173565/00765ebb-aa21-4786-b152-e290bf1ce3d3)

### To Reproduce

create an jsonconfig and export

### Expected behavior

export the config like before.
The issue is present at Admin 6.13.15.

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.admin/assets/92173565/7558bb08-3ad5-4504-b56d-c1975704c821)

### Adapter version

6.13.15

### js-controller version

5.0.17

### Node version

18.19.0

### Operating system

Docker Image

**Comment by mcm1957** [comment]
Console window shows error:

```
helpers.ts:120 Uncaught TypeError: g.Z.generateFile is not a function
    at onClick (JsonConfig.tsx:331:31)
    at Object.Re (react-dom.production.min.js:54:317)
    at Be (react-dom.production.min.js:54:471)
    at react-dom.production.min.js:55:35
    at Ir (react-dom.production.min.js:105:68)
    at Ur (react-dom.production.min.js:106:380)
    at react-dom.production.min.js:117:104
    at cs (react-dom.production.min.js:274:42)
    at Le (react-dom.production.min.js:52:375)
    at Qr (react-dom.production.min.js:109:469)
    at qn (react-dom.production.min.js:74:59)
    at $n (react-dom.production.min.js:73:73)
    at HTMLDivElement.r (helpers.ts:98:17)
```

admin 6.13.15
