### ISSUE TITLE
[bug]: Errror in GUI if try to delete one object

### ISSUE THREAD

**Issue by SurfGargano** [ioBroker/ioBroker.admin#2393]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

If I want to delete one object an error in gui occured

### To Reproduce

1. Go to objects
2. selected one object
3. try to delete
4. a gui error occurs
This was with the version 6.15.0. With 6.14.1 there was no error

### Expected behavior

No error , if I delete one object

### Screenshots & Logfiles

Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Rs (react-dom.production.min.js:303:64)
    at e (react-dom.production.min.js:161:400)
    at wo (react-dom.production.min.js:192:308)
    at Ei (react-dom.production.min.js:294:9)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at us (react-dom.production.min.js:271:88)
    at ss (react-dom.production.min.js:273:300)
    at Hl (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonymous) @ console.ts:40
Show 1 more frame
Show less

### Adapter version

6.15.0

### js-controller version

5.0.19

### Node version

18.17.1

### Operating system

Debian Linux

**Comment by harald0815** [comment]
Same Probleme


console.ts:40 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Rs (react-dom.production.min.js:303:64)
    at e (react-dom.production.min.js:161:400)
    at wo (react-dom.production.min.js:192:308)
    at Ei (react-dom.production.min.js:294:9)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at us (react-dom.production.min.js:271:88)
    at ss (react-dom.production.min.js:273:300)
    at Hl (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
