### ISSUE TITLE
[bug]: admin did not start after update

### ISSUE THREAD

**Issue by tobasium** [ioBroker/ioBroker.admin#2438]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

After Update to latest [Release v6.17.6] Admin did not start. I'm also not able to downgrade. Error still the same

I found the folowing errors in log:

`TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received 'file:// /opt/iobroker/node_modules/iobroker.alexa2/node_modules/@iobroker/adapter-core/build/cjs/helpers.js'
    at new NodeError (node:internal/errors:405:5)
    at createRequire (node:internal/modules/cjs/loader:1501:13)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/@iobroker/adapter-core/build/cjs/helpers.js:36:53)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/@iobroker/adapter-core/build/cjs/controllerTools.js:34:22) {
  code: 'ERR_INVALID_ARG_VALUE'
}`

### To Reproduce

Update admin adapter

### Expected behavior

-

### Screenshots & Logfiles

Node.js v18.20.2
================================== > LOG REDIRECT system.adapter.admin.0 => false [Process stopped]
================================== > LOG REDIRECT system.adapter.admin.0 => false [system.adapter.admin.0.logging]
node:internal/modules/cjs/loader:1501
      throw new ERR_INVALID_ARG_VALUE('filename', filename,
      ^
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received 'file:// /opt/iobroker/node_modules/iobroker.alexa2/node_modules/@iobroker/adapter-core/build/cjs/helpers.js'
    at new NodeError (node:internal/errors:405:5)
    at createRequire (node:internal/modules/cjs/loader:1501:13)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/@iobroker/adapter-core/build/cjs/helpers.js:36:53)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/@iobroker/adapter-core/build/cjs/controllerTools.js:34:22) {
  code: 'ERR_INVALID_ARG_VALUE'
}
Node.js v18.20.2
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Model yeelink.light.bslamp2 is not supported
    at Object.createDevice [as device] (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/device.js:8:11)
    at CreateDevices (script.js.Smarthome_Tobi.Geräte.Sonstige.mihome:911:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at main (script.js.Smarthome_Tobi.Geräte.Sonstige.mihome:843:5)
node:internal/modules/cjs/loader:1501
      throw new ERR_INVALID_ARG_VALUE('filename', filename,
      ^
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received 'file:// /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/adapter-core/build/cjs/helpers.js'
    at new NodeError (node:internal/errors:405:5)
    at createRequire (node:internal/modules/cjs/loader:1501:13)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/adapter-core/build/cjs/helpers.js:36:53)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/adapter-core/build/cjs/controllerTools.js:34:22) {
  code: 'ERR_INVALID_ARG_VALUE'
}
Node.js v18.20.2
================================== > LOG REDIRECT system.adapter.admin.0 => false [Process stopped]
================================== > LOG REDIRECT system.adapter.admin.0 => false [system.adapter.admin.0.logging]
node:internal/modules/cjs/loader:1501
      throw new ERR_INVALID_ARG_VALUE('filename', filename,
      ^
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received 'file:// /opt/iobroker/node_modules/iobroker.alexa2/node_modules/@iobroker/adapter-core/build/cjs/helpers.js'
    at new NodeError (node:internal/errors:405:5)
    at createRequire (node:internal/modules/cjs/loader:1501:13)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/@iobroker/adapter-core/build/cjs/helpers.js:36:53)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/@iobroker/adapter-core/build/cjs/controllerTools.js:34:22) {
  code: 'ERR_INVALID_ARG_VALUE'
}
Node.js v18.20.2
node:internal/modules/cjs/loader:1501
      throw new ERR_INVALID_ARG_VALUE('filename', filename,
      ^
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received 'file:// /opt/iobroker/node_modules/iobroker.homeconnect/node_modules/@iobroker/adapter-core/build/cjs/helpers.js'
    at new NodeError (node:internal/errors:405:5)
    at createRequire (node:internal/modules/cjs/loader:1501:13)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.homeconnect/node_modules/@iobroker/adapter-core/build/cjs/helpers.js:36:53)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.homeconnect/node_modules/@iobroker/adapter-core/build/cjs/controllerTools.js:34:22) {
  code: 'ERR_INVALID_ARG_VALUE'
}
Node.js v18.20.2

### Adapter version

6.17.6

### js-controller version

5.0.19

### Node version

18.20.2

### Operating system

docker

**Comment by dg1lxs** [comment]
the same here unfortunately

**Comment by Apollon77** [comment]
Do you use the compact mode?

**Comment by Apollon77** [comment]
Ok please try the following: 
* stop iobroker
* cd /opt/iobroker
* npm i iobroker.admin@latest
* iob upload admin

Does it work afterwards?

There was an errornous version of a used library online fpr 30mins, seems you hit this timespan unfortunately

**Comment by dg1lxs** [comment]
Hi,

Did not work:-( 
`
iobroker   | node:internal/modules/cjs/loader:1371
iobroker   |       throw new ERR_INVALID_ARG_VALUE('filename', filename,
iobroker   |       ^
iobroker   | 
iobroker   | TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received 'file:// /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/adapter-core/build/cjs/helpers.js'
iobroker   |     at new NodeError (node:internal/errors:405:5)
iobroker   |     at createRequire (node:internal/modules/cjs/loader:1371:13)
iobroker   |     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/adapter-core/build/cjs/helpers.js:36:53)
iobroker   |     at Module._compile (node:internal/modules/cjs/loader:1256:14)
iobroker   |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
iobroker   |     at Module.load (node:internal/modules/cjs/loader:1119:32)
iobroker   |     at Module._load (node:internal/modules/cjs/loader:960:12)
iobroker   |     at Module.require (node:internal/modules/cjs/loader:1143:19)
iobroker   |     at require (node:internal/modules/cjs/helpers:121:18)
iobroker   |     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/adapter-core/build/cjs/controllerTools.js:34:22) {
iobroker   |   code: 'ERR_INVALID_ARG_VALUE'
iobroker   | }
iobroker   | 
iobroker   | Node.js v18.17.1
`

I am not using the compact mode, but as Tobias I am in a docker environment….

Br,

Alexander

**Comment by foxriver76** [comment]
> Hi,
> 
> Did not work:-(
> 
> iobroker | node:internal/modules/cjs/loader:1371 iobroker | throw new ERR_INVALID_ARG_VALUE('filename', filename, iobroker | ^ iobroker | iobroker | TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received 'file:// /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/adapter-core/build/cjs/helpers.js' iobroker | at new NodeError (node:internal/errors:405:5) iobroker | at createRequire (node:internal/modules/cjs/loader:1371:13) iobroker | at Object. (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/adapter-core/build/cjs/helpers.js:36:53) iobroker | at Module._compile (node:internal/modules/cjs/loader:1256:14) iobroker | at Module._extensions..js (node:internal/modules/cjs/loader:1310:10) iobroker | at Module.load (node:internal/modules/cjs/loader:1119:32) iobroker | at Module._load (node:internal/modules/cjs/loader:960:12) iobroker | at Module.require (node:internal/modules/cjs/loader:1143:19) iobroker | at require (node:internal/modules/cjs/helpers:121:18) iobroker | at Object. (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/adapter-core/build/cjs/controllerTools.js:34:22) { iobroker | code: 'ERR_INVALID_ARG_VALUE' iobroker | } iobroker | iobroker | Node.js v18.17.1
> 
> I am not using the compact mode, but as Tobias I am in a docker environment….
> 
> Br,
> 
> Alexander

Then please try (it may depend on the npm version if it works without deleting node modules):


 - stop iobroker
 - cd /opt/iobroker
 - rm -r /opt/iobroker/node_modules/iobroker.admin/node_modules
 - npm i iobroker.admin@latest
 - iob upload admin

**Comment by dg1lxs** [comment]
Sorry, still the same issue:-( Thanks for supporting!

**Comment by foxriver76** [comment]
That’s weird tbh, then other option is 

`cd /opt/iobroker/node_modules/iobroker.admin`
`npm i @iobroker/adapter-core@3.1.4`

if still not working please show how you executed commands

**Comment by dg1lxs** [comment]
That worked! Thank you!

**Comment by tobasium** [comment]
Hi, i went back to an backup from the night before and start update again. Know it works.

**Comment by Apollon77** [comment]
https://forum.iobroker.net/topic/74238/l%C3%B6sung-f%C3%BCr-fehler-typeerror-err_invalid_arg_value
