### ISSUE TITLE
[bug]: Admin crashes when a value is edited

### ISSUE THREAD

**Issue by Marc-Berg** [ioBroker/ioBroker.admin#2443]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Admin crashes when a value is edited. The error only occurs if an instance of “influxdb.0” is activated on the data point. With “influxdb.1”, for example, no error appears.

Version 6.17.3 does not have this error.

### To Reproduce

1. activate an influxdb instance ".0"
2. Click on the value to edit with activated InfluxDB

### Expected behavior

Self-explanatory.

### Screenshots & Logfiles

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/99531337/46f9ff29-8108-440a-899b-2a08a7b0935a)

```
TypeError: this.state.historyInstances is null
    renderChart ObjectChart.tsx:1157
    render ObjectChart.tsx:1448
    React 12
    S scheduler.production.min.js:13
    T scheduler.production.min.js:14
``` 

### Adapter version

>=6.17.6

### js-controller version

5.0.19

### Node version

18.20.2

### Operating system

Linux

**Comment by XxJooO** [comment]
I have almost the same settings, use Linux Mint LMDE6 and Chrome 124.0.6367.118. Same error here when trying to edit a value which is logged by influxdb0. Error in GUI

**Comment by Eistee82** [comment]
6.17.3 is the latest version which is working for me. all later versions have this bug.

**Comment by jonnycastaway** [comment]
Same error here when trying to edit a value which is logged by influxdb0. Error in GUI.

`console.ts:40 TypeError: Cannot read properties of null (reading 'find')
    at tt.renderChart (ObjectChart.tsx:1160:42)
    at tt.render (ObjectChart.tsx:1448:23)
    at Po (react-dom.production.min.js:204:189)
    at No (react-dom.production.min.js:203:149)
    at Ei (react-dom.production.min.js:292:172)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at us (react-dom.production.min.js:271:88)
    at ss (react-dom.production.min.js:273:300)
    at Hl (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:283:470
    at Ss (react-dom.production.min.js:281:398)
    at as (react-dom.production.min.js:270:269)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
sentry.iobroker.net/…browser%2F7.111.0:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
sentry.iobroker.net/…browser%2F7.111.0:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
sentry.iobroker.net/…browser%2F7.111.0:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED`

**Comment by Marc-Berg** [comment]
Fix in 6.17.11 confirmed
