### ISSUE TITLE
[bug]:  manual change status fritz.dect - error screen

### ISSUE THREAD

**Issue by bobmorane77** [ioBroker/ioBroker.admin#2449]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

errorscreen with advice to copy browser infos:

console.ts:40 TypeError: Cannot read properties of null (reading 'find')
    at tt.renderChart (ObjectChart.tsx:1160:42)
    at tt.render (ObjectChart.tsx:1448:23)
    at Po (react-dom.production.min.js:204:189)
    at No (react-dom.production.min.js:203:149)
    at Ei (react-dom.production.min.js:292:172)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at us (react-dom.production.min.js:271:88)
    at ss (react-dom.production.min.js:273:300)
    at Hl (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:283:470
    at Ss (react-dom.production.min.js:281:398)
    at as (react-dom.production.min.js:270:269)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)

### To Reproduce

open objects
choose fritzdect folder
click on state status --> error screen

### Expected behavior

i should be able to witch the state

### Screenshots & Logfiles

<img width="2884" alt="Bildschirmfoto 2024-05-02 um 10 02 06" src="https://github.com/ioBroker/ioBroker.admin/
<img width="2618" alt="Bildschirmfoto 2024-05-02 um 10 01 14" src="https://github.com/ioBroker/ioBroker.admin/assets/12913409/0da3bc2f-5818-40ea-a70a-697f642e7495">
assets/12913409/e2c067be-33f4-448e-b634-33e644a4dbf4">

### Adapter version

6.17.6

### js-controller version

5.0.19

### Node version

18.17.1

### Operating system

Rasbian OS

**Comment by Eistee82** [comment]
see #2443
