### ISSUE TITLE
[bug]: ERROR on manual changing some stats

### ISSUE THREAD

**Issue by Heiko1977** [ioBroker/ioBroker.admin#2450]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

If i try to change some states manually, an error screen appears. I tried on some states and some works and some gives the error.

### To Reproduce

Got to Objects and try to change a boolean state even in userdata

### Expected behavior

Error in GUI! Screen

### Screenshots & Logfiles

TypeError: Cannot read properties of null (reading 'find')
    at tt.renderChart (ObjectChart.tsx:1160:42)
    at tt.render (ObjectChart.tsx:1448:23)
    at Po (react-dom.production.min.js:204:189)
    at No (react-dom.production.min.js:203:149)
    at Ei (react-dom.production.min.js:292:172)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at us (react-dom.production.min.js:271:88)
    at ss (react-dom.production.min.js:273:300)
    at Hl (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:283:470
    at Ss (react-dom.production.min.js:281:398)
    at as (react-dom.production.min.js:270:269)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)

### Adapter version

v6.17.6

### js-controller version

8.1.1

### Node version

v18.20.2

### Operating system

RaspianOS Bookworm 64Bit

**Comment by fL4sH3r** [comment]
I have exaclty the same Problem. 
![image](https://github.com/ioBroker/ioBroker.admin/assets/97987283/8bfb79a2-bf6b-46e9-b1e9-ab73f19cc067)

**Comment by jonnycastaway** [comment]
[#2443](https://github.com/ioBroker/ioBroker.admin/issues/2443#issue-2266960627)
