### ISSUE TITLE
[bug]: Error in Gui! Scripts crash

### ISSUE THREAD

**Issue by mpl1337** [ioBroker/ioBroker.admin#2455]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Admin Gui Crash when i open Scripts

### To Reproduce

Click on "Skripte"

### Expected behavior

.

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.admin/assets/19016821/c9840b2f-a7e7-44e5-86e7-d39326d91827)

### Adapter version

6.17.8

### js-controller version

5.0.19

### Node version

18.20.0

### Operating system

Debian 12.5

**Comment by Diginix** [comment]
Same here with admin 6.17.8:
```
TypeError: Cannot read properties of null (reading 'contentWindow')
    at c.componentDidMount (CustomTab.tsx:143:48)
    at Si (react-dom.production.min.js:263:222)
    at bi (react-dom.production.min.js:259:318)
    at yi (react-dom.production.min.js:258:431)
    at react-dom.production.min.js:282:96
    at ws (react-dom.production.min.js:280:398)
    at ls (react-dom.production.min.js:269:269)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
(anonymous) @ console.ts:40
co @ react-dom.production.min.js:188
a.componentDidCatch.t.callback @ react-dom.production.min.js:189
Wa @ react-dom.production.min.js:156
ki @ react-dom.production.min.js:260
bi @ react-dom.production.min.js:259
yi @ react-dom.production.min.js:258
(anonymous) @ react-dom.production.min.js:282
ws @ react-dom.production.min.js:280
is @ react-dom.production.min.js:272
Hl @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:282
ws @ react-dom.production.min.js:280
ls @ react-dom.production.min.js:269
S @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
Show 16 more frames
Show less
toolbarContentscript.js:113 {"message":"A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received"}
```

**Comment by T-S-Garp** [comment]
I see the same issue right after the admin adapter upgrade to 6.17.8. The #tab-javascript is not accessible anymore:

![image](https://github.com/ioBroker/ioBroker.admin/assets/170171107/3befcd28-b378-4aec-858d-05e07016c130)

**Comment by diamand2k22** [comment]
yes i can confirm, downgrade to V6.17.6 helps

**Comment by wittmannchris** [comment]
same here:
`echarts.png:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
zigbee.png:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
...
console.ts:40 TypeError: Cannot read properties of null (reading 'contentWindow')
    at c.componentDidMount (CustomTab.tsx:143:48)
    at Si (react-dom.production.min.js:263:222)
    at bi (react-dom.production.min.js:259:318)
    at yi (react-dom.production.min.js:258:431)
    at react-dom.production.min.js:282:96
    at ws (react-dom.production.min.js:280:398)
    at ls (react-dom.production.min.js:269:269)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
(anonymous) @ console.ts:40
Show 1 more frame
Show less`

**Comment by hombach** [comment]
Same.... Admin 6.17.8 with OpenDTU screen brings up: 
![image](https://github.com/ioBroker/ioBroker.admin/assets/63002482/9384a6c8-6a62-482c-9f8d-a1dd745d519a)

This issue is labeled as "fixed" .... would be great to have a hint for the version where it is fixed to test it upon (beta-) release.

**Comment by Grothesk242** [comment]
6.17.8 has been revoked, 6.17.7 is the latest release atm.

**Comment by Feuer-sturm** [comment]
@mpl1337 @Grothesk242 @hombach please check with current beta version v6.17.13 if this issue can be closed.

**Comment by Grothesk242** [comment]
lgtm

**Comment by hombach** [comment]
Works fine! Thank you!
