### ISSUE TITLE
[bug]: Error Admin-Adapter Update

### ISSUE THREAD

**Issue by Hans06780** [ioBroker/ioBroker.admin#2458]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Update Admin-Adapter fail with Error, Error in GUI, Skripte not accessible, Backup not accessible

### To Reproduce

4 See Error

### Expected behavior

4

### Screenshots & Logfiles

Cannot read properties of null (reading 'contentWindow')
TypeError: Cannot read properties of null (reading 'contentWindow')(e,t)=>(0,g.jsxs)("div",{children:[e,(0,g.jsx)("br",{})]},t)
    at c.componentDidMount (http://192.168.2.195:8081/static/js/5060.031ffab9.chunk.js:1:348691)(e,t)=>(0,g.jsxs)("div",{children:[e,(0,g.jsx)("br",{})]},t)
    at Si (http://192.168.2.195:8081/static/js/5096.3a6e8bdb.chunk.js:2:102405)(e,t)=>(0,g.jsxs)("div",{children:[e,(0,g.jsx)("br",{})]},t)
    at bi (http://192.168.2.195:8081/static/js/5096.3a6e8bdb.chunk.js:2:100735)(e,t)=>(0,g.jsxs)("div",{children:[e,(0,g.jsx)("br",{})]},t)
    at yi (http://192.168.2.195:8081/static/js/5096.3a6e8bdb.chunk.js:2:100399)(e,t)=>(0,g.jsxs)("div",{children:[e,(0,g.jsx)("br",{})]},t)
    at http://192.168.2.195:8081/static/js/5096.3a6e8bdb.chunk.js:2:112236(e,t)=>(0,g.jsxs)("div",{children:[e,(0,g.jsx)("br",{})]},t)
    at ws (http://192.168.2.195:8081/static/js/5096.3a6e8bdb.chunk.js:2:112751)(e,t)=>(0,g.jsxs)("div",{children:[e,(0,g.jsx)("br",{})]},t)
    at ls (http://192.168.2.195:8081/static/js/5096.3a6e8bdb.chunk.js:2:105209)(e,t)=>(0,g.jsxs)("div",{children:[e,(0,g.jsx)("br",{})]},t)
    at S (http://192.168.2.195:8081/static/js/5096.3a6e8bdb.chunk.js:2:131248)(e,t)=>(0,g.jsxs)("div",{children:[e,(0,g.jsx)("br",{})]},t)
    at MessagePort.T (http://192.168.2.195:8081/static/js/5096.3a6e8bdb.chunk.js:2:131782)

### Adapter version

6.17.8

### js-controller version

5.0.19

### Node version

18.20.2

### Operating system

Linux raspberrypi-iobroker 6.1.21-v8+

**Comment by mcm1957** [comment]
Could be related to https://github.com/ioBroker/ioBroker.admin/issues/2455

**Comment by Hans06780** [comment]
Downgrade to 6.17.6 is OK
