### ISSUE TITLE
[bug]: iobroker crashes after starting "Skripts"

### ISSUE THREAD

**Issue by jmorgenstern-priv** [ioBroker/ioBroker.admin#2459]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Admin version 6.17.8

After clicking on "Scripts" (#tab-javascript) iob crashes

### To Reproduce

open iob
click menu "Scripts"

### Expected behavior

usually the script editor should open

### Screenshots & Logfiles

TypeError: Cannot read properties of null (reading 'contentWindow')
    at c.componentDidMount (CustomTab.tsx:143:48)
    at Si (react-dom.production.min.js:263:222)
    at bi (react-dom.production.min.js:259:318)
    at yi (react-dom.production.min.js:258:431)
    at react-dom.production.min.js:282:96
    at ws (react-dom.production.min.js:280:398)
    at ls (react-dom.production.min.js:269:269)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)

### Adapter version

6.17.8

### js-controller version

5.0.19

### Node version

18.20.2

### Operating system

linux (ARM64) Bookwork

### Additional context

the issue came up after upgrading the admin-adapter to 6.17.8

**Comment by Diginix** [comment]
> ### No existing issues.

But there is already an issue #2455
