### ISSUE TITLE
Fehler Node-RED Link IOBROKER Übersicht

### ISSUE THREAD

**Issue by Chemnitzer01** [ioBroker/ioBroker.admin#2461]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

In der Übersicht von IOBROKER auf Node-RED Link geklickt dann kommt der Fehler. Wenn man Node-RED über den Port öffnet geht es.

### To Reproduce

1. Oberfläche aufgerufen
2. In der Hauptansicht Links auf den Link von Node-RED geklickt
3. Fehlermeldung kommt in Browser.

### Expected behavior

....

### Screenshots & Logfiles

console.ts:40 TypeError: Cannot read properties of null (reading 'contentWindow')
    at c.componentDidMount (CustomTab.tsx:143:48)
    at Si (react-dom.production.min.js:263:222)
    at bi (react-dom.production.min.js:259:318)
    at yi (react-dom.production.min.js:258:431)
    at react-dom.production.min.js:282:96
    at ws (react-dom.production.min.js:280:398)
    at ls (react-dom.production.min.js:269:269)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)

### Adapter version

5.2.1

### js-controller version

5.0.19

### Node version

18.20.2

### Operating system

Debian

**Comment by Grothesk242** [comment]
Duplkat von 
https://github.com/ioBroker/ioBroker.admin/issues/2455
