### ISSUE TITLE
Hilfe: Error in gui

### ISSUE THREAD

**Issue by mamsis** [ioBroker/ioBroker.admin#2462]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Ich kann in iobroker keine Rubriken aufrufen wie Backup, Zigbee, Node red, 
Ich erhalte dann die Fehlermeldung ich soll den Errortext posten: 

console.ts:40 TypeError: Cannot read properties of null (reading 'contentWindow')
    at c.componentDidMount (CustomTab.tsx:143:48)
    at Si (react-dom.production.min.js:263:222)
    at bi (react-dom.production.min.js:259:318)
    at yi (react-dom.production.min.js:258:431)
    at react-dom.production.min.js:282:96
    at ws (react-dom.production.min.js:280:398)
    at ls (react-dom.production.min.js:269:269)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)

Was kann ich tun, damit es wieder funktioniert, ich wieder damit arbeiten kann?
Neustart etc helfen nicht.

### To Reproduce

console.ts:40 TypeError: Cannot read properties of null (reading 'contentWindow')
    at c.componentDidMount (CustomTab.tsx:143:48)
    at Si (react-dom.production.min.js:263:222)
    at bi (react-dom.production.min.js:259:318)
    at yi (react-dom.production.min.js:258:431)
    at react-dom.production.min.js:282:96
    at ws (react-dom.production.min.js:280:398)
    at ls (react-dom.production.min.js:269:269)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)

### Expected behavior

DIe Seite um z.B. Javascripte zu erstellen oder bearbeiten, starten oder stoppen
Die Zigbee Adapter Übersicht
etc.

### Screenshots & Logfiles

TypeError: Cannot read properties of null (reading 'contentWindow')
    at c.componentDidMount (CustomTab.tsx:143:48)
    at Si (react-dom.production.min.js:263:222)
    at bi (react-dom.production.min.js:259:318)
    at yi (react-dom.production.min.js:258:431)
    at react-dom.production.min.js:282:96
    at ws (react-dom.production.min.js:280:398)
    at ls (react-dom.production.min.js:269:269)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)

### Adapter version

8.3.1

### js-controller version

5.0.19

### Node version

18.20.0

### Operating system

rapsberry pi, Linux arm64

**Comment by fuchs-1978** [comment]
Same here, Javascript Adapter:

```
TypeError: Cannot read properties of null (reading 'contentWindow')
    at c.componentDidMount (5060.031ffab9.chunk.js:1:348691)
    at Si (5096.3a6e8bdb.chunk.js:2:102405)
    at bi (5096.3a6e8bdb.chunk.js:2:100735)
    at yi (5096.3a6e8bdb.chunk.js:2:100399)
    at 5096.3a6e8bdb.chunk.js:2:112236
    at ws (5096.3a6e8bdb.chunk.js:2:112751)
    at ls (5096.3a6e8bdb.chunk.js:2:105209)
    at S (5096.3a6e8bdb.chunk.js:2:131248)
    at MessagePort.T (5096.3a6e8bdb.chunk.js:2:131782)
```

**Comment by Grothesk242** [comment]
Dublicate of 
https://github.com/ioBroker/ioBroker.admin/issues/2455

**Comment by ProfMertes** [comment]
Sam here:

**Console Output:** 
TypeError: this.refIframe is null
    componentDidMount CustomTab.tsx:143
    React 6
    S scheduler.production.min.js:13
    T scheduler.production.min.js:14
console.ts:40:19
Error: Promised response from onMessage listener went out of scope
