### ISSUE TITLE
[bug]: Admin GUI fails to display /#tab-enums

### ISSUE THREAD

**Issue by tseroo** [ioBroker/ioBroker.admin#2495]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

When accessing the Kategorien page (/#tab-enums) an error is shown, saying "Error in GUI":

> console.ts:40 TypeError: Cannot read properties of undefined (reading 'desc')
    at y.render (EnumBlock.tsx:405:37)
    at No (react-dom.production.min.js:203:189)
    at zo (react-dom.production.min.js:202:149)
    at xi (react-dom.production.min.js:291:172)
    at bs (react-dom.production.min.js:279:389)
    at vs (react-dom.production.min.js:279:320)
    at gs (react-dom.production.min.js:279:180)
    at as (react-dom.production.min.js:270:88)
    at ls (react-dom.production.min.js:267:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)

### To Reproduce

1. Go to Admin GUI
2. Click on Kategorien

### Expected behavior

The page for Kategorien (enumerations) opens

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.admin/assets/10330889/a1b903be-51b4-491e-841c-9403bf051d58)

![image](https://github.com/ioBroker/ioBroker.admin/assets/10330889/cfe3f4ce-1188-4275-b527-2c632bcd57df)

### Adapter version

iobroker.admin@6.17.14

### js-controller version

5.0.19

### Node version

v18.20.2

### Operating system

Debian GNU/Linux 12 (bookworm)

**Comment by DennisGeorge77** [comment]
Similar bug:
TypeError: Cannot read properties of undefined (reading 'common')
    at c.getObjectName (https://<FQDN-Hostname>/static/js/697.9827b071.chunk.js:1:316318)
    at $.onAfterSelect (https://<FQDN-Hostname>/static/js/858.5e2098e7.chunk.js:1:35629)
    at https://<FQDN-Hostname>/static/js/858.5e2098e7.chunk.js:1:34847
    at $.expandAllSelected (https://<FQDN-Hostname>/static/js/858.5e2098e7.chunk.js:1:35338)
    at $.<anonymous> (https://<FQDN-Hostname>/static/js/858.5e2098e7.chunk.js:1:34819)
    at Wa (https://<FQDN-Hostname>/static/js/5096.3a6e8bdb.chunk.js:2:59136)
    at ki (https://<FQDN-Hostname>/static/js/5096.3a6e8bdb.chunk.js:2:101295)
    at bi (https://<FQDN-Hostname>/static/js/5096.3a6e8bdb.chunk.js:2:100863)
    at bi (https://<FQDN-Hostname>/static/js/5096.3a6e8bdb.chunk.js:2:100761)
    at yi (https://<FQDN-Hostname>/static/js/5096.3a6e8bdb.chunk.js:2:100399)
    at https://<FQDN-Hostname>/static/js/5096.3a6e8bdb.chunk.js:2:112236
    at ws (https://<FQDN-Hostname>/static/js/5096.3a6e8bdb.chunk.js:2:112751)
    at ls (https://<FQDN-Hostname>/static/js/5096.3a6e8bdb.chunk.js:2:105209)
    at S (https://<FQDN-Hostname>/static/js/5096.3a6e8bdb.chunk.js:2:131248)
    at MessagePort.T (https://<FQDN-Hostname>/static/js/5096.3a6e8bdb.chunk.js:2:131782)

Error does not occure if I connect locally via IP-Adress. 
On connection through nginx reverse Proxy there is the error.

**Comment by Eistee82** [comment]
same issue on my system
node: v20.14.0
js-controller: 6.0.2
admin: v6.17.14

**Comment by Feuer-sturm** [comment]
@tseroo @Eistee82 please check with current beta version

**Comment by Eistee82** [comment]
@Feuer-sturm bei mir geht es mit dem Admin 7.0.7 wieder.
