### ISSUE TITLE
[bug]: objects can not be opened

### ISSUE THREAD

**Issue by FV1405** [ioBroker/ioBroker.admin#2504]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

when i try to open the objects i get the error message "Error in GUI"

### To Reproduce

iobroker starts normaly, but when i try to open the objects, i get the error-message

### Expected behavior

the program otherwise works normally, the adapters works 

### Screenshots & Logfiles

console from the browser:
console.ts:40 
TypeError: Cannot read properties of undefined (reading 'common')
    at c.getObjectName (Utils.tsx:156:36)
    at $.onAfterSelect (ObjectBrowser.tsx:3028:29)
    at ObjectBrowser.tsx:2975:55
    at $.expandAllSelected (ObjectBrowser.tsx:3011:19)
    at $.<anonymous> (ObjectBrowser.tsx:2975:26)
    at Wa (react-dom.production.min.js:156:189)
    at ki (react-dom.production.min.js:260:422)
    at bi (react-dom.production.min.js:259:446)
    at bi (react-dom.production.min.js:259:343)
    at yi (react-dom.production.min.js:258:431)
    at react-dom.production.min.js:282:96
    at ws (react-dom.production.min.js:280:398)
    at ls (react-dom.production.min.js:269:269)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)

### Adapter version

v7.01

### js-controller version

6.0.5-alpha.0-20240616-34d893b36 (same problem with 6.0.5

### Node version

v18.20.3

### Operating system

Linux (docker)

### Additional context

I don't know the reason, I hope for help
Thank you

**Comment by mcm1957** [comment]
Seems to be duplicate 

Admin 7.0.1 gas been revoked too. Please downgrade to currentvLATEST (6.x.x)

**Comment by FV1405** [comment]
Thank you, thats the problem!! It works again!!

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.admin/issues/2503
