### ISSUE TITLE
Error in GUI!: 

### ISSUE THREAD

**Issue by kd19vd** [ioBroker/ioBroker.admin#2509]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

No idea

### To Reproduce

no idea

### Expected behavior

don't remember

### Screenshots & Logfiles

console.ts:40 
TypeError: Cannot read properties of null (reading 'find')
    at tt.renderChart (ObjectChart.tsx:1160:42)
    at tt.render (ObjectChart.tsx:1448:23)
    at Po (react-dom.production.min.js:204:189)
    at No (react-dom.production.min.js:203:149)
    at Ei (react-dom.production.min.js:292:172)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at us (react-dom.production.min.js:271:88)
    at ss (react-dom.production.min.js:273:300)
    at Hl (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:283:470
    at Ss (react-dom.production.min.js:281:398)
    at as (react-dom.production.min.js:270:269)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)

﻿

### Adapter version

6.17.6

### js-controller version

5.0.19

### Node version

18.17.1

### Operating system

Linux (Raspberry 4)

### Additional context

![err](https://github.com/ioBroker/ioBroker.admin/assets/79649117/b56e41d0-e7db-4de7-a0d2-fa0fb23b2f32)

**Comment by GermanBluefox** [comment]
Fixed in 7.0.2

**Comment by Feuer-sturm** [comment]
@kd19vd please check with current beta version

**Comment by kd19vd** [comment]
I tested it with 7.07. I didn't notice any further crashes by changing values of manuell generated variables.
