### ISSUE TITLE
[bug]: nach Update auf 7.0.2 kein alias auswählbar

### ISSUE THREAD

**Issue by m-s-b** [ioBroker/ioBroker.admin#2522]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Nach dem Update auf 7.0.2 ist es wieder nicht möglich einen Alias Quelldatenpunkt auszuwählen.
Eintragen des des Datenpunktes per copy and paste geht.

### To Reproduce

Alias anlegen, auf die drei Punkte zur Auswahl des Quell-Datenpunktes klicken und die GUI ist hinüber.

### Expected behavior

Auswahl wie üblich auch durch auswählen.

### Screenshots & Logfiles

TypeError: Cannot read properties of undefined (reading 'palette')
    at Array.cellIdIconFolder (ObjectBrowser.js:248:22)
    at u.getStyle (Utils.js:1580:44)
    at pt.render (ObjectBrowser.js:5315:51)
    at No (react-dom.production.min.js:203:189)
    at zo (react-dom.production.min.js:202:149)
    at xi (react-dom.production.min.js:291:172)
    at bs (react-dom.production.min.js:279:389)
    at vs (react-dom.production.min.js:279:320)
    at gs (react-dom.production.min.js:279:180)
    at as (react-dom.production.min.js:270:88)
    at is (react-dom.production.min.js:272:300)
    at Hl (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:266:273

### Adapter version

7.0.2

### js-controller version

6.0.5

### Node version

20.15.0

### Operating system

Debian 12

**Comment by Feuer-sturm** [comment]
@m-s-b please check with current beta version

**Comment by m-s-b** [comment]
@Feuer-sturm 
Mit 7.0.7 läuft es wieder. (Ical hatte die gleichen Probleme, läuft mit der Version aber auch wieder)
@GermanBluefox 
Thx !
