### ISSUE TITLE
[bug]: error in gui

### ISSUE THREAD

**Issue by Felix100000** [ioBroker/ioBroker.admin#2524]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Bei dem Awtrix light Adapter lassen sich keine Objekte im iOBroker hinzufügen. Wird hinzufügen angewählt, dann erscheint die Fehlermeldung: ERROR in GUI

### To Reproduce

siehe oben

### Expected behavior

...

### Screenshots & Logfiles

console.ts:40 TypeError: Cannot read properties of undefined (reading 'palette')
    at Array.cellIdIconFolder (ObjectBrowser.js:248:22)
    at u.getStyle (Utils.js:1580:44)
    at pt.render (ObjectBrowser.js:5315:51)
    at No (react-dom.production.min.js:203:189)
    at zo (react-dom.production.min.js:202:149)
    at xi (react-dom.production.min.js:291:172)
    at bs (react-dom.production.min.js:279:389)
    at vs (react-dom.production.min.js:279:320)
    at gs (react-dom.production.min.js:279:180)
    at as (react-dom.production.min.js:270:88)
    at is (react-dom.production.min.js:272:300)
    at Hl (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:266:273

### Adapter version

awtrix-light v1.2.1

### js-controller version

v18.19.0

### Node version

v18.19.0

### Operating system

linux

**Comment by mcm1957** [comment]
@Felix100000 
Please add version of ADMIN Adapter
Please add version of js-controller (18.19.0 is a node version)

**Comment by Felix100000** [comment]
version ADMIN Adapter: 7.0.2
version of js-controller: 6.0.5

**Comment by GermanBluefox** [comment]
Please retest with 7.0.5

**Comment by Felix100000** [comment]
Can you help me? I haven't figured out how to update the adapter.

**Comment by Feuer-sturm** [comment]
@Felix100000 please check with current admin beta version
