### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by passuff** [ioBroker/ioBroker.admin#2534]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

batch change of multiple objects for lovelace does not work. chrome shows an error message. 

### To Reproduce

1. select multipe objects 
2. Edit custom config (for all items at once)
3. click "enabled" for lovelace

### Expected behavior

batch change settings for all selected objects

### Screenshots & Logfiles

TypeError: Cannot read properties of undefined (reading 'toString')
    at ConfigText.tsx:95:77
    at Array.map (<anonymous>)
    at C.renderItem (ConfigText.tsx:95:50)
    at C.render (ConfigGeneric.tsx:960:35)
    at No (react-dom.production.min.js:203:189)
    at zo (react-dom.production.min.js:202:149)
    at xi (react-dom.production.min.js:291:172)
    at bs (react-dom.production.min.js:279:389)
    at vs (react-dom.production.min.js:279:320)
    at gs (react-dom.production.min.js:279:180)
    at as (react-dom.production.min.js:270:88)
    at is (react-dom.production.min.js:272:300)
    at Hl (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:282:470
    at ws (react-dom.production.min.js:280:398)
    at ls (react-dom.production.min.js:269:269)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)

### Adapter version

6.17

### js-controller version

6.0.5

### Node version

v18.20.3

### Operating system

Debian

**Comment by foxriver76** [comment]
fixed with 7.0.9
