### ISSUE TITLE
[bug]: Error in GUI (iQontrol 

### ISSUE THREAD

**Issue by BenjaminK87** [ioBroker/ioBroker.admin#2545]
### No existing issues.

- [x] There is no existing issue for my problem.

### Describe the bug

TypeError: this.state.value.map is not a function
    at je.renderItem (ConfigTable.tsx:948:57)
    at je.render (ConfigGeneric.tsx:1009:35)
    at No (react-dom.production.min.js:203:189)
    at zo (react-dom.production.min.js:202:149)
    at xi (react-dom.production.min.js:291:172)
    at bs (react-dom.production.min.js:279:389)
    at vs (react-dom.production.min.js:279:320)
    at gs (react-dom.production.min.js:279:180)
    at as (react-dom.production.min.js:270:88)
    at ls (react-dom.production.min.js:267:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)

TypeError: this.state.value.map is not a function
    at je.renderItem (http://lausi-iob:8081/static/js/1430.5f43eaf6.chunk.js:1:175279)
    at je.render (http://lausi-iob:8081/static/js/1430.5f43eaf6.chunk.js:1:35591)
    at No (http://lausi-iob:8081/static/js/5096.3a6e8bdb.chunk.js:2:77892)
    at zo (http://lausi-iob:8081/static/js/5096.3a6e8bdb.chunk.js:2:77688)
    at xi (http://lausi-iob:8081/static/js/5096.3a6e8bdb.chunk.js:2:121220)
    at bs (http://lausi-iob:8081/static/js/5096.3a6e8bdb.chunk.js:2:109361)
    at vs (http://lausi-iob:8081/static/js/5096.3a6e8bdb.chunk.js:2:109289)
    at gs (http://lausi-iob:8081/static/js/5096.3a6e8bdb.chunk.js:2:109152)
    at as (http://lausi-iob:8081/static/js/5096.3a6e8bdb.chunk.js:2:105932)
    at ls (http://lausi-iob:8081/static/js/5096.3a6e8bdb.chunk.js:2:104483)
    at S (http://lausi-iob:8081/static/js/5096.3a6e8bdb.chunk.js:2:131248)
    at MessagePort.T (http://lausi-iob:8081/static/js/5096.3a6e8bdb.chunk.js:2:131782)

### To Reproduce

Bei machen Objekten funktioniert das aktivieren der Custom Settings nicht.

Auf das Zahnrad klicken und anschließen bei "Einstellungen iqontrol.0" den Haken bei "Aktiviert" setzen.

### Expected behavior

Die Einstellungen sollten geöffnet werden.

### Screenshots & Logfiles

Hier möglich 
![image](https://github.com/ioBroker/ioBroker.admin/assets/33461354/4f8b5c49-9f8f-4510-aaa8-50774ed542de)

Hier nicht möglich
![image](https://github.com/ioBroker/ioBroker.admin/assets/33461354/2dab0e0f-5779-4666-b9f0-bac678ebbb15)
![image](https://github.com/ioBroker/ioBroker.admin/assets/33461354/edd2b6fd-a89e-4908-9cc4-826d4ff35e1c)

### Adapter version

7.0.12

### js-controller version

5.0.19

### Node version

20.15.1

### Operating system

Windows

**Comment by GermanBluefox** [comment]
Please try with 7.0.16

**Comment by BenjaminK87** [comment]
You fixed it 👍
