### ISSUE TITLE
[bug]: Absturz beim öffnen der Kategorien

### ISSUE THREAD

**Issue by funcarv3r** [ioBroker/ioBroker.admin#2571]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Servus,

ich habe IOBroker Admin 6.17.14 installiert, wenn ich die Kategorien und Aufzählungen öffnen möchte stürzt IOBroker ab. Das Problem ist reproduzierbar.  Ein weiterer IOBroker mit NodeJS v18.20.3 läuft fehlerfrei.

### To Reproduce

1. Admin anmeldung
2. klick auf Kategorie
3. absturz

### Expected behavior

.

### Screenshots & Logfiles

TypeError: Cannot read properties of undefined (reading 'desc')
    at y.render (EnumBlock.tsx:405:37)
    at No (react-dom.production.min.js:203:189)
    at zo (react-dom.production.min.js:202:149)
    at xi (react-dom.production.min.js:291:172)
    at bs (react-dom.production.min.js:279:389)
    at vs (react-dom.production.min.js:279:320)
    at gs (react-dom.production.min.js:279:180)
    at as (react-dom.production.min.js:270:88)
    at ls (react-dom.production.min.js:267:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128

### Adapter version

6.17.14

### js-controller version

5.0.19

### Node version

v18.20.4

### Operating system

Debian 12

**Comment by mcm1957** [comment]
Please check with current beta release (6.17.18)

**Comment by funcarv3r** [comment]
can you tell me how to install 6.17.18?

I only find version 7.x.x

**Comment by mcm1957** [comment]
Sorry, I referrred to 7.17.18.
But in meantime 7.17.19 has been released.

**Comment by funcarv3r** [comment]
ok, thanks. i seams to be 7.0.18 an 7.0.19 resolve the problem. 

When IOBroker Admin 7 goes to stable release?
