### ISSUE TITLE
[bug]: Error in GUI

### ISSUE THREAD

**Issue by loki-sft** [ioBroker/ioBroker.admin#2599]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

`TypeError: Cannot read properties of undefined (reading 'name')
    at C.renderBig (DeviceCard.tsx:455:67)
    at C.render (DeviceCard.tsx:522:21)
    at No (react-dom.production.min.js:203:189)
    at zo (react-dom.production.min.js:202:149)
    at xi (react-dom.production.min.js:291:172)
    at bs (react-dom.production.min.js:279:389)
    at vs (react-dom.production.min.js:279:320)
    at gs (react-dom.production.min.js:279:180)
    at as (react-dom.production.min.js:270:88)
    at ls (react-dom.production.min.js:267:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)`

### To Reproduce

Go to instance settings: hm-rpc.0
Go to Device Manager
Click in 3 Dots for 1. Device

### Expected behavior

see more options for Device

### Screenshots & Logfiles

`TypeError: Cannot read properties of undefined (reading 'name')
    at C.renderBig (DeviceCard.tsx:455:67)
    at C.render (DeviceCard.tsx:522:21)
    at No (react-dom.production.min.js:203:189)
    at zo (react-dom.production.min.js:202:149)
    at xi (react-dom.production.min.js:291:172)
    at bs (react-dom.production.min.js:279:389)
    at vs (react-dom.production.min.js:279:320)
    at gs (react-dom.production.min.js:279:180)
    at as (react-dom.production.min.js:270:88)
    at ls (react-dom.production.min.js:267:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)`

### Adapter version

1.17.0

### js-controller version

6.0.9

### Node version

18.18.2

### Operating system

linux

**Comment by foxriver76** [comment]
Which adapter version? The one posted makes no sense.

**Comment by mcm1957** [comment]
1.17.0 seems to refer to stable hm-rp

**Comment by loki-sft** [comment]
HEy Guys, 
Admin Version ist 7.0.22   
its the latest ioBroker is offering me
HomeMatic ReGaHSS is 4.0.0  and HomeMatic RPC is 1.17.0  
No other updates available for any adapter.

**Comment by mcm1957** [comment]
7.0.23 ist at least now available at LATEST repository.
Please select LATEST repo and press "nach Updates suchen"

**Comment by Feuer-sturm** [comment]
@loki-sft please check if this issue is fixed can be close

**Comment by loki-sft** [comment]
Can be closed. It's fixed.
