### ISSUE TITLE
Error in GUI if I tab on "Files"

### ISSUE THREAD

**Issue by Triumpator** [ioBroker/ioBroker.admin#2604]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Minified React error #62
The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX.

### To Reproduce

if i want to create a map the error occurs

### Expected behavior

if i want to create a map the error occurs

### Screenshots & Logfiles

Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 8
    S scheduler.production.min.js:13
    T scheduler.production.min.js:14
    86955 scheduler.production.min.js:14
    Webpack 18

### Adapter version

7.0.18

### js-controller version

6.0.10

### Node version

18.20.4

### Operating system

linux

**Comment by foxriver76** [comment]
> if i want to create a map the error occurs

I don't get what you mean by creating a map?

**Comment by atmega328p1** [comment]
i uploaded a png file  and i got the same error

**Comment by mcm1957** [comment]
What are you trying to do when this error occures?

Coe reads 'occured in the github install dialog*. Do you try to install an adapter from github? If yes please provide link.

**Comment by Triumpator** [comment]
Now all I have to do is clicking on “Files”.

The first time I realized the error, I wanted to rename an uploaded file.

 

Regards, Thomas

 

 

Von: Martin M. ***@***.***> 
Gesendet: Samstag, 10. August 2024 18:25
An: ioBroker/ioBroker.admin ***@***.***>
Cc: Triumpator ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.admin] Error in GUI if I tab on "Files" (Issue #2604)

 

What are you trying to do when this error occures?

Coe reads 'occured in the github install dialog*. Do you try to install an adapter from github? If yes please provide link.

**Comment by mcm1957** [comment]
Where in admin adapter do you upload files? 
Please post a Screenshot showing wäre you select files.

**Comment by Triumpator** [comment]
Von: atmega328p1 ***@***.***> 
Gesendet: Samstag, 10. August 2024 18:16
An: ioBroker/ioBroker.admin ***@***.***>
Cc: Triumpator ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.admin] Error in GUI if I tab on "Files" (Issue #2604)

 

bug.PNG (view on web) <https://github.com/user-attachments/assets/b9560f50-40ac-4551-b91d-dc86a5e1dd1c>  i uploaded a png file and i got the same error

**Comment by mcm1957** [comment]
Where at admin (!) Do you upload a file?
Please Show a Screenshot BEFORE you Start the Action casting the error. I would like to see the admin Window - not the window showing the error text.

**Comment by atmega328p1** [comment]
Hi Sir

 

  does this help?

 

Shall we do netmeeting vi ateams?

 

Br

Thorsten Fricke

 

 



 

 

 

 

Von: Martin M. ***@***.***> 
Gesendet: Sonntag, 11. August 2024 07:48
An: ioBroker/ioBroker.admin ***@***.***>
Cc: atmega328p1 ***@***.***>; Comment ***@***.***>
Betreff: Re: [ioBroker/ioBroker.admin] Error in GUI if I tab on "Files" (Issue #2604)

 

Where at admin (!) Do you upload a file?
Please Show a Screenshot BEFORE you Start the Action casting the error. I would like to see the admin Window - not the window showing the error text.

**Comment by mcm1957** [comment]
I do not see an answer to my last questions:

Where at admin (!) Do you upload a file?
Please Show a Screenshot BEFORE you Start the Action casting the error. I would like to see the admin Window - not the window showing the error text.

Feel free to provide a screenshot video if easier for you. 

Currently I do not have any idea what you are doing and if you even are using admin UI or have problem with some other software part, i.e. while configuring an adapter.

So please describe the compelet steps to reproduce the problem:, i.e.

- open ioBroker admin
- select xxxx
- click on xxx
- xxx

And please post a screenshot of the iobroker page where you start the upload BEFORE the crash.

**Comment by atmega328p1** [comment]
Hi

 

It can also be that  the mistake  was that i uploaded a png file manually with filezilla

Afterwards  i change the group and user rights   to iobroker:iobroker

 

Pls try this at first!

 

 

I think it must be always be done with the gui or with special iobroker command.  Right?

 

 

 

 

Von: Martin M. ***@***.***> 
Gesendet: Sonntag, 11. August 2024 11:52
An: ioBroker/ioBroker.admin ***@***.***>
Cc: atmega328p1 ***@***.***>; Comment ***@***.***>
Betreff: Re: [ioBroker/ioBroker.admin] Error in GUI if I tab on "Files" (Issue #2604)

 

I do not see an answer to my last questions:

Where at admin (!) Do you upload a file?
Please Show a Screenshot BEFORE you Start the Action casting the error. I would like to see the admin Window - not the window showing the error text.

Feel free to provide a screenshot video if easier for you.

Currently I do not have any idea what you are doing and if you even are using admin UI or have problem with some other software part, i.e. while configuring an adapter.

So please describe the compelet steps to reproduce the problem:, i.e.

*	open ioBroker admin
*	select xxxx
*	click on xxx
*	xxx

And please post a screenshot of the iobroker page where you start the upload BEFORE the crash.

**Comment by atmega328p1** [comment]
Another thing is 

On that affected pi  i cant install  node red !  i have to ack the disclaimer  but  i cant. It is not active

 



 

The button is there but not active, thats  why snippet does not copy it

 

On another iobroker  it is working

 

 

Von: Martin M. ***@***.***> 
Gesendet: Sonntag, 11. August 2024 11:52
An: ioBroker/ioBroker.admin ***@***.***>
Cc: atmega328p1 ***@***.***>; Comment ***@***.***>
Betreff: Re: [ioBroker/ioBroker.admin] Error in GUI if I tab on "Files" (Issue #2604)

 

I do not see an answer to my last questions:

Where at admin (!) Do you upload a file?
Please Show a Screenshot BEFORE you Start the Action casting the error. I would like to see the admin Window - not the window showing the error text.

Feel free to provide a screenshot video if easier for you.

Currently I do not have any idea what you are doing and if you even are using admin UI or have problem with some other software part, i.e. while configuring an adapter.

So please describe the compelet steps to reproduce the problem:, i.e.

*	open ioBroker admin
*	select xxxx
*	click on xxx
*	xxx

And please post a screenshot of the iobroker page where you start the upload BEFORE the crash.

**Comment by mcm1957** [comment]
Where did you upload files too??? And why???

If you tried to write files into iobroker files area (/opt/iobroker/...) this is definitly no action you should have done. This might have destroyed you installation. As this is definitly no bug at admin, I suggest to open a Issue at https://forum.iobroker.net and describe what you have done. Maybe you will get help to try to repair the installation there.

And ony again (last time):

Where at admin (!) Do you upload a file?
Please Show a Screenshot BEFORE you Start the Action casting the error. I would like to see the admin Window - not the window showing the error text.

Feel free to provide a screenshot video if easier for you.

Currently I do not have any idea what you are doing and if you even are using admin UI or have problem with some other software part, i.e. while configuring an adapter.

**So please describe the compelet steps to reproduce the problem:, i.e.

*	open ioBroker admin
*	select xxxx
*	click on xxx
*	xxx

And please post a screenshot of the iobroker page where you start the upload BEFORE the crash.**

Without this information I will not spoent more time guessing in which situation you get the error.

**Comment by Triumpator** [comment]
Sorry that I cannot answer to your convenience in this moment. I catched a flu and laying in bed. Please give me a week, so I will answering to all your questions.Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: "Martin M." ***@***.***> Datum: 11.08.24  12:09  (GMT+01:00) An: "ioBroker/ioBroker.admin" ***@***.***> Cc: Triumpator ***@***.***>, Author ***@***.***> Betreff: Re: [ioBroker/ioBroker.admin] Error in GUI if I tab on "Files" (Issue
  #2604) 
Where did you upload files too??? And why???
If you tried to write files into iobroker files area (/opt/iobroker/...) this is definitly no action you should have done. This might have destroyed you installation. As this is definitly no bug at admin, I suggest to open a Issue at https://forum.iobroker.net and describe what you have done. Maybe you will get help to try to repair the installation there.
And ony again (last time):
Where at admin (!) Do you upload a file?
Please Show a Screenshot BEFORE you Start the Action casting the error. I would like to see the admin Window - not the window showing the error text.
Feel free to provide a screenshot video if easier for you.
Currently I do not have any idea what you are doing and if you even are using admin UI or have problem with some other software part, i.e. while configuring an adapter.
**So please describe the compelet steps to reproduce the problem:, i.e.

open ioBroker admin
select xxxx
click on xxx
xxx

And please post a screenshot of the iobroker page where you start the upload BEFORE the crash.**
Without this information I will not spoent more time guessing in which situation you get the error.

**Comment by atmega328p1** [comment]
Hi Sir,

 

I got the same error again.

 

I uploaded  this png    at   own user    files.

 

Maybe the png file has a invalid format.

 

Good luck

 

Br

th

 



 

 

 

 

 

 

 

 

Von: Martin M. ***@***.***> 
Gesendet: Sonntag, 11. August 2024 12:09
An: ioBroker/ioBroker.admin ***@***.***>
Cc: atmega328p1 ***@***.***>; Comment ***@***.***>
Betreff: Re: [ioBroker/ioBroker.admin] Error in GUI if I tab on "Files" (Issue #2604)

 

Where did you upload files too??? And why???

If you tried to write files into iobroker files area (/opt/iobroker/...) this is definitly no action you should have done. This might have destroyed you installation. As this is definitly no bug at admin, I suggest to open a Issue at https://forum.iobroker.net and describe what you have done. Maybe you will get help to try to repair the installation there.

And ony again (last time):

Where at admin (!) Do you upload a file?
Please Show a Screenshot BEFORE you Start the Action casting the error. I would like to see the admin Window - not the window showing the error text.

Feel free to provide a screenshot video if easier for you.

Currently I do not have any idea what you are doing and if you even are using admin UI or have problem with some other software part, i.e. while configuring an adapter.

**So please describe the compelet steps to reproduce the problem:, i.e.

*	open ioBroker admin
*	select xxxx
*	click on xxx
*	xxx

And please post a screenshot of the iobroker page where you start the upload BEFORE the crash.**

Without this information I will not spoent more time guessing in which situation you get the error.

**Comment by atmega328p1** [comment]
This is the position

 

 

 

Von: Martin M. ***@***.***> 
Gesendet: Sonntag, 11. August 2024 12:09
An: ioBroker/ioBroker.admin ***@***.***>
Cc: atmega328p1 ***@***.***>; Comment ***@***.***>
Betreff: Re: [ioBroker/ioBroker.admin] Error in GUI if I tab on "Files" (Issue #2604)

 

Where did you upload files too??? And why???

If you tried to write files into iobroker files area (/opt/iobroker/...) this is definitly no action you should have done. This might have destroyed you installation. As this is definitly no bug at admin, I suggest to open a Issue at https://forum.iobroker.net and describe what you have done. Maybe you will get help to try to repair the installation there.

And ony again (last time):

Where at admin (!) Do you upload a file?
Please Show a Screenshot BEFORE you Start the Action casting the error. I would like to see the admin Window - not the window showing the error text.

Feel free to provide a screenshot video if easier for you.

Currently I do not have any idea what you are doing and if you even are using admin UI or have problem with some other software part, i.e. while configuring an adapter.

**So please describe the compelet steps to reproduce the problem:, i.e.

*	open ioBroker admin
*	select xxxx
*	click on xxx
*	xxx

And please post a screenshot of the iobroker page where you start the upload BEFORE the crash.**

Without this information I will not spoent more time guessing in which situation you get the error.

**Comment by Triumpator** [comment]
Hello Martin.

I´m on the road again and will dicribe all my steps.

*	Open firefox browser (I tried Edge and Chrome with the same result)
*	Open vis2 (192.168.xxx.174:8082)
*	In the basics-chapter I choosed „Image“
*	I tapped on the three points (source)
*	I uploaded a file
*	I opend a new tab in firefox with the adminskin of iobroker (193.168.xxx.174:8081). Reason ist o rename the just uploaded file.
*	On the right side I tapped on „files“
*	Voila, approx. 2 seconds later I get the above errorscreen

 

Regards, Thomas

Von: Martin M. ***@***.***> 
Gesendet: Sonntag, 11. August 2024 12:09
An: ioBroker/ioBroker.admin ***@***.***>
Cc: Triumpator ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.admin] Error in GUI if I tab on "Files" (Issue #2604)

 

Where did you upload files too??? And why???

If you tried to write files into iobroker files area (/opt/iobroker/...) this is definitly no action you should have done. This might have destroyed you installation. As this is definitly no bug at admin, I suggest to open a Issue at https://forum.iobroker.net and describe what you have done. Maybe you will get help to try to repair the installation there.

And ony again (last time):

Where at admin (!) Do you upload a file?
Please Show a Screenshot BEFORE you Start the Action casting the error. I would like to see the admin Window - not the window showing the error text.

Feel free to provide a screenshot video if easier for you.

Currently I do not have any idea what you are doing and if you even are using admin UI or have problem with some other software part, i.e. while configuring an adapter.

**So please describe the compelet steps to reproduce the problem:, i.e.

*	open ioBroker admin
*	select xxxx
*	click on xxx
*	xxx

And please post a screenshot of the iobroker page where you start the upload BEFORE the crash.**

Without this information I will not spoent more time guessing in which situation you get the error.

**Comment by atmega328p1** [comment]
Super!

 

Von: Triumpator ***@***.***> 
Gesendet: Dienstag, 20. August 2024 21:11
An: ioBroker/ioBroker.admin ***@***.***>
Cc: atmega328p1 ***@***.***>; Comment ***@***.***>
Betreff: Re: [ioBroker/ioBroker.admin] Error in GUI if I tab on "Files" (Issue #2604)

 

Hello Martin. 

I´m on the road again and will dicribe all my steps. 

* Open firefox browser (I tried Edge and Chrome with the same result) 
* Open vis2 (192.168.xxx.174:8082) 
* In the basics-chapter I choosed „Image“ 
* I tapped on the three points (source) 
* I uploaded a file 
* I opend a new tab in firefox with the adminskin of iobroker (193.168.xxx.174:8081). Reason ist o rename the just uploaded file. 
* On the right side I tapped on „files“ 
* Voila, approx. 2 seconds later I get the above errorscreen 



Regards, Thomas 

Von: Martin M. ***@***.*** <mailto:***@***.***> > 
Gesendet: Sonntag, 11. August 2024 12:09 
An: ioBroker/ioBroker.admin ***@***.*** <mailto:***@***.***> > 
Cc: Triumpator ***@***.*** <mailto:***@***.***> >; Author ***@***.*** <mailto:***@***.***> > 
Betreff: Re: [ioBroker/ioBroker.admin] Error in GUI if I tab on "Files" (Issue #2604) 



Where did you upload files too??? And why??? 

If you tried to write files into iobroker files area (/opt/iobroker/...) this is definitly no action you should have done. This might have destroyed you installation. As this is definitly no bug at admin, I suggest to open a Issue at https://forum.iobroker.net and describe what you have done. Maybe you will get help to try to repair the installation there. 

And ony again (last time): 

Where at admin (!) Do you upload a file? 
Please Show a Screenshot BEFORE you Start the Action casting the error. I would like to see the admin Window - not the window showing the error text. 

Feel free to provide a screenshot video if easier for you. 

Currently I do not have any idea what you are doing and if you even are using admin UI or have problem with some other software part, i.e. while configuring an adapter. 

**So please describe the compelet steps to reproduce the problem:, i.e. 

* open ioBroker admin 
* select xxxx 
* click on xxx 
* xxx 

And please post a screenshot of the iobroker page where you start the upload BEFORE the crash.** 

Without this information I will not spoent more time guessing in which situation you get the error.

**Comment by mcm1957** [comment]
Please avoid sending EMAILS but go to GitHub website and insert info at website.

Input per mail is nearly unreadable.

**Comment by Triumpator** [comment]
Hello.

I think you need the error message on the console of developer (F12) too.

 

Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

    React 8

    S scheduler.production.min.js:13

    T scheduler.production.min.js:14

 

 

Mit freundlichen Grüßen aus Niederlangen

 

Thomas Wegener

Kapellenmoorstraße 9

49779 Niederlangen

+49.5933.6466201

+49.173.5405448

 

 

 

 

 

Von: atmega328p1 ***@***.***> 
Gesendet: Dienstag, 20. August 2024 21:46
An: ioBroker/ioBroker.admin ***@***.***>
Cc: Triumpator ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.admin] Error in GUI if I tab on "Files" (Issue #2604)

 

Super! 



Von: Triumpator ***@***.*** <mailto:***@***.***> > 
Gesendet: Dienstag, 20. August 2024 21:11 
An: ioBroker/ioBroker.admin ***@***.*** <mailto:***@***.***> > 
Cc: atmega328p1 ***@***.*** <mailto:***@***.***> >; Comment ***@***.*** <mailto:***@***.***> > 
Betreff: Re: [ioBroker/ioBroker.admin] Error in GUI if I tab on "Files" (Issue #2604) 



Hello Martin. 

I´m on the road again and will dicribe all my steps. 

* Open firefox browser (I tried Edge and Chrome with the same result) 
* Open vis2 (192.168.xxx.174:8082) 
* In the basics-chapter I choosed „Image“ 
* I tapped on the three points (source) 
* I uploaded a file 
* I opend a new tab in firefox with the adminskin of iobroker (193.168.xxx.174:8081). Reason ist o rename the just uploaded file. 
* On the right side I tapped on „files“ 
* Voila, approx. 2 seconds later I get the above errorscreen 



Regards, Thomas 

Von: Martin M. ***@***.*** <mailto:***@***.***>  <mailto:***@***.***> > 
Gesendet: Sonntag, 11. August 2024 12:09 
An: ioBroker/ioBroker.admin ***@***.*** <mailto:***@***.***>  <mailto:***@***.***> > 
Cc: Triumpator ***@***.*** <mailto:***@***.***>  <mailto:***@***.***> >; Author ***@***.*** <mailto:***@***.***>  <mailto:***@***.***> > 
Betreff: Re: [ioBroker/ioBroker.admin] Error in GUI if I tab on "Files" (Issue #2604) 



Where did you upload files too??? And why??? 

If you tried to write files into iobroker files area (/opt/iobroker/...) this is definitly no action you should have done. This might have destroyed you installation. As this is definitly no bug at admin, I suggest to open a Issue at https://forum.iobroker.net and describe what you have done. Maybe you will get help to try to repair the installation there. 

And ony again (last time): 

Where at admin (!) Do you upload a file? 
Please Show a Screenshot BEFORE you Start the Action casting the error. I would like to see the admin Window - not the window showing the error text. 

Feel free to provide a screenshot video if easier for you. 

Currently I do not have any idea what you are doing and if you even are using admin UI or have problem with some other software part, i.e. while configuring an adapter. 

**So please describe the compelet steps to reproduce the problem:, i.e. 

* open ioBroker admin 
* select xxxx 
* click on xxx 
* xxx 

And please post a screenshot of the iobroker page where you start the upload BEFORE the crash.** 

Without this information I will not spoent more time guessing in which situation you get the error.

**Comment by Xandar31** [comment]
Hi,
I have the same error, I guess since the admin update to 7
Any solution for this?

I just want to open the files tab and getting this error:
https://192.168.4.4:8081/#tab-files

```Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ye (https://192.168.4.4:8081/static/js/5096.3a6e8bdb.chunk.js:2:15172)
    at Ko (https://192.168.4.4:8081/static/js/5096.3a6e8bdb.chunk.js:2:86738)
    at ks (https://192.168.4.4:8081/static/js/5096.3a6e8bdb.chunk.js:2:109541)
    at bs (https://192.168.4.4:8081/static/js/5096.3a6e8bdb.chunk.js:2:109422)
    at vs (https://192.168.4.4:8081/static/js/5096.3a6e8bdb.chunk.js:2:109289)
    at gs (https://192.168.4.4:8081/static/js/5096.3a6e8bdb.chunk.js:2:109152)
    at as (https://192.168.4.4:8081/static/js/5096.3a6e8bdb.chunk.js:2:105932)
    at ls (https://192.168.4.4:8081/static/js/5096.3a6e8bdb.chunk.js:2:104483)
    at S (https://192.168.4.4:8081/static/js/5096.3a6e8bdb.chunk.js:2:131248)
    at MessagePort.T (https://192.168.4.4:8081/static/js/5096.3a6e8bdb.chunk.js:2:131782)```


NPM: 10.8.2
js-controller 7.0.3
node.js: v20.18.1
admin: v7.1.5

any ideas?
Thanks

**Comment by mcm1957** [comment]
Please check with current release (7.9.10)

**Comment by atmega328p1** [comment]
thank u that u still think of mebrth--Gesendet mit der GMX Mail AppAm 22.06.26, 18:37 schrieb "Martin M." ***@***.***>:
mcm1957 left a comment (ioBroker/ioBroker.admin#2604)
Please check with current release (7.9.10)

**Comment by mcm1957** [comment]
Well no more feedback - lets close for now.

Please open a new issue if problem still occures with current admin release.
