### ISSUE TITLE
[bug]: Error in GUI!

### ISSUE THREAD

**Issue by Maxim-7777** [ioBroker/ioBroker.admin#2697]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Seit letztem (21.09.2024) Admin update könnte ich nicht auf Admin zugreifen, immer wieder kommt Error in GUI!. Ich weiß nicht, was ich tun soll.

### To Reproduce

open http://iobrokerip:8081

### Expected behavior

---

### Screenshots & Logfiles

**_Log aus CHROM:_**

```
bootstrap.tsx:22 iobroker.admin@7.0.25
socket.io.js:66 [2024-09-22T20:07:19.132Z] Try to connect
bootstrap.tsx:54 
        
        
       POST https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7&sentry_client=sentry.javascript.browser%2F8.30.0 net::ERR_BLOCKED_BY_CLIENT
(anonym) @ fetch.ts:51
(anonym) @ base.ts:78
add @ promisebuffer.ts:49
send @ base.ts:94
sendEnvelope @ baseclient.ts:567
sendSession @ baseclient.ts:376
captureSession @ baseclient.ts:240
Mt @ exports.ts:335
Pt @ exports.ts:353
(anonym) @ sdk.ts:322
jn @ sdk.ts:190
44321 @ bootstrap.tsx:54
t @ bootstrap:19
Promise.then
22210 @ index.tsx:1
t @ bootstrap:19
(anonym) @ startup:4
(anonym) @ main.423e60b6.js:1
11 weitere Frames anzeigen
Weniger anzeigen
App.tsx:1019 Stored version: , new version: 7.1.2
HostsWorker.tsx:55 Connected: true
Intro.tsx:859 Double links: "admin.0" and "admin.0"
IntroCard.tsx:266 Translate: Link
Intro.tsx:1542 Translate: time
Intro.tsx:1542 Translate: timeOffset
Intro.tsx:1561 Translate: _nodeCurrent
Intro.tsx:1561 Translate: _nodeNewest
Intro.tsx:1561 Translate: _nodeNewestNext
Intro.tsx:1561 Translate: _npmCurrent
Intro.tsx:1561 Translate: _npmNewest
Intro.tsx:1561 Translate: _npmNewestNext
App.tsx:2188 
        
        
       POST https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7&sentry_client=sentry.javascript.browser%2F8.30.0 net::ERR_BLOCKED_BY_CLIENT
(anonym) @ fetch.ts:51
(anonym) @ base.ts:78
add @ promisebuffer.ts:49
send @ base.ts:94
sendEnvelope @ baseclient.ts:567
sendSession @ baseclient.ts:376
captureSession @ baseclient.ts:240
Mt @ exports.ts:335
Dt @ exports.ts:314
Rt @ exports.ts:291
(anonym) @ sdk.ts:328
Wt @ handlers.ts:54
Bt.onpopstate @ history.ts:33
doNavigate @ Router.js:74
handleNavigation @ App.tsx:2188
handleNavigation @ App.tsx:3075
onClick @ Drawer.tsx:713
Re @ react-dom.production.min.js:54
Be @ react-dom.production.min.js:54
(anonym) @ react-dom.production.min.js:55
Ir @ react-dom.production.min.js:105
Ur @ react-dom.production.min.js:106
(anonym) @ react-dom.production.min.js:117
ss @ react-dom.production.min.js:273
Le @ react-dom.production.min.js:52
Qr @ react-dom.production.min.js:109
qn @ react-dom.production.min.js:74
$n @ react-dom.production.min.js:73
r @ helpers.ts:98
26 weitere Frames anzeigen
Weniger anzeigen
App.tsx:2188 
        
        
       POST https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7&sentry_client=sentry.javascript.browser%2F8.30.0 net::ERR_BLOCKED_BY_CLIENT
(anonym) @ fetch.ts:51
(anonym) @ base.ts:78
add @ promisebuffer.ts:49
send @ base.ts:94
sendEnvelope @ baseclient.ts:567
sendSession @ baseclient.ts:376
captureSession @ baseclient.ts:240
Mt @ exports.ts:335
Pt @ exports.ts:353
(anonym) @ sdk.ts:329
Wt @ handlers.ts:54
Bt.onpopstate @ history.ts:33
doNavigate @ Router.js:74
handleNavigation @ App.tsx:2188
handleNavigation @ App.tsx:3075
onClick @ Drawer.tsx:713
Re @ react-dom.production.min.js:54
Be @ react-dom.production.min.js:54
(anonym) @ react-dom.production.min.js:55
Ir @ react-dom.production.min.js:105
Ur @ react-dom.production.min.js:106
(anonym) @ react-dom.production.min.js:117
ss @ react-dom.production.min.js:273
Le @ react-dom.production.min.js:52
Qr @ react-dom.production.min.js:109
qn @ react-dom.production.min.js:74
$n @ react-dom.production.min.js:73
r @ helpers.ts:98
25 weitere Frames anzeigen
Weniger anzeigen
App.tsx:2188 
        
        
       POST https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7&sentry_client=sentry.javascript.browser%2F8.30.0 net::ERR_BLOCKED_BY_CLIENT
(anonym) @ fetch.ts:51
(anonym) @ base.ts:78
add @ promisebuffer.ts:49
send @ base.ts:94
sendEnvelope @ baseclient.ts:567
sendSession @ baseclient.ts:376
captureSession @ baseclient.ts:240
Mt @ exports.ts:335
Dt @ exports.ts:314
Rt @ exports.ts:291
(anonym) @ sdk.ts:328
Wt @ handlers.ts:54
Bt.onpopstate @ history.ts:33
doNavigate @ Router.js:74
handleNavigation @ App.tsx:2188
handleNavigation @ App.tsx:3075
onClick @ Drawer.tsx:713
Re @ react-dom.production.min.js:54
Be @ react-dom.production.min.js:54
(anonym) @ react-dom.production.min.js:55
Ir @ react-dom.production.min.js:105
Ur @ react-dom.production.min.js:106
(anonym) @ react-dom.production.min.js:117
ss @ react-dom.production.min.js:273
Le @ react-dom.production.min.js:52
Qr @ react-dom.production.min.js:109
qn @ react-dom.production.min.js:74
$n @ react-dom.production.min.js:73
r @ helpers.ts:98
26 weitere Frames anzeigen
Weniger anzeigen
App.tsx:2188 
        
        
       POST https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7&sentry_client=sentry.javascript.browser%2F8.30.0 net::ERR_BLOCKED_BY_CLIENT
(anonym) @ fetch.ts:51
(anonym) @ base.ts:78
add @ promisebuffer.ts:49
send @ base.ts:94
sendEnvelope @ baseclient.ts:567
sendSession @ baseclient.ts:376
captureSession @ baseclient.ts:240
Mt @ exports.ts:335
Pt @ exports.ts:353
(anonym) @ sdk.ts:329
Wt @ handlers.ts:54
Bt.onpopstate @ history.ts:33
doNavigate @ Router.js:74
handleNavigation @ App.tsx:2188
handleNavigation @ App.tsx:3075
onClick @ Drawer.tsx:713
Re @ react-dom.production.min.js:54
Be @ react-dom.production.min.js:54
(anonym) @ react-dom.production.min.js:55
Ir @ react-dom.production.min.js:105
Ur @ react-dom.production.min.js:106
(anonym) @ react-dom.production.min.js:117
ss @ react-dom.production.min.js:273
Le @ react-dom.production.min.js:52
Qr @ react-dom.production.min.js:109
qn @ react-dom.production.min.js:74
$n @ react-dom.production.min.js:73
r @ helpers.ts:98
25 weitere Frames anzeigen
Weniger anzeigen
Adapters.tsx:580 [ADAPTERS] getAdapters
App.tsx:1657 Error: timeout
    at Connection.ts:1094:28
    at r (helpers.ts:98:17)
(anonym) @ console.ts:40
Za.onNews @ App.tsx:1657
await in Za.onNews
subscribeState @ Connection.ts:694
await in subscribeState
(anonym) @ App.tsx:1226
Promise.then
(anonym) @ App.tsx:1224
r @ helpers.ts:98
setTimeout
(anonym) @ browserapierrors.ts:109
onReady @ App.tsx:1222
await in onReady
doLoadData @ Connection.ts:577
await in doLoadData
loadData @ Connection.ts:500
onPreConnect @ Connection.ts:433
(anonym) @ Connection.ts:319
SocketClient.findAnswer @ socket.io.js:303
socket.onmessage @ socket.io.js:212
8 weitere Frames anzeigen
Weniger anzeigen
console.ts:40 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=%5Bobject%20Error%5D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at va (react-dom.production.min.js:135:60)
    at e (react-dom.production.min.js:145:372)
    at ko (react-dom.production.min.js:191:308)
    at xi (react-dom.production.min.js:293:9)
    at bs (react-dom.production.min.js:279:389)
    at vs (react-dom.production.min.js:279:320)
    at gs (react-dom.production.min.js:279:180)
    at as (react-dom.production.min.js:270:88)
    at ls (react-dom.production.min.js:267:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
(anonym) @ console.ts:40
co @ react-dom.production.min.js:188
a.componentDidCatch.t.callback @ react-dom.production.min.js:189
Wa @ react-dom.production.min.js:156
ki @ react-dom.production.min.js:260
bi @ react-dom.production.min.js:259
yi @ react-dom.production.min.js:258
(anonym) @ react-dom.production.min.js:282
ws @ react-dom.production.min.js:280
ls @ react-dom.production.min.js:269
S @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
12 weitere Frames anzeigen
Weniger anzeigen
Instances.tsx:464 system.adapter.admin.0
Instances.tsx:464 system.adapter.alexa2.0
Instances.tsx:464 system.adapter.awtrix-light.0
Instances.tsx:464 system.adapter.backitup.0
Instances.tsx:464 system.adapter.cloud.0
Instances.tsx:464 system.adapter.daswetter.0
Instances.tsx:464 system.adapter.discovery.0
Instances.tsx:464 system.adapter.dwd.0
Instances.tsx:464 system.adapter.ecovacs-deebot.0
Instances.tsx:464 system.adapter.email.0
Instances.tsx:464 system.adapter.energiefluss.0
Instances.tsx:464 system.adapter.energiefluss-erweitert.0
Instances.tsx:464 system.adapter.evcc.0
Instances.tsx:464 system.adapter.feiertage.0
Instances.tsx:464 system.adapter.fullybrowser.0
Instances.tsx:464 system.adapter.gruenbeck.0
Instances.tsx:464 system.adapter.history.0
Instances.tsx:464 system.adapter.hm-rega.0
Instances.tsx:464 system.adapter.hm-rpc.0
Instances.tsx:464 system.adapter.hm-rpc.1
Instances.tsx:464 system.adapter.hm-rpc.2
Instances.tsx:464 system.adapter.hm-rpc.3
Instances.tsx:464 system.adapter.hoover.0
Instances.tsx:464 system.adapter.ical.0
Instances.tsx:464 system.adapter.ical.1
Instances.tsx:464 system.adapter.icons-icons8.0
Instances.tsx:464 system.adapter.icons-mfd-png.0
Instances.tsx:464 system.adapter.icons-open-icon-library-png.0
Instances.tsx:464 system.adapter.influxdb.0
Instances.tsx:464 system.adapter.influxdb.1
Instances.tsx:464 system.adapter.info.0
Instances.tsx:464 system.adapter.iot.0
Instances.tsx:464 system.adapter.javascript.0
Instances.tsx:253 Translate: map
Instances.tsx:464 system.adapter.luftdaten.0
Instances.tsx:464 system.adapter.mihome-vacuum.0
Instances.tsx:464 system.adapter.mihome-vacuum.1
Instances.tsx:464 system.adapter.mqtt.0
Instances.tsx:464 system.adapter.mqtt.1
Instances.tsx:464 system.adapter.nuki-extended.0
Instances.tsx:464 system.adapter.openweathermap.0
Instances.tsx:464 system.adapter.ring.0
Instances.tsx:464 system.adapter.rpi2.0
Instances.tsx:464 system.adapter.scenes.0
Instances.tsx:464 system.adapter.shelly.0
Instances.tsx:464 system.adapter.shuttercontrol.0
Instances.tsx:464 system.adapter.sonoff.0
Instances.tsx:464 system.adapter.sony-bravia.0
Instances.tsx:464 system.adapter.synology.0
Instances.tsx:464 system.adapter.telegram.0
Instances.tsx:464 system.adapter.telegram.1
Instances.tsx:464 system.adapter.tesla-motors.0
Instances.tsx:464 system.adapter.trashschedule.0
Instances.tsx:464 system.adapter.unifi.0
Instances.tsx:464 system.adapter.viessmannapi.0
Instances.tsx:464 system.adapter.vis.0
Instances.tsx:464 system.adapter.vis-2.0
Instances.tsx:464 system.adapter.vis-2-widgets-energy.0
Instances.tsx:464 system.adapter.vis-2-widgets-gauges.0
Instances.tsx:464 system.adapter.vis-2-widgets-material.0
Instances.tsx:464 system.adapter.vis-bars.0
Instances.tsx:464 system.adapter.vis-canvas-gauges.0
Instances.tsx:464 system.adapter.vis-colorpicker.0
Instances.tsx:464 system.adapter.vis-google-fonts.0
Instances.tsx:464 system.adapter.vis-hqwidgets.0
Instances.tsx:464 system.adapter.vis-icontwo.0
Instances.tsx:464 system.adapter.vis-inventwo.0
Instances.tsx:464 system.adapter.vis-jqui-mfd.0
Instances.tsx:464 system.adapter.vis-justgage.0
Instances.tsx:464 system.adapter.vis-materialdesign.0
Instances.tsx:464 system.adapter.vis-metro.0
Instances.tsx:464 system.adapter.vis-plumb.0
Instances.tsx:464 system.adapter.vis-timeandweather.0
Instances.tsx:464 system.adapter.vis-weather.0
Instances.tsx:464 system.adapter.web.0
Instances.tsx:464 system.adapter.wled.0
Instances.tsx:464 system.adapter.worx.0
Instances.tsx:464 system.adapter.yahka.0
Instances.tsx:464 system.adapter.yahka.1
Instances.tsx:464 system.adapter.zigbee.0
Instances.tsx:468 getInstances: 197
Adapters.tsx:957 [ADAPTERS] getAdaptersInfo
  POST https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7&sentry_client=sentry.javascript.browser%2F8.30.0 net::ERR_BLOCKED_BY_CLIENT
(anonym) @ 6539.0a444811.chunk.js:2
(anonym) @ 6539.0a444811.chunk.js:2
add @ 6539.0a444811.chunk.js:2
send @ 6539.0a444811.chunk.js:2
sendEnvelope @ 6539.0a444811.chunk.js:2
_flushOutcomes @ 6539.0a444811.chunk.js:2
(anonym) @ 6539.0a444811.chunk.js:2

```

**_Log aus FIREFOX:_**

```
Error: timeout
    o Connection.ts:1094
    r helpers.ts:98
    setTimeout handler*78990/tn/< browserapierrors.ts:109
    l Connection.ts:1090
    request Connection.ts:1081
    request AdminConnection.ts:150
    getDiagData AdminConnection.ts:787
    onNews App.tsx:1628
    subscribeState Connection.ts:694
    onReady App.tsx:1226
    promise callback*44321/componentDidMount/onReady/< App.tsx:1224
    r helpers.ts:98
    setTimeout handler*78990/tn/< browserapierrors.ts:109
    onReady App.tsx:1222
    doLoadData Connection.ts:577
    loadData Connection.ts:500
    onPreConnect Connection.ts:433
    startSocket Connection.ts:319
    findAnswer socket.io.js:303
    onmessage socket.io.js:212
    connect socket.io.js:192
    connect socket.io.js:43
    startSocket Connection.ts:278
    h Connection.ts:98
    promise callback*h Connection.ts:98
    d AdminConnection.ts:145
    componentDidMount App.tsx:1000
    React 6
    S scheduler.production.min.js:13
    T scheduler.production.min.js:14
    9336 scheduler.production.min.js:14
    Webpack 18
console.ts:40:19
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=%5Bobject%20Error%5D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 9
    S scheduler.production.min.js:13
    T scheduler.production.min.js:14
    9336 scheduler.production.min.js:14
    Webpack 18
console.ts:40:19
```

### Adapter version

 7.1.2

### js-controller version

6.0.11

### Node version

v20.17.0

### Operating system

Raspberry Pi 4/ Raspbian GNU/Linux 11 (bullseye)

### Additional context

No response

**Comment by foxriver76** [comment]
Fixed in 7.1.3

**Comment by Feuer-sturm** [comment]
@Maxim-7777 please check with admin >= 7.1.3 and if ok please close the issue
