### ISSUE TITLE
[bug]: Cannot find i18n directory

### ISSUE THREAD

**Issue by Brainbug01** [ioBroker/ioBroker.admin#2726]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Core adapters versions
js-controller:  7.0.0-alpha.1-20241001-61327866b
admin:          7.2.0
javascript:     8.8.3

`
admin.0 2024-10-01 16:43:08.776 error Cannot init i18n: Error: Cannot find i18n directory
`

### To Reproduce

-

### Expected behavior

-

### Screenshots & Logfiles

-

### Adapter version

7.2.0

### js-controller version

7.0.0-alpha.1-20241001-61327866b

### Node version

v20.17.0

### Operating system

Linux

**Comment by arteck** [comment]
![grafik](https://github.com/user-attachments/assets/5065ef34-5ca4-4c86-b178-eb0c28bd7a19)

jep here also

**Comment by sonny1985** [comment]
I confirm it too :) Its always in the log , onetime, after a restart :)

**Comment by itProfi** [comment]
Version admin adapter 7.2.1 - same problem
![Скриншот 06-10-2024 105025](https://github.com/user-attachments/assets/8b0c51ed-e65c-4c9f-9c18-38a3debd17eb)
![Скриншот 06-10-2024 104946](https://github.com/user-attachments/assets/d9a475dd-439f-4ac5-a31d-e9bba7cacdd1)

**Comment by sonny1985** [comment]
on 7.2.1 also confirmed here. This Log Error is still present. 
JS Controller 6.0.11

**Comment by Diginix** [comment]
v7.2.1 completely doesn't work for me with this error:

```
2024-10-06 08:32:06.349 - error: admin.0 (3519244) Cannot init i18n: Error: Cannot find i18n directory
2024-10-06 08:32:10.715 - error: admin.0 (3519244) uncaught exception: Parameter "id" needs to be of type "string" but type "number" has been passed
2024-10-06 08:32:10.716 - error: admin.0 (3519244) Error: Parameter "id" needs to be of type "string" but type "number" has been passed
    at Function.assertString (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:238:19)
    at Admin.getSession (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:1373:19)
    at SocketAdmin.__getUserFromSocket (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketAdmin.js:73:33)
    at SocketAdmin._initSocket (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketCommon.js:162:22)
    at /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketCommon.js:104:22
    at /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/ws-server/dist/index.js:246:64
    at Array.forEach (<anonymous>)
    at WebSocketServer.<anonymous> (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/ws-server/dist/index.js:246:50)
    at WebSocketServer.emit (node:events:519:28)
    at WebSocketServer.emit (node:domain:488:12)
2024-10-06 08:32:10.717 - error: admin.0 (3519244) Parameter "id" needs to be of type "string" but type "number" has been passed
2024-10-06 08:32:11.373 - error: host.iobroker Caught by controller[1]: Error: Parameter "id" needs to be of type "string" but type "number" has been passed
2024-10-06 08:32:11.379 - error: host.iobroker Caught by controller[1]:     at Function.assertString (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:238:19)
2024-10-06 08:32:11.379 - error: host.iobroker Caught by controller[1]:     at Admin.getSession (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:1373:19)
2024-10-06 08:32:11.379 - error: host.iobroker Caught by controller[1]:     at SocketAdmin.__getUserFromSocket (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketAdmin.js:73:33)
2024-10-06 08:32:11.379 - error: host.iobroker Caught by controller[1]:     at SocketAdmin._initSocket (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketCommon.js:162:22)
2024-10-06 08:32:11.379 - error: host.iobroker Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketCommon.js:104:22
2024-10-06 08:32:11.379 - error: host.iobroker Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/ws-server/dist/index.js:246:64
2024-10-06 08:32:11.380 - error: host.iobroker Caught by controller[1]:     at Array.forEach (<anonymous>)
2024-10-06 08:32:11.380 - error: host.iobroker Caught by controller[1]:     at WebSocketServer.<anonymous> (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/ws-server/dist/index.js:246:50)
2024-10-06 08:32:11.380 - error: host.iobroker Caught by controller[1]:     at WebSocketServer.emit (node:events:519:28)
2024-10-06 08:32:11.380 - error: host.iobroker Caught by controller[1]:     at WebSocketServer.emit (node:domain:488:12)
2024-10-06 08:32:11.380 - error: host.iobroker instance system.adapter.admin.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
```
Downgrade to 7.2.0 works perfect without any issues or log messages.
node: v20.18.0
js-controller: 6.0.11

**Comment by mcm1957** [comment]
@GermanBluefox 
@foxriver76 

The crash does not look to be directly related to i18n not found. Maybe this comment should be splitted into a new issue ?

**Comment by Apollon77** [comment]
Yes should not he related

**Comment by Eistee82** [comment]
Kann den Fehler bestätigen 7.2.1 funktioniert nicht. Auf 7.2.0 zurück funktioniert admin wieder.

**Comment by Brainbug01** [comment]
@Eistee82 
@Diginix 

Könnte jemand von euch ein Issue für euer Problem anlegen? Hier geht es ja um das i18n Verzeichnis.

**Comment by Diginix** [comment]
> Könnte jemand von euch ein Issue für euer Problem anlegen? Hier geht es ja um das i18n Verzeichnis.

Erledigt: #2737

**Comment by crunchip77** [comment]
mit v7.2.2 auch noch vorhanden
`<html>
<body>

admin.0 | 2024-10-07 08:11:20.838 | error | Cannot init i18n: Error: Cannot find i18n directory
-- | -- | -- | --
admin.0 | 2024-10-07 08:11:20.797 | info | requesting all objects
admin.0 | 2024-10-07 08:11:20.775 | info | starting. Version 7.2.2 in /opt/iobroker/node_modules/iobroker.admin, node: v20.17.0, js-controller: 6.0.11


</body>
</html>`

**Comment by dlehmann69iob** [comment]
kann ich bestätigen
ist mit 7.2.2 noch vorhanden und wird beim neu laden gemeldet
auch mit neuem js-controller 7.0.0

**Comment by dlehmann69iob** [comment]
der Fehler mit i18n kommt mit 7.2.4 nicht mehr vor.

**Comment by Brainbug01** [comment]
Der Fehler ist weg. Dafür ist das dunkle Design nicht mehr richtig. Ist aber ein anderes Problem.

**Comment by mcm1957** [comment]
@Brainbug01 
> Dafür ist das dunkle Design nicht mehr richtig. Ist aber ein anderes Problem.

Dafür mach ggF bitte ein neues Issue auf. Hier im gelcosten (!) Issue fällt die Anmerkung nicht auf.

**Comment by Brainbug01** [comment]
@mcm1957 
Das gibt es schon, sonst hätte ich das gemacht.
