### ISSUE TITLE
[bug]: v7.2.1 restart loop and 7.2.5 REAUTHENTICATE

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.admin#2737]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

v7.2.1 completely doesn't work because of a restart loop

### To Reproduce

update from 7.2.0 to 7.2.1 leads to dead admin instance

### Expected behavior

a working admin UI

### Screenshots & Logfiles

```
2024-10-06 08:32:10.715 - error: admin.0 (3519244) uncaught exception: Parameter "id" needs to be of type "string" but type "number" has been passed
2024-10-06 08:32:10.716 - error: admin.0 (3519244) Error: Parameter "id" needs to be of type "string" but type "number" has been passed
    at Function.assertString (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:238:19)
    at Admin.getSession (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:1373:19)
    at SocketAdmin.__getUserFromSocket (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketAdmin.js:73:33)
    at SocketAdmin._initSocket (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketCommon.js:162:22)
    at /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketCommon.js:104:22
    at /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/ws-server/dist/index.js:246:64
    at Array.forEach (<anonymous>)
    at WebSocketServer.<anonymous> (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/ws-server/dist/index.js:246:50)
    at WebSocketServer.emit (node:events:519:28)
    at WebSocketServer.emit (node:domain:488:12)
2024-10-06 08:32:10.717 - error: admin.0 (3519244) Parameter "id" needs to be of type "string" but type "number" has been passed
2024-10-06 08:32:11.373 - error: host.iobroker Caught by controller[1]: Error: Parameter "id" needs to be of type "string" but type "number" has been passed
2024-10-06 08:32:11.379 - error: host.iobroker Caught by controller[1]:     at Function.assertString (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:238:19)
2024-10-06 08:32:11.379 - error: host.iobroker Caught by controller[1]:     at Admin.getSession (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:1373:19)
2024-10-06 08:32:11.379 - error: host.iobroker Caught by controller[1]:     at SocketAdmin.__getUserFromSocket (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketAdmin.js:73:33)
2024-10-06 08:32:11.379 - error: host.iobroker Caught by controller[1]:     at SocketAdmin._initSocket (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketCommon.js:162:22)
2024-10-06 08:32:11.379 - error: host.iobroker Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketCommon.js:104:22
2024-10-06 08:32:11.379 - error: host.iobroker Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/ws-server/dist/index.js:246:64
2024-10-06 08:32:11.380 - error: host.iobroker Caught by controller[1]:     at Array.forEach (<anonymous>)
2024-10-06 08:32:11.380 - error: host.iobroker Caught by controller[1]:     at WebSocketServer.<anonymous> (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/ws-server/dist/index.js:246:50)
2024-10-06 08:32:11.380 - error: host.iobroker Caught by controller[1]:     at WebSocketServer.emit (node:events:519:28)
2024-10-06 08:32:11.380 - error: host.iobroker Caught by controller[1]:     at WebSocketServer.emit (node:domain:488:12)
2024-10-06 08:32:11.380 - error: host.iobroker instance system.adapter.admin.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
```

### Adapter version

7.2.1

### js-controller version

6.0.11

### Node version

20.18.0

### Operating system

Ubuntu 24

**Comment by schnitzel14** [comment]
Same here.

**Comment by diamand2k22** [comment]
same here, after update, admin adapter don't start

**Comment by MikeRow1972** [comment]
Error still exist in 7.2.2 

error: admin.0 (1566) Parameter "id" needs to be of type "string" but type "number" has been passed

**Comment by m-s-b** [comment]
7.2.2 still not working
`2024-10-07 06:44:39.985  - error: admin.3 (3921815) Cannot init i18n: Error: Cannot find i18n directory
2024-10-07 06:44:40.020  - error: admin.0 (3921813) Cannot init i18n: Error: Cannot find i18n directory
2024-10-07 06:44:49.141  - error: admin.0 (3921813) uncaught exception: Parameter "id" needs to be of type "string" but type "number" has been passed
2024-10-07 06:44:49.142  - error: admin.0 (3921813) Error: Parameter "id" needs to be of type "string" but type "number" has been passed
    at Function.assertString (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:238:19)
    at Admin.getSession (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:1373:19)
    at SocketAdmin.__getUserFromSocket (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketAdmin.js:73:33)
    at SocketAdmin._initSocket (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketCommon.js:162:22)
    at /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketCommon.js:104:22
    at /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/ws-server/dist/index.js:246:64
    at Array.forEach (<anonymous>)
    at WebSocketServer.<anonymous> (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/ws-server/dist/index.js:246:50)
    at WebSocketServer.emit (node:events:519:28)
    at WebSocketServer.emit (node:domain:488:12)
2024-10-07 06:44:49.142  - error: admin.0 (3921813) Parameter "id" needs to be of type "string" but type "number" has been passed
2024-10-07 06:44:49.157  - warn: admin.0 (3921813) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-10-07 06:44:49.731  - error: host.iobroker-master Caught by controller[0]: Error: Parameter "id" needs to be of type "string" but type "number" has been passed
2024-10-07 06:44:49.734  - error: host.iobroker-master Caught by controller[0]:     at Function.assertString (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/                                                                                                                                                    src/lib/adapter/validator.ts:238:19)
2024-10-07 06:44:49.734  - error: host.iobroker-master Caught by controller[0]:     at Admin.getSession (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/l                                                                                                                                                    ib/adapter/adapter.ts:1373:19)
2024-10-07 06:44:49.734  - error: host.iobroker-master Caught by controller[0]:     at SocketAdmin.__getUserFromSocket (/opt/iobroker/node_modules/iobroker.admin/node_mo                                                                                                                                                    dules/@iobroker/socket-classes/lib/socketAdmin.js:73:33)
2024-10-07 06:44:49.734  - error: host.iobroker-master Caught by controller[0]:     at SocketAdmin._initSocket (/opt/iobroker/node_modules/iobroker.admin/node_modules/@i                                                                                                                                                    obroker/socket-classes/lib/socketCommon.js:162:22)
2024-10-07 06:44:49.734  - error: host.iobroker-master Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/li                                                                                                                                                    b/socketCommon.js:104:22
2024-10-07 06:44:49.734  - error: host.iobroker-master Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/ws-server/dist/in                                                                                                                                                    dex.js:246:64
2024-10-07 06:44:49.734  - error: host.iobroker-master Caught by controller[0]:     at Array.forEach (<anonymous>)
2024-10-07 06:44:49.734  - error: host.iobroker-master Caught by controller[0]:     at WebSocketServer.<anonymous> (/opt/iobroker/node_modules/iobroker.admin/node_module                                                                                                                                                    s/@iobroker/ws-server/dist/index.js:246:50)
2024-10-07 06:44:49.734  - error: host.iobroker-master Caught by controller[0]:     at WebSocketServer.emit (node:events:519:28)
2024-10-07 06:44:49.734  - error: host.iobroker-master Caught by controller[0]:     at WebSocketServer.emit (node:domain:488:12)
2024-10-07 06:44:49.734  - error: host.iobroker-master instance system.adapter.admin.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2024-10-07 06:45:21.508  - error: admin.0 (3922169) Cannot init i18n: Error: Cannot find i18n directory
2024-10-07 06:45:44.064  - error: admin.0 (3922169) uncaught exception: Parameter "id" needs to be of type "string" but type "number" has been passed
2024-10-07 06:45:44.065  - error: admin.0 (3922169) Error: Parameter "id" needs to be of type "string" but type "number" has been passed
    at Function.assertString (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:238:19)
    at Admin.getSession (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:1373:19)
    at SocketAdmin.__getUserFromSocket (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketAdmin.js:73:33)
    at SocketAdmin._initSocket (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketCommon.js:162:22)
    at /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketCommon.js:104:22
    at /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/ws-server/dist/index.js:246:64
    at Array.forEach (<anonymous>)
    at WebSocketServer.<anonymous> (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/ws-server/dist/index.js:246:50)
    at WebSocketServer.emit (node:events:519:28)
    at WebSocketServer.emit (node:domain:488:12)
2024-10-07 06:45:44.065  - error: admin.0 (3922169) Parameter "id" needs to be of type "string" but type "number" has been passed
2024-10-07 06:45:44.076  - warn: admin.0 (3922169) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-10-07 06:45:44.507  - error: host.iobroker-master Caught by controller[0]: Error: Parameter "id" needs to be of type "string" but type "number" has been passed
2024-10-07 06:45:44.507  - error: host.iobroker-master Caught by controller[0]:     at Function.assertString (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:238:19)
2024-10-07 06:45:44.507  - error: host.iobroker-master Caught by controller[0]:     at Admin.getSession (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:1373:19)
2024-10-07 06:45:44.508  - error: host.iobroker-master Caught by controller[0]:     at SocketAdmin.__getUserFromSocket (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketAdmin.js:73:33)
2024-10-07 06:45:44.508  - error: host.iobroker-master Caught by controller[0]:     at SocketAdmin._initSocket (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketCommon.js:162:22)
2024-10-07 06:45:44.508  - error: host.iobroker-master Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketCommon.js:104:22
2024-10-07 06:45:44.508  - error: host.iobroker-master Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/ws-server/dist/index.js:246:64
2024-10-07 06:45:44.508  - error: host.iobroker-master Caught by controller[0]:     at Array.forEach (<anonymous>)
2024-10-07 06:45:44.508  - error: host.iobroker-master Caught by controller[0]:     at WebSocketServer.<anonymous> (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/ws-server/dist/index.js:246:50)
2024-10-07 06:45:44.508  - error: host.iobroker-master Caught by controller[0]:     at WebSocketServer.emit (node:events:519:28)
2024-10-07 06:45:44.508  - error: host.iobroker-master Caught by controller[0]:     at WebSocketServer.emit (node:domain:488:12)
2024-10-07 06:45:44.508  - error: host.iobroker-master instance system.adapter.admin.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2024-10-07 06:46:16.328  - error: admin.0 (3922658) Cannot init i18n: Error: Cannot find i18n directory
2024-10-07 06:46:25.136  - error: admin.0 (3922658) uncaught exception: Parameter "id" needs to be of type "string" but type "number" has been passed
2024-10-07 06:46:25.137  - error: admin.0 (3922658) Error: Parameter "id" needs to be of type "string" but type "number" has been passed
    at Function.assertString (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:238:19)
    at Admin.getSession (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:1373:19)
    at SocketAdmin.__getUserFromSocket (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketAdmin.js:73:33)
    at SocketAdmin._initSocket (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketCommon.js:162:22)
    at /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketCommon.js:104:22
    at /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/ws-server/dist/index.js:246:64
    at Array.forEach (<anonymous>)
    at WebSocketServer.<anonymous> (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/ws-server/dist/index.js:246:50)
    at WebSocketServer.emit (node:events:519:28)
    at WebSocketServer.emit (node:domain:488:12)
2024-10-07 06:46:25.137  - error: admin.0 (3922658) Parameter "id" needs to be of type "string" but type "number" has been passed
2024-10-07 06:46:25.147  - warn: admin.0 (3922658) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-10-07 06:46:25.546  - error: host.iobroker-master Caught by controller[0]: Error: Parameter "id" needs to be of type "string" but type "number" has been passed
2024-10-07 06:46:25.546  - error: host.iobroker-master Caught by controller[0]:     at Function.assertString (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:238:19)
2024-10-07 06:46:25.546  - error: host.iobroker-master Caught by controller[0]:     at Admin.getSession (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:1373:19)
2024-10-07 06:46:25.546  - error: host.iobroker-master Caught by controller[0]:     at SocketAdmin.__getUserFromSocket (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketAdmin.js:73:33)
2024-10-07 06:46:25.546  - error: host.iobroker-master Caught by controller[0]:     at SocketAdmin._initSocket (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketCommon.js:162:22)
2024-10-07 06:46:25.546  - error: host.iobroker-master Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketCommon.js:104:22
2024-10-07 06:46:25.546  - error: host.iobroker-master Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/ws-server/dist/index.js:246:64
2024-10-07 06:46:25.546  - error: host.iobroker-master Caught by controller[0]:     at Array.forEach (<anonymous>)
2024-10-07 06:46:25.546  - error: host.iobroker-master Caught by controller[0]:     at WebSocketServer.<anonymous> (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/ws-server/dist/index.js:246:50)
2024-10-07 06:46:25.546  - error: host.iobroker-master Caught by controller[0]:     at WebSocketServer.emit (node:events:519:28)
2024-10-07 06:46:25.547  - error: host.iobroker-master Caught by controller[0]:     at WebSocketServer.emit (node:domain:488:12)
2024-10-07 06:46:25.547  - error: host.iobroker-master instance system.adapter.admin.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2024-10-07 06:46:57.504  - error: admin.0 (3923056) Cannot init i18n: Error: Cannot find i18n directory
2024-10-07 06:47:03.159  - error: admin.0 (3923056) uncaught exception: Parameter "id" needs to be of type "string" but type "number" has been passed
2024-10-07 06:47:03.159  - error: admin.0 (3923056) Error: Parameter "id" needs to be of type "string" but type "number" has been passed
    at Function.assertString (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:238:19)
    at Admin.getSession (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:1373:19)
    at SocketAdmin.__getUserFromSocket (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketAdmin.js:73:33)
    at SocketAdmin._initSocket (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketCommon.js:162:22)
    at /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketCommon.js:104:22
    at /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/ws-server/dist/index.js:246:64
    at Array.forEach (<anonymous>)
    at WebSocketServer.<anonymous> (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/ws-server/dist/index.js:246:50)
    at WebSocketServer.emit (node:events:519:28)
    at WebSocketServer.emit (node:domain:488:12)
2024-10-07 06:47:03.159  - error: admin.0 (3923056) Parameter "id" needs to be of type "string" but type "number" has been passed
2024-10-07 06:47:03.168  - warn: admin.0 (3923056) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-10-07 06:47:03.663  - error: host.iobroker-master Caught by controller[0]: Error: Parameter "id" needs to be of type "string" but type "number" has been passed
2024-10-07 06:47:03.664  - error: host.iobroker-master Caught by controller[0]:     at Function.assertString (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:238:19)
2024-10-07 06:47:03.664  - error: host.iobroker-master Caught by controller[0]:     at Admin.getSession (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:1373:19)
2024-10-07 06:47:03.664  - error: host.iobroker-master Caught by controller[0]:     at SocketAdmin.__getUserFromSocket (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketAdmin.js:73:33)
2024-10-07 06:47:03.664  - error: host.iobroker-master Caught by controller[0]:     at SocketAdmin._initSocket (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketCommon.js:162:22)
2024-10-07 06:47:03.664  - error: host.iobroker-master Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/socket-classes/lib/socketCommon.js:104:22
2024-10-07 06:47:03.664  - error: host.iobroker-master Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/ws-server/dist/index.js:246:64
2024-10-07 06:47:03.664  - error: host.iobroker-master Caught by controller[0]:     at Array.forEach (<anonymous>)
2024-10-07 06:47:03.664  - error: host.iobroker-master Caught by controller[0]:     at WebSocketServer.<anonymous> (/opt/iobroker/node_modules/iobroker.admin/node_modules/@iobroker/ws-server/dist/index.js:246:50)
2024-10-07 06:47:03.664  - error: host.iobroker-master Caught by controller[0]:     at WebSocketServer.emit (node:events:519:28)
2024-10-07 06:47:03.664  - error: host.iobroker-master Caught by controller[0]:     at WebSocketServer.emit (node:domain:488:12)
2024-10-07 06:47:03.664  - error: host.iobroker-master instance system.adapter.admin.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
`

**Comment by Grothesk242** [comment]
Deactivating auth and admin is starting again. 

```
iobroker set admin --auth false
```

**Comment by diamand2k22** [comment]
also not working for me, i went back to the  last working version -> 7.2.0

**Comment by quorle** [comment]
The same Problem with Admin 7.2.2.
Downgrade to 7.2.o is OK

**Comment by UweRP** [comment]
Auch unter Winndows Fehler mit 7.2.2.
Zurück auf die 7.2.0 und ein Login ist wieder möglich.


admin.0 | 2024-10-08 06:56:54.591 | error | Cannot init i18n: Error: Cannot find i18n directory
-- | -- | -- | --
admin.0 | 2024-10-08 06:49:12.771 | error | Cannot init i18n: Error: Cannot find i18n directory
admin.0 | 2024-10-08 06:48:40.043 | error | Parameter "id" needs to be of type "string" but type "number" has been passed
admin.0 | 2024-10-08 06:48:40.042 | error | Error:  Parameter "id" needs to be of type "string" but type "number" has been  passed    at Function.assertString  (c:\iobroker\node_modules\@iobroker\js-controller-adapter\src\lib\adapter\validator.ts:238:19)     at Admin.getSession  (c:\iobroker\node_modules\@iobroker\js-controller-adapter\src\lib\adapter\adapter.ts:1374:19)     at SocketAdmin.__getUserFromSocket  (c:\iobroker\node_modules\iobroker.admin\node_modules\@iobroker\socket-classes\lib\socketAdmin.js:73:33)     at SocketAdmin._initSocket  (c:\iobroker\node_modules\iobroker.admin\node_modules\@iobroker\socket-classes\lib\socketCommon.js:162:22)     at  c:\iobroker\node_modules\iobroker.admin\node_modules\@iobroker\socket-classes\lib\socketCommon.js:104:22     at  c:\iobroker\node_modules\iobroker.admin\node_modules\@iobroker\ws-server\dist\index.js:246:64     at Array.forEach (<anonymous>)    at  WebSocketServer.<anonymous>  (c:\iobroker\node_modules\iobroker.admin\node_modules\@iobroker\ws-server\dist\index.js:246:50)     at WebSocketServer.emit (node:events:519:28)    at  WebSocketServer.emit (node:domain:488:12)
admin.0 | 2024-10-08 06:48:40.042 | error | uncaught exception: Parameter "id" needs to be of type "string" but type "number" has been passed
admin.0 | 2024-10-08 06:48:37.376 | error | Cannot init i18n: Error: Cannot find i18n directory

**Comment by Apollon77** [comment]
Ich habe admin Beta version auf die 7.2.0 zurücjgestellt bis wir das gefixt haben. Bitte alle Downgraden

**Comment by GermanBluefox** [comment]
I started ioBroker 7.2.5 with authentication on brand new system and EVERYTHING works. Including dark theme and no loop.
The problem with the restart or AUTH loop should come because of old `@iobroker/ws-server` package (< 3.0.3) and why it is so, I cannot explain.
so please If you have above errors, start "npm ls @iobroker/ws-server" in iobroker folder and show the results here. ( and in `/opt/iobroker/node_modules/iobroker.admin` folder too)

**Comment by Diginix** [comment]
```
/opt/iobroker$ npm ls @iobroker/ws-server
iobroker.inst@3.0.0 /opt/iobroker
├─┬ iobroker.admin@7.2.0
│ └── @iobroker/ws-server@2.1.2
└─┬ iobroker.ws@2.6.2
  └── @iobroker/ws-server@2.1.2 deduped
```
```
/opt/iobroker/node_modules/iobroker.admin$ npm ls @iobroker/ws-server
iobroker.admin@7.2.0 /opt/iobroker/node_modules/iobroker.admin
└── (empty)
```

**Comment by JohGrei** [comment]
my ws-server is much older

iobroker.inst@2.0.3 /opt/iobroker
├─┬ iobroker.admin@7.2.0
│ └── @iobroker/ws-server@2.1.2
└─┬ iobroker.ws@2.6.2
  └── @iobroker/ws-server@2.1.2 deduped

iobroker.admin@7.2.0 /opt/iobroker/node_modules/iobroker.admin
└── (empty)

**Comment by Grothesk242** [comment]
```
echad@chet:/opt/iobroker $ npm ls @iobroker/ws-server
iobroker.inst@3.0.0 /opt/iobroker
├─┬ iobroker.admin@7.2.5
│ └── @iobroker/ws-server@3.0.3
└─┬ iobroker.ws@2.6.2
  └── @iobroker/ws-server@2.1.2
echad@chet:/opt/iobroker $
```

**Comment by Negalein** [comment]
```
iobroker.inst@3.0.0 /opt/iobroker
+-- iobroker.admin@7.2.0
| `-- @iobroker/ws-server@2.1.2
`-- iobroker.ws@2.6.2
  `-- @iobroker/ws-server@2.1.2 deduped
```

```
nega@ioBroker:/opt/iobroker/node_modules/iobroker.admin$ npm ls @iobroker/ws-server
iobroker.admin@7.2.0 /opt/iobroker/node_modules/iobroker.admin
`-- (empty)

nega@ioBroker:/opt/iobroker/node_modules/iobroker.admin$
```

**Comment by vepman** [comment]
my ws-server:
`+--` iobroker.admin@7.2.0
| `-- @iobroker/ws-server@2.1.2
`-- iobroker.ws@2.6.2
  `-- @iobroker/ws-server@2.1.2 deduped`

**Comment by Diginix** [comment]
After update admin from 7.2.0 to 7.2.5 ws-server is updated to 3.0.3 as well.

**Comment by sigi2345** [comment]
> After update admin from 7.2.0 to 7.2.5 ws-server is updated to 3.0.3 as well. For me 7.2.5 fixed this issue.

Leider nein:

![Screenshot (995)](https://github.com/user-attachments/assets/f196b58f-00b9-4c57-a99d-69dd05185e59)

**Comment by GermanBluefox** [comment]
> > After update admin from 7.2.0 to 7.2.5 ws-server is updated to 3.0.3 as well. For me 7.2.5 fixed this issue.
> 
> Leider nein:
> 
> ![Screenshot (995)](https://private-user-images.githubusercontent.com/41079106/375658551-f196b58f-00b9-4c57-a99d-69dd05185e59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzE0MjgsIm5iZiI6MTcyODYzMTEyOCwicGF0aCI6Ii80MTA3OTEwNi8zNzU2NTg1NTEtZjE5NmI1OGYtMDBiOS00YzU3LWE5OWQtNjlkZDA1MTg1ZTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA3MTg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNDg1NTcxMDEyNmUwYmIxYjVkYjIxYWJlY2MzODFkYmY3ODA1ZmYyNjNjNjlkMjA3NTQ1NGNmMjRkNmRiYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ubG1649iCb8pa3JDmPhWuVJDEeU1oz2k8bOGl1avkBQ)

Es wäre SEHR hilfreich zu sagen, ob extenre Socket.IO oder ws benutz wird.

**Comment by sigi2345** [comment]
> > > After update admin from 7.2.0 to 7.2.5 ws-server is updated to 3.0.3 as well. For me 7.2.5 fixed this issue.
> > 
> > 
> > Leider nein:

> 
> Es wäre SEHR hilfreich zu sagen, ob extenre Socket.IO oder ws benutz wird.


![Screenshot (999)](https://github.com/user-attachments/assets/0b5a8789-556c-4f4c-b5ab-c79af700cd27)
![Screenshot (998)](https://github.com/user-attachments/assets/33da130c-583a-4b39-991d-e0b3cb4b9182)
![Screenshot (997)](https://github.com/user-attachments/assets/5f6f71b6-83d4-4285-bd66-3123cdaf7206)
![Screenshot (996)](https://github.com/user-attachments/assets/f447be3b-1b93-4bf1-a130-fb59f1e242c4)

**Comment by joergeli** [comment]
Unfortunately restart loop still exists with V 7.2.5 and also with "light"-mode.
![web](https://github.com/user-attachments/assets/58a4b7f6-984b-471f-acde-3fc3e6286a77)

**Comment by GermanBluefox** [comment]
> Unfortunately restart loop still exists with V 7.2.5 and also with "light"-mode. ![web](https://private-user-images.githubusercontent.com/62521927/375704711-58a4b7f6-984b-471f-acde-3fc3e6286a77.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NDIxMTAsIm5iZiI6MTcyODY0MTgxMCwicGF0aCI6Ii82MjUyMTkyNy8zNzU3MDQ3MTEtNThhNGI3ZjYtOTg0Yi00NzFmLWFjZGUtM2ZjM2U2Mjg2YTc3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDEwMTY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0ZTU5NGQ4NzhlNDZjMmZlYmUyYmUyNmMxNWU5NDliMDI0MzlkMTYyMjBlMWVlMmI2ZWEwYmU4ZWMzNTdiYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8kHEClZ1C2m5u69d0eQkLYChqe-kkjRGBIMqYyeqwa0)

auf dem Bild sieht man 7.2.0

**Comment by joergeli** [comment]
"auf dem Bild sieht man 7.2.0" --> ja, ich hatte es vorher mit 7.2.5 getestet und bin dann wieder zurück auf 7.2.0 - sorry

**Comment by GermanBluefox** [comment]
> "auf dem Bild sieht man 7.2.0" --> ja, ich hatte es vorher mit 7.2.5 getestet und bin dann wieder zurück auf 7.2.0 - sorry

Dark mode muss gehen

**Comment by joergeli** [comment]
"Dark mode muss gehen" --> sorry, weder Dark- noch Light-Mode, in beiden Modi bei mir Restart mit V 7.2.5

**Comment by Grothesk242** [comment]
> "Dark mode muss gehen" --> sorry, weder Dark- noch Light-Mode, in beiden Modi bei mir Restart mit V 7.2.5

Der dark/light-Mode hat ja auch mit dem Restart nichts tun. Das muss man getrennt betrachten.

**Comment by Brainbug01** [comment]
7.2.5

tobias@iobroker:/opt/iobroker$ npm ls @iobroker/ws-server
iobroker.inst@3.0.0 /opt/iobroker
+-- iobroker.admin@7.2.5
| `-- @iobroker/ws-server@3.0.3
`-- iobroker.web@6.3.1
  `-- iobroker.ws@2.6.2
    `-- @iobroker/ws-server@2.1.2

tobias@iobroker:/opt/iobroker/node_modules/iobroker.admin$ npm ls @iobroker/ws-server
iobroker.admin@7.2.5 /opt/iobroker/node_modules/iobroker.admin
`-- @iobroker/ws-server@3.0.3

`
admin.0
2024-10-11 14:58:52.872	warn	REAUTHENTICATE!
admin.0
2024-10-11 14:57:47.458	warn	REAUTHENTICATE!
`

**Comment by crunchip77** [comment]
admin v7.2.6 no Problems

**Comment by sigi2345** [comment]
> admin v7.2.6 no Problems

Dito

**Comment by joergeli** [comment]
yes, with V 7.2.6 problem is fixed. Thanks!

**Comment by vepman** [comment]
Ja, bis jetzt O.K.
