### ISSUE TITLE
[bug]: Cannot get list of adapter - Error in GUI

### ISSUE THREAD

**Issue by alkaraschu** [ioBroker/ioBroker.admin#2773]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Cannot get list of adapters in the GUI

### To Reproduce

open iobroker
go to adapters

### Expected behavior

Open a list of all (installed) adapter

### Screenshots & Logfiles

![image](https://github.com/user-attachments/assets/31f6166f-852a-4fd6-93f8-9630c6f6ec55)
![image](https://github.com/user-attachments/assets/e36b29dd-3acf-428e-b616-765d7f20dc68)

### Adapter version

7.1.5

### js-controller version

6.0.11

### Node version

20.18.0

### Operating system

Mac OS

**Comment by mcm1957** [comment]
@averlon 
@alkaraschu 
Thanks for reporting.

**Please retry after reloading repository data.**
There was som invlid data distributed by stable repository.

Go to adapter tab and press "Adapter auf Updates prüfen" (Icon with circular arrow).
![image](https://github.com/user-attachments/assets/7b47bd17-d557-4eea-80c9-da0f0e828e4d)

Afterwards refreh screen. Shoudl work for now..

Please keep Issue open even if it works - there's a code part that must be improved at admin!

**Comment by mcm1957** [comment]
Problem analyzes (german as copied from Telegram)

In sources-dist.json, also der offiziellen vom Fileserver ausgelieferten Datei, fand sich folgende Zeile beim zigbee2mqtt Adapter:

```
        ],
        "licenseInformation": "MIT",
        "platform": "Javascript/Node.js",
```

licenseInformation ist hier ein STRING und nicht wie vorgesehen ein OBJECT.
Der fehlerhafte Eintrag steht auch so im io-package.json auf npm (release 2.13.10).

Damit kommt der Admin nicht zurecht:

```
react-dom.production.min.js:282 Uncaught TypeError: s.includes is not a function
    at O (Utils.ts:22:18)
    at lt.renderLicenseInfo (AdapterGeneric.tsx:401:15)
    at lt.render (AdapterRow.tsx:94:26)
    at No (react-dom.production.min.js:203:189)
    at zo (react-dom.production.min.js:202:149)
    at xi (react-dom.production.min.js:291:172)
    at bs (react-dom.production.min.js:279:389)
    at vs (react-dom.production.min.js:279:320)
    at gs (react-dom.production.min.js:279:180)
    at ls (react-dom.production.min.js:267:209)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
```

Codestelle:

```
if (!url  !url.includes('/LICENSE')  !url.includes('raw.githubusercontent.com')) {
        url = adapterRepo.extIcon;
        if (!url) {
            url = adapterRepo.readme;
```

Im Debugger (Chrome F12) zeigt sich dass in url statt des Strings aus 'link' nun func() steht.

**Comment by GermanBluefox** [comment]
Fixed long time ago
