### ISSUE TITLE
[bug]: Admin 7.3.1 Error: write EPIPE after update

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#2806]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

After updating admin to current beta version 7.3.1 there are errors in log file

### To Reproduce

update admin from 7.2.6 to version 7.3.1 

### Expected behavior

no errors in the log

### Screenshots & Logfiles

```
host.ioB-Prod-Testsystem
	2024-11-14 22:08:40.701	warn	Detected missing upload of adapter "admin" - starting upload now.
host.ioB-Prod-Testsystem
	2024-11-14 22:08:10.537	info	Restart adapter system.adapter.admin.0 because enabled
host.ioB-Prod-Testsystem
	2024-11-14 22:08:10.533	error	instance system.adapter.admin.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.ioB-Prod-Testsystem
	2024-11-14 22:08:10.527	error	Caught by controller[0]: }
host.ioB-Prod-Testsystem
	2024-11-14 22:08:10.520	error	Caught by controller[0]: syscall: 'write'
host.ioB-Prod-Testsystem
	2024-11-14 22:08:10.515	error	Caught by controller[0]: code: 'EPIPE',
host.ioB-Prod-Testsystem
	2024-11-14 22:08:10.510	error	Caught by controller[0]: errno: -32,
host.ioB-Prod-Testsystem
	2024-11-14 22:08:10.507	error	Caught by controller[0]: at Socket.emit (node:events:518:28) {
host.ioB-Prod-Testsystem
	2024-11-14 22:08:10.501	error	Caught by controller[0]: at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.admin/src/lib/checkLinuxPass.ts:61:42)
host.ioB-Prod-Testsystem
	2024-11-14 22:08:10.497	error	Caught by controller[0]: at _checkPassword (/opt/iobroker/node_modules/iobroker.admin/src/lib/checkLinuxPass.ts:43:30)
host.ioB-Prod-Testsystem
	2024-11-14 22:08:10.493	error	Caught by controller[0]: at Socket.Writable.write (node:internal/streams/writable:510:10)
host.ioB-Prod-Testsystem
	2024-11-14 22:08:10.490	error	Caught by controller[0]: at _write (node:internal/streams/writable:501:10)
host.ioB-Prod-Testsystem
	2024-11-14 22:08:10.486	error	Caught by controller[0]: at writeOrBuffer (node:internal/streams/writable:572:12)
host.ioB-Prod-Testsystem
	2024-11-14 22:08:10.483	error	Caught by controller[0]: at Socket._write (node:net:969:8)
host.ioB-Prod-Testsystem
	2024-11-14 22:08:10.480	error	Caught by controller[0]: at Socket._writeGeneric (node:net:957:11)
host.ioB-Prod-Testsystem
	2024-11-14 22:08:10.476	error	Caught by controller[0]: at writeGeneric (node:internal/stream_base_commons:150:3)
host.ioB-Prod-Testsystem
	2024-11-14 22:08:10.473	error	Caught by controller[0]: at afterWriteDispatched (node:internal/stream_base_commons:159:15)
host.ioB-Prod-Testsystem
	2024-11-14 22:08:10.468	error	Caught by controller[0]: Error: write EPIPE
admin.0
	2024-11-14 22:08:09.951	info	terminating http server on port 8081
admin.0
	2024-11-14 22:08:09.425	error	Exception-Code: EPIPE: write EPIPE
admin.0
	2024-11-14 22:08:09.419	error	Error: write EPIPE at afterWriteDispatched (node:internal/stream_base_commons:159:15) at writeGeneric (node:internal/stream_base_commons:150:3) at Socket._writeGeneric (node:net:957:11) at Socket._write (node:net:969:8) at writeOrBuffer (node:internal/streams/writable:572:12) at _write (node:internal/streams/writable:501:10) at Socket.Writable.write (node:internal/streams/writable:510:10) at _checkPassword (/opt/iobroker/node_modules/iobroker.admin/src/lib/checkLinuxPass.ts:43:30) at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.admin/src/lib/checkLinuxPass.ts:61:42) at Socket.emit (node:events:518:28)
admin.0
	2024-11-14 22:08:09.412	error	uncaught exception: write EPIPE
admin.0
	2024-11-14 22:08:06.627	info	Use link "http://127.0.0.1:8081" to configure.
admin.0
	2024-11-14 22:08:06.622	info	http server listening on port 8081
admin.0
	2024-11-14 22:08:06.612	info	socket.io server listening on port 8081
admin.0
	2024-11-14 22:08:05.640	info	received all objects
admin.0
	2024-11-14 22:08:03.084	info	requesting all objects
admin.0
	2024-11-14 22:08:02.978	info	starting. Version 7.3.1 in /opt/iobroker/node_modules/iobroker.admin, node: v22.11.0, js-controller: 7.0.2
host.ioB-Prod-Testsystem
	2024-11-14 22:07:56.793	info	instance system.adapter.admin.0 in version "7.3.1" started with pid 3841
host.ioB-Prod-Testsystem
	2024-11-14 22:07:25.558	info	Restart adapter system.adapter.admin.0 because enabled
```

### Adapter version

7.3.1

### js-controller version

7.0.2

### Node version

v22.11.0

### Operating system

Ubuntu 24.04.1 LTS (GNU/Linux 6.8.12-2-pve x86_64)

**Comment by Feuer-sturm** [comment]
update to admin v7.4.0 without any problems. Thanks.
