### ISSUE TITLE
[bug]: Error in GUI when opening hmip instance (getOwnPropertyDescriptors)

### ISSUE THREAD

**Issue by xantiva** [ioBroker/ioBroker.admin#2818]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

I created a new ioBroker installation (v7.1.5) and installed the hmip (HomeMaticIP Cloud AccessPoint) adapter. If I try to open the configuration of the instance I got an "Error in GUI!"

### To Reproduce

1. Fresh install of ioBroker on QNAP NAS with buanet image (buanet/iobroker:latest-v10).
2. Install hmip adapter.
3. Try to open the configuration of the instance: /#tab-instances/config/system.adapter.hmip.0

### Expected behavior

The config page should be displayed without an error.

### Screenshots & Logfiles

```
console.ts:40  TypeError: Cannot convert undefined or null to object
    at getOwnPropertyDescriptors (<anonymous>)
    at ie (vendors-node_modules_mui_material_styles_createTheme_js-node_modules_mui_material_styles_iden-d3475a.c5071a2c.chunk.js:1:465)
    at ce (vendors-node_modules_mui_material_styles_ThemeProvider_js.ec053d35.chunk.js:1:568)
    at v (vendors-node_modules_mui_material_styles_ThemeProvider_js.ec053d35.chunk.js:1:1095)
    at hu (react-dom.production.min.js:160:137)
    at xi (react-dom.production.min.js:289:337)
    at bs (react-dom.production.min.js:279:389)
    at vs (react-dom.production.min.js:279:320)
    at gs (react-dom.production.min.js:279:180)
    at as (react-dom.production.min.js:270:88)
    at ls (react-dom.production.min.js:267:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
```

### Adapter version

1.24.3

### js-controller version

?

### Node version

v20.18.0

### Operating system

linux

**Comment by GermanBluefox** [comment]
Please provide hmip version

**Comment by Feuer-sturm** [comment]
linkt to issue https://github.com/ioBroker/ioBroker.admin/issues/2835
