### ISSUE TITLE
[bug]: When opening "Files" - GUI Crash - Minified React error #62

### ISSUE THREAD

**Issue by PeeBeerBeach** [ioBroker/ioBroker.admin#2838]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

When i click on "files" in the iobroker admin section the GUI crashes.
Not sure what causes it.

### To Reproduce

1. open iobroker admin
2. click on "files"
3. Crash

### Expected behavior

Show files

### Screenshots & Logfiles

`Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ye (https://192.168.1.35:8081/static/js/5096.3a6e8bdb.chunk.js:2:15172)
    at Ko (https://192.168.1.35:8081/static/js/5096.3a6e8bdb.chunk.js:2:86738)
    at ks (https://192.168.1.35:8081/static/js/5096.3a6e8bdb.chunk.js:2:109541)
    at bs (https://192.168.1.35:8081/static/js/5096.3a6e8bdb.chunk.js:2:109422)
    at vs (https://192.168.1.35:8081/static/js/5096.3a6e8bdb.chunk.js:2:109289)
    at gs (https://192.168.1.35:8081/static/js/5096.3a6e8bdb.chunk.js:2:109152)
    at as (https://192.168.1.35:8081/static/js/5096.3a6e8bdb.chunk.js:2:105932)
    at ls (https://192.168.1.35:8081/static/js/5096.3a6e8bdb.chunk.js:2:104483)
    at S (https://192.168.1.35:8081/static/js/5096.3a6e8bdb.chunk.js:2:131248)
    at T (https://192.168.1.35:8081/static/js/5096.3a6e8bdb.chunk.js:2:131782)
    at run (chrome-extension://aiifbnbfobpmeekipheeijimdpnlpgpp/inpage.js:138529:13)
    at runIfPresent (chrome-extension://aiifbnbfobpmeekipheeijimdpnlpgpp/inpage.js:138558:21)
    at onGlobalMessage (chrome-extension://aiifbnbfobpmeekipheeijimdpnlpgpp/inpage.js:138598:17)`

### Adapter version

not related to an adapter

### js-controller version

5.0.12

### Node version

20.18.1

### Operating system

Debian - iobroker running in docker

### Additional context

nothing to add

**Comment by PeeBeerBeach** [comment]
Ok never mind. I installed Admin version 7.2.6 and now it works.
