### ISSUE TITLE
[bug]: uncaught exception: write EPIPE after update to admin 7.4.2

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#2839]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

After upgrading admin adapter from 7.4.1 to 7.4.2 the following error is shown in the log.
After a while admin UI is reachable.

### To Reproduce

see above

### Expected behavior

no error

### Screenshots & Logfiles

```
2024-11-28 19:26:19.045 - info: host.iobtestsystemmatter instance system.adapter.admin.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2024-11-28 19:26:21.022 - info: host.iobtestsystemmatter [WEBSERVER_UPGRADE] (admin) Server is running on http://localhost:8081
2024-11-28 19:27:54.030 - info: host.iobtestsystemmatter [WEBSERVER_UPGRADE] (admin) Successfully upgraded admin to version 7.4.2
2024-11-28 19:27:54.359 - info: host.iobtestsystemmatter [WEBSERVER_UPGRADE] (admin) Final information delivered
2024-11-28 19:27:54.434 - info: host.iobtestsystemmatter "system.adapter.admin.0" enabled
2024-11-28 19:27:54.444 - info: host.iobtestsystemmatter [WEBSERVER_UPGRADE] (admin) Successfully started adapter
2024-11-28 19:27:57.745 - info: host.iobtestsystemmatter instance system.adapter.admin.0 in version "7.4.2" started with pid 32079
2024-11-28 19:28:07.727 - info: admin.0 (32079) starting. Version 7.4.2 in /opt/iobroker/node_modules/iobroker.admin, node: v20.18.1, js-controller: 7.0.3
2024-11-28 19:28:07.868 - info: admin.0 (32079) requesting all objects
2024-11-28 19:28:14.169 - info: admin.0 (32079) received all objects
2024-11-28 19:28:16.653 - error: admin.0 (32079) uncaught exception: write EPIPE
2024-11-28 19:28:16.663 - error: admin.0 (32079) Error: write EPIPE
at afterWriteDispatched (node:internal/stream_base_commons:161:15)
at writeGeneric (node:internal/stream_base_commons:152:3)
at Socket._writeGeneric (node:net:958:11)
at Socket._write (node:net:970:8)
at writeOrBuffer (node:internal/streams/writable:572:12)
at _write (node:internal/streams/writable:501:10)
at Socket.Writable.write (node:internal/streams/writable:510:10)
at _checkPassword (/opt/iobroker/node_modules/iobroker.admin/src/lib/checkLinuxPass.ts:47:35)
at Socket. (/opt/iobroker/node_modules/iobroker.admin/src/lib/checkLinuxPass.ts:81:21)
at Socket.emit (node:events:518:28)
2024-11-28 19:28:16.670 - error: admin.0 (32079) Exception-Code: EPIPE: write EPIPE
2024-11-28 19:28:17.323 - info: admin.0 (32079) terminating http server on port 8081
2024-11-28 19:28:18.393 - error: host.iobtestsystemmatter Caught by controller[0]: Error: write EPIPE
2024-11-28 19:28:18.399 - error: host.iobtestsystemmatter Caught by controller[0]: at afterWriteDispatched (node:internal/stream_base_commons:161:15)
2024-11-28 19:28:18.403 - error: host.iobtestsystemmatter Caught by controller[0]: at writeGeneric (node:internal/stream_base_commons:152:3)
2024-11-28 19:28:18.406 - error: host.iobtestsystemmatter Caught by controller[0]: at Socket._writeGeneric (node:net:958:11)
2024-11-28 19:28:18.409 - error: host.iobtestsystemmatter Caught by controller[0]: at Socket._write (node:net:970:8)
2024-11-28 19:28:18.413 - error: host.iobtestsystemmatter Caught by controller[0]: at writeOrBuffer (node:internal/streams/writable:572:12)
2024-11-28 19:28:18.418 - error: host.iobtestsystemmatter Caught by controller[0]: at _write (node:internal/streams/writable:501:10)
2024-11-28 19:28:18.421 - error: host.iobtestsystemmatter Caught by controller[0]: at Socket.Writable.write (node:internal/streams/writable:510:10)
2024-11-28 19:28:18.424 - error: host.iobtestsystemmatter Caught by controller[0]: at _checkPassword (/opt/iobroker/node_modules/iobroker.admin/src/lib/checkLinuxPass.ts:47:35)
2024-11-28 19:28:18.428 - error: host.iobtestsystemmatter Caught by controller[0]: at Socket. (/opt/iobroker/node_modules/iobroker.admin/src/lib/checkLinuxPass.ts:81:21)
2024-11-28 19:28:18.432 - error: host.iobtestsystemmatter Caught by controller[0]: at Socket.emit (node:events:518:28) {
2024-11-28 19:28:18.435 - error: host.iobtestsystemmatter Caught by controller[0]: errno: -32,
2024-11-28 19:28:18.439 - error: host.iobtestsystemmatter Caught by controller[0]: code: 'EPIPE',
2024-11-28 19:28:18.443 - error: host.iobtestsystemmatter Caught by controller[0]: syscall: 'write'
2024-11-28 19:28:18.446 - error: host.iobtestsystemmatter Caught by controller[0]: }
2024-11-28 19:28:18.450 - error: host.iobtestsystemmatter instance system.adapter.admin.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2024-11-28 19:28:18.455 - info: host.iobtestsystemmatter Restart adapter system.adapter.admin.0 because enabled
2024-11-28 19:28:50.446 - info: host.iobtestsystemmatter instance system.adapter.admin.0 in version "7.4.2" started with pid 32106
2024-11-28 19:28:58.634 - info: admin.0 (32106) starting. Version 7.4.2 in /opt/iobroker/node_modules/iobroker.admin, node: v20.18.1, js-controller: 7.0.3
2024-11-28 19:28:58.812 - info: admin.0 (32106) requesting all objects
2024-11-28 19:29:02.233 - error: admin.0 (32106) uncaught exception: write EPIPE
2024-11-28 19:29:02.242 - error: admin.0 (32106) Error: write EPIPE
at afterWriteDispatched (node:internal/stream_base_commons:161:15)
at writeGeneric (node:internal/stream_base_commons:152:3)
at Socket._writeGeneric (node:net:958:11)
at Socket._write (node:net:970:8)
at writeOrBuffer (node:internal/streams/writable:572:12)
at _write (node:internal/streams/writable:501:10)
at Socket.Writable.write (node:internal/streams/writable:510:10)
at _checkPassword (/opt/iobroker/node_modules/iobroker.admin/src/lib/checkLinuxPass.ts:47:35)
at Socket. (/opt/iobroker/node_modules/iobroker.admin/src/lib/checkLinuxPass.ts:81:21)
at Socket.emit (node:events:518:28)
2024-11-28 19:29:02.251 - error: admin.0 (32106) Exception-Code: EPIPE: write EPIPE
2024-11-28 19:29:02.440 - info: admin.0 (32106) terminating http server on port 8081
2024-11-28 19:29:02.447 - info: admin.0 (32106) terminating
2024-11-28 19:29:02.457 - warn: admin.0 (32106) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-11-28 19:29:02.978 - info: admin.0 (32106) terminating
2024-11-28 19:29:05.239 - info: admin.0 (32106) received all objects
2024-11-28 19:29:06.022 - error: host.iobtestsystemmatter Caught by controller[0]: Error: write EPIPE
2024-11-28 19:29:06.034 - error: host.iobtestsystemmatter Caught by controller[0]: at afterWriteDispatched (node:internal/stream_base_commons:161:15)
2024-11-28 19:29:06.039 - error: host.iobtestsystemmatter Caught by controller[0]: at writeGeneric (node:internal/stream_base_commons:152:3)
2024-11-28 19:29:06.044 - error: host.iobtestsystemmatter Caught by controller[0]: at Socket._writeGeneric (node:net:958:11)
2024-11-28 19:29:06.050 - error: host.iobtestsystemmatter Caught by controller[0]: at Socket._write (node:net:970:8)
2024-11-28 19:29:06.056 - error: host.iobtestsystemmatter Caught by controller[0]: at writeOrBuffer (node:internal/streams/writable:572:12)
2024-11-28 19:29:06.065 - error: host.iobtestsystemmatter Caught by controller[0]: at _write (node:internal/streams/writable:501:10)
2024-11-28 19:29:06.073 - error: host.iobtestsystemmatter Caught by controller[0]: at Socket.Writable.write (node:internal/streams/writable:510:10)
2024-11-28 19:29:06.081 - error: host.iobtestsystemmatter Caught by controller[0]: at _checkPassword (/opt/iobroker/node_modules/iobroker.admin/src/lib/checkLinuxPass.ts:47:35)
2024-11-28 19:29:06.096 - error: host.iobtestsystemmatter Caught by controller[0]: at Socket. (/opt/iobroker/node_modules/iobroker.admin/src/lib/checkLinuxPass.ts:81:21)
2024-11-28 19:29:06.108 - error: host.iobtestsystemmatter Caught by controller[0]: at Socket.emit (node:events:518:28) {
2024-11-28 19:29:06.112 - error: host.iobtestsystemmatter Caught by controller[0]: errno: -32,
2024-11-28 19:29:06.124 - error: host.iobtestsystemmatter Caught by controller[0]: code: 'EPIPE',
2024-11-28 19:29:06.128 - error: host.iobtestsystemmatter Caught by controller[0]: syscall: 'write'
2024-11-28 19:29:06.133 - error: host.iobtestsystemmatter Caught by controller[0]: }
2024-11-28 19:29:06.136 - error: host.iobtestsystemmatter instance system.adapter.admin.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2024-11-28 19:29:06.139 - info: host.iobtestsystemmatter Restart adapter system.adapter.admin.0 because enabled
2024-11-28 19:29:38.624 - info: host.iobtestsystemmatter instance system.adapter.admin.0 in version "7.4.2" started with pid 32160
2024-11-28 19:29:48.228 - info: admin.0 (32160) starting. Version 7.4.2 in /opt/iobroker/node_modules/iobroker.admin, node: v20.18.1, js-controller: 7.0.3
2024-11-28 19:29:48.393 - info: admin.0 (32160) requesting all objects
2024-11-28 19:29:53.958 - info: admin.0 (32160) received all objects
2024-11-28 19:29:55.635 - info: admin.0 (32160) socket.io server listening on port 8081
2024-11-28 19:29:55.654 - info: admin.0 (32160) http server listening on port 8081
2024-11-28 19:29:55.683 - info: admin.0 (32160) Use link "http://127.0.0.1:8081" to configure.
2024-11-28 19:30:35.571 - info: admin.0 (32160) ==> Connected system.user.admin from ::ffff:192.168.178.128

```

### Adapter version

7.4.2

### js-controller version

js-controller: 7.0.3

### Node version

node: v20.18.1

### Operating system

ubuntu VM Ubuntu 24.04.1 LTS (GNU/Linux 6.8.0-49-generic x86_64)

**Comment by Feuer-sturm** [comment]
there was a similar error with an older admin version https://github.com/ioBroker/ioBroker.admin/issues/2806

**Comment by GermanBluefox** [comment]
I think we can close it
