### ISSUE TITLE
[bug]: Error in GUI! Admin 7.4.3

### ISSUE THREAD

**Issue by Brainbug01** [ioBroker/ioBroker.admin#2846]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Wenn ich z.B. durch die Tabs des backipup Adapter klicke kommt irgendwann dieses Fenter:
![image](https://github.com/user-attachments/assets/b4dddc30-77ac-439d-b4df-58f3a14d24f5)
![image](https://github.com/user-attachments/assets/5d890d53-97f9-4ecb-8711-89ba331289c0)
![image](https://github.com/user-attachments/assets/eb5393d6-39b5-493d-9352-a893cffe88f9)

Beim Admin durch klick auf diesen Tab:
![image](https://github.com/user-attachments/assets/4868928b-a3dc-4b4c-abdc-4ad2e171a4f0)
![image](https://github.com/user-attachments/assets/30449590-4895-425b-8ebc-bba845280318)
![image](https://github.com/user-attachments/assets/b61045d7-b620-45a8-9216-2f0a264175e6)

### To Reproduce

-

### Expected behavior

-

### Screenshots & Logfiles

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'sendTo')
    at W.checkConfiguration (src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:12:8060)
    at W.<anonymous> (src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:12:10114)
    at Generator.next (<anonymous>)
    at src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:12:7894
    at new Promise (<anonymous>)
    at Pe (src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:12:7714)
    at W.componentDidMount (src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:12:10014)
    at ki (react-dom.production.min.js:260:217)
    at bi (react-dom.production.min.js:259:446)
    at bi (react-dom.production.min.js:259:343)
    at yi (react-dom.production.min.js:258:431)
    at react-dom.production.min.js:282:96
    at ws (react-dom.production.min.js:280:398)
    at ls (react-dom.production.min.js:269:269)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)Understand this errorAI
src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:12 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'sendTo')
    at W.checkConfiguration (src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:12:8060)
    at W.<anonymous> (src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:12:10114)
    at Generator.next (<anonymous>)
    at src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:12:7894
    at new Promise (<anonymous>)
    at Pe (src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:12:7714)
    at W.componentDidMount (src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:12:10014)`

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'sendTo')
    at W.checkConfiguration (src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:12:8060)
    at W.<anonymous> (src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:12:10114)
    at Generator.next (<anonymous>)
    at src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:12:7894
    at new Promise (<anonymous>)
    at Pe (src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:12:7714)
    at W.componentDidMount (src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:12:10014)
    at ki (react-dom.production.min.js:260:217)
    at bi (react-dom.production.min.js:259:446)
    at bi (react-dom.production.min.js:259:343)
    at yi (react-dom.production.min.js:258:431)
    at react-dom.production.min.js:282:96
    at ws (react-dom.production.min.js:280:398)
    at is (react-dom.production.min.js:272:439)
    at Hl (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:266:273Understand this errorAI
8src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:9 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getObjectViewCustom')
    at N.<anonymous> (src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:9:19979)
    at Generator.next (<anonymous>)
    at src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:9:19628
    at new Promise (<anonymous>)
    at B (src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:9:19448)
    at N.componentDidMount (src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:9:19683)
    at ki (react-dom.production.min.js:260:217)
    at bi (react-dom.production.min.js:259:446)
    at bi (react-dom.production.min.js:259:343)
    at yi (react-dom.production.min.js:258:431)
    at react-dom.production.min.js:282:96
    at ws (react-dom.production.min.js:280:398)
    at is (react-dom.production.min.js:272:439)
    at Hl (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:266:273Understand this errorAI
src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:12 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'sendTo')
    at W.checkConfiguration (src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:12:8060)
    at W.<anonymous> (src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:12:10114)
    at Generator.next (<anonymous>)
    at src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:12:7894
    at new Promise (<anonymous>)
    at Pe (src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:12:7714)
    at W.componentDidMount (src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:12:10014)
    at ki (react-dom.production.min.js:260:217)
    at bi (react-dom.production.min.js:259:446)
    at bi (react-dom.production.min.js:259:343)
    at yi (react-dom.production.min.js:258:431)
    at react-dom.production.min.js:282:96
    at ws (react-dom.production.min.js:280:398)
    at is (react-dom.production.min.js:272:439)
    at Hl (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:266:273Understand this errorAI
src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:9 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'subscribeState')
    at C.<anonymous> (src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:9:1802)
    at Generator.next (<anonymous>)
    at src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:8:3215
    at new Promise (<anonymous>)
    at Z (src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:8:3035)
    at C.componentDidMount (src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:9:1702)
    at ki (react-dom.production.min.js:260:217)
    at bi (react-dom.production.min.js:259:446)
    at bi (react-dom.production.min.js:259:343)
    at yi (react-dom.production.min.js:258:431)
    at react-dom.production.min.js:282:96
    at ws (react-dom.production.min.js:280:398)
    at is (react-dom.production.min.js:272:439)
    at Hl (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:266:273Understand this errorAI
console.ts:40 TypeError: Cannot read properties of undefined (reading 'unsubscribeState')
    at C.componentWillUnmount (src_Components_jsx-src_assets_history_png.838b08ff.chunk.js:9:2202)`

### Adapter version

7.4.3

### js-controller version

7.0.3

### Node version

20.18.1

### Operating system

Linux

**Comment by Pritt60** [comment]
Kann ich bestätigen, habe das gleiche Problem. 
Bin darauf aufmerksam geworden weil das Backup beim Zugriff auf Influx-DB2 hängengeblieben ist.
Bei der Suche warum das so war, trat der beschriebene Fehler auf...

Admin: v7.4.3
backitup v3.0.31
js-controller 7.0.3
influxDB2 v4.0.2

VG
Pritt

**Comment by Brainbug01** [comment]
Works with 7.4.4
