### ISSUE TITLE
[bug]: Adminadapter - Error in GUI

### ISSUE THREAD

**Issue by Nepomukl** [ioBroker/ioBroker.admin#2849]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

In den Einstellungen der Admin GUI erscheint dieser Fehler. Ebenfalls in den Einstellungen des Telegram Adapters. 
Wenn ich den Admin Adapter auf 7.3.2 zurück setze ist dieser Fehler nicht mehr vorhanden. 
Neuinstallation sowie Fix haben nichts gebracht. Erst das zurück setzen des Admin Adapters.
Ich habe es gerade noch einmal probiert, ein zurück setzen auf 7.4.2 reicht auch.

### To Reproduce

Upgraden des Adapters auf 7.4.3 und der Fehler ist wieder da.

### Expected behavior

sollte gefixt werden

### Screenshots & Logfiles

`onpage-dialog.preload.js:118 Uncaught ReferenceError: browser is not defined
    at start (onpage-dialog.preload.js:118:5)
    at onpage-dialog.preload.js:132:1
    at onpage-dialog.preload.js:390:12Understand this errorAI
bootstrap.tsx:22 iobroker.admin@7.0.25
console.ts:40 [2024-12-07T14:45:32.253Z] Try to connect
console.ts:40 Stored version: , new version: 7.4.3
console.ts:40 Please add to "system.adapter.alexa2" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please modify "system.adapter.energiefluss" common.adminUI={"config":"materialize","tab":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.energiefluss-erweitert" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.flot" common.adminUI={"config":"none"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.hm-rega" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.icons-addictive-flavour-png" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.icons-material-png" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.icons-mfd-png" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.icons-mfd-svg" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.icons-ultimate-png" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.iot" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.lgtv11" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.sourceanalytix" common.adminUI={"config":"materialize","custom":"json"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.tr-064" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.vis-bars" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.vis-fancyswitch" common.adminUI={"config":"none"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.vis-history" common.adminUI={"config":"none"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.vis-icontwo" common.adminUI={"config":"materialize","tab":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.vis-inventwo" common.adminUI={"config":"materialize","tab":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.vis-jqui-mfd" common.adminUI={"config":"none"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.vis-materialdesign" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.vis-plumb" common.adminUI={"config":"none"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.vis-rgraph" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.yeelight-2" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please modify "system.adapter.zigbee2mqtt" common.adminUI={"config":"json","tab":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.homekit-controller" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.alexa2" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please modify "system.host.omv-iob.adapter.energiefluss" common.adminUI={"config":"materialize","tab":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.energiefluss-erweitert" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.flot" common.adminUI={"config":"none"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.hm-rega" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.icons-addictive-flavour-png" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.icons-material-png" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.icons-mfd-png" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.icons-mfd-svg" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.icons-ultimate-png" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.iot" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.lgtv11" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.sourceanalytix" common.adminUI={"config":"materialize","custom":"json"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.tr-064" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.vis-bars" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.vis-fancyswitch" common.adminUI={"config":"none"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.vis-history" common.adminUI={"config":"none"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.vis-icontwo" common.adminUI={"config":"materialize","tab":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.vis-inventwo" common.adminUI={"config":"materialize","tab":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.vis-jqui-mfd" common.adminUI={"config":"none"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.vis-materialdesign" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.vis-plumb" common.adminUI={"config":"none"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.vis-rgraph" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.yeelight-2" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please modify "system.host.omv-iob.adapter.zigbee2mqtt" common.adminUI={"config":"json","tab":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.homekit-controller" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 [ADAPTERS] getAdapters
console.ts:40 Please add to "system.host.omv-iob.adapter.alexa2" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please modify "system.host.omv-iob.adapter.energiefluss" common.adminUI={"config":"materialize","tab":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.energiefluss-erweitert" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.flot" common.adminUI={"config":"none"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.hm-rega" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.icons-addictive-flavour-png" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.icons-material-png" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.icons-mfd-png" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.icons-mfd-svg" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.icons-ultimate-png" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.iot" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.lgtv11" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.sourceanalytix" common.adminUI={"config":"materialize","custom":"json"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.tr-064" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.vis-bars" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.vis-fancyswitch" common.adminUI={"config":"none"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.vis-history" common.adminUI={"config":"none"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.vis-icontwo" common.adminUI={"config":"materialize","tab":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.vis-inventwo" common.adminUI={"config":"materialize","tab":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.vis-jqui-mfd" common.adminUI={"config":"none"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.vis-materialdesign" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.vis-plumb" common.adminUI={"config":"none"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.vis-rgraph" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.yeelight-2" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please modify "system.host.omv-iob.adapter.zigbee2mqtt" common.adminUI={"config":"json","tab":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.host.omv-iob.adapter.homekit-controller" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 [ADAPTERS] getAdaptersInfo
console.ts:40 [ADAPTERS] 2024-12-07T14:45:34.736Z Update cache!
console.ts:40 Render because of cachedAdapters 62 <> 0
console.ts:40 Render because of listOfVisibleAdapter
socketio.png:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)Understand this errorAI
ws.png:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)Understand this errorAI
console.ts:40 Please add to "system.adapter.alexa2" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.energiefluss-erweitert" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please modify "system.adapter.energiefluss" common.adminUI={"config":"materialize","tab":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.flot" common.adminUI={"config":"none"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.hm-rega" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.icons-addictive-flavour-png" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.icons-material-png" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.icons-mfd-png" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.icons-mfd-svg" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.icons-ultimate-png" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.iot" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.lgtv11" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.sourceanalytix" common.adminUI={"config":"materialize","custom":"json"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.tr-064" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.vis-bars" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.vis-fancyswitch" common.adminUI={"config":"none"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.vis-history" common.adminUI={"config":"none"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.vis-icontwo" common.adminUI={"config":"materialize","tab":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.vis-inventwo" common.adminUI={"config":"materialize","tab":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.vis-jqui-mfd" common.adminUI={"config":"none"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.vis-materialdesign" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.vis-plumb" common.adminUI={"config":"none"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.vis-rgraph" common.adminUI={"config":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.yeelight-2" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please modify "system.adapter.zigbee2mqtt" common.adminUI={"config":"json","tab":"html"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Please add to "system.adapter.homekit-controller" common.adminUI={"config":"materialize"}
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 system.adapter.admin.1
console.ts:40 system.adapter.alexa2.0
console.ts:40 system.adapter.backitup.0
console.ts:40 system.adapter.deyeidc.0
console.ts:40 system.adapter.discovery.0
console.ts:40 system.adapter.doorbird.0
console.ts:40 system.adapter.dwd.0
console.ts:40 system.adapter.echarts.0
console.ts:40 system.adapter.energiefluss.0
console.ts:40 system.adapter.energiefluss-erweitert.0
console.ts:40 system.adapter.flot.0
console.ts:40 system.adapter.fritzdect.0
console.ts:40 system.adapter.fullybrowser.0
console.ts:40 system.adapter.history.0
console.ts:40 system.adapter.hm-rega.0
console.ts:40 system.adapter.hm-rpc.0
console.ts:40 system.adapter.homekit-controller.0
console.ts:40 system.adapter.ical.0
console.ts:40 system.adapter.icons-addictive-flavour-png.0
console.ts:40 system.adapter.icons-material-png.0
console.ts:40 system.adapter.icons-mfd-png.0
console.ts:40 system.adapter.icons-mfd-svg.0
console.ts:40 system.adapter.icons-ultimate-png.0
console.ts:40 system.adapter.iot.0
console.ts:40 system.adapter.javascript.0
console.ts:40 system.adapter.lgtv11.0
console.ts:40 system.adapter.mqtt.0
console.ts:40 system.adapter.opendtu.0
console.ts:40 system.adapter.ping.0
console.ts:40 system.adapter.shelly.0
console.ts:40 system.adapter.shuttercontrol.0
console.ts:40 system.adapter.simple-api.0
console.ts:40 system.adapter.snmp.0
console.ts:40 system.adapter.sonoff.0
console.ts:40 system.adapter.sourceanalytix.0
console.ts:40 system.adapter.statistics.0
console.ts:40 system.adapter.telegram.0
console.ts:40 system.adapter.text2command.0
console.ts:40 system.adapter.tr-064.0
console.ts:40 system.adapter.vis.0
console.ts:40 system.adapter.vis-bars.0
console.ts:40 system.adapter.vis-canvas-gauges.0
console.ts:40 system.adapter.vis-fancyswitch.0
console.ts:40 system.adapter.vis-history.0
console.ts:40 system.adapter.vis-hqwidgets.0
console.ts:40 system.adapter.vis-icontwo.0
console.ts:40 system.adapter.vis-inventwo.0
console.ts:40 system.adapter.vis-jqui-mfd.0
console.ts:40 system.adapter.vis-lcars.0
console.ts:40 system.adapter.vis-materialdesign.0
console.ts:40 system.adapter.vis-metro.0
console.ts:40 system.adapter.vis-plumb.0
console.ts:40 system.adapter.vis-rgraph.0
console.ts:40 system.adapter.vis-timeandweather.0
console.ts:40 system.adapter.web.0
console.ts:40 system.adapter.yeelight-2.0
console.ts:40 system.adapter.yr.0
console.ts:40 system.adapter.zendure-solarflow.0
console.ts:40 system.adapter.zigbee.0
console.ts:40 system.adapter.zigbee2mqtt.0
console.ts:40 getInstances: 17
console.ts:40 Translate: controller
console.ts:40 fetch http://192.168.1.150:8081/validate_config/admin
console.ts:40 Translation for word "users permissions" in "de" was ignored: existing = "Gruppen-Rechte", new = Benutzerberechtigungen
(anonymous) @ console.ts:40Understand this warningAI
console.ts:40 Translate: manuell
console.ts:40 Translate: alle 12 Stunden
console.ts:40 Translate: jeden Tag
console.ts:40 Translate: alle 2 Tage
console.ts:40 Translate: alle 3 Tage
console.ts:40 Translate: jede Woche
console.ts:40 Translate: alle 2 Wochen
console.ts:40 Translate: Systemsprache
console.ts:40 AdminComponentEasyAccessSet Components ConfigCustomEasyAccess
console.ts:40 TypeError: Cannot read properties of undefined (reading 'getAdapterInstances')
    at f.componentDidMount (ConfigCustomEasyAccess.jsx:35:27)
    at ki (react-dom.production.min.js:260:217)
    at bi (react-dom.production.min.js:259:446)
    at bi (react-dom.production.min.js:259:343)
    at yi (react-dom.production.min.js:258:431)
    at react-dom.production.min.js:282:96
    at ws (react-dom.production.min.js:280:398)
    at ls (react-dom.production.min.js:269:269)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
(anonymous) @ console.ts:40Understand this errorAI`

### Adapter version

7.4.3

### js-controller version

7.0.4

### Node version

20.18.1

### Operating system

Debian

**Comment by Nepomukl** [comment]
Sorry, jetzt erst gesehen das es schon gemeldet wurde.
