### ISSUE TITLE
[bug]: Admin Adapter shows Error by enter ""Zugriff auf Instanzen" (simple mode)

### ISSUE THREAD

**Issue by Zlupo** [ioBroker/ioBroker.admin#2853]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

I cannot open the “Access to instances” tab in the admin instance settings.

### To Reproduce

I start Iobroker and log in to the browser. I click on “Instances” and then on Settings under Admin.0.
The admin settings are now open. When I select “Access to instances”, the error is displayed.

### Expected behavior

can you help me and suggest a solution

### Screenshots & Logfiles

TypeError: Cannot read properties of undefined (reading 'getAdapterInstances')
    at f.componentDidMount (ConfigCustomEasyAccess.jsx:35:27)
    at ki (react-dom.production.min.js:260:217)
    at bi (react-dom.production.min.js:259:446)
    at bi (react-dom.production.min.js:259:343)
    at yi (react-dom.production.min.js:258:431)
    at react-dom.production.min.js:282:96
    at ws (react-dom.production.min.js:280:398)
    at ls (react-dom.production.min.js:269:269)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
(anonym) @ console.ts:40
1 weiteren Frame anzeigen
Weniger anzeigen

### Adapter version

Admin: 7.4.3

### js-controller version

7.0.3

### Node version

20.18.0

### Operating system

Raspberry Pi 5 8GB RAM

**Comment by Zlupo** [comment]
when I downgrade the Admin Adapter to version 7.4.2 and everything works perfectly. When I upgrade to version 7.4.3 again, the error is there again.

**Comment by Feuer-sturm** [comment]
@Zlupo please check with current beta version of admin
