### ISSUE TITLE
[bug]: Error in GUI: Cannot read properties of undefined (reading 'unsubscribeState')

### ISSUE THREAD

**Issue by Gunter66** [ioBroker/ioBroker.admin#2856]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Error in GUI after adapter installed.

### To Reproduce

Install new Adapter (Hometatik IPHomeMatic IP Cloud-Zugriffspunkt)
adapter section appears but changed to the ERROR in GUI.

### Expected behavior

adapter settings available :-)

### Screenshots & Logfiles

TypeError: Cannot read properties of undefined (reading 'unsubscribeState')
    at g.componentWillUnmount (http://192.168.178.42:8081/adapter/hmip/custom/static/js/src_Components_jsx-node_modules_mui_system_esm_RtlProvider_index_js-node_modules_mui_system_e-44e065.d4eea41a.chunk.js:1:2056)
    at pi (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:96126)
    at di (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95213)
    at pi (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:96168)
    at di (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95213)
    at pi (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95411)
    at di (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95213)
    at pi (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95975)
    at di (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95213)
    at pi (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95975)
    at di (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95213)
    at pi (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95411)
    at di (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95213)
    at pi (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95975)
    at di (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95213)
    at pi (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95975)
    at di (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95213)
    at pi (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:96168)
    at di (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95213)
    at pi (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95411)
    at di (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95213)
    at pi (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:96168)
    at di (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95213)
    at pi (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95411)
    at di (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95213)
    at pi (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:96168)
    at di (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95213)
    at pi (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95411)
    at di (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95213)
    at pi (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95975)
    at di (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95213)
    at pi (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95975)
    at di (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95213)
    at pi (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:96168)
    at di (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95213)
    at pi (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95411)
    at di (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95213)
    at pi (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95975)
    at di (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95213)
    at pi (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95975)
    at di (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95213)
    at pi (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:96168)
    at di (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95213)
    at pi (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95975)
    at di (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95213)
    at pi (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:96260)
    at di (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95213)
    at pi (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:96300)
    at di (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95213)
    at pi (http://192.168.178.42:8081/static/js/5546.823d00ce.chunk.js:2:95411)

### Adapter version

1.25.0

### js-controller version

7.0.3

### Node version

20.18.1

### Operating system

linux (on rspberry 5 8GB)

**Comment by GermanBluefox** [comment]
Please test 7.4.7

**Comment by Feuer-sturm** [comment]
link to https://github.com/ioBroker/ioBroker.admin/issues/2835

@GermanBluefox please find my result of test with admin 7.4.8 here https://github.com/ioBroker/ioBroker.admin/issues/2835#issuecomment-2558512906

**Comment by mcm1957** [comment]
@Feuer-sturm 
@Gunter66 

Does the problem still exist with 7.6.3 ?

**Comment by Gunter66** [comment]
Hey. No, it works on my system. Thanks!
