### ISSUE TITLE
[bug]: Error in GUI when opening the tab files

### ISSUE THREAD

**Issue by timoSK08** [ioBroker/ioBroker.admin#2869]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Wenn ich im ioBroker den Tab Dateien öffne, kommt die Fehlermeldung "Error in GUI"

### To Reproduce

bei jedem Versuch den Tab "Dateien" zu öffnen

### Expected behavior

der Tab Dateien öffnet sich

### Screenshots & Logfiles

console.ts:40 Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ye (react-dom.production.min.js:50:341)
    at Ko (react-dom.production.min.js:229:311)
    at ks (react-dom.production.min.js:280:85)
    at bs (react-dom.production.min.js:279:450)
    at vs (react-dom.production.min.js:279:320)
    at gs (react-dom.production.min.js:279:180)
    at as (react-dom.production.min.js:270:88)
    at ls (react-dom.production.min.js:267:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)

﻿

### Adapter version

7.1.5 (admin)

### js-controller version

7.0.3

### Node version

v20.18.1

### Operating system

linux (raspberrypi 5)

**Comment by GermanBluefox** [comment]
Please test 7.4.7

**Comment by timoSK08** [comment]
with this update, it works again, thank you!
