### ISSUE TITLE
[bug]: Error in GUI!

### ISSUE THREAD

**Issue by e-i-k-e** [ioBroker/ioBroker.admin#2878]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

I navigated between objects, scripts, protocols and instances on the web interface. 
Suddenly the instance icons were no longer displayed to me. I reloaded the page but got no improvement. 
After I wanted to open the settings of an instance, I received this message.

Please open the browser console (F12), copy error text from there and create the issue on [github](https://github.com/ioBroker/ioBroker.admin/issues)
Without this information it is not possible to analyse the error.
It should looks like
error
If in the second line you will see at :3000/static/js/main.chunk.js:36903 and not the normal file name,
please try to reproduce an error with opened browser console. In this case the special "map" files will be loaded and the developers can see the real name of functions and files.
Loading chunk 3834 failed. (error: https://192.168.3.100:8081/static/js/3834.d81ffc60.chunk.js)
ChunkLoadError
    at r.f.j (https://192.168.3.100:8081/static/js/main.a833ed54.js:1:15668)
    at https://192.168.3.100:8081/static/js/main.a833ed54.js:1:1181
    at Array.reduce (<anonymous>)
    at r.e (https://192.168.3.100:8081/static/js/main.a833ed54.js:1:1159)
    at https://192.168.3.100:8081/static/js/288.23e8413f.chunk.js:1:1652048
    at P (https://192.168.3.100:8081/static/js/4303.41753ebf.chunk.js:2:3345)
    at xi (https://192.168.3.100:8081/static/js/5546.823d00ce.chunk.js:2:120729)
    at bs (https://192.168.3.100:8081/static/js/5546.823d00ce.chunk.js:2:109361)
    at vs (https://192.168.3.100:8081/static/js/5546.823d00ce.chunk.js:2:109289)
    at gs (https://192.168.3.100:8081/static/js/5546.823d00ce.chunk.js:2:109152)
    at is (https://192.168.3.100:8081/static/js/5546.823d00ce.chunk.js:2:106268)
    at Hl (https://192.168.3.100:8081/static/js/5546.823d00ce.chunk.js:2:46915)
    at https://192.168.3.100:8081/static/js/5546.823d00ce.chunk.js:2:103865`
    

### To Reproduce

-

### Expected behavior

-

### Screenshots & Logfiles

[cleaned_192.168.3.100-1734896391095.log](https://github.com/user-attachments/files/18223201/cleaned_192.168.3.100-1734896391095.log)
[cleaned_3834.d81ffc60.chunk.js.txt](https://github.com/user-attachments/files/18223207/cleaned_3834.d81ffc60.chunk.js.txt)

### Adapter version

7.4.8

### js-controller version

7.0.6

### Node version

20.18.1

### Operating system

Debian 12

### Additional context

-

**Comment by Feuer-sturm** [comment]
@e-i-k-e Please add to your description what you did to trigger the error. Thanks.

**Comment by e-i-k-e** [comment]
> @e-i-k-e Please add to your description what you did to trigger the error. Thanks.

done

**Comment by GermanBluefox** [comment]
This error comes if admin was updated, front-end not reloaded. The error should be gone, after the admin is restarted and Browser is refreshed (F5)

**Comment by Feuer-sturm** [comment]
@e-i-k-e please check if the issue does not exist any more after browser refreshing.

**Comment by mcm1957** [comment]
no feedback since januar.
Could be closed in my opinnion.

**Comment by mcm1957** [comment]
@Feuer-sturm 
I've added label "stale" to some issues which look orphaned to me. So those issues can be selected ruther fast for review from time to time. If it's ok for you it would be a good step that you review such issues and close them if you think my oppinion is correct / appropiate - or remove the stale if you think, theres something to processe or keep in evidence.

I will NOT decide to close any issues unless thea are created by me or explicitly conformed by creator as fixed.
