### ISSUE TITLE
upgrade to 3.4.9 has no effect

### ISSUE THREAD

**Issue by xyronx** [ioBroker/ioBroker.admin#296]
I have a problem with the update. 
following issues:
`sudo iobroker upgrade admin
Update admin from @3.4.7 to @3.4.9
host.raspberrypi3B Adapter "system.adapter.admin.0" is stopped.
NPM version: 3.10.10
npm install iobroker.admin@3.4.9 --production --save --prefix "/opt/iobroker" (System call)
/usr/lib/node_modules/npm/node_modules/request/node_modules/form-data/node_modules/asynckit/lib/abort.js:1
(function (exports, require, module, __filename, __dirname) {

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/node_modules/form-data/node_modules/asynckit/lib/iterate.js:2:13)
npm ERR! Linux 4.14.52-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "iobroker.admin@3.4.9" "--production" "--save" "--prefix" "/opt/iobroker"
npm ERR! node v6.14.1
npm ERR! npm  v3.10.10

npm ERR! Invalid or unexpected token
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
host.raspberrypi3B Adapter "system.adapter.admin.0" is started
npm install --production (System call) in "/opt/iobroker/node_modules/iobroker.js-controller/node_modules/iobroker.admin"
/usr/lib/node_modules/npm/node_modules/request/node_modules/form-data/node_modules/asynckit/lib/abort.js:1
(function (exports, require, module, __filename, __dirname) {

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/node_modules/form-data/node_modules/asynckit/lib/iterate.js:2:13)
npm ERR! Linux 4.14.52-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--production"
npm ERR! node v6.14.1
npm ERR! npm  v3.10.10

npm ERR! Invalid or unexpected token
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
got /opt/iobroker/node_modules/iobroker.js-controller/node_modules/iobroker.admin/admin
upload [3] admin.admin /opt/iobroker/node_modules/iobroker.js-controller/node_modules/iobroker.admin/admin/words.js words.js application/javascript
upload [2] admin.admin /opt/iobroker/node_modules/iobroker.js-controller/node_modules/iobroker.admin/admin/index_m.html index_m.html text/html
upload [1] admin.admin /opt/iobroker/node_modules/iobroker.js-controller/node_modules/iobroker.admin/admin/index.html index.html text/html
upload [0] admin.admin /opt/iobroker/node_modules/iobroker.js-controller/node_modules/iobroker.admin/admin/admin.png admin.png image/png
Adapter "admin" updated
`
What am I doing wrong?

**Comment by GermanBluefox** [comment]
npm cache clean
and try again

it is not the problem with admin
