### ISSUE TITLE
After udate admin.0 not working

### ISSUE THREAD

**Issue by Michaelnorge** [ioBroker/ioBroker.admin#381]
Error: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.admin/lib/../www/login/index.html'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at prepareLoginTemplate (/opt/iobroker/node_modules/iobroker.admin/lib/web.js:109:27)
    at Web.server.app.get (/opt/iobroker/node_modules/iobroker.admin/lib/web.js:243:46)
    at Layer.handle [as handle_request] (/opt/iobroker/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/iobroker/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/opt/iobroker/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/iobroker/node_modules/express/lib/router/layer.js:95:5)
    at /opt/iobroker/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/opt/iobroker/node_modules/express/lib/router/index.js:335:12

**Comment by GermanBluefox** [comment]
Cannot confirm. Please reinstall the adapter and report the adapter version

**Comment by WLAN-Kabel** [comment]
Please comment or reopen if the problem is not resolved.

**Comment by burow1978** [comment]
If you use HTTPS, use the original LINK:
https://"Your IP address":8081/
