### ISSUE TITLE
UnhandledPromiseRejectionWarning: ParserError: Protocol error, got "H" as reply type byte

### ISSUE THREAD

**Issue by jpawlowski** [ioBroker/ioBroker.admin#457]
With a fresh install using the `latest` repository, the admin adapter would through an error message (would still come up, so it's more a warning I suppose):

`````shell
root@demucvmcp01iob:/opt/iobroker# iob start admin.0
(node:1389) UnhandledPromiseRejectionWarning: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:190:15)
    at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:304:14)
(node:1389) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1389) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1389) UnhandledPromiseRejectionWarning: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:190:15)
    at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:304:14)
(node:1389) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
The adapter "admin.0" was started.
`````

It says "please report" so that's what I'm doing here.

You may easily replicate this using the official Docker beta image.

**Comment by jpawlowski** [comment]
It actually seems this warning appears whenever I use the command line interface so my apologies if this is not the correct place here.

**Comment by Apollon77** [comment]
Which js-Controller? It is a 2.0 ... with latest 2.0.35 this error should not appear anymore.

**Comment by Apollon77** [comment]
Ps: warning ;-)

**Comment by jpawlowski** [comment]
It is indeed version 2.0.35.

**Comment by jpawlowski** [comment]
I DID restart the services but it seems in order for this to work, opening a new shell is also required.
After this, the warnings no longer appear.

So in general it is wise to reboot the complete container to be on the safe side (maybe worth mentioning somewhere in the doc).
