### ISSUE TITLE
Error bei Buttonclick oben rechts 3.7.2

### ISSUE THREAD

**Issue by vr6syncro** [ioBroker/ioBroker.admin#470]
Wenn ich oben rechts auf das ioBroker Logo klicke kommt folgendes:
`Error: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.admin/lib/../src/configs.html'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at generateConfigPage (/opt/iobroker/node_modules/iobroker.admin/lib/web.js:213:20)
    at Layer.handle [as handle_request] (/opt/iobroker/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/iobroker/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/opt/iobroker/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/iobroker/node_modules/express/lib/router/layer.js:95:5)
    at /opt/iobroker/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/opt/iobroker/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/iobroker/node_modules/express/lib/router/index.js:275:10)`

**Comment by GermanBluefox** [comment]
Just restart admin
