### ISSUE TITLE
Admin adapter crashes with ring adapter 

### ISSUE THREAD

**Issue by schmupu** [ioBroker/ioBroker.admin#485]
Hello @GermanBluefox , @Apollon77 , ...

first, happy new year!!

**Error description** 
If you install the ring adapter in version >= 1.0.6,  the ring and admin adapter is running. If you restart the admin adapter, the admin adapter crashes with the error below.  The library ws is installed in version 1.1.1 .  If I stop the ring adapter and start the admin adapter, it will still crash. I have to remove the  ring adapter instance first, before the admin adapter does not crash anymore.

If I do a `npm update` in the `/opt/iobroker `directory a newer version (>= version 6) will be installed and the admin adapter does not crash anymore. 

**Question (I hope you can help me)**
1.  Why is the error  _"Cannot read property 'isValidUTF8' of undefined"_ thrown? What is the admin adapter checking at this point? Is there an error in one of the ring adapter files (wrong file type) which I can fix?
2. Is it possible that you install a newer ws version for the admin adapter?   

**Error logfile**
```
2020-01-03 07:44:08.340  - error: host.iobroker-test Caught by controller[0]: TypeError: Cannot read property 'isValidUTF8' of undefined
2020-01-03 07:44:08.344  - error: host.iobroker-test Caught by controller[0]:     at /opt/iobroker/node_modules/engine.io/node_modules/ws/lib/Receiver.js:532:29
2020-01-03 07:44:08.346  - error: host.iobroker-test Caught by controller[0]:     at /opt/iobroker/node_modules/engine.io/node_modules/ws/lib/Receiver.js:368:7
2020-01-03 07:44:08.347  - error: host.iobroker-test Caught by controller[0]:     at /opt/iobroker/node_modules/engine.io/node_modules/ws/lib/PerMessageDeflate.js:249:5
2020-01-03 07:44:08.348  - error: host.iobroker-test Caught by controller[0]:     at afterWrite (_stream_writable.js:485:3)
2020-01-03 07:44:08.348  - error: host.iobroker-test Caught by controller[0]:     at onwrite (_stream_writable.js:476:7)
2020-01-03 07:44:08.351  - error: host.iobroker-test Caught by controller[0]:     at InflateRaw.afterTransform (_stream_transform.js:94:3)
2020-01-03 07:44:08.352  - error: host.iobroker-test Caught by controller[0]:     at Zlib.processCallback (zlib.js:557:8)
2020-01-03 07:44:08.353  - info: host.iobroker-test instance system.adapter.admin.0 terminated with code 0 (NO_ERROR)
```
other user have the error in file /opt/iobroker/node_modules/ws/lib/Receiver.js instead of /opt/iobroker/node_modules/**engine.io**/node_modules/ws/lib/Receiver.js . 

I hope you can help me and you have an idea how to fix the error. If I have a chance to fix the error in the ring adapter please contact me.

Thanx
Stübi

**Comment by Apollon77** [comment]
@GermanBluefox could the old socket.io be the reason (again)?

**Comment by Jey-Cee** [comment]
I saw the same error. The only solution was to remove the ring instance. 
`npm update` has no effect before the instance was deleted.

**Comment by schmupu** [comment]
Workaround, in die einzelnen Adapter gehen die es betrifft wie z.B. ioBroker.socketio und ein npm Install ws@7.2.1 ausführen. Danach ging bei mir wieder alles.

**Comment by Apollon77** [comment]
We currently try to update socketio to 2.3 in Web and also Admin. So we should solve this by that. Or from which dep we get ws?

**Comment by Apollon77** [comment]
We have a branch from socketio and web adapters with updated socketio lib to 2.3 ... an admin branch is there too

**Comment by Apollon77** [comment]
Please check Admin 4.0.0

**Comment by Apollon77** [comment]
@schmupu checked?

**Comment by schmupu** [comment]
I have no problems anymore
