### ISSUE TITLE
Admin 5.0.4: Login not possible, adapter crashes (Cannot read property 'replace' of undefined)

### ISSUE THREAD

**Issue by cernst1980** [ioBroker/ioBroker.admin#710]
2021-04-19 12:22:07.674  - error: admin.1 (72155) uncaught exception: Cannot read property 'replace' of undefined
2021-04-19 12:22:07.675  - error: admin.1 (72155) TypeError: Cannot read property 'replace' of undefined
    at Immediate.<anonymous> (/usr/local/www/iobroker/node_modules/iobroker.admin/lib/web.js:451:52)
    at processImmediate (internal/timers.js:463:21)
2021-04-19 12:22:07.676  - error: admin.1 (72155) Cannot read property 'replace' of undefined
2021-04-19 12:22:07.680  - info: admin.1 (72155) terminating https server on port 8081
2021-04-19 12:22:07.681  - info: admin.1 (72155) terminating
2021-04-19 12:22:07.681  - warn: admin.1 (72155) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-04-19 12:22:08.269  - error: host.iobroker.intern.ernst1980.de instance system.adapter.admin.1 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-04-19 12:22:08.271  - info: host.iobroker.intern.ernst1980.de Restart adapter system.adapter.admin.1 because enabled

 - Adapter version: 5.0.4
 - JS-Controller version: 3.2.16
 - Node version: v12.21.0
 - Operating system: FreeBSD 12.2-RELEASE-p6

New instance of adapter (HTTP or HTTPS without login) works.

**Comment by Apollon77** [comment]
Will be fixed in next version

**Comment by MarkSau** [comment]
have the same issue with 5.0.4, please fix

**Comment by Apollon77** [comment]
Please check 5.0.5

**Comment by cernst1980** [comment]
fixed with version 5.0.5
