### ISSUE TITLE
Admin 5.0.5: Login not possible, adapter crashes (Cannot read property 'replace' of undefined)

### ISSUE THREAD

**Issue by ujconsulting** [ioBroker/ioBroker.admin#735]
**Describe the bug**  
Same as in #710 - Admin Adapter crashes with same error.
Webinterface after Login not available: Cannot POST /login error

**Screenshots & Logfiles**  
2021-04-21 16:04:51.615  - info: admin.0 (16225) starting. Version 5.0.4 in /opt/iobroker/node_modules/iobroker.a                                                                 dmin, node: v12.22.1, js-controller: 3.2.16
2021-04-21 16:04:51.672  - info: admin.0 (16225) requesting all states
2021-04-21 16:04:51.673  - info: admin.0 (16225) requesting all objects
2021-04-21 16:04:53.331  - info: admin.0 (16225) received all objects
2021-04-21 16:04:53.524  - info: admin.0 (16225) http server listening on port 8081
2021-04-21 16:04:53.525  - info: admin.0 (16225) Use link "http://localhost:8081" to configure.
**2021-04-21 16:04:55.241  - error: admin.0 (16225) uncaught exception: Cannot read property 'replace' of undefined**
**2021-04-21 16:04:55.242  - error: admin.0 (16225) TypeError: Cannot read property 'replace' of undefined**
    at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.admin/lib/web.js:451:52)
    at processImmediate (internal/timers.js:463:21)
**2021-04-21 16:04:55.242  - error: admin.0 (16225) Cannot read property 'replace' of undefined**
**2021-04-21 16:04:55.260  - info: admin.0 (16225) terminating http server on port 8081**
2021-04-21 16:04:55.261  - info: admin.0 (16225) terminating
**2021-04-21 16:04:55.263  - warn: admin.0 (16225) Terminated (UNCAUGHT_EXCEPTION): Without reason**
2021-04-21 16:04:55.687  - error: host.pihome Caught by controller[0]: TypeError: Cannot read property 'replace'                                                                  of undefined
2021-04-21 16:04:55.688  - error: host.pihome Caught by controller[0]:     at Immediate.<anonymous> (/opt/iobroke                                                                 r/node_modules/iobroker.admin/lib/web.js:451:52)
2021-04-21 16:04:55.688  - error: host.pihome Caught by controller[0]:     at processImmediate (internal/timers.j                                                                 s:463:21)
2021-04-21 16:04:55.689  - error: host.pihome instance system.adapter.admin.0 terminated with code 1 (JS_CONTROLL                                                                 ER_STOPPED)
2021-04-21 16:04:55.689  - info: host.pihome Restart adapter system.adapter.admin.0 because enabled
2021-04-21 16:04:55.702  - debug: musiccast.0 (4599) system.adapter.admin.0: logging false
2021-04-21 16:05:25.735  - info: host.pihome instance system.adapter.admin.0 started with pid 16648
2021-04-21 16:05:28.039  - info: admin.0 (16648) starting. Version 5.0.4 in /opt/iobroker/node_modules/iobroker.a                                                                 dmin, node: v12.22.1, js-controller: 3.2.16
2021-04-21 16:05:28.099  - info: admin.0 (16648) requesting all states
2021-04-21 16:05:28.100  - info: admin.0 (16648) requesting all objects
2021-04-21 16:05:29.716  - info: admin.0 (16648) received all objects
2021-04-21 16:05:29.910  - info: admin.0 (16648) http server listening on port 8081
2021-04-21 16:05:29.910  - info: admin.0 (16648) Use link "http://localhost:8081" to configure.
2021-04-21 16:06:44.220  - info: influxdb.0 (4689) Store 101 buffered influxDB history points
2021-04-21 16:07:56.666  - info: javascript.0 (3214) script.js.Wetter: Material Design Widgets: Wetter Skript tri                                                                 ggered by 'zigbee.0.00158d0004658d25.temperature'
2021-04-21 16:09:20.951  - error: admin.0 (16648) uncaught exception: Cannot read property 'replace' of undefined
2021-04-21 16:09:20.952  - error: admin.0 (16648) TypeError: Cannot read property 'replace' of undefined
    at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.admin/lib/web.js:451:52)
    at processImmediate (internal/timers.js:463:21)
2021-04-21 16:09:20.953  - error: admin.0 (16648) Cannot read property 'replace' of undefined
2021-04-21 16:09:20.972  - info: admin.0 (16648) terminating http server on port 8081
2021-04-21 16:09:20.973  - info: admin.0 (16648) terminating
2021-04-21 16:09:20.975  - warn: admin.0 (16648) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-04-21 16:09:21.431  - error: host.pihome Caught by controller[0]: TypeError: Cannot read property 'replace'                                                                  of undefined
2021-04-21 16:09:21.436  - error: host.pihome Caught by controller[0]:     at Immediate.<anonymous> (/opt/iobroke                                                                 r/node_modules/iobroker.admin/lib/web.js:451:52)
2021-04-21 16:09:21.436  - error: host.pihome Caught by controller[0]:     at processImmediate (internal/timers.j                                                                 s:463:21)
2021-04-21 16:09:21.437  - error: host.pihome instance system.adapter.admin.0 terminated with code 1 (JS_CONTROLL                                                                 ER_STOPPED)

**Versions:**  
 - Adapter version: 5.05
 - JS-Controller version: 3.2.16
 - Node version: 12.22.1
 - Operating system: debian buster

**Comment by Apollon77** [comment]
please check again your version. the log states: "starting. Version 5.0.4" and this was fixed in 5.0.5

**Comment by Apollon77** [comment]
maybe run upgrade manually on cli "iobroker upgrade admin@5.0.5"

**Comment by ujconsulting** [comment]
works now... upgrade manualy done. :) Sorry not to see that...
