### ISSUE TITLE
Uncaught exception: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#915]
Master Admin 5.0.30
Slave Admin 5.0.30

Master
```
proxmox@ioBrokerTestsystem:~$ iobroker multihost status
No configuration change needed.


Multihost discovery server: disabled
Discovery authentication:   enabled
Persistent activation:      disabled
Objects:                    file on 0.0.0.0
States:                     file on 0.0.0.0
```

Slave

```
proxmox@ioBrokerNew:~$ iobroker multihost status
No configuration change needed.


Multihost discovery server: disabled
Discovery authentication:   enabled
Persistent activation:      disabled
Objects:                    file on 192.168.178.77
States:                     file on 192.168.178.77
```

If I enter in host basic settings on the master the submenu "Multihost" the following error will be shown:
![grafik](https://user-images.githubusercontent.com/25422320/119197733-85521600-ba88-11eb-8044-19e2f7d16d5c.png)

After a few secons I am able to activate the checkbox "Allow slave connections".
If I do this and confirm the reset during restart the following error will be shown in the log and iobroker makes always a reset:

In which cases is there a need to activate "Allow slave connections"
I configured multihost in the past on the CLI

```
21 May 2021 22:43:30.774
 iobrokerTestsystem host.ioBrokerTestsystem TypeError: Cannot read property 'startsWith' of undefined at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/main.js:196:60) at processImmediate (internal/timers.js:463:21)
21 May 2021 22:43:30.772
 iobrokerTestsystem host.ioBrokerTestsystem uncaught exception: Cannot read property 'startsWith' of undefined
21 May 2021 22:43:30.218
 iobrokerTestsystem host.ioBrokerTestsystem added notifications configuration of host
21 May 2021 22:43:29.987
 iobrokerTestsystem host.ioBrokerTestsystem connected to Objects and States
21 May 2021 22:43:28.936
 iobrokerTestsystem host.ioBrokerTestsystem ip addresses: 192.168.178.77 fe80::f854:cfff:fe5f:6c25
21 May 2021 22:43:28.935
 iobrokerTestsystem host.ioBrokerTestsystem hostname: ioBrokerTestsystem, node: v12.21.0
21 May 2021 22:43:28.933
 iobrokerTestsystem host.ioBrokerTestsystem Copyright (c) 2014-2021 bluefox, 2014 hobbyquaker
21 May 2021 22:43:28.929
 iobrokerTestsystem host.ioBrokerTestsystem iobroker.js-controller version 3.3.10 js-controller starting
21 May 2021 22:43:28.788
 iobrokerTestsystemSlave zwave2.0 (2132) Objects database error: connect ECONNREFUSED 192.168.178.77:9001
21 May 2021 22:43:28.785
 iobrokerTestsystemSlave zwave2.0 (2132) States database error: connect ECONNREFUSED 192.168.178.77:9000
21 May 2021 22:43:28.782
 iobrokerTestsystemSlave history.1 (2117) States database error: connect ECONNREFUSED 192.168.178.77:9000
21 May 2021 22:43:28.779
 iobrokerTestsystemSlave history.1 (2117) Objects database error: connect ECONNREFUSED 192.168.178.77:9001
21 May 2021 22:43:28.756
 iobrokerTestsystemSlave host.ioBrokerNew States database error: connect ECONNREFUSED 192.168.178.77:9000
21 May 2021 22:43:28.753
 iobrokerTestsystemSlave host.ioBrokerNew Objects database error: connect ECONNREFUSED 192.168.178.77:9001
21 May 2021 22:43:25.691
 iobrokerTestsystem host.ioBrokerTestsystem added notifications configuration of host
21 May 2021 22:43:25.512
 iobrokerTestsystem host.ioBrokerTestsystem connected to Objects and States
21 May 2021 22:43:24.446
 iobrokerTestsystem host.ioBrokerTestsystem ip addresses: 192.168.178.77 fe80::f854:cfff:fe5f:6c25
21 May 2021 22:43:24.444
 iobrokerTestsystem host.ioBrokerTestsystem hostname: ioBrokerTestsystem, node: v12.21.0
21 May 2021 22:43:24.443
 iobrokerTestsystem host.ioBrokerTestsystem Copyright (c) 2014-2021 bluefox, 2014 hobbyquaker
21 May 2021 22:43:24.438
 iobrokerTestsystem host.ioBrokerTestsystem iobroker.js-controller version 3.3.10 js-controller starting
21 May 2021 22:43:23.763
 iobrokerTestsystemSlave zwave2.0 (2132) States database error: connect ECONNREFUSED 192.168.178.77:9000
21 May 2021 22:43:23.760
 iobrokerTestsystemSlave history.1 (2117) Objects database error: connect ECONNREFUSED 192.168.178.77:9001
21 May 2021 22:43:23.756
 iobrokerTestsystemSlave history.1 (2117) States database error: connect ECONNREFUSED 192.168.178.77:9000
21 May 2021 22:43:23.752
 iobrokerTestsystemSlave zwave2.0 (2132) Objects database error: connect ECONNREFUSED 192.168.178.77:9001
21 May 2021 22:43:23.745
 iobrokerTestsystemSlave host.ioBrokerNew Objects database error: connect ECONNREFUSED 192.168.178.77:9001
21 May 2021 22:43:23.743
 iobrokerTestsystemSlave host.ioBrokerNew States database error: connect ECONNREFUSED 192.168.178.77:9000
21 May 2021 22:43:22.038
 iobrokerTestsystem host.ioBrokerTestsystem iobroker _restart
21 May 2021 22:43:22.027
 iobrokerTestsystem host.ioBrokerTestsystem TypeError: Cannot read property 'startsWith' of undefined at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/main.js:196:60) at processImmediate (internal/timers.js:463:21)
21 May 2021 22:43:22.025
 iobrokerTestsystem host.ioBrokerTestsystem uncaught exception: Cannot read property 'startsWith' of undefined
21 May 2021 22:43:21.488
 iobrokerTestsystem host.ioBrokerTestsystem added notifications configuration of host
21 May 2021 22:43:21.283
 iobrokerTestsystem host.ioBrokerTestsystem connected to Objects and States
21 May 2021 22:43:20.193
 iobrokerTestsystem host.ioBrokerTestsystem ip addresses: 192.168.178.77 fe80::f854:cfff:fe5f:6c25
21 May 2021 22:43:20.191
 iobrokerTestsystem host.ioBrokerTestsystem hostname: ioBrokerTestsystem, node: v12.21.0
21 May 2021 22:43:20.190
 iobrokerTestsystem host.ioBrokerTestsystem Copyright (c) 2014-2021 bluefox, 2014 hobbyquaker
21 May 2021 22:43:20.186
 iobrokerTestsystem host.ioBrokerTestsystem iobroker.js-controller version 3.3.10 js-controller starting
21 May 2021 22:43:17.751
 iobrokerTestsystemSlave history.1 (2117) Objects database successfully reconnected
21 May 2021 22:43:17.736
 iobrokerTestsystemSlave host.ioBrokerNew Objects database successfully reconnected
21 May 2021 22:43:16.243
 iobrokerTestsystem host.ioBrokerTestsystem connected to Objects and States
21 May 2021 22:43:14.316
 iobrokerTestsystem host.ioBrokerTestsystem ip addresses: 192.168.178.77 fe80::f854:cfff:fe5f:6c25
21 May 2021 22:43:14.312
 iobrokerTestsystem host.ioBrokerTestsystem hostname: ioBrokerTestsystem, node: v12.21.0
21 May 2021 22:43:14.310
 iobrokerTestsystem host.ioBrokerTestsystem Copyright (c) 2014-2021 bluefox, 2014 hobbyquaker
21 May 2021 22:43:14.305
 iobrokerTestsystem host.ioBrokerTestsystem iobroker.js-controller version 3.3.10 js-controller starting
```

**Comment by Apollon77** [comment]
"Activate slave connections" is basically the same as doing "iobroker multihost enable" which allows discovery

Can you please show your "iobroker.json" after you did that change via admin?

**Comment by Apollon77** [comment]
In fact this is a controller issue I will fix ... because it seems that the password which is normally defined when ebnabling slave connections is not existing!
@GermanBluefox I think this also needs to be added to the config to be entered. But I will adjust contreoller that it does not crash

**Comment by Feuer-sturm** [comment]
@Apollon77 Do you still need my iobroker.json?

**Comment by Apollon77** [comment]
no ... :-) password is undefined

**Comment by Feuer-sturm** [comment]
@Apollon77 

Master: js-contrller 3.3.11
Slave: js-controller 3.3.11

I retested this issue with new js-controller. There is now different error in the log and still an error in the browser console.

```
23 May 2021 22:33:56.773
 iobrokerTestsystem admin.0 (6899) Use link "http://localhost:8081" to configure.
23 May 2021 22:33:56.772
 iobrokerTestsystem admin.0 (6899) http server listening on port 8081
23 May 2021 22:33:56.568
 iobrokerTestsystem admin.0 (6899) received all objects
23 May 2021 22:33:53.475
 iobrokerTestsystem admin.0 (6899) requesting all objects
23 May 2021 22:33:53.471
 iobrokerTestsystem admin.0 (6899) requesting all states
23 May 2021 22:33:53.358
 iobrokerTestsystem admin.0 (6899) starting. Version 5.0.31 in /opt/iobroker/node_modules/iobroker.admin, node: v12.22.1, js-controller: 3.3.11
23 May 2021 22:33:49.886
 iobrokerTestsystem host.ioBrokerTestsystem instance system.adapter.admin.0 started with pid 6899
23 May 2021 22:33:19.801
 iobrokerTestsystem host.ioBrokerTestsystem Restart adapter system.adapter.admin.0 because enabled
23 May 2021 22:33:19.799
 iobrokerTestsystem host.ioBrokerTestsystem instance system.adapter.admin.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
23 May 2021 22:33:19.798
 iobrokerTestsystem host.ioBrokerTestsystem Caught by controller[0]: at processImmediate (internal/timers.js:463:21)
23 May 2021 22:33:19.797
 iobrokerTestsystem host.ioBrokerTestsystem Caught by controller[0]: at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.admin/lib/socket.js:1370:88)
23 May 2021 22:33:19.795
 iobrokerTestsystem host.ioBrokerTestsystem Caught by controller[0]: at Object.decrypt (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1874:79)
23 May 2021 22:33:19.794
 iobrokerTestsystem host.ioBrokerTestsystem Caught by controller[0]: at Decipheriv.final (internal/crypto/cipher.js:172:29)
23 May 2021 22:33:19.792
 iobrokerTestsystem host.ioBrokerTestsystem Caught by controller[0]: Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
```

![grafik](https://user-images.githubusercontent.com/25422320/119275839-98472080-bc17-11eb-8352-85a3e0ec9802.png)

**Comment by Apollon77** [comment]
@Feuer-sturm you did and post here and deleted it ... so solved or not?

**Comment by Feuer-sturm** [comment]
@Apollon77 
I deleted my first feedback because I wanted to do some more tests. Here is my feedback:


## Multihost default setting
- iobroker with js-controller 3.3.10
- Update to Admin 5.1.0
- Update to 3.3.11
- Start of iobroker
- Entering Multihostmenu which looks like this
![grafik](https://user-images.githubusercontent.com/25422320/119544542-17f8fa80-bd92-11eb-8f21-9936b3eb63d9.png)
- Error is in the browser console if Multihost menu is activated
![grafik](https://user-images.githubusercontent.com/25422320/119558667-fa339180-bda1-11eb-86c1-3cba6bca92e6.png)


Question: What is the expected behavior if multihost was configrued over CLI an user enters the first time the "Multihost" menu in Host Basic settings?


- After entering a "Multi-Host-Passwort" and manual restart of iobroker no error is shown in the browser console if the menu "multihost" is selected




## Changing configuration Multihost
If I activate "Slave-Verbindungen zulassen" this will first have an effect if I make a manual restart of iobroker host.
In the past there was a message after saving that a restart of the controller is necessary and if this message was confirmed iobroker host was restarted. With Admin 5.1.0 and js-controller 3.3.11 this does not happen.

Is this a new issue for Admin?

**Comment by GermanBluefox** [comment]
> Is this a new issue for Admin?

Yes
