### ISSUE TITLE
beim aufrufen von Objekten absturz

### ISSUE THREAD

**Issue by spidermike-74** [ioBroker/ioBroker.admin#933]
**Describe the bug**  instrument.ts:129 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Oi (http://192.168.178.78:8081/static/js/5.acef7c19.chunk.js:2:5455560)
    at jl (http://192.168.178.78:8081/static/js/5.acef7c19.chunk.js:2:5467372)
    at t.unstable_runWithPriority (http://192.168.178.78:8081/static/js/5.acef7c19.chunk.js:2:5493961)
    at Wa (http://192.168.178.78:8081/static/js/5.acef7c19.chunk.js:2:5410347)
    at Sl (http://192.168.178.78:8081/static/js/5.acef7c19.chunk.js:2:5465330)
    at ml (http://192.168.178.78:8081/static/js/5.acef7c19.chunk.js:2:5461416)
    at http://192.168.178.78:8081/static/js/5.acef7c19.chunk.js:2:5410570
    at t.unstable_runWithPriority (http://192.168.178.78:8081/static/js/5.acef7c19.chunk.js:2:5493961)
    at Wa (http://192.168.178.78:8081/static/js/5.acef7c19.chunk.js:2:5410347)
    at Ga (http://192.168.178.78:8081/static/js/5.acef7c19.chunk.js:2:5410515)
    at Ua (http://192.168.178.78:8081/static/js/5.acef7c19.chunk.js:2:5410450)
    at hl (http://192.168.178.78:8081/static/js/5.acef7c19.chunk.js:2:5458560)
    at Object.enqueueForceUpdate (http://192.168.178.78:8081/static/js/5.acef7c19.chunk.js:2:5414775)
    at s.m.forceUpdate (http://192.168.178.78:8081/static/js/5.acef7c19.chunk.js:2:5485559)
    at http://192.168.178.78:8081/static/js/2.a7ae975c.chunk.js:1:11300
    at r (http://192.168.178.78:8081/static/js/5.acef7c19.chunk.js:2:6075150)

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by GermanBluefox** [comment]
Is this error after update of admin? F5 should help to fix the error

**Comment by spidermike-74** [comment]
Ja nach update des admin Adapters.--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 24.05.21, 19:09 schrieb Bluefox ***@***.***>:

   
  Is this error after update of admin? F5 should help to fix the error
