### ISSUE TITLE
Fehler bei Hilfe für sourceanalytix

### ISSUE THREAD

**Issue by Semmy100** [ioBroker/ioBroker.admin#954]
Das ist die Fehlermeldung in der Console, wenn ich auf das Fragezeichen von sourceanalytix klicke:

instrument.ts:129 DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('img<') is not a valid name.
    at ai (http://192.168.20.55:8081/static/js/5.47bf7541.chunk.js:2:5443604)
    at Vl (http://192.168.20.55:8081/static/js/5.47bf7541.chunk.js:2:5464884)
    at Cl (http://192.168.20.55:8081/static/js/5.47bf7541.chunk.js:2:5464766)
    at Hl (http://192.168.20.55:8081/static/js/5.47bf7541.chunk.js:2:5464633)
    at El (http://192.168.20.55:8081/static/js/5.47bf7541.chunk.js:2:5464496)
    at ml (http://192.168.20.55:8081/static/js/5.47bf7541.chunk.js:2:5461462)
    at http://192.168.20.55:8081/static/js/5.47bf7541.chunk.js:2:5410841
    at t.unstable_runWithPriority (http://192.168.20.55:8081/static/js/5.47bf7541.chunk.js:2:5494232)
    at Wa (http://192.168.20.55:8081/static/js/5.47bf7541.chunk.js:2:5410618)
    at Ga (http://192.168.20.55:8081/static/js/5.47bf7541.chunk.js:2:5410786)
    at Ua (http://192.168.20.55:8081/static/js/5.47bf7541.chunk.js:2:5410721)
    at hl (http://192.168.20.55:8081/static/js/5.47bf7541.chunk.js:2:5458831)
    at Object.enqueueSetState (http://192.168.20.55:8081/static/js/5.47bf7541.chunk.js:2:5414739)
    at a.m.setState (http://192.168.20.55:8081/static/js/5.47bf7541.chunk.js:2:5485743)
    at a.<anonymous> (http://192.168.20.55:8081/static/js/main.90e72440.chunk.js:2:1164349)
    at u (http://192.168.20.55:8081/static/js/5.47bf7541.chunk.js:2:5496720)
    at Generator._invoke (http://192.168.20.55:8081/static/js/5.47bf7541.chunk.js:2:5496508)
    at Generator.next (http://192.168.20.55:8081/static/js/5.47bf7541.chunk.js:2:5497145)
    at r (http://192.168.20.55:8081/static/js/5.47bf7541.chunk.js:2:40143)
    at i (http://192.168.20.55:8081/static/js/5.47bf7541.chunk.js:2:40346)
(anonymous) @ instrument.ts:129
stateSettings.png:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
mainSettings.png:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
stateStartValues.png:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

**Comment by GermanBluefox** [comment]
Wo ist dieses Fragezeichen? Custom? Config?

**Comment by Semmy100** [comment]
Bei Adapter Liesmich

**Comment by DutchmanNL** [comment]
@GermanBluefox included in SA release 0.4.9. please close
