### ISSUE TITLE
Error in GUI!

### ISSUE THREAD

**Issue by Hosenroller** [ioBroker/ioBroker.admin#961]
Hallo

Ich habe noch nicht so oft ein ISSUE eröffnet.
Ich habe in einer alten Session auf das IOBROKER Icon geclickt (switch to EASY ADMIN)
Dann habe ich eine Meldung bekommen ein Issue aufzumachen.
Ich hoffe ihr könnt mit den Infos was anfangen

iobroker.admin@5.1.2
instrument.ts:129 [2021-05-27T07:36:22.238Z] Try to connect
instrument.ts:129 Translate: esphome
​ iobroker.javascript@5.1.3 using theme "dark"
​ 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

​ Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
​ Help us to create open source project with reactJS!
​ See you :)
​ [2021-05-27T07:36:28.452Z] Try to connect
​ Detected custom blockly: cloud
​ Detected custom blockly: iot
​ Detected custom blockly: iqontrol
​ Detected custom blockly: pushover
​ Detected custom blockly: whatsapp-cmb
sentry.iobroker.net/api/56/envelope/?sentry_key=504499a725eb4898930d3b9e9da95740&sentry_version=7:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
2:8081/adapter/javasc…b6edad9e.chunk.js:2 Uncaught Error: Cannot read property '0' of null

TypeError: Cannot read property '0' of null
    at l.fire (http://192.168.0.5:8081/adapter/javascript/vs/editor/editor.main.js:71:956)
    at n.i.onMouseDown (http://192.168.0.5:8081/adapter/javascript/vs/editor/editor.main.js:1754:445)
    at n.emitMouseDown (http://192.168.0.5:8081/adapter/javascript/vs/editor/editor.main.js:1632:400)
    at t.ViewController.emitMouseDown (http://192.168.0.5:8081/adapter/javascript/vs/editor/editor.main.js:1432:295)
    at u._onMouseDown (http://192.168.0.5:8081/adapter/javascript/vs/editor/editor.main.js:1620:706)
    at http://192.168.0.5:8081/adapter/javascript/vs/editor/editor.main.js:1618:66
    at HTMLDivElement.<anonymous> (http://192.168.0.5:8081/adapter/javascript/vs/editor/editor.main.js:437:386)
    at HTMLDivElement.a (http://192.168.0.5:8081/adapter/javascript/static/js/2.b6edad9e.chunk.js:2:79218)
sentry.iobroker.net/api/56/store/?sentry_key=504499a725eb4898930d3b9e9da95740&sentry_version=7:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
5:8081/adapter/javasc…b6edad9e.chunk.js:2 Uncaught Error: Cannot read property '0' of null

TypeError: Cannot read property '0' of null
    at l.fire (http://192.168.0.5:8081/adapter/javascript/vs/editor/editor.main.js:71:956)
    at n.i.onMouseDown (http://192.168.0.5:8081/adapter/javascript/vs/editor/editor.main.js:1754:445)
    at n.emitMouseDown (http://192.168.0.5:8081/adapter/javascript/vs/editor/editor.main.js:1632:400)
    at t.ViewController.emitMouseDown (http://192.168.0.5:8081/adapter/javascript/vs/editor/editor.main.js:1432:295)
    at u._onMouseDown (http://192.168.0.5:8081/adapter/javascript/vs/editor/editor.main.js:1620:706)
    at http://192.168.0.5:8081/adapter/javascript/vs/editor/editor.main.js:1618:66
    at HTMLDivElement.<anonymous> (http://192.168.0.5:8081/adapter/javascript/vs/editor/editor.main.js:437:386)
    at HTMLDivElement.a (http://192.168.0.5:8081/adapter/javascript/static/js/2.b6edad9e.chunk.js:2:79218)
​ [2021-05-27T12:25:48.832Z] ws connection error: CLOSE_ABNORMAL
(anonymous) @ :8081/adapter/javasc…b6edad9e.chunk.js:2
​ [2021-05-27T12:25:48.896Z] Start reconnect 0
instrument.ts:129 [2021-05-27T12:25:48.902Z] ws connection error: CLOSE_ABNORMAL
(anonymous) @ instrument.ts:129
instrument.ts:129 [2021-05-27T12:25:49.336Z] Start reconnect 0
gc.kis.v2.scr.kaspersky-labs.com/7D8B79A2-8974-4D7B-A76A-F4F29624C06Bbinf4Px_oePKP2_9sg7TApjYsvk4LRwBhg9B_CqWTLy9NDbVrMgvwlWYV55N2F97MYfxjKommrYAZCtUqowg2g/init?url=http%3A%2F%2F192.168.0.5%3A8081%2F&plugins=wsm%26wnt%26kpm%26vs%26ua%26cb%26xhr_content&data=%7B%22data%22%3A%5B%7B%22plugin%22%3A%22wsm%22%2C%22parameters%22%3A%22%7B%5C%22referrer%5C%22%3A%5C%22%5C%22%2C%5C%22stubId%5C%22%3A%5C%22%5C%22%7D%22%7D%2C%7B%22plugin%22%3A%22wnt%22%2C%22parameters%22%3A%22%7B%5C%22referrer%5C%22%3A%5C%22%5C%22%7D%22%7D%2C%7B%22plugin%22%3A%22xhr_content%22%2C%22parameters%22%3A%22%7B%5C%22referrer%5C%22%3A%5C%22%5C%22%7D%22%7D%5D%7D&isTopLevel=true&nocache=16cab:1 Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
gc.kis.v2.scr.kaspersky-labs.com/7D8B79A2-8974-4D7B-A76A-F4F29624C06BvXGmVRqtqpXygOGlY0HuXk6s48BMXyXBPvxZXYOh8tx5Arf4D8PyPjPJDEy2LRau5T6nNFRavX9z3NSZ_Np9UA/init?url=http%3A%2F%2F192.168.0.5%3A8081%2Fadapter%2Fjavascript%2Ftab.html%3FnewReact%3Dtrue&plugins=wsm%26wnt%26kpm%26vs%26ua%26cb%26xhr_content&data=%7B%22data%22%3A%5B%7B%22plugin%22%3A%22wsm%22%2C%22parameters%22%3A%22%7B%5C%22referrer%5C%22%3A%5C%22http%3A%2F%2F192.168.0.5%3A8081%2F%5C%22%2C%5C%22stubId%5C%22%3A%5C%22%5C%22%7D%22%7D%2C%7B%22plugin%22%3A%22wnt%22%2C%22parameters%22%3A%22%7B%5C%22referrer%5C%22%3A%5C%22http%3A%2F%2F192.168.0.5%3A8081%2F%5C%22%7D%22%7D%2C%7B%22plugin%22%3A%22xhr_content%22%2C%22parameters%22%3A%22%7B%5C%22referrer%5C%22%3A%5C%22http%3A%2F%2F192.168.0.5%3A8081%2F%5C%22%7D%22%7D%5D%7D&isTopLevel=false&nocache=1b489:1 Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
​ [2021-05-28T04:34:12.731Z] Try to connect
instrument.ts:129 [2021-05-28T04:34:12.748Z] Try to connect
​ [2021-05-28T04:34:17.583Z] ws connection error: CLOSE_ABNORMAL
(anonymous) @ :8081/adapter/javasc…b6edad9e.chunk.js:2
​ [2021-05-28T04:34:18.511Z] Start reconnect 0
instrument.ts:129 [2021-05-28T04:34:18.512Z] ws connection error: CLOSE_ABNORMAL
(anonymous) @ instrument.ts:129
instrument.ts:129 [2021-05-28T04:34:18.596Z] Start reconnect 0
​ [2021-05-28T04:34:18.633Z] Try to connect
instrument.ts:129 [2021-05-28T04:34:18.648Z] Try to connect
instrument.ts:129 [2021-05-28T04:46:34.072Z] ws connection error: CLOSE_ABNORMAL
(anonymous) @ instrument.ts:129
instrument.ts:129 [2021-05-28T04:46:34.128Z] Start reconnect 0
​ [2021-05-28T04:46:34.129Z] ws connection error: CLOSE_ABNORMAL
(anonymous) @ :8081/adapter/javasc…b6edad9e.chunk.js:2
​ [2021-05-28T04:46:34.229Z] Start reconnect 0
gc.kis.v2.scr.kaspersky-labs.com/7D8B79A2-8974-4D7B-A76A-F4F29624C06Bbinf4Px_oePKP2_9sg7TApjYsvk4LRwBhg9B_CqWTLy9NDbVrMgvwlWYV55N2F97MYfxjKommrYAZCtUqowg2g/init?url=http%3A%2F%2F192.168.0.5%3A8081%2F&plugins=wsm%26wnt%26kpm%26vs%26ua%26cb%26xhr_content&data=%7B%22data%22%3A%5B%7B%22plugin%22%3A%22wsm%22%2C%22parameters%22%3A%22%7B%5C%22referrer%5C%22%3A%5C%22%5C%22%2C%5C%22stubId%5C%22%3A%5C%22%5C%22%7D%22%7D%2C%7B%22plugin%22%3A%22wnt%22%2C%22parameters%22%3A%22%7B%5C%22referrer%5C%22%3A%5C%22%5C%22%7D%22%7D%2C%7B%22plugin%22%3A%22xhr_content%22%2C%22parameters%22%3A%22%7B%5C%22referrer%5C%22%3A%5C%22%5C%22%7D%22%7D%5D%7D&isTopLevel=true&nocache=140f4:1 Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
gc.kis.v2.scr.kaspersky-labs.com/7D8B79A2-8974-4D7B-A76A-F4F29624C06Bbinf4Px_oePKP2_9sg7TApjYsvk4LRwBhg9B_CqWTLy9NDbVrMgvwlWYV55N2F97MYfxjKommrYAZCtUqowg2g/init?url=http%3A%2F%2F192.168.0.5%3A8081%2F&plugins=wsm%26wnt%26kpm%26vs%26ua%26cb%26xhr_content&data=%7B%22data%22%3A%5B%7B%22plugin%22%3A%22wsm%22%2C%22parameters%22%3A%22%7B%5C%22referrer%5C%22%3A%5C%22%5C%22%2C%5C%22stubId%5C%22%3A%5C%22%5C%22%7D%22%7D%2C%7B%22plugin%22%3A%22wnt%22%2C%22parameters%22%3A%22%7B%5C%22referrer%5C%22%3A%5C%22%5C%22%7D%22%7D%2C%7B%22plugin%22%3A%22xhr_content%22%2C%22parameters%22%3A%22%7B%5C%22referrer%5C%22%3A%5C%22%5C%22%7D%22%7D%5D%7D&isTopLevel=true&nocache=11c4d:1 Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
gc.kis.v2.scr.kaspersky-labs.com/7D8B79A2-8974-4D7B-A76A-F4F29624C06BvXGmVRqtqpXygOGlY0HuXk6s48BMXyXBPvxZXYOh8tx5Arf4D8PyPjPJDEy2LRau5T6nNFRavX9z3NSZ_Np9UA/init?url=http%3A%2F%2F192.168.0.5%3A8081%2Fadapter%2Fjavascript%2Ftab.html%3FnewReact%3Dtrue&plugins=wsm%26wnt%26kpm%26vs%26ua%26cb%26xhr_content&data=%7B%22data%22%3A%5B%7B%22plugin%22%3A%22wsm%22%2C%22parameters%22%3A%22%7B%5C%22referrer%5C%22%3A%5C%22http%3A%2F%2F192.168.0.5%3A8081%2F%5C%22%2C%5C%22stubId%5C%22%3A%5C%22%5C%22%7D%22%7D%2C%7B%22plugin%22%3A%22wnt%22%2C%22parameters%22%3A%22%7B%5C%22referrer%5C%22%3A%5C%22http%3A%2F%2F192.168.0.5%3A8081%2F%5C%22%7D%22%7D%2C%7B%22plugin%22%3A%22xhr_content%22%2C%22parameters%22%3A%22%7B%5C%22referrer%5C%22%3A%5C%22http%3A%2F%2F192.168.0.5%3A8081%2F%5C%22%7D%22%7D%5D%7D&isTopLevel=false&nocache=136b0:1 Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
instrument.ts:129 [2021-05-28T04:46:53.789Z] Try to connect
​ [2021-05-28T04:46:53.793Z] Try to connect
instrument.ts:129 [2021-05-28T04:46:57.856Z] No READY flag received in 3 seconds. Re-init
(anonymous) @ instrument.ts:129
socket.io.js:337 WebSocket connection to 'ws://192.168.0.5:8081/?sid=1622177213789&name=admin' failed: WebSocket is closed before the connection is established.
SocketClient.close @ socket.io.js:337
instrument.ts:129 [2021-05-28T04:46:57.878Z] Start reconnect 1
instrument.ts:129 [2021-05-28T04:46:57.883Z] ws connection error: CLOSE_ABNORMAL
(anonymous) @ instrument.ts:129
2instrument.ts:129 [2021-05-28T04:46:57.883Z] Reconnect is already running 1
​ [2021-05-28T04:46:57.884Z] No READY flag received in 3 seconds. Re-init
(anonymous) @ :8081/adapter/javasc…b6edad9e.chunk.js:2
​ WebSocket connection to 'ws://192.168.0.5:8081/?sid=1622177213793&name=javascript' failed: WebSocket is closed before the connection is established.
SocketClient.close @ socket.io.js:337
​ [2021-05-28T04:46:57.892Z] Start reconnect 1
​ [2021-05-28T04:46:57.894Z] ws connection error: CLOSE_ABNORMAL
(anonymous) @ :8081/adapter/javasc…b6edad9e.chunk.js:2
2​ [2021-05-28T04:46:57.894Z] Reconnect is already running 1
instrument.ts:129 [2021-05-28T04:46:59.449Z] Try to connect
​ [2021-05-28T04:46:59.462Z] Try to connect
:8081/static/js/1.e148fa2b.chunk.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
instrument.ts:129 ChunkLoadError: Loading chunk 1 failed.
(error: http://192.168.0.5:8081/static/js/1.e148fa2b.chunk.js)
    at Function.f.e (http://192.168.0.5:8081/:2:3968)
    at http://192.168.0.5:8081/static/js/main.90e72440.chunk.js:2:1061703
    at S (http://192.168.0.5:8081/static/js/5.47bf7541.chunk.js:2:5487926)
    at Ui (http://192.168.0.5:8081/static/js/5.47bf7541.chunk.js:2:5478111)
    at Cl (http://192.168.0.5:8081/static/js/5.47bf7541.chunk.js:2:5464705)
    at Hl (http://192.168.0.5:8081/static/js/5.47bf7541.chunk.js:2:5464633)
    at El (http://192.168.0.5:8081/static/js/5.47bf7541.chunk.js:2:5464496)
    at ml (http://192.168.0.5:8081/static/js/5.47bf7541.chunk.js:2:5461462)
    at http://192.168.0.5:8081/static/js/5.47bf7541.chunk.js:2:5410841
    at t.unstable_runWithPriority (http://192.168.0.5:8081/static/js/5.47bf7541.chunk.js:2:5494232)
    at Wa (http://192.168.0.5:8081/static/js/5.47bf7541.chunk.js:2:5410618)
    at Ga (http://192.168.0.5:8081/static/js/5.47bf7541.chunk.js:2:5410786)
    at Ua (http://192.168.0.5:8081/static/js/5.47bf7541.chunk.js:2:5410721)
    at ke (http://192.168.0.5:8081/static/js/5.47bf7541.chunk.js:2:5482070)
    at Yt (http://192.168.0.5:8081/static/js/5.47bf7541.chunk.js:2:5389345)
    at HTMLDivElement.r (http://192.168.0.5:8081/static/js/5.47bf7541.chunk.js:2:6076188)
(anonymous) @ instrument.ts:129
:8081/static/js/16.ce92c795.chunk.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
DevTools failed to load SourceMap: Could not load content for http://192.168.0.5:8081/static/js/12.584a7fca.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://192.168.0.5:8081/static/js/main.90e72440.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by Anzic23** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found)
5.47bf7541.chunk.js:2 ChunkLoadError: Loading chunk 11 failed.
(error: http://192.168.1.100:8081/static/js/11.86dccfaf.chunk.js)
    at Function.f.e (http://192.168.1.100:8081/:1:3799)
    at http://192.168.1.100:8081/static/js/main.90e72440.chunk.js:2:1061624
    at S (http://192.168.1.100:8081/static/js/5.47bf7541.chunk.js:2:5487926)
    at Ui (http://192.168.1.100:8081/static/js/5.47bf7541.chunk.js:2:5478111)
    at Cl (http://192.168.1.100:8081/static/js/5.47bf7541.chunk.js:2:5464705)
    at Hl (http://192.168.1.100:8081/static/js/5.47bf7541.chunk.js:2:5464633)
    at El (http://192.168.1.100:8081/static/js/5.47bf7541.chunk.js:2:5464496)
    at ml (http://192.168.1.100:8081/static/js/5.47bf7541.chunk.js:2:5461462)
    at http://192.168.1.100:8081/static/js/5.47bf7541.chunk.js:2:5410841
    at t.unstable_runWithPriority (http://192.168.1.100:8081/static/js/5.47bf7541.chunk.js:2:5494232)
    at Wa (http://192.168.1.100:8081/static/js/5.47bf7541.chunk.js:2:5410618)
    at Ga (http://192.168.1.100:8081/static/js/5.47bf7541.chunk.js:2:5410786)
    at Ua (http://192.168.1.100:8081/static/js/5.47bf7541.chunk.js:2:5410721)
    at ke (http://192.168.1.100:8081/static/js/5.47bf7541.chunk.js:2:5482070)
    at Yt (http://192.168.1.100:8081/static/js/5.47bf7541.chunk.js:2:5389345)
    at HTMLDivElement.r (http://192.168.1.100:8081/static/js/5.47bf7541.chunk.js:2:6076188)
(anonymous) @ 5.47bf7541.chunk.js:2
DevTools failed to load SourceMap: Could not load content for http://192.168.1.100:8081/static/js/5.47bf7541.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://192.168.1.100:8081/static/js/main.90e72440.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://192.168.1.100:8081/static/js/12.584a7fca.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by GermanBluefox** [comment]
This is error in javascript adapter and not admin:
ttp://192.168.0.5:8081/adapter **/javascript** /vs/editor/editor.main.js:71:956
